#!/usr/bin/env python3
"""Writes supabase_duel_v2.sql from the bank in index.html.

The duel's answer key lives on the server so a client cannot simply claim it was right. It
was generated once, by hand, and the bank has been corrected since: two questions (862 and
1046) had their answers fixed in the page but not on the server, so a duel marked the right
answer wrong. Generating the key from the page means re-running this after any bank change
keeps the two in step — and QA_BANK compares them, so a drift fails the suite.

    python3 gen_duel_v2.py      # then run supabase_duel_v2.sql in the Supabase SQL editor
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent
page = (ROOT / "index.html").read_text(encoding="utf-8")
bank = json.loads(re.search(r'<script id="data" type="application/json">(.*?)</script>', page, re.S).group(1))
qs = bank["questions"]
key = {str(i): sorted(q["a"]) for i, q in enumerate(qs)}
m = re.search(r"const PAPER_LEN=(\d+)", page)
paper_len = int(m.group(1))
key_json = json.dumps(key, separators=(",", ":"))
assert "'" not in key_json

sql = f"""-- ============================================================================
--  Neon Grid — Question Duel v2: exam questions, and the answer after every question
--  Run after supabase_duel.sql. Safe to re-run. Generated by gen_duel_v2.py — edit that.
--
--  * The answer key is rebuilt from the current bank ({len(qs)} questions). Two answers had been
--    corrected in the app since the first key was written, so a duel marked them wrong.
--  * A duel can be played on one practice exam (1-{-(-len(qs)//paper_len)}) or on any. The exams are the
--    bank cut into {paper_len}s in bank order, so exam n is questions (n-1)*{paper_len} .. n*{paper_len}-1.
--    Someone on "any exam" can sit down with someone on a particular one; the exam wins.
--  * Every finished question is written to duels.hist with its answer and both picks, so
--    each player sees what the answer was, and what the other side chose, once it is over.
--    Nothing about the question in play is revealed.
--  * Moving a question on now takes the row first: both players poll, and two calls that
--    both saw the clock run out could otherwise skip a question between them.
--  * Roulette: the wheel spun forever whenever nobody had bet — the finished round was never
--    written down, so there was no result to land on. The table now records it.
-- ============================================================================

-- ---------------------------------------------------------------- answer key
insert into public.answer_key (id, ans) values (1, '{key_json}'::jsonb)
on conflict (id) do update set ans = excluded.ans;

-- ---------------------------------------------------------------- columns
alter table public.duels add column if not exists exam int not null default 0;   -- 0 = any exam
alter table public.duels add column if not exists hist jsonb not null default '[]'::jsonb;

-- ---------------------------------------------------------------- exams
create or replace function public.duel_exam_len() returns int
language sql immutable as $$ select {paper_len}; $$;

create or replace function public.duel_exam_count() returns int
language sql stable security definer set search_path = public
as $$
  select ceil((select count(*) from jsonb_object_keys((select ans from public.answer_key where id = 1)))::numeric
              / public.duel_exam_len())::int;
$$;

-- five questions, from one exam or from all of them
create or replace function public.duel_pick_questions(ex int)
returns int[]
language plpgsql security definer set search_path = public
as $$
declare ids int[];
begin
  select array_agg(k) into ids from (
    select key::int as k
      from jsonb_object_keys((select ans from public.answer_key where id = 1)) as key
     where ex = 0
        or key::int between (ex - 1) * public.duel_exam_len() and ex * public.duel_exam_len() - 1
     order by random()
     limit 5
  ) s;
  return ids;
end $$;
revoke all on function public.duel_pick_questions(int) from public, anon, authenticated;

-- ---------------------------------------------------------------- history
-- Write the question in play to hist, once. Only ever called on a question that is over.
create or replace function public.duel_log_turn(d public.duels)
returns public.duels
language plpgsql security definer set search_path = public
as $$
begin
  if d.status <> 'active' or jsonb_array_length(d.hist) > d.turn then return d; end if;
  update public.duels
     set hist = hist || jsonb_build_array(jsonb_build_object(
           'q',   d.q_ids[d.turn + 1],
           'ans', to_jsonb(public.duel_answers(d.q_ids[d.turn + 1])),
           'ap',  to_jsonb(d.a_pick), 'bp',  to_jsonb(d.b_pick),
           'aok', d.a_ok,             'bok', d.b_ok)),
         updated_at = now()
   where id = d.id returning * into d;
  return d;
end $$;
revoke all on function public.duel_log_turn(public.duels) from public, anon, authenticated;

-- ---------------------------------------------------------------- view
create or replace function public.duel_view(d public.duels)
returns jsonb
language plpgsql stable set search_path = public
as $$
declare me uuid := auth.uid(); iam_a boolean; mine text[]; theirs text[]; answered boolean;
begin
  iam_a := (d.a = me);
  mine   := case when iam_a then d.a_pick else d.b_pick end;
  theirs := case when iam_a then d.b_pick else d.a_pick end;
  answered := mine is not null;
  return jsonb_build_object(
    'id', d.id, 'status', d.status, 'stake', d.stake, 'turn', d.turn, 'exam', d.exam,
    'count', coalesce(array_length(d.q_ids, 1), 5),
    'question', case when d.status = 'active' then d.q_ids[d.turn + 1] else null end,
    'you',      jsonb_build_object('name', case when iam_a then d.a_name else d.b_name end,
                                   'score', case when iam_a then d.a_score else d.b_score end,
                                   'answered', answered),
    'them',     jsonb_build_object('name', case when iam_a then d.b_name else d.a_name end,
                                   'score', case when iam_a then d.b_score else d.a_score end,
                                   -- only that they answered, never what they chose
                                   'answered', theirs is not null),
    -- questions that are over: the answer and both picks, from the caller's side
    'hist', coalesce((
      select jsonb_agg(jsonb_build_object(
               'q', e -> 'q', 'answer', e -> 'ans',
               'you',    case when iam_a then e -> 'ap'  else e -> 'bp'  end,
               'them',   case when iam_a then e -> 'bp'  else e -> 'ap'  end,
               'youOk',  case when iam_a then e -> 'aok' else e -> 'bok' end,
               'themOk', case when iam_a then e -> 'bok' else e -> 'aok' end) order by n)
        from jsonb_array_elements(d.hist) with ordinality as t(e, n)), '[]'::jsonb),
    'secondsTotal', public.duel_seconds(),
    'secondsLeft', case when d.status = 'active' and d.turn_start is not null
                        then greatest(0, public.duel_seconds()
                                          - round(extract(epoch from (now() - d.turn_start))))::int
                        else null end,
    'winner', d.winner, 'reason', d.reason,
    'youWon', (d.winner is not null and d.winner = me));
end $$;

-- ---------------------------------------------------------------- settle and advance
create or replace function public.duel_finish(d public.duels, win uuid, why text)
returns public.duels
language plpgsql security definer set search_path = public
as $$
declare cur public.duels;
begin
  -- both players poll, so two calls can decide the same duel is over at once: take the row
  -- first, or each pays the pot out
  select * into cur from public.duels where id = d.id for update;
  if cur.id is null then return d; end if;
  if cur.status = 'done' then return cur; end if;
  d := public.duel_log_turn(cur);

  if win is not null then
    update public.wallets set chips = chips + d.stake * 2,
           lifetime_won = lifetime_won + d.stake, updated_at = now()
     where user_id = win;
    update public.wallets set lifetime_lost = lifetime_lost + d.stake, updated_at = now()
     where user_id = case when win = d.a then d.b else d.a end;
  else                                                -- draw: both stakes returned
    update public.wallets set chips = chips + d.stake where user_id in (d.a, d.b);
  end if;
  update public.duels set status = 'done', winner = win, reason = why, updated_at = now()
   where id = d.id and status <> 'done' returning * into d;
  insert into public.casino_log (user_id, game, bet, delta, detail)
       values (d.a, 'duel', d.stake,
               case when win = d.a then d.stake when win is null then 0 else -d.stake end,
               jsonb_build_object('reason', why, 'exam', d.exam));
  return d;
end $$;
revoke all on function public.duel_finish(public.duels, uuid, text) from public, anon, authenticated;

create or replace function public.duel_next(d public.duels)
returns public.duels
language plpgsql security definer set search_path = public
as $$
declare cur public.duels;
begin
  -- both players poll duel_state; two calls that saw the same clock run out must move the
  -- duel on by one question, not two
  select * into cur from public.duels where id = d.id for update;
  if cur.id is null then return d; end if;
  if cur.status <> 'active' or cur.turn <> d.turn then return cur; end if;
  d := public.duel_log_turn(cur);
  if d.turn + 1 >= array_length(d.q_ids, 1) then
    if    d.a_score > d.b_score then return public.duel_finish(d, d.a, 'higher score');
    elsif d.b_score > d.a_score then return public.duel_finish(d, d.b, 'higher score');
    else  return public.duel_finish(d, null, 'draw');
    end if;
  end if;
  update public.duels
     set turn = turn + 1, a_pick = null, b_pick = null, a_ok = null, b_ok = null,
         turn_start = now(), updated_at = now()
   where id = d.id returning * into d;
  return d;
end $$;
revoke all on function public.duel_next(public.duels) from public, anon, authenticated;

-- ---------------------------------------------------------------- queue
-- The one-argument version is dropped rather than overloaded: PostgREST picks a function by
-- its argument names, and two candidates for {{stake}} would make every call ambiguous. A page
-- still on the old build sends {{stake}} alone and lands here with exam = 0.
drop function if exists public.duel_find(bigint);
create or replace function public.duel_find(stake bigint, exam int default 0)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare w public.wallets; d public.duels; nm text; ex int; use_ex int;
begin
  w := public.wallet_row();
  if duel_find.stake <= 0 then raise exception 'stake must be positive'; end if;
  ex := coalesce(duel_find.exam, 0);
  if ex < 0 or ex > public.duel_exam_count() then ex := 0; end if;
  if w.chips < duel_find.stake then
    return jsonb_build_object('ok', false, 'reason', 'not enough chips', 'chips', w.chips);
  end if;

  -- already in something? hand it back rather than starting a second one
  select * into d from public.duels
   where (a = auth.uid() or b = auth.uid()) and status in ('waiting','active')
   order by created_at desc limit 1;
  if d.id is not null then
    return jsonb_build_object('ok', true, 'duel', public.duel_view(d), 'chips', w.chips);
  end if;

  select username into nm from public.profiles where id = auth.uid();
  nm := coalesce(nm, 'player');

  -- a seat at the same stake, on the same exam first; "any exam" sits with anyone
  select * into d from public.duels dd
   where dd.status = 'waiting' and dd.stake = duel_find.stake and dd.a <> auth.uid()
     and (dd.exam = ex or dd.exam = 0 or ex = 0)
   order by (dd.exam = ex) desc, dd.created_at
   limit 1
   for update skip locked;

  if d.id is not null then
    use_ex := case when d.exam <> 0 then d.exam else ex end;
    update public.duels
       set b = auth.uid(), b_name = nm, status = 'active', exam = use_ex,
           q_ids = public.duel_pick_questions(use_ex), hist = '[]'::jsonb,
           turn = 0, turn_start = now(), updated_at = now()
     where id = d.id returning * into d;
    update public.wallets set chips = chips - duel_find.stake, updated_at = now()
     where user_id = auth.uid();
  else
    insert into public.duels (stake, a, a_name, status, exam)
         values (duel_find.stake, auth.uid(), nm, 'waiting', ex) returning * into d;
    update public.wallets set chips = chips - duel_find.stake, updated_at = now()
     where user_id = auth.uid();
  end if;

  select * into w from public.wallets where user_id = auth.uid();
  return jsonb_build_object('ok', true, 'duel', public.duel_view(d), 'chips', w.chips);
end $$;

-- ---------------------------------------------------------------- roulette: the wheel that never landed
-- supabase_duel.sql added roulette_mark() to write down the round that just finished, so the
-- wheel has a result to land on when nobody bet on it — but nothing ever called it. With no
-- bets there were no rounds at all (and the sweep clears old ones), "last" stayed null, and
-- every client spun forever. The table now marks the previous round whenever anyone looks.
create or replace function public.roulette_table()
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare cur bigint; ends timestamptz; last record; bets jsonb; mine jsonb; w public.wallets;
begin
  w   := public.wallet_row();
  cur := public.roulette_now();
  perform public.roulette_settle();
  perform public.roulette_mark(cur - 1);
  if random() < 0.05 then perform public.casino_sweep(); end if;   -- amortised cleanup

  ends := to_timestamp((cur + 1) * 25);

  select * into last from public.roulette_rounds
   where resolved_at is not null and id < cur order by id desc limit 1;

  select coalesce(jsonb_agg(jsonb_build_object(
           'who', coalesce(b.username, 'player'), 'pick', b.pick, 'amount', b.amount,
           'me', b.user_id = auth.uid()) order by b.id), '[]'::jsonb)
    into bets
    from public.roulette_bets b where b.round_id = cur;

  select coalesce(jsonb_agg(jsonb_build_object('pick', pick, 'amount', amount)), '[]'::jsonb)
    into mine
    from public.roulette_bets where round_id = cur and user_id = auth.uid();

  return jsonb_build_object(
    'round', cur,
    'endsAt', ends,
    'secondsLeft', greatest(0, round(extract(epoch from (ends - now()))))::int,
    'open', extract(epoch from (ends - now())) > 3,      -- no more bets in the last 3 seconds
    'bets', bets, 'mine', mine, 'chips', w.chips,
    'last', case when last is null then null else
      jsonb_build_object('round', last.id, 'pocket', last.pocket, 'colour', last.colour) end);
end $$;

-- ---------------------------------------------------------------- permissions
do $$
declare f text;
begin
  foreach f in array array['duel_find(bigint,int)','duel_state(uuid)','duel_answer(uuid,text[])',
                           'duel_leave(uuid)','duel_seconds()','roulette_table()']
  loop
    execute format('revoke all on function public.%s from public, anon;', f);
    execute format('grant execute on function public.%s to authenticated;', f);
  end loop;
  execute 'revoke all on function public.duel_exam_count() from public, anon, authenticated';
end $$;

notify pgrst, 'reload schema';

-- ---------------------------------------------------------------- verify
-- expect: {len(qs)} questions in the key, {-(-len(qs)//paper_len)} exams, the new columns, one duel_find
select (select count(*) from jsonb_object_keys((select ans from public.answer_key where id = 1))) as questions,
       public.duel_exam_count() as exams,
       (select count(*) from information_schema.columns
         where table_name = 'duels' and column_name in ('exam','hist')) as new_columns,
       (select count(*) from pg_proc where proname = 'duel_find') as duel_find_versions;
"""
(ROOT / "supabase_duel_v2.sql").write_text(sql, encoding="utf-8")
print(f"supabase_duel_v2.sql: {len(qs)} answers, exams of {paper_len}")
