# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 0,
"nm": "IAM & AWS CLI",
"tag": "Identity",
"modules": [
{
 "id": "identities",
 "nm": "Who can act: users, groups, roles",
 "goal": "Tell a user, a group and a role apart, and say which one an exam scenario needs.",
 "min": 7,
 "blocks": [
  {"t":"p","x":"IAM answers one question for every AWS API call ever made: **is this caller allowed to do this?** Everything else in this subject is detail hanging off that. An identity is *who is asking*; a policy is *what that identity may do*."},
  {"t":"h","x":"The three identities"},
  {"t":"table","head":["Identity","What it is","Credentials","Use it for"],
   "rows":[
    ["User","One person or one application, permanent","Password for the console, access keys for the CLI/SDK — both long-lived","A human who signs in. Almost nothing else"],
    ["Group","A bag of users you attach policies to","None — a group is not an identity that can act","Managing permissions for many people at once"],
    ["Role","An identity anything can temporarily *assume*","None stored. STS mints temporary keys on assumption","EC2, Lambda, ECS, another AWS account, a federated user"]]},
  {"t":"key","x":"A group is not a principal. It cannot be named in a trust policy, it cannot own credentials, and groups cannot be nested inside other groups. If an answer says \"add the group as the principal\", it is wrong."},
  {"t":"h","x":"Why roles win almost every scenario"},
  {"t":"p","x":"A user's access keys live forever until someone rotates them. A role's credentials come from **STS**, carry an expiry, and are fetched automatically — nothing is stored on disk, in an AMI, or in an environment variable, so nothing can leak from there."},
  {"t":"flow","x":["EC2 / Lambda / ECS needs S3","It assumes its attached role","STS returns temporary keys","Call is signed and allowed","Keys expire and refresh"],
   "cap":"No human, no stored secret, no rotation job."},
  {"t":"h","x":"The root user"},
  {"t":"list","x":[
   "Created with the account, identified by the sign-up email, and holds unrestricted power that **no IAM policy can limit**.",
   "Enable MFA on it immediately — hardware MFA for anything serious.",
   "Delete its access keys outright. Do not rotate them; root should have none at all.",
   "Use it only for the handful of tasks that require it: closing the account, changing the support plan, some billing settings."]},
  {"t":"trap","x":"\"Give the developer root access so they can finish quickly\" is never the answer, in any question, ever. Create an IAM role or user with the permissions actually needed."},
  {"t":"h","x":"Naming the right identity"},
  {"t":"dtree","x":[
   ["A person signs in at a keyboard","IAM user, in a group, with MFA"],
   ["An EC2 instance, Lambda function or ECS task calls an AWS API","IAM role attached to that compute"],
   ["Code running outside AWS in another company's account","A role in your account that their role assumes"],
   ["Hundreds of employees across many AWS accounts","IAM Identity Center, not one user per account"],
   ["Customers signing in to the app you built","Cognito — they are not workforce identities"]]}
 ],
 "checks":[
  {"q":"An EC2 instance needs to read objects from an S3 bucket. What should be attached to the instance?",
   "o":["An IAM role granting the S3 read permissions",
        "An IAM user's access keys written into a file on the instance",
        "The root user's access keys, stored as an environment variable",
        "An IAM group containing the instance"],
   "a":[0],
   "x":"Compute that calls an AWS API gets a role. STS hands the instance temporary credentials that rotate on their own, so there is no long-lived secret sitting on disk to leak. Access keys on an instance are the classic wrong answer, root keys are worse, and a group cannot contain an instance at all."},
  {"q":"Which statement about IAM groups is correct?",
   "o":["A group can contain users, but groups cannot be nested and cannot be a principal",
        "A group has its own access keys that its members share",
        "A group can be assumed the same way a role can",
        "A group can contain both users and EC2 instances"],
   "a":[0],
   "x":"A group is purely a convenience for attaching policies to many users at once. It holds no credentials, cannot be assumed, cannot be named as a principal in a trust policy, and cannot be put inside another group."},
  {"q":"Which task genuinely requires the root user?",
   "o":["Attaching a policy to a developer's IAM user",
        "Closing the AWS account",
        "Launching an EC2 instance in a new region",
        "Creating an S3 bucket for production logs"],
   "a":[1],
   "x":"Closing the account is one of the few operations reserved for root. Day-to-day work — policies, EC2, S3 — belongs to an IAM user or role with the right permissions. Root should be locked away behind MFA with no access keys at all."},
  {"q":"Why are role credentials considered safer than an IAM user's access keys?",
   "o":["They are longer, so they are harder to guess",
        "They are issued by STS, expire on their own, and are never stored on the instance",
        "They work only inside a single VPC",
        "They cannot be used by the AWS CLI"],
   "a":[1],
   "x":"The safety comes from the credentials being temporary and never written down. STS issues them on assumption with a fixed expiry and the SDK refreshes them automatically, so a leaked copy is useless within hours — unlike an access key that stays valid until a human rotates it."}
 ]
},
{
 "id":"policies",
 "nm":"What they may do: policies and evaluation",
 "goal":"Read a policy document and work out whether a specific call is allowed or denied.",
 "min":9,
 "blocks":[
  {"t":"p","x":"A policy is a JSON document made of statements. Each statement has an **Effect** (Allow or Deny), an **Action**, a **Resource**, and optionally a **Condition**. That is the whole language."},
  {"t":"code","x":"{\n  \"Effect\": \"Allow\",\n  \"Action\": [\"s3:GetObject\"],\n  \"Resource\": \"arn:aws:s3:::reports/*\",\n  \"Condition\": {\"Bool\": {\"aws:MultiFactorAuthPresent\": \"true\"}}\n}",
   "cap":"Read GetObject on one bucket's objects — but only when the caller authenticated with MFA."},
  {"t":"h","x":"Two places a policy can hang"},
  {"t":"split","cols":[
   {"nm":"Identity-based policy","items":["Attached to a user, group or role","Says: *this identity may do X*","Cannot grant anything to a caller in another account on its own"]},
   {"nm":"Resource-based policy","items":["Attached to the resource — S3 bucket policy, KMS key policy, SQS queue policy","Says: *this principal may touch me*","The only way to grant cross-account access without assuming a role"]}]},
  {"t":"h","x":"Evaluation logic — the part that is tested constantly"},
  {"t":"steps","x":[
   "Start from an implicit **deny**. Nothing is allowed by default.",
   "Look for an explicit **Deny** anywhere at all — identity policy, resource policy, SCP, permissions boundary. If one applies, the call fails and nothing can override it.",
   "Look for an explicit **Allow**. If one applies and no Deny did, the call succeeds.",
   "No Allow found? The implicit deny stands and the call fails."]},
  {"t":"key","x":"Explicit Deny beats every Allow, always, no matter how many Allows there are or where they came from. This single rule answers a surprising number of exam questions."},
  {"t":"h","x":"Cross-account access needs both halves"},
  {"t":"flow","x":["Account B identity policy allows the call","Account A resource policy names B's principal","Call succeeds"],
   "cap":"Granting on only one side leaves the request implicitly denied on the other."},
  {"t":"trap","x":"An answer that adds only the bucket policy in the owning account, or only the IAM policy in the calling account, is incomplete. Cross-account always needs permission on both sides."},
  {"t":"h","x":"Managed versus inline"},
  {"t":"table","head":["Kind","Reusable","When to use"],
   "rows":[
    ["AWS managed policy","Yes, maintained by AWS","Quick standard access such as ReadOnlyAccess"],
    ["Customer managed policy","Yes, you own the version history","The normal choice for your own permissions"],
    ["Inline policy","No, it lives and dies with one identity","A one-off permission that must never be reused"]]}
 ],
 "checks":[
  {"q":"A user has an identity policy allowing s3:GetObject, and an SCP on their account explicitly denies all S3 actions. What happens when the user calls GetObject?",
   "o":["The call is allowed, because the identity policy is more specific",
        "The call is denied — an explicit Deny cannot be overridden by any Allow",
        "The call is allowed only from inside a VPC",
        "The two policies cancel out and the call is retried"],
   "a":[1],
   "x":"An explicit Deny anywhere in the evaluation — identity policy, resource policy, SCP or permissions boundary — ends the decision immediately. No number of Allow statements can rescue the call."},
  {"q":"An IAM role has no policy that mentions DynamoDB at all, and nothing denies it either. Can the role call DynamoDB?",
   "o":["No — with no explicit Allow, the implicit deny stands",
        "Yes, because nothing denied it",
        "Yes, but only for read actions",
        "Only if the table is in the same region"],
   "a":[0],
   "x":"IAM starts from an implicit deny. Silence is not permission: without a statement that explicitly allows the action, the call fails even though no Deny was written anywhere."},
  {"q":"Team B in Account B needs to read an S3 bucket owned by Account A. What is required?",
   "o":["A bucket policy in Account A naming Account B's principal only",
        "An IAM policy on the role in Account B only",
        "A bucket policy in Account A naming the principal, and an IAM policy in Account B allowing the S3 actions",
        "Making the bucket public so both accounts can reach it"],
   "a":[2],
   "x":"Cross-account access needs both halves. The resource-based bucket policy in the owning account has to name the calling principal, and the calling identity's own policy has to permit the S3 actions. Doing one side leaves the request denied on the other, and making the bucket public is never the fix."},
  {"q":"Which policy type can grant access to a principal in a different AWS account without that principal assuming a role?",
   "o":["A resource-based policy such as an S3 bucket policy",
        "An inline policy on a local IAM user",
        "An IAM group policy",
        "A customer managed policy attached to a local role"],
   "a":[0],
   "x":"Only a resource-based policy can name an external principal directly, which is what lets an S3 bucket, SQS queue or KMS key be shared across accounts. Identity-based policies of every flavour only describe what their own identity may do."}
 ]
},
{
 "id":"roles-sts",
 "nm":"Roles, STS and cross-account",
 "goal":"Diagnose why a role assumption failed, and design cross-account access correctly.",
 "min":8,
 "blocks":[
  {"t":"p","x":"Assuming a role is a call to **STS**, the Security Token Service. It returns three things — an access key, a secret key and a **session token** — with an expiry. Anything without that session token is not a role credential."},
  {"t":"h","x":"A role has two policies, and they are not the same policy"},
  {"t":"split","cols":[
   {"nm":"Trust policy","items":["Answers: *who may assume me?*","Names principals — an account, a role, a service such as ec2.amazonaws.com","A failure here means the assumption itself is refused"]},
   {"nm":"Permission policy","items":["Answers: *what may I do once assumed?*","Names actions and resources","A failure here means you got the credentials and then got AccessDenied"]}]},
  {"t":"key","x":"Failed to assume the role at all → fix the **trust policy**. Assumed it fine, then got AccessDenied on the API call → fix the **permission policy**. Which failure you were told about tells you which document is wrong."},
  {"t":"h","x":"The cross-account pattern"},
  {"t":"steps","x":[
   "In the target account, create a role whose **trust policy** names the source account (or a specific role in it).",
   "Give that role a permission policy covering exactly what the caller needs.",
   "In the source account, allow the calling identity to run `sts:AssumeRole` on that role's ARN.",
   "The caller assumes the role, receives temporary credentials, and acts **as a principal of the target account**."]},
  {"t":"trap","x":"A third-party vendor whose tooling runs in their own AWS account should assume a cross-account role in yours. Creating an IAM user for the vendor and emailing them access keys is the wrong answer even though it works."},
  {"t":"h","x":"Where role credentials come from, by compute type"},
  {"t":"table","head":["Compute","Mechanism","Notes"],
   "rows":[
    ["EC2","Instance profile","A thin wrapper the console creates around the role; read \"instance profile\" as \"the role on the instance\""],
    ["Lambda","Execution role","Also controls CloudWatch Logs access and VPC attachment"],
    ["ECS / Fargate","Task role","Per-task, distinct from the EC2 instance role underneath it"],
    ["Outside AWS","OIDC or SAML federation","A CI system assumes a role with no stored keys at all"]]},
  {"t":"note","x":"`aws sts get-caller-identity` prints exactly which identity the current credentials belong to. It is the fastest way to prove whether you are running as the role you think you are."}
 ],
 "checks":[
  {"q":"An application can assume its role, but every S3 call then returns AccessDenied. Which document should you fix?",
   "o":["The trust policy on the role",
        "The permission policy on the role",
        "The account password policy",
        "The role's session token"],
   "a":[1],
   "x":"The assumption succeeded, so the trust policy already allows the caller. What fails afterwards is the action itself, which is governed by the role's permission policy. Trust policy failures stop you before any credentials are issued."},
  {"q":"What does STS return when a role is assumed?",
   "o":["A permanent access key pair",
        "A temporary access key, secret key and session token with an expiry",
        "Only a session token",
        "A console password for the role"],
   "a":[1],
   "x":"Role credentials are a triple — access key, secret key and session token — and they expire. The session token is what marks them as temporary; a credential set without one is a long-lived IAM user key."},
  {"q":"An external vendor's software runs in the vendor's own AWS account and needs to read your CloudWatch metrics. What should you set up?",
   "o":["An IAM user in your account whose keys you send to the vendor",
        "A role in your account whose trust policy names the vendor's account, which their role assumes",
        "Public read access on the metrics",
        "A shared root password for the two accounts"],
   "a":[1],
   "x":"Cross-account access is a role in the account that owns the data, trusted to the account that needs it. Nothing long-lived is ever handed over, and access is revoked by editing one trust policy rather than by chasing down a key someone copied."},
  {"q":"On an EC2 instance, what is an instance profile?",
   "o":["The wrapper that attaches an IAM role to the instance",
        "A saved set of access keys stored in the AMI",
        "The instance's security group",
        "A CloudWatch configuration file"],
   "a":[0],
   "x":"An instance profile is a thin container the console creates automatically so a role can be attached to EC2. Whenever a question says instance profile, read it as the IAM role the instance is running with."}
 ]
},
{
 "id":"account-security",
 "nm":"MFA, password policy and the audit tools",
 "goal":"Apply the account-hardening answers the exam expects, and name the tool that proves it.",
 "min":6,
 "blocks":[
  {"t":"p","x":"A block of questions in this subject is really asking *what does a well-run account look like?* The answers are always the same handful of controls."},
  {"t":"h","x":"Multi-factor authentication"},
  {"t":"list","x":[
   "Virtual MFA — an app on a phone. Hardware key or U2F security key for higher assurance.",
   "MFA on root is non-negotiable, and on every privileged human identity.",
   "MFA can be **required by policy**, not merely suggested, using the condition key `aws:MultiFactorAuthPresent`.",
   "Long-lived IAM user keys do not carry the MFA flag. The user calls `sts:GetSessionToken` while authenticated with MFA, and uses the temporary credentials that come back."]},
  {"t":"key","x":"\"Force MFA for these CLI actions\" → deny the actions unless `aws:MultiFactorAuthPresent` is true, then have the user obtain temporary credentials with `GetSessionToken`. You cannot make the CLI prompt for a code by itself."},
  {"t":"h","x":"Password policy"},
  {"t":"p","x":"Account-wide and configurable: minimum length, required character types, expiry and rotation, reuse prevention, and whether users may change their own password."},
  {"t":"h","x":"The two audit tools people mix up"},
  {"t":"table","head":["Tool","Scope","Answers the question"],
   "rows":[
    ["Credential report","Account-wide CSV of every user","Who has keys, how old are they, who has MFA, who never signs in?"],
    ["Access Advisor","One user, group, role or policy","Which services has this identity actually used, and when?"]]},
  {"t":"trap","x":"Access Advisor is the tool for trimming an over-permissive policy, because it shows services granted but never touched. The credential report is for finding stale keys and missing MFA. Picking the wrong one is a common trap."},
  {"t":"h","x":"The best-practice answers"},
  {"t":"list","x":[
   "Least privilege: grant the permissions the job needs, then widen only if something breaks.",
   "One IAM user per human, never a shared login.",
   "Roles for anything that is not a human.",
   "Rotate what must exist, and delete what should not exist at all — starting with root access keys."]}
 ],
 "checks":[
  {"q":"A policy must require multi-factor authentication for a set of sensitive CLI actions. What is the mechanism?",
   "o":["Enable MFA on the root user and nothing else is needed",
        "Deny the actions unless aws:MultiFactorAuthPresent is true, and have the user get temporary credentials with GetSessionToken",
        "Ask the user to type the MFA code as an argument to every command",
        "It cannot be done outside the console"],
   "a":[1],
   "x":"MFA is enforced as a policy condition. Because a long-lived access key carries no MFA flag, the user first authenticates with MFA through GetSessionToken and then uses the temporary credentials, which do carry it."},
  {"q":"Which tool shows, for a single role, which services it was granted but has never actually called?",
   "o":["Access Advisor",
        "The credential report",
        "A password policy",
        "An instance profile"],
   "a":[0],
   "x":"Access Advisor reports last-accessed data per identity, which is exactly what you need to trim a policy down to least privilege. The credential report is account-wide and describes credentials, not service usage."},
  {"q":"Which finding would the IAM credential report reveal?",
   "o":["Which EC2 instances are running without a role",
        "That several users have access keys older than a year and no MFA device",
        "Which S3 buckets are public",
        "Which API calls failed yesterday"],
   "a":[1],
   "x":"The credential report is a per-user inventory of credentials: password age, key age, whether keys are active and whether MFA is enabled. Public buckets and failed API calls come from entirely different services."},
  {"q":"What is the recommended handling of root user access keys?",
   "o":["Rotate them every 90 days",
        "Delete them so the root user has no access keys at all",
        "Store them in an S3 bucket for the team",
        "Share them with the on-call engineer"],
   "a":[1],
   "x":"Root should have no programmatic credentials to rotate in the first place. Delete them, protect root with MFA, and do everyday work through IAM roles and users that can actually be constrained by policy."}
 ]
},
{
 "id":"cli-sdk",
 "nm":"CLI, SDK and the credential chain",
 "goal":"Predict which credentials a call will use, and harden instance metadata.",
 "min":7,
 "blocks":[
  {"t":"p","x":"The CLI and every SDK look for credentials in a fixed order and stop at the first source that produces them. Knowing the order explains almost every \"why is it using the wrong account?\" question."},
  {"t":"flow","x":["Command-line options","Environment variables","~/.aws/credentials","~/.aws/config","Container credentials (ECS task role)","Instance metadata (EC2 role)"],
   "cap":"First match wins — a stale environment variable silently beats the instance role."},
  {"t":"key","x":"An EC2 instance with an attached role needs **zero** stored credentials. The SDK reads them from the instance metadata service at `169.254.169.254` and refreshes them before they expire."},
  {"t":"h","x":"IMDSv1 versus IMDSv2"},
  {"t":"table","head":["","IMDSv1","IMDSv2"],
   "rows":[
    ["How it works","A plain request returns the data","A PUT first obtains a session token, which every later request must carry"],
    ["Exposure","A server-side request forgery bug can reach it","Token requirement blocks the usual SSRF path"],
    ["Guidance","Legacy","Prefer it, and enforce it"]]},
  {"t":"trap","x":"If a question mentions stolen instance credentials through an application vulnerability, the hardening answer is enforcing IMDSv2 — not a security group change. Metadata never leaves the instance, so no network rule touches it."},
  {"t":"h","x":"Profiles and identity"},
  {"t":"list","x":[
   "`aws configure` writes a profile; `--profile` picks between them.",
   "`aws sts get-caller-identity` proves which identity is really in use.",
   "**CloudShell** is a browser shell already holding your console identity — no keys to configure, and it is region-based."]},
  {"t":"h","x":"Where each credential type belongs"},
  {"t":"dtree","x":[
   ["A developer's laptop","A profile in ~/.aws/credentials, ideally short-lived federated credentials"],
   ["An EC2 instance","An attached role, read through IMDSv2"],
   ["An ECS task","A task role, read through the container credentials endpoint"],
   ["A CI pipeline outside AWS","OIDC federation assuming a role — no stored keys"],
   ["A quick one-off command in the console","CloudShell"]]}
 ],
 "checks":[
  {"q":"An EC2 instance has an IAM role attached, but the CLI on it keeps acting as a different identity. What is the most likely cause?",
   "o":["The role is missing a trust policy",
        "Credentials earlier in the chain — environment variables or ~/.aws/credentials — are being found first",
        "IMDSv2 is enabled",
        "The instance is in a private subnet"],
   "a":[1],
   "x":"The chain stops at the first source that yields credentials, and the instance role sits last. A leftover environment variable or credentials file silently wins, which is why get-caller-identity is the first troubleshooting step."},
  {"q":"An application vulnerability was used to read EC2 instance credentials from the metadata service. What hardening step addresses this directly?",
   "o":["Enforce IMDSv2 so metadata requests require a session token",
        "Remove the instance from its security group",
        "Move the instance to a public subnet",
        "Rotate the role's trust policy"],
   "a":[0],
   "x":"IMDSv2 requires a PUT to obtain a token before any metadata read, which defeats the server-side request forgery pattern used to reach the metadata endpoint. Security groups are irrelevant here — the metadata service is local to the instance."},
  {"q":"Which command confirms which identity the CLI is currently using?",
   "o":["aws configure list-profiles",
        "aws sts get-caller-identity",
        "aws iam list-users",
        "aws ec2 describe-instances"],
   "a":[1],
   "x":"get-caller-identity returns the account, the ARN and the user or role ID behind the credentials in use. It answers \"who am I right now\", which listing profiles or users cannot."},
  {"q":"What is AWS CloudShell?",
   "o":["A browser-based shell that already carries your console identity, with no keys to configure",
        "A managed EC2 instance you pay for hourly",
        "A local installer for the AWS CLI",
        "A service that stores long-lived access keys for a team"],
   "a":[0],
   "x":"CloudShell is a terminal in the console running as the identity you signed in with, so the CLI is pre-authenticated. It is region-based and needs no access keys, which makes it the quick answer for one-off commands."}
 ]
}
],
"recap":[
 {"t":"h","x":"The one rule everything else hangs off"},
 {"t":"p","x":"Every AWS API call is evaluated the same way: **implicit deny → explicit Deny wins → explicit Allow → otherwise denied.** When a question describes an unexpected AccessDenied, walk that ladder before anything else."},
 {"t":"h","x":"Identity selection, end to end"},
 {"t":"table","head":["The scenario says…","The answer is","Why"],
  "rows":[
   ["An EC2 instance, Lambda or ECS task needs AWS access","An IAM role","Temporary credentials, nothing stored, automatic rotation"],
   ["Another AWS account needs access","A cross-account role, or a resource-based policy","Both halves must permit the call"],
   ["Employees need access to many AWS accounts","IAM Identity Center","One place to assign access; no user per account"],
   ["Customers sign in to your application","Cognito","They are app users, not workforce identities"],
   ["A CI system outside AWS needs credentials","OIDC federation to a role","No stored keys anywhere"],
   ["A human administrator","IAM user in a group, MFA enforced","Groups carry the policies; MFA carries the risk"]]},
 {"t":"h","x":"Trust policy or permission policy?"},
 {"t":"split","cols":[
  {"nm":"Cannot assume the role","items":["The trust policy is wrong","Check the principal it names","No credentials were ever issued"]},
  {"nm":"Assumed it, then AccessDenied","items":["The permission policy is wrong","Check actions and resources","Credentials were fine all along"]}]},
 {"t":"h","x":"Policy attachment cheat sheet"},
 {"t":"table","head":["Policy","Attached to","Can name an external principal"],
  "rows":[
   ["Identity-based","User, group, role","No"],
   ["Resource-based","Bucket, queue, key, topic","Yes — this is the point of it"],
   ["SCP","An organizational unit or account","Restricts only; never grants"],
   ["Permissions boundary","A user or role","Caps what its own policies may grant"]]},
 {"t":"key","x":"Cross-account access needs permission on **both** sides — the caller's identity policy and the target's resource or trust policy. An answer that changes only one account is incomplete."},
 {"t":"h","x":"Credential resolution order"},
 {"t":"flow","x":["CLI options","Environment variables","credentials file","config file","Container (ECS)","Instance metadata (EC2)"],
  "cap":"First source that produces credentials wins — this is why stale environment variables cause \"wrong identity\" bugs."},
 {"t":"h","x":"Account hygiene answers"},
 {"t":"list","x":[
  "Root: MFA on, access keys deleted, used only for account-level tasks.",
  "MFA by policy: deny unless `aws:MultiFactorAuthPresent`, plus `sts:GetSessionToken`.",
  "Credential report → stale keys and missing MFA across the account.",
  "Access Advisor → services granted but never used, for trimming to least privilege.",
  "IMDSv2 → the answer whenever instance credentials were stolen through the application."]},
 {"t":"trap","x":"Recurring distractors in this subject: access keys baked into an AMI or environment variable; making a bucket public to solve a permissions problem; naming a group as a principal; fixing a permission policy when the assumption itself failed; and sharing root credentials for convenience."},
 {"t":"h","x":"Vocabulary you must not blur"},
 {"t":"table","head":["Term","Precise meaning"],
  "rows":[
   ["STS","The service that issues temporary credentials when a role is assumed"],
   ["Session token","The third credential that marks a key pair as temporary"],
   ["Instance profile","The wrapper attaching an IAM role to an EC2 instance"],
   ["Trust policy","Who may assume this role"],
   ["Permission policy","What the role may do once assumed"],
   ["Access Advisor","Per-identity record of services actually used"],
   ["IMDSv2","Token-protected instance metadata service"]]}
],
"final":[
 {"m":"roles-sts",
  "q":"A Lambda function must write objects to an S3 bucket in the same account. Which approach is correct and most secure?",
  "o":["Attach an execution role to the function with a policy allowing s3:PutObject on the bucket",
       "Create an IAM user and put its access keys in the function's environment variables",
       "Make the bucket public so the function can write without credentials",
       "Use the root account's access keys inside the function code"],
  "a":[0],
  "w":["Correct — the execution role is how Lambda authenticates, and its credentials are temporary and rotated automatically.",
      "Long-lived keys in environment variables are readable by anyone who can view the function configuration, and they never expire on their own.",
      "Public write removes access control entirely and is never the answer to a permissions question.",
      "Root credentials cannot be constrained by any policy, so this maximises blast radius instead of reducing it."],
  "x":"Compute that needs AWS access gets a role. The execution role's permission policy names the exact action and bucket, credentials come from STS with an expiry, and nothing sensitive is stored in the function."},
 {"m":"policies",
  "q":"A developer's IAM policy allows s3:* on all buckets, but a permissions boundary on the same user allows only DynamoDB actions. What can the developer do in S3?",
  "o":["Nothing in S3 — the boundary caps what their policies can grant",
       "Everything in S3, because the identity policy grants it",
       "Read but not write in S3",
       "Everything in S3 only from the console"],
  "a":[0],
  "w":["Correct — effective permissions are the intersection of the identity policy and the boundary, and S3 is outside the boundary.",
      "A boundary is not overridden by a broad identity policy; it is a ceiling applied on top of it.",
      "A boundary does not grade actions into read and write; S3 is simply not within it.",
      "The console and the API are evaluated by the same policy engine, so the access path changes nothing."],
  "x":"A permissions boundary never grants anything — it limits what the identity's own policies are able to grant. Where the two do not overlap, there is no access, which is what makes boundaries safe for delegated administration."},
 {"m":"policies",
  "q":"An S3 bucket policy explicitly denies a role, while that role's identity policy allows s3:GetObject. What is the result of a GetObject call?",
  "o":["Denied — an explicit Deny in any applicable policy wins",
       "Allowed, because identity policies take precedence over resource policies",
       "Allowed, because the two statements cancel out",
       "Denied only if the object is encrypted"],
  "a":[0],
  "w":["Correct — explicit Deny is evaluated first and terminates the decision regardless of source.",
      "There is no precedence of identity over resource policies; both feed the same evaluation.",
      "Policies never cancel out — an explicit Deny is absolute.",
      "Encryption affects KMS permissions, not the outcome of this Deny."],
  "x":"The evaluation order is implicit deny, then explicit Deny, then explicit Allow. Because a Deny was found, evaluation stops there — this is the rule that decides most surprising AccessDenied scenarios."},
 {"m":"cli-sdk",
  "q":"An application on EC2 uses an instance role, but after a deployment it started making calls as an unrelated IAM user. What should you check first?",
  "o":["Environment variables and ~/.aws/credentials on the instance, which sit earlier in the credential chain",
       "The instance's security group rules",
       "Whether the bucket is in the same region",
       "The role's trust policy, which must have expired"],
  "a":[0],
  "w":["Correct — the SDK stops at the first credential source it finds, and both of those precede instance metadata.",
      "Security groups control network traffic and have nothing to do with which identity signs a request.",
      "Region affects endpoints, not which credentials the SDK picked up.",
      "Trust policies do not expire; had it been a trust problem, no credentials would have been issued at all."],
  "x":"Credential resolution is ordered: CLI options, environment variables, the credentials file, the config file, container credentials, then instance metadata. A leftover file or exported variable silently overrides the role."},
 {"m":"account-security",
  "q":"Security requires that deleting objects from a sensitive bucket only succeeds when the caller has authenticated with MFA. How is this enforced?",
  "o":["A policy condition denying the action unless aws:MultiFactorAuthPresent is true",
       "Enabling MFA on the root user",
       "Setting a password policy that requires rotation",
       "Adding the users to a group named MFA-Required"],
  "a":[0],
  "w":["Correct — MFA is expressed as a condition key, and the caller supplies MFA-backed temporary credentials through GetSessionToken.",
      "Root MFA protects root alone and says nothing about what other identities may do.",
      "Password rotation is unrelated to whether a given API call carried MFA.",
      "Group membership carries no MFA signal; only the condition key does."],
  "x":"The condition key aws:MultiFactorAuthPresent is the enforcement mechanism. Long-lived keys never carry it, so the user calls sts:GetSessionToken while authenticated with MFA and uses the returned temporary credentials."},
 {"m":"identities",
  "q":"Which design correctly gives fifty engineers access to twelve AWS accounts?",
  "o":["IAM Identity Center with permission sets assigned to groups",
       "An IAM user for each engineer in each account",
       "One shared IAM user per account with the password in a wiki",
       "Cognito user pools federated into each account"],
  "a":[0],
  "w":["Correct — Identity Center assigns permission sets centrally and the engineers assume roles in each account.",
      "Six hundred user records is an administrative and offboarding disaster, and it is the classic wrong answer.",
      "Shared credentials destroy attribution and cannot be revoked per person.",
      "Cognito is for the end users of an application you built, not for workforce access to AWS accounts."],
  "x":"Workforce identity across many accounts is what IAM Identity Center exists for: one assignment of a permission set, roles assumed per account, and offboarding handled in one place."},
 {"m":"roles-sts",
  "q":"A partner company's application, running in their own AWS account, needs read access to your DynamoDB table. What should you create?",
  "o":["A role in your account trusting the partner's account, which their application assumes",
       "An IAM user in your account whose access keys you email to the partner",
       "A public endpoint in front of the table",
       "A copy of the table in the partner's account, refreshed nightly by hand"],
  "a":[0],
  "w":["Correct — a cross-account role with a trust policy naming their account keeps the credentials temporary and revocation instant.",
      "Emailed long-lived keys cannot be rotated reliably and will outlive the relationship.",
      "Exposing a datastore publicly is never the intended answer to an access-control requirement.",
      "Manual copying introduces staleness and does not address access control at all."],
  "x":"Cross-account access is always a role in the account that owns the resource, trusted to the account that needs it, with the caller permitted to run sts:AssumeRole. Revoking access is then a single trust policy edit."},
 {"m":"account-security",
  "q":"A security review must identify every IAM user whose access keys are more than a year old and who has no MFA device. Which tool produces this?",
  "o":["The IAM credential report",
       "Access Advisor",
       "A bucket policy audit",
       "The instance metadata service"],
  "a":[0],
  "w":["Correct — the credential report is an account-wide CSV listing key age, key state, password age and MFA status per user.",
      "Access Advisor reports which services an identity has used, not the state of its credentials.",
      "Bucket policies describe access to S3 objects and say nothing about IAM users.",
      "Instance metadata serves credentials to one EC2 instance; it is not an audit tool."],
  "x":"The credential report is the account-wide credential inventory, which makes it the right tool for stale keys and missing MFA. Access Advisor answers a different question — what an identity actually used — and is the tool for trimming permissions."},
 {"m":"cli-sdk",
  "q":"Which measure most directly reduces the risk of an application vulnerability being used to steal an EC2 instance's role credentials?",
  "o":["Enforcing IMDSv2 on the instance",
       "Attaching a second IAM role to the instance",
       "Moving the instance into a public subnet",
       "Disabling the instance profile and storing keys in a file instead"],
  "a":[0],
  "w":["Correct — IMDSv2 requires a session token obtained by a PUT, which breaks the server-side request forgery path to the metadata endpoint.",
      "An instance can only have one role attached, and a second one would not change how metadata is reached.",
      "Subnet placement changes routing, not local access to the metadata service.",
      "Replacing rotating temporary credentials with a static key file makes the exposure permanently worse."],
  "x":"Instance credentials are served locally by the metadata service, so no network control protects them. IMDSv2's token requirement is the specific hardening for the SSRF pattern that leaks them."},
 {"m":"identities",
  "q":"A startup wants its mobile app's customers to sign in and then upload directly to S3 with temporary AWS credentials. Which service fits?",
  "o":["Amazon Cognito, with an identity pool issuing temporary credentials",
       "IAM Identity Center with a permission set per customer",
       "An IAM user created per customer at sign-up",
       "The root user with MFA enabled"],
  "a":[0],
  "w":["Correct — Cognito user pools handle app sign-in and identity pools exchange that identity for scoped temporary AWS credentials.",
      "Identity Center is built for workforce access across accounts, not for consumers of an application.",
      "Creating an IAM user per customer hits account limits and leaves permanent credentials everywhere.",
      "Root is a single account-level identity and can never represent application users."],
  "x":"The cue is who signs in. Customers of an application are Cognito's job — the user pool authenticates them and the identity pool trades that token for temporary credentials scoped by an IAM role."}
]
}
