# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 1,
"nm": "EC2 Fundamentals",
"tag": "Compute",
"modules": [
{
 "id": "instance-basics",
 "nm": "What an instance is made of",
 "goal": "Name the five things you choose when launching an instance, and what user data does.",
 "min": 7,
 "blocks": [
  {"t":"p","x":"EC2 is a virtual machine you rent by the second. Launching one is really five decisions, and the exam questions are almost always about one of them."},
  {"t":"table","head":["Decision","What it controls"],
   "rows":[
    ["AMI","The operating system and any software baked into the image"],
    ["Instance type","How much CPU, memory, network and storage the machine gets"],
    ["Storage","EBS volumes that outlive the instance, or instance store that does not"],
    ["Security group","Which traffic may reach it — a firewall, attached to the instance"],
    ["Key pair","The SSH key you will log in with, downloadable exactly once"]]},
  {"t":"h","x":"User data"},
  {"t":"p","x":"A script passed at launch that runs **once, on the first boot, as root**. It is how an instance configures itself — installing packages, pulling code, registering with a load balancer."},
  {"t":"key","x":"User data runs once at first boot, not on every restart, and it runs with root privileges. A question about \"bootstrapping\" or \"automatically install software at launch\" means user data."},
  {"t":"h","x":"Stop, terminate, reboot — three different things"},
  {"t":"table","head":["Action","Instance store data","EBS root volume","Public IPv4"],
   "rows":[
    ["Reboot","Kept","Kept","Kept"],
    ["Stop / start","**Lost**","Kept","**New one on start**"],
    ["Terminate","Lost","Deleted unless you said otherwise","Gone"]]},
  {"t":"trap","x":"Stopping and starting an instance gives it a *different* public IPv4 address. If something must keep the same address across a stop, that is an Elastic IP — or, better, a load balancer or a DNS record."},
  {"t":"h","x":"Billing"},
  {"t":"list","x":[
   "A stopped instance costs nothing for compute, but its **EBS volumes are still billed**.",
   "Linux and Windows are billed per second after the first minute; some other operating systems are billed per hour.",
   "Data transfer *into* AWS is free; transfer out to the internet is where the cost is."]}
 ],
 "checks":[
  {"q":"A script must install and start a web server the first time an instance boots. Where does it go?",
   "o":["In the user data of the instance","In the security group","In the key pair","In the instance type"],
   "a":[0],
   "x":"User data is the bootstrap script. It runs once on first boot, as root, which is exactly what installing and starting software at launch requires."},
  {"q":"An instance is stopped and started again. What happens to its public IPv4 address?",
   "o":["It is replaced with a new address","It stays the same forever","It becomes a private address","It is released only on terminate"],
   "a":[0],
   "x":"A public IPv4 is leased for the life of a running instance. Stopping it releases the address, and starting again takes a fresh one — which is why anything that needs a stable address uses an Elastic IP or a DNS name."},
  {"q":"Which data is lost when an instance is stopped and started?",
   "o":["Data on the instance store","Data on an EBS root volume","The security group rules","The key pair"],
   "a":[0],
   "x":"Instance store is physically attached disk that does not survive a stop. EBS volumes are network storage and persist; security groups and key pairs are configuration, not data."},
  {"q":"A stopped instance still generates a bill. For what?",
   "o":["Its attached EBS volumes","Its vCPU hours","Its user data script","Its security group"],
   "a":[0],
   "x":"Compute stops being billed when the instance stops, but the EBS volumes keep existing and keep costing. Deleting the volume, or the instance, is what stops that charge."}
 ]
},
{
 "id":"instance-types",
 "nm":"Instance families and how to read a type name",
 "goal":"Pick the right instance family from the words a question uses to describe a workload.",
 "min":6,
 "blocks":[
  {"t":"p","x":"An instance type name such as `m5.2xlarge` reads as family, generation, then size. The letter is what the exam cares about."},
  {"t":"table","head":["Family","Optimised for","The wording that points at it"],
   "rows":[
    ["**T** (t3, t4g)","Burstable, cheap baseline","\"low traffic most of the time with occasional spikes\", dev and test"],
    ["**M**","General purpose, balanced","\"a typical web application\", no stated bias"],
    ["**C**","Compute — high CPU per dollar","\"batch processing\", \"high performance computing\", \"media transcoding\", \"gaming servers\""],
    ["**R**, **X**, **z**","Memory — large RAM","\"in-memory database\", \"large caches\", \"SAP HANA\", \"real-time big data analytics\""],
    ["**I**, **D**, **H**","Storage — fast local disk","\"very high IOPS from local storage\", \"data warehousing\", \"distributed file systems\""],
    ["**P**, **G**, **Inf**","Accelerated — GPU or inference chips","\"machine learning training\", \"graphics rendering\""]]},
  {"t":"key","x":"Reading the letter is usually enough: C for compute-bound, R for memory-bound, I for storage-bound, M when nothing is emphasised."},
  {"t":"h","x":"Burstable instances and CPU credits"},
  {"t":"list","x":[
   "A T instance runs at a baseline percentage of a vCPU and earns **CPU credits** while it stays under that baseline.",
   "A spike spends credits to run at full speed. Run out of credits and performance is throttled back to the baseline.",
   "**Unlimited mode** lets it keep bursting past zero credits for an extra charge — the fix when a T instance is throttling but you do not want to resize."]},
  {"t":"trap","x":"A T instance that \"gets slower after a while under sustained load\" has exhausted its CPU credits. The answer is unlimited mode or a different family — not more memory, and not a bigger EBS volume."},
  {"t":"h","x":"Changing your mind"},
  {"t":"p","x":"Resizing an instance means **stop, change the type, start**. It is not a live operation, so a question that forbids downtime wants a load balancer and more instances rather than a bigger one."}
 ],
 "checks":[
  {"q":"A nightly job transcodes video and is limited entirely by CPU. Which instance family fits?",
   "o":["Compute optimised — the C family","Memory optimised — the R family","Storage optimised — the I family","Burstable — the T family"],
   "a":[0],
   "x":"Media transcoding is the textbook compute-bound workload, and the C family gives the most CPU per dollar. Memory and storage families spend money on resources this job does not use."},
  {"q":"An in-memory database needs to hold a very large working set in RAM. Which family?",
   "o":["The R family","The C family","The T family","The D family"],
   "a":[0],
   "x":"R is the memory optimised family, built for in-memory databases and large caches. Compute, burstable and dense-storage families all give far less RAM per instance."},
  {"q":"A t3 instance performs well at first and then slows down under sustained load. What explains it?",
   "o":["It has exhausted its CPU credits and is throttled to its baseline",
        "Its EBS volume is full",
        "Its security group is rate limiting traffic",
        "The user data script is still running"],
   "a":[0],
   "x":"Burstable instances earn CPU credits while idle and spend them while bursting. Once the balance hits zero, performance falls back to the baseline — which is what sustained load looks like from the outside."},
  {"q":"How do you change an existing instance from m5.large to m5.2xlarge?",
   "o":["Stop it, change the instance type, then start it",
        "Change it live with no interruption",
        "Terminate it and restore from an instance store snapshot",
        "Edit the user data and reboot"],
   "a":[0],
   "x":"Resizing requires the instance to be stopped, which means downtime. When a question forbids downtime, the answer is scaling out behind a load balancer instead of scaling up."}
 ]
},
{
 "id":"security-groups",
 "nm":"Security groups and the ports that matter",
 "goal":"Diagnose a connection failure from the security group rules, and name the classic ports.",
 "min":7,
 "blocks":[
  {"t":"p","x":"A security group is a firewall attached to an instance's network interface. It has one property that decides most exam questions: it only ever **allows**."},
  {"t":"h","x":"The rules of security groups"},
  {"t":"list","x":[
   "**Allow rules only.** There is no deny rule. Anything not allowed is blocked by default.",
   "**Stateful.** If the inbound request is allowed, the reply goes back out automatically, whatever the outbound rules say.",
   "Inbound is **blocked by default**; outbound is **allowed by default**.",
   "A rule's source can be an IP range **or another security group** — that is how you say \"only the web tier may reach the database tier\" without hard-coding addresses.",
   "One security group can be attached to many instances, and one instance can have several."]},
  {"t":"key","x":"A source that names another security group is the cleanest answer for tier-to-tier access: the rule keeps working as instances come and go, because it never mentions an address."},
  {"t":"h","x":"Reading a failed connection"},
  {"t":"dtree","x":[
   ["The connection times out","Almost always a security group (or a NACL, or a route) — nothing replied at all"],
   ["The connection is refused","The network got through; the application on that port is not running"],
   ["It works from inside the VPC but not outside","Check the public IP, the route table and the internet gateway, not just the group"]]},
  {"t":"h","x":"Ports worth memorising"},
  {"t":"table","head":["Port","Protocol"],
   "rows":[["22","SSH — and SFTP, which runs over it"],["21","FTP"],["80","HTTP"],["443","HTTPS"],
           ["3389","RDP, for Windows"],["3306","MySQL and Aurora MySQL"],["5432","PostgreSQL"],
           ["1433","Microsoft SQL Server"],["1521","Oracle"],["6379","Redis"],["11211","Memcached"]]},
  {"t":"trap","x":"A timeout is a security group problem. \"Connection refused\" is not — the packets arrived, so the firewall let them through and the application is the thing that is down."}
 ],
 "checks":[
  {"q":"SSH to an instance times out. What is the most likely cause?",
   "o":["A security group that does not allow inbound port 22 from your address",
        "The SSH daemon is not running","The key pair is the wrong format","The instance type is too small"],
   "a":[0],
   "x":"A timeout means nothing answered at all, which points at the network path — the security group first. If the daemon were down you would get a connection refused instead, because the packets would have reached the instance."},
  {"q":"Which statement about security groups is true?",
   "o":["They contain allow rules only, and are stateful",
        "They contain both allow and deny rules","They are stateless, so replies need their own rule",
        "They apply to a whole subnet"],
   "a":[0],
   "x":"Security groups only allow, and because they are stateful the return traffic for an allowed request is automatically permitted. Deny rules and stateless evaluation belong to network ACLs, which work at the subnet level."},
  {"q":"Only the web tier should be able to reach the database instances. What is the cleanest rule?",
   "o":["Allow inbound on the database port with the web tier's security group as the source",
        "Allow inbound from 0.0.0.0/0 on the database port",
        "Allow inbound from each web server's private IP, updated by hand",
        "Remove all outbound rules from the web tier"],
   "a":[0],
   "x":"Naming the other security group as the source keeps working as web servers are added and removed, because no address is written down. Hard-coded IPs break the moment Auto Scaling replaces an instance."},
  {"q":"Which port does an application connect to for a PostgreSQL database?",
   "o":["5432","3306","1433","6379"],
   "a":[0],
   "x":"PostgreSQL listens on 5432. MySQL and Aurora MySQL use 3306, Microsoft SQL Server 1433, and Redis 6379 — these show up in security group questions constantly."}
 ]
},
{
 "id":"access-roles",
 "nm":"Getting in, and letting the instance out",
 "goal":"Choose the right way to reach an instance, and the right way for it to call AWS.",
 "min":6,
 "blocks":[
  {"t":"h","x":"Three ways to reach an instance"},
  {"t":"table","head":["Way","What it needs","Good for"],
   "rows":[
    ["SSH with a key pair","Port 22 open, the private key file","The normal path from a laptop"],
    ["EC2 Instance Connect","Port 22 open to the Instance Connect service, IAM permission","Browser access with no key file to manage"],
    ["Systems Manager Session Manager","The SSM agent and an instance role — **no open port at all**","The answer when the question says no inbound ports or no bastion"]]},
  {"t":"key","x":"\"Administrators must reach instances in a private subnet without opening any inbound port and without a bastion host\" is Session Manager, every time."},
  {"t":"h","x":"The key pair"},
  {"t":"list","x":[
   "The private key is downloadable **once**, at creation. Lose it and you cannot recover it from AWS.",
   "On Linux and Mac the key file must be readable only by you, or SSH refuses it.",
   "Locked out of a Linux instance? Detach the root EBS volume, attach it to another instance, fix the authorized keys, reattach."]},
  {"t":"h","x":"Letting the instance call AWS"},
  {"t":"flow","x":["Instance needs S3","Its attached IAM role","Metadata serves temporary keys","The SDK signs the call"],
   "cap":"No access keys are stored anywhere on the instance."},
  {"t":"trap","x":"Access keys written into a file, an environment variable or an AMI is always the wrong answer for an instance calling AWS. The right one is an IAM role, attached through an instance profile."}
 ],
 "checks":[
  {"q":"Administrators must get a shell on instances in a private subnet with no inbound ports open and no bastion host. What do you use?",
   "o":["Systems Manager Session Manager","SSH over port 22 through an internet gateway",
        "EC2 Instance Connect over the public internet","A VPN to each instance"],
   "a":[0],
   "x":"Session Manager works through the SSM agent calling out, so no inbound port needs to be open and no bastion is needed. Every other option requires an inbound path to the instance."},
  {"q":"An application on EC2 needs to read from S3. How should it authenticate?",
   "o":["Through an IAM role attached to the instance",
        "With access keys in an environment variable",
        "With access keys baked into the AMI",
        "With the key pair used for SSH"],
   "a":[0],
   "x":"An attached role gives the instance temporary credentials that rotate automatically and are never written to disk. Stored access keys are the standard wrong answer, and the SSH key pair has nothing to do with AWS API calls."},
  {"q":"You lost the private key file for a running Linux instance. What is the recovery path?",
   "o":["Detach the root EBS volume, attach it to another instance, fix the authorized keys, reattach",
        "Download the private key again from the console",
        "Reset it from the instance's security group",
        "Change the instance type to regenerate the key"],
   "a":[0],
   "x":"AWS lets you download a private key once and keeps no copy, so recovery means editing the file system directly by moving the root volume to an instance you can already reach."},
  {"q":"What does EC2 Instance Connect give you?",
   "o":["Browser-based SSH with no long-lived key file to manage",
        "A private connection to S3","A second network interface","Automatic patching of the operating system"],
   "a":[0],
   "x":"Instance Connect pushes a short-lived key for a single session and lets you connect from the console, so there is no permanent key file. It still needs port 22 reachable from the Instance Connect service."}
 ]
},
{
 "id":"purchasing",
 "nm":"Purchasing options: paying less for the same compute",
 "goal":"Match a workload's tolerance for interruption and commitment to the cheapest correct option.",
 "min":8,
 "blocks":[
  {"t":"p","x":"Every pricing question is the same question: how predictable is this workload, and can it survive being interrupted?"},
  {"t":"table","head":["Option","Commitment","Discount","Use it when"],
   "rows":[
    ["On-Demand","None","—","Short, unpredictable, or first-time workloads"],
    ["Reserved Instance","1 or 3 years, a specific family and region","Large","A steady workload that will not change, such as a database"],
    ["Savings Plan","1 or 3 years, a dollars-per-hour spend","Large","A steady spend where you still want to change instance types"],
    ["Spot","None, but AWS can reclaim it","Largest","Anything interruptible: batch, rendering, CI, big-data workers"],
    ["Dedicated Instance","None","—","Hardware not shared with other customers"],
    ["Dedicated Host","Optional","—","**Per-socket licensing** or visibility of the physical server"],
    ["Capacity Reservation","None, pay whether used or not","—","Guaranteed capacity in one AZ for a known burst"]]},
  {"t":"key","x":"Spot is the answer whenever the workload is described as fault tolerant, interruptible, stateless, or batch. Never Spot for a database, a queue consumer that must not miss messages, or anything holding state locally."},
  {"t":"h","x":"Spot, precisely"},
  {"t":"list","x":[
   "You set a maximum price. The instance runs while the Spot price stays below it.",
   "When capacity is reclaimed you get a **two-minute interruption notice** — enough to drain work, checkpoint, and deregister.",
   "A **Spot Fleet** meets a target capacity across several pools, mixing Spot and On-Demand so a single pool running out does not take the fleet down.",
   "Spot **Blocks** are gone; do not pick an answer that promises an uninterruptible Spot instance."]},
  {"t":"h","x":"Reserved versus Savings Plan"},
  {"t":"split","cols":[
   {"nm":"Reserved Instance","items":["Commits to an instance family and region","Can be Standard (cheapest, rigid) or Convertible (flexible, less discount)","Sellable on the Reserved Instance Marketplace"]},
   {"nm":"Savings Plan","items":["Commits to an hourly spend, not a machine","Compute Savings Plans also cover Fargate and Lambda","Simpler when instance types will change"]}]},
  {"t":"trap","x":"\"Licensing is charged per physical socket or per core\" means a **Dedicated Host** — that is the only option that exposes the physical server. A Dedicated Instance gives you isolated hardware but no visibility into it."}
 ],
 "checks":[
  {"q":"A batch job runs for hours, can be restarted from a checkpoint, and cost is the main concern. Which purchasing option?",
   "o":["Spot Instances","Reserved Instances","Dedicated Hosts","On-Demand"],
   "a":[0],
   "x":"Interruptible and restartable is exactly the profile Spot is priced for, and it is the deepest discount available. Reserved commits for a year, and On-Demand simply costs more for the same work."},
  {"q":"Software is licensed per physical socket and must be audited against the actual hardware. Which option?",
   "o":["Dedicated Hosts","Dedicated Instances","Spot Instances","Reserved Instances"],
   "a":[0],
   "x":"Only a Dedicated Host exposes the physical server — its sockets and cores — which is what per-socket licensing and hardware audits require. A Dedicated Instance isolates the hardware but tells you nothing about it."},
  {"q":"How much warning does a Spot Instance get before it is reclaimed?",
   "o":["A two-minute interruption notice","No warning at all","One hour","Twenty-four hours"],
   "a":[0],
   "x":"The two-minute notice is what makes graceful handling possible: drain work, checkpoint state, and deregister from the load balancer before the instance disappears."},
  {"q":"A company wants a large discount on a steady compute spend but expects to move between instance families during the year. What fits best?",
   "o":["A Compute Savings Plan","A Standard Reserved Instance","Spot Instances","Capacity Reservations"],
   "a":[0],
   "x":"A Compute Savings Plan commits to an hourly spend rather than a machine, so changing family or region keeps the discount. A Standard Reserved Instance is locked to a family, and Spot cannot promise steady capacity."}
 ]
}
],
"recap":[
 {"t":"h","x":"The five launch decisions"},
 {"t":"table","head":["Decision","What a question is really asking"],
  "rows":[
   ["AMI","Which operating system, and is the software pre-baked or installed by user data?"],
   ["Instance type","Is this workload CPU, memory or storage bound?"],
   ["Storage","Must the data survive a stop? Then EBS, not instance store"],
   ["Security group","Who may reach it — and a timeout means this is wrong"],
   ["Key pair","How you get in, unless the answer is Session Manager"]]},
 {"t":"h","x":"Family selection, in one table"},
 {"t":"table","head":["Wording","Family"],
  "rows":[["Batch, HPC, transcoding, gaming servers","C — compute"],
          ["In-memory database, large cache, SAP HANA","R or X — memory"],
          ["Very high local IOPS, data warehouse","I or D — storage"],
          ["Machine learning training, rendering","P or G — accelerated"],
          ["Spiky low-traffic app, dev and test","T — burstable"],
          ["A normal web application","M — general purpose"]]},
 {"t":"h","x":"Cost decisions"},
 {"t":"dtree","x":[
  ["Interruptible, stateless, batch","Spot — and a Spot Fleet if capacity must be met"],
  ["Steady for a year or more, fixed family","Reserved Instance"],
  ["Steady spend, changing instance types","Savings Plan"],
  ["Per-socket or per-core licensing","Dedicated Host"],
  ["Guaranteed capacity in one AZ for a known event","Capacity Reservation"],
  ["Short, unpredictable, or being measured","On-Demand"]]},
 {"t":"key","x":"State lives on EBS, never on instance store, unless losing it is acceptable. Stop and start gives a new public IPv4. A timeout is the security group; a refusal is the application."},
 {"t":"h","x":"Access paths compared"},
 {"t":"split","cols":[
  {"nm":"Needs an open port","items":["SSH with a key pair","EC2 Instance Connect","A bastion host in a public subnet"]},
  {"nm":"Needs no open port","items":["Session Manager through the SSM agent","IAM role for AWS API calls","VPC endpoints for private service access"]}]},
 {"t":"trap","x":"Recurring distractors: access keys on the instance instead of a role; instance store for data that must survive; resizing an instance when the requirement says no downtime; Spot for a stateful database; and a Dedicated Instance where the licensing needs a Dedicated Host."},
 {"t":"h","x":"Ports, one last time"},
 {"t":"table","head":["22 / 3389","80 / 443","3306 / 5432 / 1433 / 1521","6379 / 11211"],
  "rows":[["SSH / RDP","HTTP / HTTPS","MySQL / PostgreSQL / SQL Server / Oracle","Redis / Memcached"]]}
],
"final":[
 {"m":"purchasing",
  "q":"A rendering pipeline processes thousands of independent frames, and any frame can be retried. Which purchasing option minimises cost?",
  "o":["Spot Instances, with the two-minute notice used to requeue the frame in flight",
       "Reserved Instances for three years","On-Demand instances in several AZs","Dedicated Hosts"],
  "a":[0],
  "w":["Correct — independent, retryable work is exactly what Spot exists for, and the interruption notice makes the retry orderly.",
      "A three-year commitment locks in capacity for a workload described as burstable and interruptible, and costs far more than Spot.",
      "On-Demand across AZs improves availability but pays full price for work that tolerates interruption.",
      "Dedicated Hosts are about hardware isolation and licensing, and are the most expensive option here."],
  "x":"Interruptible, stateless and retryable is the Spot profile. The two-minute interruption notice lets a worker put its frame back on the queue before it disappears, so no work is lost even though the instance is."},
 {"m":"security-groups",
  "q":"A web server can be reached on port 443 but its calls to a database instance time out. Both are in the same VPC. What should you check first?",
  "o":["The database security group's inbound rule for the database port",
       "The web server's outbound rules, which block replies",
       "The database instance type","The key pair on the database instance"],
  "a":[0],
  "w":["Correct — inbound is denied by default, so the database group must explicitly allow the web tier on the database port.",
      "Security groups are stateful, so replies to an allowed request are never blocked by outbound rules.",
      "Instance size affects speed, not whether a connection is accepted at all.",
      "Key pairs authenticate SSH sessions and have nothing to do with a database connection."],
  "x":"A timeout means the packets never got a response, and inbound traffic is blocked by default. The clean rule allows the database port with the web tier's security group as the source, so it survives instances being replaced."},
 {"m":"instance-basics",
  "q":"An application writes temporary scratch files to the instance store. The instance is stopped overnight to save money. What happens to those files?",
  "o":["They are lost, because instance store does not survive a stop",
       "They are preserved, because AWS snapshots instance store automatically",
       "They move to the EBS root volume","They are preserved only if the instance is in a private subnet"],
  "a":[0],
  "w":["Correct — instance store is physically attached disk, released the moment the instance stops.",
      "There is no automatic snapshot of instance store; that is an EBS feature.",
      "Nothing migrates data between volumes on its own.",
      "Subnet placement has no bearing on storage durability."],
  "x":"Instance store is ephemeral by design: fast, local and gone on stop or termination. Anything that must survive belongs on EBS, or on S3 if it is shared."},
 {"m":"instance-types",
  "q":"A t3.medium runs a reporting job that now takes hours. Monitoring shows the CPU credit balance sitting at zero. Which change addresses the cause with the least redesign?",
  "o":["Enable unlimited mode, or move to a compute optimised instance",
       "Attach a larger EBS volume","Add a second network interface","Move the instance to another Availability Zone"],
  "a":[0],
  "w":["Correct — a zero credit balance throttles the instance to its baseline, and both of these restore full CPU.",
      "Disk size does not affect CPU throttling, and the symptom is a CPU credit balance.",
      "Network interfaces add addresses, not processing capacity.",
      "Availability Zones affect resilience and latency, not CPU credits."],
  "x":"Burstable instances trade cheap idle time for throttling under sustained load. Unlimited mode buys the burst for a fee; a C-family instance removes the credit mechanism entirely, which suits a job that is CPU-bound for hours."},
 {"m":"access-roles",
  "q":"A security policy forbids any inbound port on production instances, and bastion hosts are being removed. How should engineers get a shell?",
  "o":["Systems Manager Session Manager with an instance role and the SSM agent",
       "EC2 Instance Connect over port 22","SSH from a NAT gateway","RDP over port 3389 restricted to the office IP"],
  "a":[0],
  "w":["Correct — the agent makes an outbound connection, so nothing needs to listen on the instance.",
      "Instance Connect still requires port 22 to be reachable.",
      "A NAT gateway carries outbound traffic only and cannot accept an inbound SSH session.",
      "Restricting RDP by address still means an inbound port is open, which the policy forbids."],
  "x":"Session Manager reverses the direction: the instance connects out to Systems Manager, and the session is brokered there. That satisfies \"no inbound ports, no bastion\" while keeping full IAM control and an audit trail."},
 {"m":"instance-basics",
  "q":"An instance must keep the same public IP address across stops and starts. What provides this?",
  "o":["An Elastic IP associated with the instance",
       "A larger instance type","A second security group","A user data script that requests the old address"],
  "a":[0],
  "w":["Correct — an Elastic IP is an address you own and can keep attached across stop and start.",
      "Instance size has no effect on addressing.",
      "Security groups filter traffic; they do not assign addresses.",
      "There is no mechanism for reclaiming a released public IPv4 from user data."],
  "x":"Default public IPv4 addresses are leased per run, so a stop releases them. An Elastic IP is allocated to your account and stays with whatever you associate it to — though a load balancer or DNS record is usually the better design."},
 {"m":"purchasing",
  "q":"Finance wants a discount on a predictable production workload, but the architecture team expects to migrate from m5 to m6i instances within the year. Which commitment fits?",
  "o":["A Compute Savings Plan","A Standard Reserved Instance for m5","Capacity Reservations in one AZ","Spot Instances with a fleet"],
  "a":[0],
  "w":["Correct — it commits to spend per hour, so the discount follows the workload across families and regions.",
      "A Standard RI is tied to the m5 family, so the planned migration would waste it.",
      "Capacity Reservations guarantee capacity but give no discount at all.",
      "Spot cannot underpin a steady production workload that must not be interrupted."],
  "x":"The distinguishing requirement is a planned change of instance family. Savings Plans commit to dollars per hour rather than to a machine, which is exactly the flexibility a migration needs."},
 {"m":"instance-types",
  "q":"A workload keeps a 400 GB dataset entirely in memory for sub-millisecond lookups. Which instance family should be chosen?",
  "o":["Memory optimised, such as the R family",
       "Compute optimised, such as the C family","Storage optimised, such as the I family","Burstable, such as the T family"],
  "a":[0],
  "w":["Correct — the constraint is RAM per instance, which is what memory optimised families are built around.",
      "Compute optimised maximises CPU per dollar and offers comparatively little memory.",
      "Storage optimised gives fast local disk, which is not where this dataset lives.",
      "Burstable instances are small and throttle under sustained load."],
  "x":"Pick the family from the binding resource. \"Held entirely in memory\" names RAM as the constraint, which is the R (or X) family; disk and CPU choices would leave the dataset unable to fit."},
 {"m":"security-groups",
  "q":"An engineer reports \"connection refused\" when reaching a web server on port 80. What does that tell you?",
  "o":["The traffic reached the instance and nothing is listening on port 80",
       "The security group is blocking port 80","The route table has no internet gateway","The instance has no public IP"],
  "a":[0],
  "w":["Correct — a refusal is an active response, so the packets arrived and the network path is open.",
      "A blocked port produces a timeout, not a refusal, because nothing answers at all.",
      "A missing route also produces a timeout.",
      "With no public IP the connection would never reach the instance to be refused."],
  "x":"The distinction is worth memorising: a timeout is a network problem — security group, NACL, route, address. A refusal proves the network worked and points at the service on the instance."},
 {"m":"access-roles",
  "q":"Which approach lets an EC2 application call DynamoDB without any credential ever being stored on the instance?",
  "o":["An IAM role attached through an instance profile",
       "An IAM user's access keys in ~/.aws/credentials","Access keys baked into the AMI","The instance's SSH key pair"],
  "a":[0],
  "w":["Correct — the metadata service supplies temporary credentials that the SDK refreshes automatically.",
      "A credentials file is a stored long-lived secret, which is what the question rules out.",
      "Keys baked into an AMI spread to every instance launched from it and cannot be rotated.",
      "An SSH key pair authenticates shell logins and is not an AWS API credential at all."],
  "x":"An instance profile carries the role; the SDK reads temporary credentials from instance metadata and refreshes them before expiry. Nothing is written to disk, so there is no secret to leak or rotate."}
]
}
