# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 2,
"nm": "EC2 at Solutions Architect level",
"tag": "Compute",
"modules": [
{
 "id": "addressing",
 "nm": "Private, public and Elastic IPs",
 "goal": "Say which address an instance has, when it changes, and when an Elastic IP is right.",
 "min": 6,
 "blocks": [
  {"t":"p","x":"Every instance has a **private** IPv4 from its subnet. It may also have a **public** IPv4, which is not configured on the instance at all — the internet gateway translates between the two."},
  {"t":"table","head":["Address","Scope","Survives a stop","Costs"],
   "rows":[
    ["Private IPv4","Inside the VPC only","Yes, it is fixed for the life of the instance","Free"],
    ["Public IPv4","Reachable from the internet","**No — a new one on start**","Charged per hour"],
    ["Elastic IP","Reachable from the internet","Yes, you own it","Charged, and charged more when not attached"]]},
  {"t":"key","x":"An Elastic IP is a fixed public address you own. You are limited to five per region by default, and AWS charges for one that is allocated but not associated — the opposite of most services."},
  {"t":"h","x":"When an Elastic IP is the wrong answer"},
  {"t":"p","x":"Needing a fixed address is usually a sign of an architecture that has not been made elastic. The better answers are a **load balancer** in front of instances, or a **Route 53 record** pointing at whatever is current."},
  {"t":"flow","x":["Client","Route 53 name","Load balancer","Any healthy instance"],
   "cap":"No client ever learns an instance address, so instances can come and go."},
  {"t":"trap","x":"An answer that gives every Auto Scaling instance an Elastic IP is wrong: it does not scale, it hits the per-region limit, and it defeats the point of a load balancer."},
  {"t":"h","x":"Inside the VPC"},
  {"t":"list","x":[
   "Instances talk to each other on **private** addresses. Routing through a public address costs money and adds latency.",
   "A public IPv4 is only assigned if the subnet or the launch says so — the setting is `auto-assign public IPv4`.",
   "IPv6 addresses on AWS are all public, and they do not change on stop."]}
 ],
 "checks":[
  {"q":"Which address does an instance keep unchanged for its whole life?",
   "o":["Its private IPv4","Its public IPv4","Its DNS cache entry","Its instance type"],
   "a":[0],
   "x":"The private IPv4 comes from the subnet and stays with the instance until it is terminated. A public IPv4 is leased per run and is replaced after a stop and start."},
  {"q":"When is an allocated Elastic IP charged at a higher rate?",
   "o":["When it is not associated with a running instance","When it is attached to a running instance",
        "Only when traffic flows through it","Never — Elastic IPs are free"],
   "a":[0],
   "x":"AWS prices idle Elastic IPs deliberately, because addresses are scarce. Holding one that is not attached is the expensive case, which is why unused allocations should be released."},
  {"q":"Fleet instances behind Auto Scaling need to be reachable by clients. What is the right design?",
   "o":["A load balancer in front, with clients resolving a DNS name",
        "An Elastic IP per instance, published to clients",
        "Public IPv4 addresses shared by all instances",
        "Clients connecting on private addresses over the internet"],
   "a":[0],
   "x":"Clients should never know instance addresses. A load balancer plus a DNS name lets instances be replaced freely, and avoids the Elastic IP limit of five per region."},
  {"q":"Two instances in the same VPC communicate. Which address should they use?",
   "o":["Their private IPv4 addresses","Their public IPv4 addresses",
        "Their Elastic IPs","The VPC's CIDR broadcast address"],
   "a":[0],
   "x":"Private addressing keeps the traffic inside the VPC, which is faster and free. Going out and back through public addresses adds latency and data transfer charges for no benefit."}
 ]
},
{
 "id":"placement-groups",
 "nm":"Placement groups",
 "goal":"Choose cluster, spread or partition from what the workload is afraid of.",
 "min":6,
 "blocks":[
  {"t":"p","x":"A placement group tells AWS how to position your instances relative to each other. There are three strategies and they solve opposite problems."},
  {"t":"split","cols":[
   {"nm":"Cluster","items":["All in one rack, one AZ","Lowest latency, highest throughput between instances","If that rack fails, everything fails","For tightly coupled HPC and low-latency workloads"]},
   {"nm":"Spread","items":["Each instance on distinct hardware","Maximum isolation from hardware failure","Hard limit: **seven instances per AZ** per group","For a small number of critical instances"]},
   {"nm":"Partition","items":["Instances grouped into partitions, each on its own set of racks","Up to seven partitions per AZ, hundreds of instances","A rack failure takes out one partition, not the group","For HDFS, Cassandra, Kafka — anything rack-aware"]}]},
  {"t":"key","x":"Cluster for speed, spread for isolation, partition for large distributed data systems that already understand racks."},
  {"t":"h","x":"The numbers that get tested"},
  {"t":"table","head":["Strategy","Limit","Failure behaviour"],
   "rows":[
    ["Cluster","One AZ","A single rack failure can take out the whole group"],
    ["Spread","Seven instances per AZ","One failure affects one instance"],
    ["Partition","Seven partitions per AZ","One failure affects one partition"]]},
  {"t":"trap","x":"\"Spread placement group with 20 instances in one Availability Zone\" is impossible — the limit is seven per AZ. Either spread across more AZs or use a partition group."},
  {"t":"note","x":"Placement groups can be changed, but the instance has to be stopped to move it in or out of one."}
 ],
 "checks":[
  {"q":"A tightly coupled HPC job needs the lowest possible network latency between nodes. Which placement group?",
   "o":["Cluster","Spread","Partition","No placement group at all"],
   "a":[0],
   "x":"A cluster group packs instances onto the same rack, which gives the lowest latency and highest throughput between them. The cost is that a single rack failure can take the whole group down."},
  {"q":"What is the limit on a spread placement group?",
   "o":["Seven instances per Availability Zone","Seven instances in total across all zones",
        "Seven partitions per Availability Zone","There is no limit"],
   "a":[0],
   "x":"Spread guarantees distinct underlying hardware per instance, and AWS caps that at seven instances per AZ per group. Larger deployments need a partition group instead."},
  {"q":"A Cassandra cluster of forty nodes should survive a rack failure without losing a whole replica set. Which placement group?",
   "o":["Partition","Cluster","Spread","Cluster inside a spread group"],
   "a":[0],
   "x":"Partition groups map naturally onto rack-aware distributed systems: each partition sits on its own racks, so a failure removes one partition rather than random nodes across the cluster."},
  {"q":"A workload must move an existing instance into a placement group. What does that require?",
   "o":["Stopping the instance first","Nothing — it can be done live",
        "Terminating and relaunching from an AMI only","Changing the instance's subnet"],
   "a":[0],
   "x":"Placement is decided when the instance starts, so joining or leaving a group needs a stop and start. That makes it a planned change rather than a live one."}
 ]
},
{
 "id":"eni",
 "nm":"Elastic Network Interfaces",
 "goal":"Explain what an ENI carries and why moving one is a failover technique.",
 "min":5,
 "blocks":[
  {"t":"p","x":"An **ENI** is a virtual network card. The instance is not really where the network identity lives — the interface is."},
  {"t":"h","x":"What an ENI carries"},
  {"t":"list","x":[
   "A primary private IPv4, and optionally several secondary private IPv4 addresses.",
   "One Elastic IP per private address, and optionally a public IPv4.",
   "A MAC address, and one or more security groups.",
   "It is **bound to one Availability Zone** and can only attach to instances in that zone."]},
  {"t":"key","x":"Detaching an ENI from a failed instance and attaching it to a standby moves the private address, the Elastic IP and the security groups in one step. That is a low-cost failover pattern for an appliance with a fixed address."},
  {"t":"h","x":"Why a second interface"},
  {"t":"table","head":["Reason","What it looks like"],
   "rows":[
    ["Management separation","One interface for application traffic, one for administration, each with its own security group"],
    ["Network appliances","A firewall or proxy instance with a public side and a private side"],
    ["Failover","A standby instance takes over the interface, and with it the address clients already know"]]},
  {"t":"trap","x":"An ENI cannot cross an Availability Zone. A failover design that moves an interface to a standby in another AZ does not work — that standby needs its own interface and a DNS or load balancer change."}
 ],
 "checks":[
  {"q":"What moves with an ENI when it is attached to a different instance?",
   "o":["Its private IP, Elastic IP and security groups","Only its MAC address",
        "Its attached EBS volumes","Its instance type"],
   "a":[0],
   "x":"The network identity lives on the interface, so addresses and security groups travel with it. Storage and instance sizing are properties of the instance and stay behind."},
  {"q":"Can an ENI be moved to an instance in a different Availability Zone?",
   "o":["No — an ENI is bound to one Availability Zone","Yes, within the same region",
        "Yes, within the same VPC","Yes, but only if it has an Elastic IP"],
   "a":[0],
   "x":"An ENI belongs to a subnet, and a subnet lives in exactly one AZ. Cross-zone failover therefore has to be handled with DNS or a load balancer, not by moving an interface."},
  {"q":"Why give a network appliance instance two ENIs?",
   "o":["To separate a public-facing side from a private side, each with its own security group",
        "To double its CPU","To get more EBS throughput","To join two placement groups at once"],
   "a":[0],
   "x":"Two interfaces give two independent network identities and two sets of security group rules, which is how a firewall or proxy separates the traffic it accepts from the traffic it forwards."},
  {"q":"An instance with a fixed private address fails. What is the fastest way to restore service on a standby in the same Availability Zone?",
   "o":["Detach the ENI and attach it to the standby","Change the standby's instance type",
        "Recreate the subnet","Assign the standby a new Elastic IP and tell clients"],
   "a":[0],
   "x":"Moving the interface carries the address and security groups over in one action, so existing clients keep working without any change on their side."}
 ]
},
{
 "id":"hibernate",
 "nm":"Hibernate and the instance lifecycle",
 "goal":"Decide between stop, hibernate and terminate, and name hibernate's constraints.",
 "min":5,
 "blocks":[
  {"t":"p","x":"Hibernating writes the instance's **RAM contents to the root EBS volume** and shuts it down. Starting it again restores memory, so processes resume where they were."},
  {"t":"table","head":["","Stop","Hibernate","Terminate"],
   "rows":[
    ["RAM","Discarded","Saved to the root volume","Discarded"],
    ["Boot time on start","Full boot","Resumes in place","New instance"],
    ["Root EBS volume","Kept","Kept, and must be **encrypted**","Deleted by default"],
    ["Charged for compute","No","No","No"]]},
  {"t":"key","x":"Hibernate is for a long boot or a large in-memory cache that would take a long time to rebuild — a service whose start-up work you do not want to repeat."},
  {"t":"h","x":"The constraints that get tested"},
  {"t":"list","x":[
   "The root volume must be **EBS, encrypted**, and large enough to hold the RAM image.",
   "RAM size is capped for hibernation, and only certain instance families support it.",
   "An instance cannot stay hibernated indefinitely — there is a maximum period.",
   "It must be enabled **at launch**; it cannot be turned on for an existing instance."]},
  {"t":"trap","x":"Hibernate is not a high-availability feature and does not protect against an AZ failure. It is a start-up time optimisation, nothing more."}
 ],
 "checks":[
  {"q":"What does hibernating an instance preserve that stopping it does not?",
   "o":["The contents of RAM","The public IPv4 address","The instance store volumes","The placement group membership"],
   "a":[0],
   "x":"Hibernate writes memory to the encrypted root EBS volume and restores it on start, so processes resume. A plain stop discards RAM and boots fresh."},
  {"q":"Which is a requirement for hibernation?",
   "o":["The root volume must be an encrypted EBS volume","The instance must have an Elastic IP",
        "The instance must be in a cluster placement group","The instance must use instance store as its root"],
   "a":[0],
   "x":"The RAM image is written to the root volume, so it must be EBS, encrypted, and big enough. Instance store cannot be used, and networking or placement have nothing to do with it."},
  {"q":"When is hibernation the right choice?",
   "o":["When a service takes a long time to warm its in-memory cache on boot",
        "When an Availability Zone might fail",
        "When an instance must keep serving traffic while stopped",
        "When the root volume must be deleted on shutdown"],
   "a":[0],
   "x":"Hibernate exists to avoid repeating expensive start-up work. It offers nothing for availability, and a hibernated instance serves no traffic at all."},
  {"q":"Can hibernation be enabled on an instance that is already running?",
   "o":["No — it has to be enabled at launch","Yes, from the console at any time",
        "Yes, after stopping the instance once","Yes, by editing the user data"],
   "a":[0],
   "x":"Hibernation support is fixed at launch time, so an existing instance has to be replaced. That makes it a decision to get right when the instance is first created."}
 ]
}
],
"recap":[
 {"t":"h","x":"Addressing, settled"},
 {"t":"table","head":["Requirement","Answer"],
  "rows":[
   ["A stable address for clients","A load balancer and a DNS name, not an Elastic IP per instance"],
   ["A fixed public address for one appliance","An Elastic IP"],
   ["Instance-to-instance traffic in a VPC","Private addresses"],
   ["An address that survives a stop","Private IPv4 always; public IPv4 never; Elastic IP yes"]]},
 {"t":"h","x":"Placement groups by fear"},
 {"t":"table","head":["What the workload is afraid of","Strategy","Limit"],
  "rows":[
   ["Network latency between nodes","Cluster","One AZ, one rack"],
   ["Losing two instances to one hardware failure","Spread","Seven instances per AZ"],
   ["A rack failure taking out a replica set","Partition","Seven partitions per AZ"]]},
 {"t":"key","x":"Cluster is fast and fragile; spread is small and safe; partition is large and rack-aware. The seven-per-AZ limit on spread groups is the number most often used to make an option wrong."},
 {"t":"h","x":"ENI in one line"},
 {"t":"flow","x":["Network identity lives on the ENI","Detach from the failed instance","Attach to the standby in the same AZ","Address and security groups follow"]},
 {"t":"h","x":"Lifecycle"},
 {"t":"split","cols":[
  {"nm":"Stop","items":["RAM discarded","New public IPv4 on start","EBS kept and still billed"]},
  {"nm":"Hibernate","items":["RAM written to the encrypted root volume","Resumes instead of booting","Enabled at launch only"]},
  {"nm":"Terminate","items":["Root volume deleted by default","Instance store gone","Nothing to resume"]}]},
 {"t":"trap","x":"Recurring distractors: an Elastic IP for every instance in an Auto Scaling group; a spread group with more than seven instances in an AZ; moving an ENI across Availability Zones; and hibernation offered as a high-availability answer."}
],
"final":[
 {"m":"placement-groups",
  "q":"A simulation runs across sixteen nodes that exchange messages constantly, and the team wants the lowest inter-node latency. Which placement strategy fits?",
  "o":["A cluster placement group in a single Availability Zone",
       "A spread placement group across three Availability Zones",
       "A partition placement group with sixteen partitions",
       "No placement group, relying on random placement"],
  "a":[0],
  "w":["Correct — packing the nodes onto one rack gives the lowest latency and highest throughput between them.",
      "Spreading maximises isolation and therefore distance, which is the opposite of what a chatty simulation wants.",
      "Partitions deliberately separate groups of instances, adding latency between them.",
      "Random placement gives no latency guarantee at all."],
  "x":"Tightly coupled HPC wants instances physically close, which is what a cluster group provides. The accepted trade-off is that a single rack failure can take out the whole group, so this is for work that can be rerun."},
 {"m":"placement-groups",
  "q":"An architect proposes a spread placement group with twelve instances in one Availability Zone. What is wrong with it?",
  "o":["A spread group allows at most seven instances per Availability Zone",
       "Spread groups cannot be used with EBS-backed instances",
       "Spread groups require a cluster group as a parent",
       "Spread groups are limited to one instance type"],
  "a":[0],
  "w":["Correct — the guarantee of distinct hardware per instance is what caps the group at seven per zone.",
      "Storage type has no bearing on placement strategy.",
      "Placement groups are independent of each other; there is no nesting.",
      "A placement group does not restrict instance types in that way."],
  "x":"Spread groups promise that no two instances share underlying hardware, which AWS can only guarantee for seven per Availability Zone. Larger rack-aware deployments use partition groups instead."},
 {"m":"addressing",
  "q":"An Auto Scaling group of web servers must be reachable by customers on a stable name. What should the architecture use?",
  "o":["An Application Load Balancer with a Route 53 record pointing at it",
       "One Elastic IP per instance, published in DNS",
       "Public IPv4 addresses recorded by clients at first connection",
       "A fixed private IPv4 range advertised to customers"],
  "a":[0],
  "w":["Correct — the name resolves to the load balancer, which tracks healthy instances as they are replaced.",
      "Elastic IPs per instance do not scale, are limited per region, and break as instances are replaced.",
      "Public IPv4 addresses change on stop and start, so any cached address goes stale.",
      "Private addresses are not reachable from the internet at all."],
  "x":"Clients must never learn instance addresses in an elastic architecture. A load balancer gives one stable target, and Route 53 gives it a name, so instances can be created and destroyed freely underneath."},
 {"m":"eni",
  "q":"A monitoring appliance has a private IP that dozens of systems are configured to reach. The instance fails. What restores service fastest, without reconfiguring the clients?",
  "o":["Detach its ENI and attach it to a standby instance in the same Availability Zone",
       "Launch a replacement in another Availability Zone and move the ENI to it",
       "Assign the standby a new private IP and update every client",
       "Recreate the subnet with the same CIDR"],
  "a":[0],
  "w":["Correct — the interface carries the private address, any Elastic IP and the security groups to the standby.",
      "An ENI cannot cross an Availability Zone, so this fails.",
      "Reconfiguring dozens of clients is exactly the work the question asks to avoid.",
      "Recreating a subnet does not restore a specific instance's address and would disrupt everything else in it."],
  "x":"Network identity belongs to the ENI, not the instance, so moving the interface moves the address and the rules at once. The constraint to remember is that it only works within one Availability Zone."},
 {"m":"hibernate",
  "q":"A service takes eight minutes to load a large model into memory at start-up, and instances are stopped outside business hours. Which feature avoids repeating that work?",
  "o":["Hibernation, so RAM is saved to the encrypted root volume and restored",
       "A cluster placement group","An Elastic IP attached before stopping","Instance store volumes for the model"],
  "a":[0],
  "w":["Correct — hibernation persists memory and resumes the running processes instead of booting fresh.",
      "Placement affects latency between instances and does nothing for start-up time.",
      "An address has no bearing on how long the application takes to warm up.",
      "Instance store is wiped on stop, so the model would have to be loaded again anyway."],
  "x":"Hibernation is a start-up time optimisation: the RAM image goes to the encrypted root EBS volume and comes back on start. It must be enabled at launch and is unrelated to availability."},
 {"m":"addressing",
  "q":"A finance report shows charges for several Elastic IPs that are not attached to anything. What should be done?",
  "o":["Release the unattached Elastic IPs","Attach them to stopped instances to avoid the charge",
       "Convert them to private addresses","Move them to another region"],
  "a":[0],
  "w":["Correct — an allocated but idle Elastic IP is the case AWS charges most for, and releasing it stops the charge.",
      "A stopped instance does not make the address active, and the charge continues.",
      "There is no conversion between an Elastic IP and a private address.",
      "Moving the allocation does not change the fact that it is idle."],
  "x":"Elastic IPs are priced to discourage hoarding scarce IPv4 addresses, so an unassociated one costs more than an associated one. If nothing needs it, releasing it is the only fix."},
 {"m":"eni",
  "q":"Why would an instance acting as a proxy be given two Elastic Network Interfaces?",
  "o":["To separate public-facing and internal traffic, each with its own security group",
       "To double the instance's network bandwidth guarantee",
       "To allow the instance to span two Availability Zones",
       "To attach EBS volumes from two different zones"],
  "a":[0],
  "w":["Correct — two interfaces give two network identities and two independent sets of rules.",
      "Bandwidth is a property of the instance type, not the number of interfaces.",
      "An instance lives in exactly one Availability Zone regardless of its interfaces.",
      "EBS volumes are zone-bound and unrelated to network interfaces."],
  "x":"Appliances typically need one interface facing the untrusted side and one facing the trusted side, with different security groups on each. That separation is the usual reason for a second ENI."},
 {"m":"hibernate",
  "q":"Which requirement must be met before an instance can be hibernated?",
  "o":["Hibernation was enabled at launch and the root EBS volume is encrypted",
       "The instance has an Elastic IP associated",
       "The instance is in a spread placement group",
       "The instance uses an instance store root volume"],
  "a":[0],
  "w":["Correct — the RAM image is written to the encrypted root volume, and support cannot be added afterwards.",
      "Addressing is irrelevant to hibernation.",
      "Placement groups have nothing to do with saving memory state.",
      "Instance store cannot hold the RAM image and does not survive a stop."],
  "x":"Two constraints catch people out: hibernation must be chosen at launch, and the root volume must be encrypted EBS with room for the memory image. Neither can be retrofitted to a running instance."},
 {"m":"addressing",
  "q":"Two application servers in the same VPC exchange large volumes of data. Traffic costs are higher than expected. What is the likely cause?",
  "o":["They are communicating over public IPv4 addresses instead of private ones",
       "They are in the same Availability Zone","They are using a cluster placement group","They both have Elastic IPs allocated but idle"],
  "a":[0],
  "w":["Correct — traffic sent to a public address leaves and re-enters the network and is charged accordingly.",
      "Same-zone traffic is the cheapest case, not the expensive one.",
      "A cluster placement group reduces latency and does not add data transfer charges.",
      "Idle Elastic IPs cost a flat hourly rate, which does not scale with data volume."],
  "x":"Inside a VPC, instances should reach each other on private addresses. Using public addressing routes the traffic through the internet gateway path, which adds both latency and data transfer cost."},
 {"m":"placement-groups",
  "q":"An existing instance needs to join a partition placement group. What does the change involve?",
  "o":["Stopping the instance, moving it into the group, then starting it",
       "No change — placement groups can be joined while running",
       "Terminating the instance and rebuilding it from scratch",
       "Moving the instance to a different VPC"],
  "a":[0],
  "w":["Correct — placement is decided at start, so joining a group needs a stop and start.",
      "Placement cannot be altered while the instance is running.",
      "A full rebuild is unnecessary; a stop and start is enough.",
      "Placement groups are unrelated to which VPC the instance is in."],
  "x":"Because the hypervisor chooses physical placement when an instance starts, group membership can only change while the instance is stopped. Plan it as a short outage rather than a live operation."}
]
}
