# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 3,
"nm": "EC2 storage: EBS, instance store and EFS",
"tag": "Storage",
"modules": [
{
 "id": "ebs-basics",
 "nm": "EBS: a network disk for one instance",
 "goal": "State what EBS is, where it lives, and what happens to it when an instance dies.",
 "min": 6,
 "blocks": [
  {"t":"p","x":"An **EBS volume** is a network drive attached to one instance at a time. Because it is network storage, it survives the instance — and because it is a *drive*, it lives in exactly one Availability Zone."},
  {"t":"list","x":[
   "Bound to **one Availability Zone**. To use it in another zone you snapshot it and restore the snapshot there.",
   "Attached to one instance at a time, except for the Multi-Attach volumes covered later.",
   "Provisioned in advance: you pay for the size you asked for, not the bytes you wrote.",
   "**Delete on termination** is on for the root volume by default and off for extra volumes — this flag decides whether your data survives."]},
  {"t":"key","x":"The delete-on-termination flag is the single most tested EBS detail. A root volume disappears with the instance unless the flag is cleared; an attached data volume stays behind unless the flag is set."},
  {"t":"h","x":"EBS versus instance store"},
  {"t":"split","cols":[
   {"nm":"EBS","items":["Network attached, survives stop and terminate","Can be snapshotted and encrypted","Throughput limited by the network","Can be detached and reattached"]},
   {"nm":"Instance store","items":["Physically attached disk","**Lost on stop or terminate**","Very high IOPS, no snapshots","Good for cache, buffers and scratch"]}]},
  {"t":"trap","x":"\"We need the highest possible IOPS and the data is a cache that can be rebuilt\" points at instance store. \"The data must survive\" rules it out completely, however fast it is."},
  {"t":"flow","x":["Instance terminated","Root volume deleted by default","Data volume remains","Attach it to a new instance"],
   "cap":"Moving a data volume to a replacement instance is a normal recovery path — in the same AZ."}
 ],
 "checks":[
  {"q":"Where can an EBS volume be attached?",
   "o":["To an instance in the same Availability Zone","To any instance in the region",
        "To any instance in the account","To instances in two zones at once for redundancy"],
   "a":[0],
   "x":"An EBS volume lives in one Availability Zone. Getting the data into another zone means taking a snapshot, which is regional, and restoring it there."},
  {"q":"An instance is terminated. What happens to an extra data volume attached to it?",
   "o":["It remains, unless delete on termination was enabled for it",
        "It is always deleted with the instance","It converts to instance store",
        "It is snapshotted automatically"],
   "a":[0],
   "x":"Delete on termination defaults to on for the root volume and off for additional volumes, so a data volume normally survives and can be attached to a replacement instance."},
  {"q":"Which storage gives the highest IOPS but loses everything when the instance stops?",
   "o":["Instance store","A gp3 EBS volume","An EFS file system","An EBS snapshot"],
   "a":[0],
   "x":"Instance store is disk physically attached to the host, so it is extremely fast and completely ephemeral. It suits caches and scratch space, never data that must survive."},
  {"q":"How do you make an EBS volume's data available in a different Availability Zone?",
   "o":["Take a snapshot and restore it in the other zone","Detach it and attach it across zones",
        "Enable Multi-Attach","Change the volume type"],
   "a":[0],
   "x":"Snapshots are stored regionally, which makes them the bridge between zones. Volumes themselves never cross a zone boundary, and Multi-Attach is still limited to one zone."}
 ]
},
{
 "id":"volume-types",
 "nm":"Volume types and Multi-Attach",
 "goal":"Pick a volume type from the IOPS, throughput and boot requirements in a question.",
 "min":7,
 "blocks":[
  {"t":"table","head":["Type","Character","Can boot","Reach for it when"],
   "rows":[
    ["**gp3**","General purpose SSD; IOPS and throughput set independently of size","Yes","The default answer for most workloads, and cheaper than gp2"],
    ["**gp2**","General purpose SSD; IOPS tied to size","Yes","Legacy — a question mentioning \"IOPS grows with volume size\" means gp2"],
    ["**io1 / io2**","Provisioned IOPS SSD, highest durability","Yes","Databases needing sustained high IOPS; io2 Block Express for the extreme end"],
    ["**st1**","Throughput optimised HDD","**No**","Big sequential reads: log processing, data warehouses"],
    ["**sd1 / sc1**","Cold HDD, cheapest","**No**","Infrequently accessed data where cost dominates"]]},
  {"t":"key","x":"Only SSD types can be a boot volume. An answer that boots an instance from st1 or sc1 is wrong on that fact alone."},
  {"t":"h","x":"gp3 versus gp2, the practical difference"},
  {"t":"p","x":"With gp2 you bought a bigger volume to get more IOPS. With **gp3** you set IOPS and throughput directly, so a small fast volume is possible — which is usually cheaper."},
  {"t":"h","x":"Multi-Attach"},
  {"t":"list","x":[
   "Available on **io1 and io2** only.",
   "One volume attached to up to sixteen instances **in the same Availability Zone**.",
   "The file system must be cluster-aware — an ordinary XFS or ext4 will corrupt itself.",
   "For clustered applications that manage their own concurrent writes, not for general sharing."]},
  {"t":"trap","x":"\"Several instances need to share files\" is **EFS**, not EBS Multi-Attach. Multi-Attach is for a clustered application that handles concurrency itself, and it cannot cross an Availability Zone."},
  {"t":"h","x":"Changing a volume"},
  {"t":"p","x":"Size, type and IOPS can be changed on a live volume with **elastic volumes**; the file system then has to be extended inside the operating system. Volumes can only grow, never shrink."}
 ],
 "checks":[
  {"q":"A database needs sustained high IOPS with the highest durability. Which volume type?",
   "o":["io2","st1","sc1","gp2"],
   "a":[0],
   "x":"Provisioned IOPS SSD is built for sustained, predictable IOPS, and io2 adds higher durability. The HDD types cannot deliver random IOPS at all, and gp2 ties performance to volume size."},
  {"q":"Which volume types cannot be used as a boot volume?",
   "o":["st1 and sc1","gp2 and gp3","io1 and io2","gp3 and io2"],
   "a":[0],
   "x":"The HDD-backed types are for large sequential throughput and cannot boot an instance. All the SSD types — gp2, gp3, io1 and io2 — can."},
  {"q":"Ten instances in one Availability Zone run a clustered application that coordinates its own writes to a shared block device. What makes that possible?",
   "o":["EBS Multi-Attach on an io2 volume","Attaching a gp3 volume to each instance",
        "An st1 volume shared across zones","Instance store replicated by AWS"],
   "a":[0],
   "x":"Multi-Attach lets io1 and io2 volumes attach to up to sixteen instances in one zone, on the condition that the application and file system handle concurrency. Other volume types attach to one instance at a time."},
  {"q":"A volume was created as gp2 and needs more IOPS without growing in size. What is the fix?",
   "o":["Change it to gp3 and set the IOPS directly","Grow the volume until the IOPS are enough",
        "Convert it to st1","Detach it and reattach it to a larger instance"],
   "a":[0],
   "x":"gp3 decouples IOPS and throughput from capacity, so performance can be raised on a small volume. Under gp2 the only lever was size, which is why gp3 is usually both faster and cheaper."}
 ]
},
{
 "id":"snapshots-amis",
 "nm":"Snapshots, AMIs and getting data between places",
 "goal":"Use snapshots to move, back up and share volumes, and explain what an AMI adds.",
 "min":7,
 "blocks":[
  {"t":"p","x":"A **snapshot** is a point-in-time, incremental copy of a volume held in S3-backed storage you never see directly. It is regional, which is what makes it the tool for moving data around."},
  {"t":"flow","x":["Snapshot the volume","Copy it to another region","Restore into a volume there","Attach to an instance"],
   "cap":"The same path is how you move a volume between Availability Zones — restore into the target zone."},
  {"t":"h","x":"What snapshots give you"},
  {"t":"table","head":["Feature","What it does"],
   "rows":[
    ["Incremental","Only changed blocks are stored, so repeated snapshots are cheap"],
    ["Cross-region copy","The basis of disaster recovery and region migration"],
    ["Sharing","Share with another account, or make public — an encrypted snapshot must not use the default key to be shared"],
    ["Archive tier","Much cheaper storage for snapshots kept for months, with a restore delay of up to 72 hours"],
    ["Recycle Bin","Retention rules that let a deleted snapshot be recovered"],
    ["Fast Snapshot Restore","Removes the first-touch latency when restoring, for an extra charge"]]},
  {"t":"key","x":"A restored volume is normally lazy-loaded, so the first read of each block is slow. **Fast Snapshot Restore** is the answer when a restored volume must be at full speed immediately."},
  {"t":"h","x":"AMIs"},
  {"t":"list","x":[
   "An **AMI** packages a root volume snapshot plus launch permissions and block device mappings.",
   "Building an AMI with software pre-installed shortens boot time — the alternative to doing the same work in user data every launch.",
   "AMIs are **regional**: copy an AMI to another region before launching there.",
   "Sharing an encrypted AMI requires sharing the KMS key as well, and the default EBS key cannot be shared."]},
  {"t":"trap","x":"\"Boot time is too long because user data installs packages every launch\" is answered by baking a **custom AMI** — sometimes called a golden image — not by a bigger instance."}
 ],
 "checks":[
  {"q":"How do you get a volume's data into another region?",
   "o":["Snapshot the volume and copy the snapshot to that region","Detach the volume and attach it there",
        "Enable Multi-Attach across regions","Change the volume type to a regional one"],
   "a":[0],
   "x":"Snapshots are the only mechanism that crosses a region boundary. Volumes are tied to one Availability Zone and cannot be moved directly."},
  {"q":"A volume restored from a snapshot is slow on first access to each block. Which feature removes that?",
   "o":["Fast Snapshot Restore","The snapshot archive tier","The Recycle Bin","Multi-Attach"],
   "a":[0],
   "x":"Restored volumes lazy-load blocks from the snapshot, so the first touch is slow. Fast Snapshot Restore pre-initialises the volume for an extra charge, which suits a restore that must serve traffic immediately."},
  {"q":"Instances take several minutes to boot because user data installs a long list of packages. What reduces that?",
   "o":["Bake the packages into a custom AMI","Use a larger instance type",
        "Move the user data into the security group","Switch the root volume to st1"],
   "a":[0],
   "x":"A custom AMI captures the work once so every launch starts from it. Bigger instances speed up the installation a little but still repeat it, and the other options are unrelated."},
  {"q":"What makes repeated EBS snapshots inexpensive?",
   "o":["They are incremental — only changed blocks are stored",
        "They are compressed to a fixed size","They are deleted after seven days",
        "They are stored on instance store"],
   "a":[0],
   "x":"After the first snapshot, each one records only the blocks that changed, so a daily schedule costs far less than a full copy every day."}
 ]
},
{
 "id":"encryption",
 "nm":"EBS encryption",
 "goal":"Encrypt an existing unencrypted volume, and say what encryption covers.",
 "min":5,
 "blocks":[
  {"t":"p","x":"EBS encryption uses **KMS** and is transparent: the operating system sees an ordinary disk, and there is a negligible performance cost."},
  {"t":"h","x":"What is covered"},
  {"t":"list","x":[
   "Data at rest on the volume.",
   "Data **in transit between the instance and the volume**.",
   "All snapshots taken from it.",
   "All volumes restored from those snapshots."]},
  {"t":"key","x":"Encryption cannot be switched on for an existing volume in place. The path is: snapshot it, **copy the snapshot with encryption enabled**, then restore a volume from the encrypted copy."},
  {"t":"steps","x":[
   "Take a snapshot of the unencrypted volume.",
   "Copy that snapshot, ticking encryption and choosing a KMS key.",
   "Create a volume from the encrypted copy.",
   "Stop the instance, detach the old volume, attach the new one."]},
  {"t":"table","head":["Question","Answer"],
   "rows":[
    ["Can an existing volume be encrypted in place?","No — snapshot, copy with encryption, restore"],
    ["Are snapshots of an encrypted volume encrypted?","Yes, and so is every volume restored from them"],
    ["Is there a noticeable performance cost?","No — it is transparent to the operating system"],
    ["Can an encrypted snapshot be shared across accounts?","Only if it uses a customer managed KMS key"]]},
  {"t":"h","x":"Account-wide default"},
  {"t":"p","x":"Encryption by default can be turned on per region, so every new volume and snapshot is encrypted without anyone remembering. It does not retroactively encrypt anything that already exists."},
  {"t":"trap","x":"Sharing an encrypted snapshot with another account requires a **customer managed key**, because the AWS-managed default EBS key cannot be shared. That constraint appears in cross-account questions."}
 ],
 "checks":[
  {"q":"How do you encrypt an existing unencrypted EBS volume?",
   "o":["Snapshot it, copy the snapshot with encryption enabled, restore a volume from the copy",
        "Toggle encryption on the volume in the console",
        "Attach it to an encrypted instance and reboot",
        "Change its volume type to io2"],
   "a":[0],
   "x":"Encryption is fixed when a volume is created, so the only route is through a snapshot copy that adds encryption. The new volume then replaces the old one on the instance."},
  {"q":"What does EBS encryption protect beyond the data sitting on the disk?",
   "o":["Data in transit between the instance and the volume, and all snapshots taken from it",
        "Data inside the application's memory","Traffic between two instances",
        "Objects stored in S3"],
   "a":[0],
   "x":"The encryption boundary covers the volume, the link to the instance, and everything derived from it — snapshots and volumes restored from them. It says nothing about application memory or other services."},
  {"q":"An encrypted snapshot must be shared with another AWS account. What is required?",
   "o":["It must be encrypted with a customer managed KMS key, shared with that account",
        "It must be copied to instance store first","It must be made public",
        "It must be converted to an AMI"],
   "a":[0],
   "x":"The AWS-managed default EBS key cannot be shared, so a snapshot encrypted with it cannot be used by another account. Re-encrypting the copy under a customer managed key, and granting that account use of the key, is the fix."},
  {"q":"What does turning on EBS encryption by default in a region do?",
   "o":["Encrypts every newly created volume and snapshot in that region",
        "Encrypts all existing volumes overnight","Encrypts S3 buckets in that region",
        "Forces all instances to restart"],
   "a":[0],
   "x":"The setting applies from that point onwards, so nothing that already exists changes. Existing volumes still need the snapshot-and-copy route."}
 ]
},
{
 "id":"efs",
 "nm":"EFS: a file system many instances share",
 "goal":"Choose between EFS, EBS and S3, and pick the right EFS class for a cost question.",
 "min":6,
 "blocks":[
  {"t":"p","x":"**EFS** is a managed NFS file system. Many instances, across **many Availability Zones**, mount it at the same time, and it grows and shrinks on its own."},
  {"t":"table","head":["","EBS","EFS","Instance store"],
   "rows":[
    ["Shape","Block device","File system (NFS)","Block device"],
    ["Attached to","One instance (or a cluster with Multi-Attach)","Thousands of instances at once","One instance, physically"],
    ["Scope","One Availability Zone","**Multi-AZ**","One host"],
    ["Capacity","Provisioned in advance","Grows automatically, pay for what you use","Fixed by instance type"],
    ["Cost","Moderate","Higher per GB","Included in the instance"]]},
  {"t":"key","x":"\"Several instances need to read and write the same files\" is EFS. \"One instance needs a disk\" is EBS. \"Objects fetched over HTTP by anything\" is S3."},
  {"t":"h","x":"Storage classes and lifecycle"},
  {"t":"list","x":[
   "**Standard** for active files; **Infrequent Access (IA)** is much cheaper to store and charges per read.",
   "A **lifecycle policy** moves files to IA after a period without access — the standard cost answer.",
   "**One Zone** classes cut cost further by dropping multi-AZ durability; suitable for development or reproducible data.",
   "Performance modes: General Purpose for latency, Max I/O for very large parallel workloads. Throughput can be bursting or provisioned."]},
  {"t":"h","x":"Access control"},
  {"t":"p","x":"EFS is reached through mount targets inside your VPC and controlled with **security groups**, plus POSIX permissions and optional IAM policies. It is Linux-only — a Windows file share is **FSx for Windows** instead."},
  {"t":"trap","x":"EFS is Linux only. A question about a shared file system for Windows servers using SMB is FSx for Windows File Server, no matter how well EFS fits otherwise."}
 ],
 "checks":[
  {"q":"Twelve application servers across three Availability Zones must read and write the same uploaded files. What fits?",
   "o":["An EFS file system mounted by all of them","One EBS volume attached to each server",
        "Instance store on each server","An io2 volume with Multi-Attach"],
   "a":[0],
   "x":"EFS is a shared file system that spans Availability Zones and can be mounted by many instances at once. EBS volumes, including Multi-Attach, are limited to one zone, and instance store is local to a single host."},
  {"q":"Files on EFS are rarely read after thirty days, and storage cost is the concern. What do you configure?",
   "o":["A lifecycle policy moving them to Infrequent Access","A larger performance mode",
        "Provisioned throughput","A second mount target"],
   "a":[0],
   "x":"EFS lifecycle management moves files that have not been accessed for a set period into the cheaper IA class automatically, with a per-read charge when they are needed again."},
  {"q":"Windows servers need a shared SMB file share. Which service?",
   "o":["FSx for Windows File Server","EFS","An EBS volume with Multi-Attach","Instance store"],
   "a":[0],
   "x":"EFS speaks NFS and supports Linux only. Windows workloads that need SMB, Active Directory integration and NTFS permissions use FSx for Windows File Server."},
  {"q":"How is network access to an EFS file system controlled?",
   "o":["With security groups on its mount targets","With a key pair","With a placement group",
        "With the instance's user data"],
   "a":[0],
   "x":"EFS is reached through mount targets in your VPC subnets, and those have security groups like any other interface. POSIX permissions and IAM policies control what happens once a client is connected."}
 ]
}
],
"recap":[
 {"t":"h","x":"Choosing a storage service"},
 {"t":"dtree","x":[
  ["One instance needs a disk that survives","EBS"],
  ["Many instances need the same files, across zones","EFS"],
  ["Many Windows instances need an SMB share","FSx for Windows"],
  ["A cache or scratch space, rebuildable, fastest possible","Instance store"],
  ["Objects fetched over HTTP, unlimited size","S3"],
  ["A clustered app coordinating its own block writes in one AZ","EBS Multi-Attach on io1 or io2"]]},
 {"t":"h","x":"Volume types"},
 {"t":"table","head":["Type","Boot","Use"],
  "rows":[["gp3","Yes","The default; IOPS set independently of size"],
          ["gp2","Yes","Legacy; IOPS grows with size"],
          ["io1 / io2","Yes","Sustained high IOPS, databases, Multi-Attach"],
          ["st1","No","Large sequential throughput"],
          ["sc1","No","Cold, cheapest"]]},
 {"t":"key","x":"Only SSD volumes boot. EBS lives in one Availability Zone; snapshots are regional and are how data crosses zones and regions. Delete-on-termination is on for root volumes and off for data volumes."},
 {"t":"h","x":"The snapshot toolbox"},
 {"t":"table","head":["Need","Feature"],
  "rows":[["Cross-region disaster recovery","Copy the snapshot to the other region"],
          ["A restored volume at full speed immediately","Fast Snapshot Restore"],
          ["Cheap long-term retention","Snapshot archive tier, restore takes up to 72 hours"],
          ["Undo an accidental deletion","Recycle Bin retention rules"],
          ["Encrypt an unencrypted volume","Snapshot, copy with encryption, restore"],
          ["Faster boots","A custom AMI with the software already installed"]]},
 {"t":"h","x":"EFS cost levers"},
 {"t":"split","cols":[
  {"nm":"Cheaper storage","items":["Lifecycle to Infrequent Access","One Zone classes where durability can be relaxed"]},
  {"nm":"More performance","items":["Provisioned throughput instead of bursting","Max I/O performance mode for very parallel workloads"]}]},
 {"t":"trap","x":"Recurring distractors: instance store for data that must survive; booting from st1; Multi-Attach offered as a general file-sharing answer; EFS offered to Windows SMB clients; and toggling encryption on an existing volume."}
],
"final":[
 {"m":"efs",
  "q":"A content management system runs on instances in three Availability Zones, and every instance must see uploads made by any other instance immediately. What storage should it use?",
  "o":["Amazon EFS mounted by every instance",
       "An EBS volume attached to each instance, synchronised by a cron job",
       "Instance store on each instance","An io2 volume using Multi-Attach"],
  "a":[0],
  "w":["Correct — EFS is a shared NFS file system that spans Availability Zones and is consistent across all clients.",
      "Copying between separate volumes introduces delay and conflict, which the requirement rules out.",
      "Instance store is local to one host and disappears when the instance stops.",
      "Multi-Attach is confined to a single Availability Zone and needs a cluster-aware file system."],
  "x":"Shared files across zones is EFS's exact purpose. EBS in any form is zone-bound, and instance store is neither shared nor durable."},
 {"m":"encryption",
  "q":"An unencrypted production volume must become encrypted with the least data loss. What is the correct sequence?",
  "o":["Snapshot the volume, copy the snapshot with encryption enabled, create a volume from the copy, then swap it in",
       "Enable encryption on the existing volume from the console",
       "Attach the volume to an instance with encryption by default enabled",
       "Change the volume type to io2, which is always encrypted"],
  "a":[0],
  "w":["Correct — encryption is set at creation, so a snapshot copy is the only way to produce an encrypted version of existing data.",
      "There is no in-place toggle for encryption on an existing volume.",
      "Encryption by default applies to newly created volumes, not to one that already exists.",
      "Volume type has nothing to do with encryption; io2 is not encrypted automatically."],
  "x":"The snapshot-copy-restore path is the standard answer whenever existing data must become encrypted. Encryption by default prevents the problem for future volumes but does nothing retroactively."},
 {"m":"volume-types",
  "q":"A log processing job reads very large files sequentially and cost matters more than random access. Which volume type suits it?",
  "o":["st1, a throughput optimised HDD",
       "io2 provisioned IOPS SSD","gp3 general purpose SSD as the boot volume","sc1 as the boot volume"],
  "a":[0],
  "w":["Correct — st1 is priced for large sequential throughput, which is exactly this access pattern.",
      "Provisioned IOPS is built for random access and costs far more than this job needs.",
      "gp3 would work but costs more than an HDD for purely sequential reads.",
      "sc1 cannot be a boot volume, and the option is wrong on that fact alone."],
  "x":"Sequential throughput at low cost is what the HDD types are for. Remember that neither st1 nor sc1 can boot an instance, which is often what makes an option incorrect."},
 {"m":"ebs-basics",
  "q":"An instance in us-east-1a is terminated by mistake. Its separately attached data volume was created with the defaults. What is the situation?",
  "o":["The volume still exists and can be attached to a new instance in the same Availability Zone",
       "The volume was deleted with the instance","The volume moved automatically to another zone",
       "The volume became an instance store volume"],
  "a":[0],
  "w":["Correct — delete on termination is off by default for additional volumes, so the data survives.",
      "That default applies to the root volume, not to volumes attached afterwards.",
      "Volumes never move between Availability Zones on their own.",
      "A volume's type does not change; EBS and instance store are different things entirely."],
  "x":"Root volumes are deleted with the instance by default and data volumes are not. The surviving volume can be attached to a replacement instance, provided that instance is in the same Availability Zone."},
 {"m":"snapshots-amis",
  "q":"A disaster recovery plan must keep recent copies of production volumes in a second region. What is the mechanism?",
  "o":["Take EBS snapshots and copy them to the second region",
       "Attach the volumes to instances in the second region","Enable Multi-Attach across regions",
       "Move the volumes into an EFS file system"],
  "a":[0],
  "w":["Correct — snapshots are the only way EBS data crosses a region, and copies can be scheduled.",
      "Volumes cannot be attached across zones, let alone across regions.",
      "Multi-Attach works within one Availability Zone and is not a replication feature.",
      "EFS is a different service; moving data into it does not replicate EBS volumes."],
  "x":"Cross-region snapshot copy is the standard EBS disaster recovery answer, and Data Lifecycle Manager or AWS Backup can run it on a schedule."},
 {"m":"volume-types",
  "q":"An application needs 16,000 IOPS from a 100 GB volume, and the team wants the lowest cost that meets it. Which choice fits best?",
  "o":["gp3, with IOPS provisioned independently of the volume size",
       "gp2, sized up until the IOPS target is reached","st1 with provisioned throughput","sc1 with Fast Snapshot Restore"],
  "a":[0],
  "w":["Correct — gp3 lets you buy the IOPS you need without paying for capacity you do not.",
      "gp2 ties IOPS to size, so hitting the target means buying a much larger volume than needed.",
      "st1 is an HDD built for sequential throughput and cannot deliver that many IOPS.",
      "sc1 is the coldest, slowest option and Fast Snapshot Restore does not change its performance."],
  "x":"The gp3 to gp2 difference is exactly this: gp3 decouples performance from capacity. Paying for a large gp2 volume only to reach an IOPS number is the pattern gp3 was introduced to remove."},
 {"m":"snapshots-amis",
  "q":"Instances launched by Auto Scaling take six minutes to become healthy because their user data installs and configures software every time. What reduces the launch time most?",
  "o":["Create a custom AMI with the software already installed and launch from it",
       "Increase the instance size","Move the volume to io2","Add a second network interface"],
  "a":[0],
  "w":["Correct — baking the image does the installation once instead of on every launch.",
      "A bigger instance shortens the install a little but still repeats all of it.",
      "Faster storage does not remove the work of downloading and configuring packages.",
      "Network interfaces have no effect on boot time."],
  "x":"A golden AMI turns repeated launch-time work into build-time work, which is the standard answer when scale-out is too slow. User data then handles only the small per-instance differences."},
 {"m":"efs",
  "q":"An EFS file system holds many files that are never read after their first week, and the bill is dominated by storage. What should be configured?",
  "o":["A lifecycle policy that moves files to the Infrequent Access class",
       "Max I/O performance mode","Provisioned throughput","A second mount target in each subnet"],
  "a":[0],
  "w":["Correct — lifecycle management moves untouched files to a much cheaper class automatically.",
      "Performance mode affects latency and parallelism, not storage price.",
      "Provisioned throughput increases cost rather than reducing it.",
      "Mount targets are about reachability, not cost."],
  "x":"EFS Infrequent Access trades a per-read charge for far cheaper storage, and the lifecycle policy applies it based on how long a file has gone untouched — the standard answer for a storage-heavy EFS bill."},
 {"m":"ebs-basics",
  "q":"A workload needs the fastest possible local disk for temporary shuffle files that can be regenerated. Which storage should be used?",
  "o":["Instance store volumes on the instance",
       "A gp3 EBS volume","An EFS file system","An io2 volume with Multi-Attach"],
  "a":[0],
  "w":["Correct — instance store is physically attached, giving the highest IOPS, and the data is regenerable so its volatility does not matter.",
      "EBS is network attached and slower than local disk for this pattern.",
      "EFS adds network file system overhead, which is the wrong direction for scratch data.",
      "Multi-Attach adds sharing complexity for data that only one instance uses."],
  "x":"Two facts decide it: the requirement asks for maximum speed, and the data is explicitly rebuildable. That combination is the one case where instance store's volatility is acceptable."},
 {"m":"encryption",
  "q":"A team must share an encrypted EBS snapshot with a partner AWS account. The snapshot was encrypted with the default EBS key. What has to change?",
  "o":["Copy the snapshot and re-encrypt it with a customer managed KMS key that the partner account may use",
       "Make the snapshot public","Decrypt the snapshot and share it unencrypted","Convert the snapshot into an instance store volume"],
  "a":[0],
  "w":["Correct — AWS-managed keys cannot be shared, so the snapshot must be re-encrypted under a key whose policy grants the partner access.",
      "Making an encrypted snapshot public is not possible and would be a serious exposure in any case.",
      "Removing encryption to enable sharing defeats the control the encryption exists to provide.",
      "Snapshots and instance store are unrelated; there is no such conversion."],
  "x":"The blocking constraint is the key, not the snapshot. Default service keys have no shareable key policy, so cross-account sharing always requires a customer managed key granted to the other account."}
]
}
