# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 4,
"nm": "Load balancing and Auto Scaling",
"tag": "Availability",
"modules": [
{
 "id": "elb-types",
 "nm": "Which load balancer, and why",
 "goal": "Pick ALB, NLB or GWLB from the protocol and the requirement in the question.",
 "min": 8,
 "blocks": [
  {"t":"p","x":"A load balancer spreads traffic across healthy targets and gives clients one stable name. AWS has three, and they operate at different layers."},
  {"t":"table","head":["","Application Load Balancer","Network Load Balancer","Gateway Load Balancer"],
   "rows":[
    ["Layer","7 — HTTP and HTTPS","4 — TCP, UDP, TLS","3 — IP packets"],
    ["Routes on","Path, hostname, headers, query string, method","Port and protocol only"," All traffic, transparently"],
    ["Performance","High","**Millions of requests per second, ultra low latency**","High"],
    ["Addressing","A DNS name only","**One static IP per AZ, and Elastic IPs are supported**","A DNS name"],
    ["Targets","Instances, IPs, **Lambda functions**","Instances, IPs, an ALB","Virtual appliances"],
    ["Use it for","Web applications and microservices","TCP or UDP workloads, static IPs, extreme throughput","Sending traffic through firewalls and inspection appliances"]]},
  {"t":"key","x":"Two phrases decide almost every load balancer question. **\"A static IP address\"** or **\"UDP\"** means NLB. **\"Route by URL path or hostname\"** means ALB."},
  {"t":"h","x":"What only the ALB can do"},
  {"t":"list","x":[
   "Rules by **path** (`/api/*` to one target group), **host** (`shop.example.com`), header, query string or HTTP method.",
   "Invoke a **Lambda function** as a target.",
   "Redirect HTTP to HTTPS, and return fixed responses without a backend.",
   "Authenticate users through Cognito or an OIDC provider before traffic reaches the target.",
   "Pass the client's address in the **X-Forwarded-For** header — the target sees the load balancer's IP otherwise."]},
  {"t":"h","x":"What only the NLB can do"},
  {"t":"list","x":[
   "Handle **UDP** and raw TCP.",
   "Give you a **static IP per Availability Zone**, and accept an Elastic IP — the answer when a client's firewall must allow specific addresses.",
   "Preserve the client's source IP all the way to the target.",
   "Serve as the entry point for a **PrivateLink** endpoint service."]},
  {"t":"trap","x":"A Gateway Load Balancer is not for application traffic. It exists to route packets transparently through third-party appliances — firewalls, intrusion detection, deep packet inspection — and back."}
 ],
 "checks":[
  {"q":"Clients must connect to a fixed set of IP addresses that their firewalls allow. Which load balancer?",
   "o":["Network Load Balancer","Application Load Balancer","Gateway Load Balancer","Any of them — all support static IPs"],
   "a":[0],
   "x":"Only the NLB gives a static IP per Availability Zone and accepts an Elastic IP. An ALB is reached by DNS name and its addresses change."},
  {"q":"Requests for /api must go to one target group and /images to another. Which load balancer?",
   "o":["Application Load Balancer","Network Load Balancer","Gateway Load Balancer","A Route 53 weighted record"],
   "a":[0],
   "x":"Path-based routing is a layer 7 feature and only the ALB can read the URL. An NLB works at layer 4 and sees ports, not paths."},
  {"q":"A game server uses UDP. Which load balancer supports it?",
   "o":["Network Load Balancer","Application Load Balancer","Gateway Load Balancer","Neither — UDP cannot be load balanced on AWS"],
   "a":[0],
   "x":"The NLB is the only one that handles UDP, because it works at the transport layer. ALBs are HTTP and HTTPS only."},
  {"q":"Targets behind an ALB see the load balancer's IP address rather than the client's. How do they get the real client address?",
   "o":["From the X-Forwarded-For header","From the security group","From the target group's health check",
        "From the instance's user data"],
   "a":[0],
   "x":"An ALB terminates the connection and opens a new one to the target, so it records the original address in X-Forwarded-For. An NLB does not need this because it preserves the source IP directly."}
 ]
},
{
 "id":"elb-features",
 "nm":"Health checks, stickiness, TLS and cross-zone",
 "goal":"Explain how a load balancer decides a target is healthy and how it keeps a session in place.",
 "min":7,
 "blocks":[
  {"t":"h","x":"Health checks"},
  {"t":"p","x":"The load balancer polls each target on a port and path. A target failing the threshold stops receiving traffic; it is not terminated — that is Auto Scaling's job, if you tell it to use ELB health checks."},
  {"t":"flow","x":["Health check fails","Target marked unhealthy","Traffic stops going to it","ASG replaces it — if it uses ELB health checks"],
   "cap":"Without that last link, a broken-but-running instance stays in the group forever."},
  {"t":"key","x":"An Auto Scaling group defaults to **EC2 health checks**, which only notice a stopped instance. Set the health check type to **ELB** so an instance that is running but failing its health check is replaced."},
  {"t":"h","x":"Sticky sessions"},
  {"t":"list","x":[
   "Stickiness sends one client back to the same target, using a cookie.",
   "The **AWSALB** cookie is generated by the load balancer; an application cookie may be used instead.",
   "It causes uneven load, and it is a workaround — the better answer is to move session state out to **ElastiCache** or **DynamoDB**.",
   "NLB stickiness is per source IP, not per cookie."]},
  {"t":"h","x":"Cross-zone load balancing"},
  {"t":"table","head":["","Application Load Balancer","Network Load Balancer"],
   "rows":[
    ["Cross-zone by default","**On**, and it cannot be turned off","**Off**"],
    ["Charge when enabled","None","Inter-AZ data transfer is charged"],
    ["Effect when off","Not applicable","Each zone takes an equal share regardless of target count"]]},
  {"t":"trap","x":"With cross-zone off, each Availability Zone gets an equal share of traffic regardless of how many targets are in it. Two instances in one zone and eight in another means the two carry half the load."},
  {"t":"h","x":"TLS and connection handling"},
  {"t":"list","x":[
   "Certificates come from **ACM**, free for use with a load balancer, and renew automatically.",
   "**SNI** lets one load balancer serve many certificates for many hostnames.",
   "**Connection draining** — deregistration delay — lets in-flight requests finish before a target is removed. Default 300 seconds, tunable from 0 to 3600."]}
 ],
 "checks":[
  {"q":"An instance is running but its application has crashed, and Auto Scaling never replaces it. What is misconfigured?",
   "o":["The group is using EC2 health checks instead of ELB health checks",
        "The load balancer has no listener","The instance has no Elastic IP","Cross-zone load balancing is disabled"],
   "a":[0],
   "x":"EC2 health checks only report whether the instance itself is running. Switching the group to ELB health checks means a target failing the load balancer's check is treated as unhealthy and replaced."},
  {"q":"Users are being logged out when their requests land on different servers. What is the quickest fix, and what is the better one?",
   "o":["Enable sticky sessions now; move session state to ElastiCache or DynamoDB properly",
        "Disable health checks now; add more instances later",
        "Enable cross-zone load balancing now; add an Elastic IP later",
        "Increase the deregistration delay now; shorten it later"],
   "a":[0],
   "x":"Stickiness pins a client to one target and solves the symptom immediately, at the cost of uneven load. Externalising session state removes the requirement altogether, which is why it is the architecturally correct answer."},
  {"q":"Cross-zone load balancing is disabled on an NLB. Zone A has two targets and zone B has eight. How is traffic distributed?",
   "o":["Half to each zone, so each target in zone A receives four times as much",
        "Evenly across all ten targets","Only to zone B, which has more capacity",
        "Round robin weighted by instance size"],
   "a":[0],
   "x":"Without cross-zone balancing, traffic is split evenly between zones first and only then among the targets inside each zone. That is why an uneven target count becomes an uneven load."},
  {"q":"What does the deregistration delay control?",
   "o":["How long in-flight requests may finish before a target is removed",
        "How often health checks run","How long a sticky session lasts",
        "How long a TLS certificate is cached"],
   "a":[0],
   "x":"Also called connection draining, it stops the load balancer cutting off requests mid-flight when an instance is being taken out of service. The default is 300 seconds."}
 ]
},
{
 "id":"asg-basics",
 "nm":"Auto Scaling groups",
 "goal":"Set minimum, desired and maximum correctly, and say what replaces an unhealthy instance.",
 "min":6,
 "blocks":[
  {"t":"p","x":"An **Auto Scaling group** keeps a chosen number of instances running, launching and terminating them to match. It gives you elasticity *and* self-healing, and the exam cares about both."},
  {"t":"table","head":["Setting","Meaning"],
   "rows":[
    ["Minimum","Never go below this, even with no traffic"],
    ["Desired","What the group aims for right now — scaling policies move this number"],
    ["Maximum","Never go above this, however busy it gets"],
    ["Launch template","What a new instance looks like: AMI, type, security groups, user data, role"]]},
  {"t":"key","x":"An Auto Scaling group spanning **multiple Availability Zones** is what makes an architecture survive losing a zone. A group in one zone is a single point of failure, no matter how many instances it holds."},
  {"t":"h","x":"Self-healing"},
  {"t":"list","x":[
   "An instance failing its health check is terminated and replaced.",
   "With **ELB health checks** the group also replaces instances whose application is broken.",
   "A **health check grace period** stops the group killing an instance before it has finished booting — too short a grace period causes an endless replace loop.",
   "**Lifecycle hooks** pause an instance as it launches or terminates, so you can install something or drain it cleanly."]},
  {"t":"h","x":"Launch templates"},
  {"t":"p","x":"Launch configurations are legacy and immutable. **Launch templates** are versioned, support mixed instance types and Spot, and are the expected answer."},
  {"t":"trap","x":"An instance stuck in a launch-terminate loop usually has a health check grace period that is shorter than its boot time, or a user data script that fails. The fix is not a larger instance."}
 ],
 "checks":[
  {"q":"What makes an Auto Scaling group survive the loss of an Availability Zone?",
   "o":["Configuring it across subnets in several Availability Zones","Raising the maximum size",
        "Using a cluster placement group","Attaching Elastic IPs to its instances"],
   "a":[0],
   "x":"Spanning zones is the point: if one zone fails the group launches replacements in the others. A larger maximum in a single zone does not help when that zone is the thing that failed."},
  {"q":"New instances are terminated shortly after launching, before the application finishes starting. What should be adjusted?",
   "o":["The health check grace period","The maximum group size","The load balancer's listener port",
        "The instance's key pair"],
   "a":[0],
   "x":"The grace period tells the group how long to wait before health checks count. When it is shorter than the boot time, every new instance is judged unhealthy and replaced, producing a loop."},
  {"q":"Which should be used to define what a new instance looks like?",
   "o":["A launch template","A launch configuration","A placement group","A target group"],
   "a":[0],
   "x":"Launch templates are versioned and support mixed instance types and purchase options. Launch configurations are the legacy, immutable predecessor and are no longer the expected answer."},
  {"q":"You need to run a script on an instance before it is removed from the group. What provides the pause?",
   "o":["A lifecycle hook","A health check grace period","A scaling cooldown","A deregistration delay"],
   "a":[0],
   "x":"A lifecycle hook holds an instance in a wait state as it launches or terminates, giving you time to act. The deregistration delay only drains connections at the load balancer."}
 ]
},
{
 "id":"scaling-policies",
 "nm":"Scaling policies",
 "goal":"Choose target tracking, step, simple or scheduled scaling from the trigger described.",
 "min":7,
 "blocks":[
  {"t":"table","head":["Policy","How it decides","Reach for it when"],
   "rows":[
    ["**Target tracking**","Keep a metric at a value, like average CPU at 50%","The default answer — simplest and usually right"],
    ["**Step scaling**","Add more instances the further the alarm is breached","The response should be proportional to how bad it is"],
    ["**Simple scaling**","One action per alarm, then wait for a cooldown","Legacy; rarely the best answer"],
    ["**Scheduled**","At a time you specify","A known pattern — market open, a sale, month end"],
    ["**Predictive**","Machine learning over past traffic","A recurring daily or weekly shape, scaled before it arrives"]]},
  {"t":"key","x":"\"Keep average CPU around X\" is target tracking. \"Every weekday at 9 a.m.\" is scheduled scaling. \"Scale ahead of the pattern we see every day\" is predictive."},
  {"t":"h","x":"Useful metrics"},
  {"t":"list","x":[
   "`ASGAverageCPUUtilization` — the usual starting point.",
   "`ALBRequestCountPerTarget` — better for web tiers, because requests are the load, not CPU.",
   "`ASGAverageNetworkIn` and `NetworkOut` for bandwidth-bound work.",
   "A **custom metric** such as queue depth — the standard answer for scaling workers on an SQS queue."]},
  {"t":"h","x":"Scaling on a queue"},
  {"t":"flow","x":["Messages pile up in SQS","ApproximateNumberOfMessagesVisible rises","CloudWatch alarm","ASG adds workers","Backlog drains"],
   "cap":"Scale on backlog per instance, not CPU — a worker waiting on I/O looks idle."},
  {"t":"h","x":"Cooldowns and warm-up"},
  {"t":"p","x":"A **cooldown** stops the group reacting again before the last change has taken effect. Target tracking uses an **instance warm-up** instead, so instances still booting are not counted in the metric."},
  {"t":"trap","x":"Scaling a queue-consuming fleet on CPU is a classic wrong answer. Workers blocked on I/O show low CPU while the backlog grows — scale on the number of messages instead."}
 ],
 "checks":[
  {"q":"A web tier should keep average CPU near 60%. Which scaling policy?",
   "o":["Target tracking","Step scaling","Scheduled scaling","Predictive scaling"],
   "a":[0],
   "x":"Target tracking takes a metric and a target value and manages the rest. Naming a value to hold is the phrasing that points straight at it."},
  {"q":"Traffic rises every weekday at 08:00 and the fleet is always a few minutes behind. What addresses it most directly?",
   "o":["Scheduled scaling that adds capacity before 08:00","A shorter cooldown",
        "A larger maximum size","Sticky sessions"],
   "a":[0],
   "x":"A known clock-time pattern is what scheduled scaling exists for: capacity is in place before the load arrives rather than reacting after it. Predictive scaling is the automatic version of the same idea."},
  {"q":"Workers consume an SQS queue. Their CPU stays low while the backlog grows. What should the group scale on?",
   "o":["The number of visible messages in the queue","Average CPU utilisation",
        "Network throughput","The number of healthy targets"],
   "a":[0],
   "x":"The backlog is the real measure of work waiting. Workers blocked on I/O look idle by CPU, so a CPU-based policy never scales out while the queue keeps growing."},
  {"q":"What does an instance warm-up setting do for a target tracking policy?",
   "o":["Excludes instances that are still starting from the metric","Delays health checks",
        "Keeps a minimum number of instances running","Pre-pulls container images"],
   "a":[0],
   "x":"Instances that are still booting would otherwise drag the average down and trigger more scaling. The warm-up period leaves them out of the calculation until they are serving."}
 ]
}
],
"recap":[
 {"t":"h","x":"Load balancer selection"},
 {"t":"dtree","x":[
  ["Route by URL path, hostname or header","Application Load Balancer"],
  ["A static IP or an Elastic IP is required","Network Load Balancer"],
  ["UDP, or extreme throughput at very low latency","Network Load Balancer"],
  ["Lambda as a target","Application Load Balancer"],
  ["Authenticate users before the request reaches the app","Application Load Balancer with Cognito or OIDC"],
  ["Send traffic through a third-party firewall appliance","Gateway Load Balancer"],
  ["Expose a service privately to other VPCs","Network Load Balancer behind PrivateLink"]]},
 {"t":"h","x":"The settings that change behaviour"},
 {"t":"table","head":["Setting","Default","Why it matters"],
  "rows":[
   ["ASG health check type","EC2","Switch to ELB or a broken application is never replaced"],
   ["Health check grace period","300s","Too short and instances are killed before they boot"],
   ["Deregistration delay","300s","In-flight requests finish before a target leaves"],
   ["Cross-zone (ALB)","On","Cannot be turned off"],
   ["Cross-zone (NLB)","Off","Uneven target counts produce uneven load; enabling it adds inter-AZ charges"],
   ["Stickiness","Off","A workaround; external session state is the real fix"]]},
 {"t":"key","x":"Multi-AZ Auto Scaling behind a load balancer is the shape of nearly every highly available answer on this exam. One zone, or no load balancer, is what makes an option wrong."},
 {"t":"h","x":"Scaling policies"},
 {"t":"table","head":["The question says","Policy"],
  "rows":[["Keep this metric at this value","Target tracking"],
          ["Bigger breach, bigger response","Step scaling"],
          ["Every weekday at nine","Scheduled"],
          ["Learn the daily pattern and act ahead of it","Predictive"],
          ["Queue is backing up","Custom metric on queue depth"]]},
 {"t":"h","x":"Two chains worth remembering"},
 {"t":"split","cols":[
  {"nm":"Self-healing","items":["ELB health check fails","Target stops receiving traffic","ASG with ELB health checks terminates it","Launch template creates a replacement"]},
  {"nm":"Elasticity","items":["Metric crosses the target","Policy changes desired capacity","Instances warm up","Load balancer registers them"]}]},
 {"t":"trap","x":"Recurring distractors: an ALB where a static IP is required; scaling a queue fleet on CPU; leaving the health check type on EC2; a single-AZ Auto Scaling group described as highly available; and sticky sessions offered as a scaling improvement."}
],
"final":[
 {"m":"elb-types",
  "q":"A partner's firewall can only allow traffic to specific IP addresses, and the workload is plain TCP. Which load balancer meets this?",
  "o":["A Network Load Balancer, which provides a static IP per Availability Zone",
       "An Application Load Balancer with a Route 53 alias","A Gateway Load Balancer","An Application Load Balancer with an Elastic IP attached"],
  "a":[0],
  "w":["Correct — the NLB is the only load balancer that offers static addressing, including Elastic IPs.",
      "An alias record still resolves to changing ALB addresses, which a firewall allow-list cannot pin.",
      "A Gateway Load Balancer routes traffic to inspection appliances and is not the entry point for an application.",
      "An ALB cannot be given an Elastic IP at all."],
  "x":"\"The client firewall must allow specific IPs\" is the strongest NLB signal on the exam. ALBs are addressed by name, and their addresses change."},
 {"m":"asg-basics",
  "q":"Instances in an Auto Scaling group keep running after their application process dies, and users see errors. What change fixes this?",
  "o":["Set the group's health check type to ELB",
       "Increase the desired capacity","Enable cross-zone load balancing","Shorten the deregistration delay"],
  "a":[0],
  "w":["Correct — with ELB health checks the group treats a failing load balancer check as an unhealthy instance and replaces it.",
      "More instances means more broken ones too; nothing detects the failure.",
      "Cross-zone balancing changes distribution, not health detection.",
      "Draining affects how targets leave, not whether they are found unhealthy."],
  "x":"EC2 health checks only see whether the virtual machine is running. Pointing the group at the load balancer's health check is what makes the architecture self-healing at the application level."},
 {"m":"scaling-policies",
  "q":"A fleet of workers pulls jobs from an SQS queue. During busy periods the queue grows for hours while CPU stays near 15%. How should the group scale?",
  "o":["On a custom metric derived from the number of messages waiting in the queue",
       "On average CPU utilisation with a lower target","On network throughput","On the count of healthy hosts"],
  "a":[0],
  "w":["Correct — the backlog is the work waiting, and scaling on it adds workers exactly when jobs are queued.",
      "Lowering a CPU target still measures the wrong thing; I/O-bound workers never reach it.",
      "Network volume does not track job count for small messages with long processing times.",
      "Healthy host count is an output of scaling, not an input to it."],
  "x":"Queue depth, ideally as a backlog-per-instance figure, is the standard answer for worker fleets. CPU-based scaling fails precisely because a worker waiting on I/O looks idle."},
 {"m":"elb-types",
  "q":"A single domain serves a web application at /shop and an API at /api, each running on its own fleet. What routes them?",
  "o":["An Application Load Balancer with path-based rules to two target groups",
       "A Network Load Balancer with two listeners","Two Elastic IPs and a Route 53 failover record","A Gateway Load Balancer with two appliance groups"],
  "a":[0],
  "w":["Correct — reading the URL path is a layer 7 capability, and rules can send each path to its own target group.",
      "An NLB sees ports and addresses, never the request path.",
      "Failover records choose between endpoints for availability, not by URL path.",
      "Gateway Load Balancers pass packets to inspection appliances and cannot route on paths."],
  "x":"Path-based routing is the defining ALB feature, alongside host-based rules, header matching and Lambda targets. Anything that has to read HTTP is an ALB question."},
 {"m":"elb-features",
  "q":"Deployments cut off user requests mid-flight when instances are taken out of service. What setting addresses this?",
  "o":["The deregistration delay, also known as connection draining",
       "The health check interval","Sticky sessions","The instance warm-up period"],
  "a":[0],
  "w":["Correct — it keeps a departing target alive long enough to finish requests already in progress.",
      "The health check interval changes how quickly failures are noticed, not how targets are removed.",
      "Stickiness routes a client consistently; it does not protect in-flight requests during removal.",
      "Warm-up concerns instances arriving, not leaving."],
  "x":"Connection draining exists for exactly this: the target stops receiving new requests but keeps serving existing ones for up to the configured delay, which defaults to 300 seconds."},
 {"m":"scaling-policies",
  "q":"Traffic to a retail site climbs sharply at 19:00 every evening and the fleet is always several minutes behind demand. Which approach removes the lag?",
  "o":["Scheduled scaling that raises desired capacity shortly before 19:00",
       "A shorter cooldown on a simple scaling policy","Sticky sessions to reduce load","Moving to an NLB for faster routing"],
  "a":[0],
  "w":["Correct — capacity is added ahead of a known clock-time pattern rather than reacting after the load arrives.",
      "Reacting faster still means reacting after users are already waiting.",
      "Stickiness does not reduce total load; it only pins clients to targets.",
      "Changing load balancer type does nothing about insufficient capacity."],
  "x":"A repeating clock-time pattern is scheduled scaling's exact use case; predictive scaling automates the same idea from history. Reactive policies always trail a sharp ramp."},
 {"m":"elb-features",
  "q":"An NLB has cross-zone load balancing disabled. One Availability Zone holds two targets and another holds eight. What is the consequence?",
  "o":["Each zone receives half the traffic, so the two targets carry four times the per-target load",
       "Traffic is spread evenly across all ten targets","The zone with two targets is removed from service","Health checks fail in the smaller zone"],
  "a":[0],
  "w":["Correct — traffic is divided between zones first, and only then among the targets inside each zone.",
      "Even per-target distribution is what enabling cross-zone balancing would achieve.",
      "Zones are not removed for having fewer targets.",
      "Uneven distribution does not itself cause health check failures, though overload eventually might."],
  "x":"This is why NLB target counts should be balanced per zone, or cross-zone enabled — with the caveat that enabling it on an NLB adds inter-AZ data transfer charges."},
 {"m":"asg-basics",
  "q":"An Auto Scaling group must run a configuration script and register an instance with an external system before it starts receiving traffic. What provides the pause?",
  "o":["A lifecycle hook on instance launch",
       "A longer cooldown period","A scheduled scaling action","A deregistration delay"],
  "a":[0],
  "w":["Correct — the hook holds the instance in a pending wait state until the work completes or the timeout expires.",
      "Cooldowns govern how soon another scaling action may occur, not what happens to one instance.",
      "Scheduled actions change capacity at a time; they do not pause an individual launch.",
      "Deregistration delay applies when an instance leaves, not when it joins."],
  "x":"Lifecycle hooks exist on both launch and terminate, which makes them the answer for install-before-serving and drain-before-terminate requirements alike."},
 {"m":"elb-types",
  "q":"An application must authenticate users with an OIDC identity provider before any request reaches the backend, with no authentication code in the application. What supports this?",
  "o":["An Application Load Balancer configured to authenticate with OIDC or Cognito",
       "A Network Load Balancer with TLS termination","A Gateway Load Balancer with an identity appliance","Route 53 with a failover policy"],
  "a":[0],
  "w":["Correct — the ALB can complete the authentication flow itself and pass user claims to the target.",
      "An NLB works at layer 4 and cannot participate in an HTTP authentication flow.",
      "Gateway Load Balancers forward packets to appliances and do not perform user authentication.",
      "Route 53 resolves names and has no notion of a user session."],
  "x":"Built-in authentication is an ALB feature that removes login handling from the application entirely: unauthenticated requests are redirected to the provider and only authenticated ones reach the target group."},
 {"m":"scaling-policies",
  "q":"A new target tracking policy keeps adding instances during a scale-out, overshooting the required capacity. Which setting most directly reduces the overshoot?",
  "o":["An instance warm-up period, so instances that are still starting are excluded from the metric",
       "A larger maximum group size","A shorter health check grace period","Enabling sticky sessions"],
  "a":[0],
  "w":["Correct — booting instances contribute no work but count in the average, which drags the metric down and triggers further scaling.",
      "A larger maximum permits more overshoot rather than preventing it.",
      "A shorter grace period risks terminating healthy instances mid-boot.",
      "Stickiness has no effect on how the scaling metric is calculated."],
  "x":"Overshoot in target tracking usually comes from counting instances that are not yet serving. The warm-up period leaves them out until they are ready, which stabilises the loop."}
]
}
