# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 5,
"nm": "RDS, Aurora and ElastiCache",
"tag": "Databases",
"modules": [
{
 "id": "rds-basics",
 "nm": "RDS, and what AWS manages for you",
 "goal": "Say what RDS takes over from you, and what it refuses to give you.",
 "min": 6,
 "blocks": [
  {"t":"p","x":"**RDS** runs a relational database engine for you — MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, and Aurora. You get the database; AWS keeps the machine."},
  {"t":"split","cols":[
   {"nm":"AWS handles","items":["Provisioning and patching the operating system","Automated backups and point-in-time recovery","Monitoring, metrics and events","Multi-AZ failover and read replicas","Storage that grows on its own"]},
   {"nm":"You never get","items":["SSH access to the host","Root on the operating system","Anything that needs an OS-level agent"]}]},
  {"t":"key","x":"\"We need SSH access to the database server\" rules RDS out. That requirement means EC2, or **RDS Custom** for Oracle and SQL Server, which deliberately gives back host access."},
  {"t":"h","x":"Backups"},
  {"t":"table","head":["","Automated backups","Manual snapshots"],
   "rows":[
    ["Taken","Daily, plus transaction logs every 5 minutes","When you ask"],
    ["Retention","1 to 35 days","Until you delete them"],
    ["Restores to","Any point in time within the window","That exact moment"],
    ["Deleted with the database","Yes, unless a final snapshot is taken","No"]]},
  {"t":"h","x":"Storage autoscaling"},
  {"t":"p","x":"RDS can grow its storage automatically when free space runs low, up to a maximum you set. It is the answer when an application's data growth is unpredictable — storage never shrinks back."},
  {"t":"trap","x":"A restore always creates a **new database instance with a new endpoint**. Any answer that implies restoring \"in place\" over the existing instance is wrong."}
 ],
 "checks":[
  {"q":"A workload needs an agent installed on the database host's operating system. What does that rule out?",
   "o":["Standard RDS, because it gives no OS access","Multi-AZ deployments","Automated backups","Read replicas"],
   "a":[0],
   "x":"RDS is a managed service and never grants host access. The requirement points at running the engine on EC2, or at RDS Custom where AWS deliberately hands back operating system control."},
  {"q":"How far back can RDS point-in-time recovery reach by default configuration limits?",
   "o":["Up to 35 days, depending on the retention period set","Exactly 7 days always",
        "Up to 90 days","Only to the most recent daily backup"],
   "a":[0],
   "x":"Automated backups retain between 1 and 35 days, and transaction logs are captured every five minutes, so any moment inside the window can be restored. Manual snapshots persist indefinitely but restore only to their own point in time."},
  {"q":"What happens when you restore an RDS backup?",
   "o":["A new database instance is created with a new endpoint","The existing instance is overwritten in place",
        "The data is merged into the running instance","Only the schema is restored"],
   "a":[0],
   "x":"Restores always produce a new instance, which means the application's connection string has to be repointed. That is why answers claiming an in-place restore are wrong."},
  {"q":"An application's data volume is unpredictable and the database keeps running out of space. What addresses it?",
   "o":["Enable RDS storage autoscaling with a maximum threshold","Add a read replica",
        "Enable Multi-AZ","Shorten the backup retention period"],
   "a":[0],
   "x":"Storage autoscaling grows the volume when free space drops below a threshold, up to a limit you set. Replicas and Multi-AZ address reads and availability, not capacity."}
 ]
},
{
 "id":"multiaz-replicas",
 "nm":"Multi-AZ versus read replicas",
 "goal":"Tell availability apart from scale, and pick the right one for a stated requirement.",
 "min":8,
 "blocks":[
  {"t":"p","x":"These two are confused constantly, and the exam relies on it. One is for **surviving failure**; the other is for **serving more reads**."},
  {"t":"table","head":["","Multi-AZ","Read replicas"],
   "rows":[
    ["Purpose","Availability and failover","Scaling read traffic"],
    ["Replication","**Synchronous**","**Asynchronous** — replicas can lag"],
    ["Can you read from it","No — the standby serves nothing","Yes, that is the point"],
    ["Where","A second Availability Zone","Same AZ, another AZ, or **another region**"],
    ["Failover","Automatic, the endpoint is repointed","Manual — you promote a replica"],
    ["How many","One standby","Up to 5 (15 for Aurora)"]]},
  {"t":"key","x":"\"Reporting queries are slowing the production database\" → a read replica. \"The database must survive an Availability Zone failure\" → Multi-AZ. A question can want both, and the answer then uses both."},
  {"t":"h","x":"What failover actually does"},
  {"t":"flow","x":["The primary fails","RDS promotes the standby","The DNS endpoint now points at it","The application reconnects"],
   "cap":"The endpoint name does not change, which is why applications need only reconnect."},
  {"t":"h","x":"Consistency"},
  {"t":"list","x":[
   "Multi-AZ replication is synchronous, so the standby is always current.",
   "Read replica replication is asynchronous, so a read may return slightly **stale data** — the reason they are unsuitable for anything requiring read-after-write consistency.",
   "A cross-region read replica also serves disaster recovery and cuts read latency for a distant region."]},
  {"t":"trap","x":"Promoting a read replica breaks replication permanently and turns it into an independent database. It is a disaster recovery action, not a routine one."}
 ],
 "checks":[
  {"q":"A nightly analytics job is slowing down the production database. What is the standard fix?",
   "o":["Point the job at a read replica","Enable Multi-AZ","Take more frequent snapshots","Shorten the backup window"],
   "a":[0],
   "x":"Read replicas exist to take read load off the primary. Multi-AZ adds a standby that serves no traffic at all, so it would not help this at all."},
  {"q":"Which statement about Multi-AZ is correct?",
   "o":["Replication is synchronous and the standby serves no traffic",
        "Replication is asynchronous and the standby can be read",
        "The standby is in the same Availability Zone","You can have up to five standbys"],
   "a":[0],
   "x":"Multi-AZ is purely about availability: writes are committed to both instances synchronously, and the standby stays idle until a failover promotes it."},
  {"q":"An application must always read data it has just written. What rules out a read replica for those reads?",
   "o":["Replication is asynchronous, so a replica can return stale data",
        "Replicas are read-only","Replicas cannot be in another Availability Zone",
        "Replicas do not support encryption"],
   "a":[0],
   "x":"Replication lag means a write may not have reached the replica yet. Reads that must be immediately consistent have to go to the primary."},
  {"q":"What happens when a read replica is promoted?",
   "o":["It becomes an independent database and replication stops permanently",
        "It becomes the Multi-AZ standby","It keeps replicating but also accepts writes",
        "It is deleted after the promotion"],
   "a":[0],
   "x":"Promotion is one-way: the replica stops following the source and becomes a standalone database. That makes it a recovery step rather than something used routinely."}
 ]
},
{
 "id":"aurora",
 "nm":"Aurora",
 "goal":"Name what Aurora changes about storage and endpoints, and when to use its variants.",
 "min":8,
 "blocks":[
  {"t":"p","x":"**Aurora** is an AWS-built engine compatible with MySQL and PostgreSQL. What is different is underneath: a shared, distributed storage layer rather than a disk per instance."},
  {"t":"list","x":[
   "Storage is replicated **six ways across three Availability Zones**, and grows automatically up to 128 TB.",
   "Up to **15 read replicas**, all reading the same storage, so replica lag is very low.",
   "Failover to a replica is fast — typically under 30 seconds — because no data has to be copied.",
   "Backups are continuous to S3, with point-in-time restore and no performance impact."]},
  {"t":"h","x":"The endpoints"},
  {"t":"table","head":["Endpoint","Points at","Use it for"],
   "rows":[
    ["Writer","The current primary, whichever instance that is","All writes"],
    ["Reader","Load balanced across all replicas","All read traffic — this is what scales reads"],
    ["Custom","A subset of instances you choose","Sending reporting queries to larger instances"]]},
  {"t":"key","x":"The **reader endpoint** is what spreads read traffic. An answer that has the application connect to individual replica addresses is doing by hand what the reader endpoint does automatically."},
  {"t":"h","x":"The variants"},
  {"t":"table","head":["Variant","What it solves"],
   "rows":[
    ["**Aurora Serverless v2**","Capacity scales in fine steps with load — for unpredictable or intermittent traffic, without managing instance sizes"],
    ["**Aurora Global Database**","One primary region, up to five secondary regions, replication typically under a second; cross-region disaster recovery with a recovery time around a minute"],
    ["**Aurora Multi-Master**","More than one writer, for write availability rather than write throughput"],
    ["**Aurora Machine Learning**","Calls SageMaker or Comprehend directly from SQL"],
    ["**Babelfish**","Lets SQL Server applications talk to Aurora PostgreSQL with few code changes"]]},
  {"t":"trap","x":"Aurora Global Database is the answer for a cross-region recovery objective measured in **minutes**. A cross-region read replica of ordinary RDS is slower to promote and lags more."},
  {"t":"h","x":"Cost control"},
  {"t":"p","x":"Aurora supports **cloning** — a new cluster sharing the same storage, created almost instantly and paying only for changed blocks. It is the cheap way to make a production-sized test environment."}
 ],
 "checks":[
  {"q":"How does an application spread read traffic across Aurora replicas?",
   "o":["By connecting to the reader endpoint","By connecting to the writer endpoint",
        "By listing each replica's address in the connection string","By enabling Multi-AZ"],
   "a":[0],
   "x":"The reader endpoint load balances connections across the available replicas and follows the cluster as instances change. Hard-coding replica addresses does the same job badly."},
  {"q":"A workload has long idle periods and unpredictable bursts. Which Aurora option fits?",
   "o":["Aurora Serverless v2","Aurora Global Database","Aurora Multi-Master","A larger provisioned instance"],
   "a":[0],
   "x":"Serverless v2 scales capacity up and down with demand in fine increments, so idle time is cheap and bursts are absorbed without resizing instances by hand."},
  {"q":"A company needs cross-region disaster recovery with a recovery time of about a minute. Which fits best?",
   "o":["Aurora Global Database","A cross-region snapshot copy schedule",
        "A read replica in the same region","Aurora cloning"],
   "a":[0],
   "x":"A Global Database replicates to secondary regions with sub-second lag and can be promoted in about a minute. Snapshot copies are far slower, and a same-region replica does not survive a regional failure."},
  {"q":"How many copies of Aurora storage are kept, and where?",
   "o":["Six copies across three Availability Zones","Two copies in one Availability Zone",
        "Three copies in three regions","One copy, with snapshots"],
   "a":[0],
   "x":"Aurora's storage layer keeps six copies across three Availability Zones, which is what lets it lose disks or a whole zone without data loss and without the instance doing the replication."}
 ]
},
{
 "id":"proxy-security",
 "nm":"RDS Proxy, security and the ports",
 "goal":"Name the connection and access controls, and the port for each engine.",
 "min":6,
 "blocks":[
  {"t":"h","x":"RDS Proxy"},
  {"t":"p","x":"A managed connection pool in front of the database. It matters most for **Lambda**, where thousands of short-lived functions would otherwise each open their own connection."},
  {"t":"list","x":[
   "Pools and shares connections, so the database is not exhausted.",
   "Cuts failover time noticeably, because the proxy holds the client connection while the database fails over.",
   "Can **enforce IAM authentication** and keep credentials in Secrets Manager.",
   "It is never publicly accessible — it lives inside your VPC."]},
  {"t":"key","x":"\"Lambda functions are exhausting database connections\" is RDS Proxy. It is the standard answer whenever a serverless front end meets a relational database."},
  {"t":"h","x":"Security layers"},
  {"t":"table","head":["Layer","Mechanism"],
   "rows":[
    ["Network","Security groups, and a private subnet — never a publicly accessible database"],
    ["At rest","KMS encryption, chosen at creation; add it later by restoring an encrypted snapshot"],
    ["In transit","TLS between client and database"],
    ["Authentication","Engine users, or **IAM database authentication** for MySQL and PostgreSQL, which issues short-lived tokens"],
    ["Credentials","Secrets Manager, with automatic rotation"],
    ["Audit","CloudTrail for API calls; engine logs pushed to CloudWatch Logs for queries"]]},
  {"t":"trap","x":"Encryption cannot be enabled on a running RDS instance. The route is snapshot → copy the snapshot with encryption → restore — the same shape as EBS."},
  {"t":"h","x":"Ports"},
  {"t":"table","head":["Engine","Port"],
   "rows":[["MySQL, MariaDB, Aurora MySQL","3306"],["PostgreSQL, Aurora PostgreSQL","5432"],
           ["Oracle","1521"],["Microsoft SQL Server","1433"],["Redis","6379"],["Memcached","11211"]]}
 ],
 "checks":[
  {"q":"Thousands of Lambda invocations are exhausting an RDS instance's connection limit. What solves it?",
   "o":["Put RDS Proxy in front of the database","Add a read replica","Enable Multi-AZ",
        "Increase the backup retention period"],
   "a":[0],
   "x":"RDS Proxy pools and reuses connections so short-lived functions share a small set of database connections. Replicas and Multi-AZ address read load and availability, not connection count."},
  {"q":"How do you encrypt an existing unencrypted RDS instance?",
   "o":["Take a snapshot, copy it with encryption enabled, and restore from the copy",
        "Toggle encryption on the running instance","Enable Multi-AZ, which encrypts the standby",
        "Attach a KMS key to the security group"],
   "a":[0],
   "x":"Encryption is fixed at creation, so producing an encrypted instance means going through an encrypted snapshot copy. The application then repoints to the new endpoint."},
  {"q":"What does IAM database authentication provide for MySQL and PostgreSQL on RDS?",
   "o":["Short-lived authentication tokens instead of a stored database password",
        "Encryption of data at rest","A managed connection pool","Automatic failover"],
   "a":[0],
   "x":"IAM authentication issues a token valid for a short period, which removes long-lived database passwords from applications. Encryption, pooling and failover are separate features."},
  {"q":"Which port does Aurora PostgreSQL listen on?",
   "o":["5432","3306","1433","6379"],
   "a":[0],
   "x":"Aurora PostgreSQL uses the standard PostgreSQL port 5432, just as Aurora MySQL uses 3306. Security group questions rely on knowing these."}
 ]
},
{
 "id":"elasticache",
 "nm":"ElastiCache and caching strategy",
 "goal":"Choose Redis or Memcached, and name the caching pattern a question is describing.",
 "min":7,
 "blocks":[
  {"t":"p","x":"**ElastiCache** is managed Redis or Memcached. It takes read load off a database and cuts latency to sub-millisecond — but the application has to be changed to use it."},
  {"t":"split","cols":[
   {"nm":"Redis","items":["**Multi-AZ with automatic failover**","Read replicas, and persistence with AOF","Backup and restore","Rich types: sorted sets, lists, geospatial","Use it when the cache must survive, or for leaderboards and sessions"]},
   {"nm":"Memcached","items":["Multi-node sharding, pure cache","**No replication, no persistence, no failover**","Multi-threaded","Use it when losing the cache is fine and you want simple, fast, horizontally sharded memory"]}]},
  {"t":"key","x":"Any requirement mentioning high availability, failover, persistence, backup, or a data structure beyond a plain key and value means **Redis**. Memcached is the answer only when the cache is disposable."},
  {"t":"h","x":"Caching patterns"},
  {"t":"table","head":["Pattern","How it works","The cost"],
   "rows":[
    ["**Lazy loading** (cache aside)","On a miss, read the database and write the result to the cache","The first request after a miss is slow, and stale data can linger"],
    ["**Write through**","Every write goes to the database and the cache together","Writes are slower, and data written but never read wastes cache space"],
    ["**TTL**","Entries expire after a set time","Simple, and the usual answer to \"the cache is serving stale data\""]]},
  {"t":"h","x":"Session state"},
  {"t":"flow","x":["User signs in","Session written to ElastiCache","Any web server can serve the next request","Sticky sessions become unnecessary"],
   "cap":"This is the proper fix for the stickiness problem in load balancing."},
  {"t":"trap","x":"ElastiCache is not a drop-in performance fix. If a question stresses \"no application changes\", the answer is a read replica or a larger instance — using a cache always requires code changes."}
 ],
 "checks":[
  {"q":"A cache must survive a node failure without losing its contents. Which engine?",
   "o":["Redis, which supports replication and Multi-AZ failover","Memcached, which shards across nodes",
        "Either — both replicate","Neither — caches are always volatile"],
   "a":[0],
   "x":"Redis supports read replicas, Multi-AZ with automatic failover, persistence and backups. Memcached has none of these, so a node failure takes its data with it."},
  {"q":"An application reads from the cache, and on a miss reads the database and stores the result. What is this pattern called?",
   "o":["Lazy loading, or cache aside","Write through","Time to live expiry","Write behind"],
   "a":[0],
   "x":"Lazy loading only populates the cache with data that is actually requested, at the cost of a slow first request after each miss and the possibility of stale entries."},
  {"q":"Users are being logged out as requests land on different web servers. Which fix removes the problem rather than hiding it?",
   "o":["Store session state in ElastiCache so any server can serve any request",
        "Enable sticky sessions permanently","Reduce the number of web servers",
        "Increase the load balancer's idle timeout"],
   "a":[0],
   "x":"External session state makes web servers interchangeable, which is what elasticity requires. Stickiness works but pins users to servers and unbalances load."},
  {"q":"A requirement says database performance must improve with no application changes. What does that rule out?",
   "o":["ElastiCache, because using a cache requires code changes","A read replica","A larger instance class",
        "Storage autoscaling"],
   "a":[0],
   "x":"A cache only helps if the application checks it, which is a code change. Replicas and resizing can be adopted by repointing or restarting, without rewriting the application's data access."}
 ]
}
],
"recap":[
 {"t":"h","x":"The decision that matters most"},
 {"t":"dtree","x":[
  ["Survive an Availability Zone failure","Multi-AZ — synchronous, standby serves nothing"],
  ["Too much read traffic","Read replicas, or the Aurora reader endpoint"],
  ["Reads must be immediately consistent","The primary, never an asynchronous replica"],
  ["Cross-region recovery in minutes","Aurora Global Database"],
  ["Idle much of the time, unpredictable bursts","Aurora Serverless v2"],
  ["Lambda exhausting connections","RDS Proxy"],
  ["Sub-millisecond reads, app can be changed","ElastiCache"],
  ["Needs OS access on the database host","EC2, or RDS Custom"]]},
 {"t":"h","x":"Multi-AZ against read replicas"},
 {"t":"table","head":["","Multi-AZ","Read replica"],
  "rows":[["Solves","Availability","Read scaling"],
          ["Replication","Synchronous","Asynchronous, can lag"],
          ["Readable","No","Yes"],
          ["Failover","Automatic","Manual promotion, and it is permanent"],
          ["Cross-region","No","Yes"]]},
 {"t":"h","x":"Aurora at a glance"},
 {"t":"table","head":["Feature","Number to remember"],
  "rows":[["Storage copies","6 across 3 Availability Zones"],
          ["Read replicas","Up to 15"],
          ["Storage ceiling","128 TB, grown automatically"],
          ["Failover time","Typically under 30 seconds"],
          ["Global Database regions","One primary, up to five secondaries"]]},
 {"t":"key","x":"Encryption on RDS and Aurora is set at creation. Adding it later means snapshot, copy with encryption, restore — and a new endpoint for the application."},
 {"t":"h","x":"Caching, in one place"},
 {"t":"split","cols":[
  {"nm":"Redis","items":["Replication and Multi-AZ failover","Persistence and backups","Sorted sets, lists, geospatial","Sessions, leaderboards, anything that must survive"]},
  {"nm":"Memcached","items":["Sharded, multi-threaded, simple","No replication or persistence","Pure disposable cache"]}]},
 {"t":"trap","x":"Recurring distractors: Multi-AZ offered to fix read load; a read replica offered where reads must be consistent; ElastiCache offered when the question forbids application changes; and restoring a backup described as an in-place operation."}
],
"final":[
 {"m":"multiaz-replicas",
  "q":"A reporting team runs heavy queries that slow the production database, and the business also requires the database to survive an Availability Zone failure. What meets both?",
  "o":["Enable Multi-AZ, and add a read replica for the reporting queries",
       "Enable Multi-AZ and point reporting at the standby",
       "Add two read replicas and rely on promotion for failure",
       "Increase the instance size and shorten the backup window"],
  "a":[0],
  "w":["Correct — Multi-AZ covers availability and a replica takes the read load, which are two separate problems.",
      "A Multi-AZ standby serves no traffic at all, so reporting cannot use it.",
      "Replica promotion is manual and permanent, which does not meet an automatic failover requirement.",
      "A bigger instance postpones the read problem and does nothing for zone failure."],
  "x":"The two features look similar and solve different problems. When a question asks for availability *and* read scaling, the answer uses both rather than choosing between them."},
 {"m":"aurora",
  "q":"An application must fail over to another region within a few minutes with minimal data loss, on a PostgreSQL-compatible database. What fits?",
  "o":["Aurora Global Database with a secondary region",
       "Daily cross-region snapshot copies","A same-region Aurora replica","Aurora Serverless v2 in one region"],
  "a":[0],
  "w":["Correct — replication lag is typically under a second, and a secondary region can be promoted in about a minute.",
      "Daily snapshots lose up to a day of data and take far longer to restore.",
      "A replica in the same region does not survive a regional failure.",
      "Serverless scales capacity; it does not provide a second region."],
  "x":"Recovery time in minutes with near-zero data loss across regions is Aurora Global Database's exact profile. Snapshot copies serve much looser objectives."},
 {"m":"proxy-security",
  "q":"A serverless API built on Lambda intermittently fails with \"too many connections\" from its RDS database. What is the correct fix?",
  "o":["Introduce RDS Proxy so functions share a pooled set of connections",
       "Add read replicas and spread queries across them","Increase the Lambda timeout","Enable Multi-AZ on the database"],
  "a":[0],
  "w":["Correct — the proxy maintains a pool and multiplexes many short-lived function invocations onto few database connections.",
      "Replicas add read capacity but each still has its own connection limit, and writes still hit the primary.",
      "A longer timeout makes functions hold connections for longer, which is worse.",
      "Multi-AZ is about failover and does not change connection limits."],
  "x":"Connection exhaustion is the classic friction between serverless compute and relational databases, and RDS Proxy is the purpose-built answer. It also shortens failover from the client's point of view."},
 {"m":"elasticache",
  "q":"A leaderboard must rank millions of scores in real time and survive a node failure. Which service and engine?",
  "o":["ElastiCache for Redis, using sorted sets with Multi-AZ failover",
       "ElastiCache for Memcached with more nodes","An RDS read replica","DynamoDB with a scan on every request"],
  "a":[0],
  "w":["Correct — sorted sets rank efficiently, and Redis supports replication with automatic failover.",
      "Memcached has no sorted set type and no replication, so a node failure loses the data.",
      "A relational replica cannot maintain a live ranking at this scale with low latency.",
      "Scanning a table for every request is expensive and slow."],
  "x":"Two clues point the same way: a data structure richer than key-value, and a durability or failover requirement. Both are Redis features that Memcached lacks entirely."},
 {"m":"rds-basics",
  "q":"A database was deleted along with its automated backups. Which retention choice would have preserved a copy?",
  "o":["Taking a manual snapshot, or a final snapshot at deletion",
       "Increasing the automated backup retention to 35 days","Enabling Multi-AZ","Adding a read replica"],
  "a":[0],
  "w":["Correct — manual and final snapshots persist independently of the instance's lifecycle.",
      "Automated backups are removed with the instance regardless of the retention period.",
      "Multi-AZ maintains a standby that is deleted along with the database.",
      "A replica is not a backup and is also removed when the source is deleted."],
  "x":"Automated backups are tied to the instance; manual snapshots are not. That distinction is the point of the final snapshot prompt when a database is deleted."},
 {"m":"multiaz-replicas",
  "q":"After moving reads to a read replica, users occasionally do not see a record they just created. What explains it?",
  "o":["Replication to the replica is asynchronous, so the write may not have arrived yet",
       "The replica has a smaller instance class","The replica is in a different Availability Zone","The replica is encrypted and the primary is not"],
  "a":[0],
  "w":["Correct — replica lag means a very recent write can be missing from a replica read.",
      "Instance size affects speed, not whether a committed write is present.",
      "Zone placement adds a little latency but does not change the consistency model.",
      "Encryption has no effect on replication timing or visibility."],
  "x":"Read replicas are eventually consistent by design. Reads that must reflect a just-completed write have to go to the primary, which is why read-after-write flows are excluded from replica routing."},
 {"m":"aurora",
  "q":"A team wants a full-size copy of a production Aurora cluster for testing, created quickly and cheaply. What should they use?",
  "o":["Aurora cloning, which shares storage and charges only for changed blocks",
       "A snapshot restore into a new cluster","A cross-region read replica","Aurora Serverless v2 with a small minimum capacity"],
  "a":[0],
  "w":["Correct — a clone is created almost instantly and only diverging blocks are charged.",
      "A snapshot restore copies the data, which takes longer and costs full storage.",
      "A cross-region replica is for latency and recovery, not for an isolated test copy.",
      "Serverless changes how capacity is billed but still needs the data copied in."],
  "x":"Cloning uses Aurora's copy-on-write storage: the clone starts sharing the same blocks and only pays for what it changes, which is what makes production-sized test environments affordable."},
 {"m":"elasticache",
  "q":"A cache is returning values that no longer match the database. Which mechanism most directly limits how stale an entry can be?",
  "o":["A time to live on cached entries","Switching from Redis to Memcached",
       "Adding more cache nodes","Enabling Multi-AZ on the cache"],
  "a":[0],
  "w":["Correct — a TTL bounds how long any entry can survive after the underlying data changes.",
      "Changing engines does not address invalidation at all.",
      "More nodes add capacity, not freshness.",
      "Multi-AZ improves availability and has nothing to do with staleness."],
  "x":"Lazy loading leaves entries in place until something evicts them, so a TTL is the simplest bound on staleness. Write-through keeps the cache current at the cost of slower writes."},
 {"m":"proxy-security",
  "q":"Security requires that applications hold no database password, using short-lived credentials instead, on an RDS MySQL database. What supports this?",
  "o":["IAM database authentication, which issues short-lived tokens",
       "A security group restricted to the application subnet","TLS in transit","Automated backups with a long retention"],
  "a":[0],
  "w":["Correct — the application requests a token from IAM and uses it instead of a stored password.",
      "Restricting the network limits who can connect but does not remove the stored password.",
      "TLS protects the connection; the credential is still a password.",
      "Backups are unrelated to authentication."],
  "x":"IAM database authentication for MySQL and PostgreSQL replaces long-lived passwords with tokens that expire in minutes, and access is then governed by IAM policy rather than by database grants alone."},
 {"m":"rds-basics",
  "q":"A regulated workload requires an agent on the database host and full control of patching, but the team still wants AWS to manage backups and the instance lifecycle. What fits?",
  "o":["RDS Custom, which grants operating system access while keeping managed features",
       "Standard RDS with a parameter group change","Aurora Serverless v2","ElastiCache for Redis"],
  "a":[0],
  "w":["Correct — RDS Custom exists exactly for Oracle and SQL Server workloads that need host access.",
      "Standard RDS never grants host access, whatever the parameter group says.",
      "Aurora is further from host access, not closer to it.",
      "A cache is not a relational database and does not meet the requirement at all."],
  "x":"The requirement for an OS agent normally rules RDS out entirely. RDS Custom is the middle ground: you get host access and responsibility for it, while AWS still handles much of the lifecycle."}
]
}
