# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 6,
"nm": "Route 53",
"tag": "Networking",
"modules": [
{
 "id": "records-ttl",
 "nm": "Records, hosted zones and TTL",
 "goal": "Name the record types the exam uses and explain what TTL changes.",
 "min": 6,
 "blocks": [
  {"t":"p","x":"**Route 53** is a DNS service that is also a domain registrar and a health checker. DNS turns a name into an address; everything else here is a refinement of that."},
  {"t":"table","head":["Record","What it holds"],
   "rows":[
    ["**A**","An IPv4 address"],
    ["**AAAA**","An IPv6 address"],
    ["**CNAME**","Another name — and **never at the zone apex**"],
    ["**Alias**","An AWS resource, as an extension Route 53 adds; works at the apex"],
    ["**NS**","The name servers for a hosted zone"],
    ["**MX**, **TXT**","Mail routing, and verification or SPF records"]]},
  {"t":"h","x":"Hosted zones"},
  {"t":"split","cols":[
   {"nm":"Public hosted zone","items":["Answers queries from anywhere on the internet","For your public domain names"]},
   {"nm":"Private hosted zone","items":["Answers only from inside the VPCs you associate","For internal names such as `db.internal`"]}]},
  {"t":"key","x":"A name that must resolve only inside your VPCs belongs in a **private hosted zone**. Putting internal hostnames in a public zone leaks your architecture to anyone who asks."},
  {"t":"h","x":"TTL"},
  {"t":"list","x":[
   "TTL is how long a resolver may cache an answer. Route 53 is not consulted again until it expires.",
   "A **high TTL** means fewer queries and lower cost, but changes take longer to take effect.",
   "A **low TTL** means changes propagate quickly and you pay for more queries.",
   "Before a planned migration, lower the TTL well in advance, make the change, then raise it again.",
   "**Alias records have a TTL set by AWS** — you do not choose it."]},
  {"t":"trap","x":"A failover that takes hours to reach users usually has a long TTL on the record. Health checks cannot help a resolver that is still serving a cached answer."}
 ],
 "checks":[
  {"q":"An internal hostname must resolve only from inside your VPCs. What do you use?",
   "o":["A private hosted zone associated with those VPCs","A public hosted zone with a restrictive TTL",
        "A CNAME to a private IP in a public zone","An A record with a health check"],
   "a":[0],
   "x":"Private hosted zones answer only for the VPCs you associate, so internal names are never visible publicly. Putting a private address in a public zone still publishes the name and the address."},
  {"q":"A DNS change must take effect within minutes during a planned migration. What should be done first?",
   "o":["Lower the TTL well before the change","Raise the TTL before the change",
        "Delete the record and recreate it","Switch the record type to CNAME"],
   "a":[0],
   "x":"Resolvers cache for the length of the TTL that was in force when they last queried, so the reduction has to be published far enough ahead for old cached values to expire."},
  {"q":"Which record type cannot be used at the zone apex, such as example.com?",
   "o":["CNAME","A","AAAA","TXT"],
   "a":[0],
   "x":"The DNS standard forbids a CNAME coexisting with the NS and SOA records that must exist at the apex. Route 53's alias record is the AWS extension that solves it."},
  {"q":"Who controls the TTL of an alias record?",
   "o":["AWS sets it for the target resource","You set it per record",
        "It is always 300 seconds","It is inherited from the parent zone"],
   "a":[0],
   "x":"Alias records point at AWS resources and Route 53 manages their TTL, which is one of the practical differences from a CNAME where you choose the value."}
 ]
},
{
 "id":"alias",
 "nm":"Alias versus CNAME",
 "goal":"Decide which to use for a given target, and explain why alias is usually right.",
 "min":5,
 "blocks":[
  {"t":"table","head":["","Alias","CNAME"],
   "rows":[
    ["Points at","AWS resources: ALB, NLB, CloudFront, S3 website, API Gateway, another Route 53 record","Any DNS name"],
    ["At the zone apex","**Yes**","**No**"],
    ["Cost","Free to query","Charged per query"],
    ["TTL","Set by AWS","Set by you"],
    ["Health of the target","Can be evaluated automatically","Not evaluated"]]},
  {"t":"key","x":"For `example.com` pointing at a load balancer or CloudFront, the answer is an **alias record**. A CNAME cannot exist at the apex, so any option using one there is wrong on the standard alone."},
  {"t":"h","x":"What alias cannot do"},
  {"t":"list","x":[
   "It cannot point at an **EC2 instance's** DNS name — use an A record with the address, or put a load balancer in front.",
   "It cannot point at an arbitrary external name — that is a CNAME.",
   "Not every AWS service is a valid alias target; the list is specific."]},
  {"t":"flow","x":["example.com","Alias record","Application Load Balancer","Healthy target"],
   "cap":"No extra lookup, no per-query charge, and the apex works."},
  {"t":"trap","x":"`www.example.com` as a CNAME to a load balancer is legal and common. The same thing at `example.com` is not — that is the distinction being tested."}
 ],
 "checks":[
  {"q":"The apex name example.com must point at an Application Load Balancer. What record type?",
   "o":["An alias record","A CNAME record","An MX record","An NS record"],
   "a":[0],
   "x":"CNAMEs are forbidden at the zone apex, and an ALB has no fixed IP to put in an A record. The alias record exists precisely for this case, and it is free to query."},
  {"q":"Which is a valid alias target?",
   "o":["A CloudFront distribution","An EC2 instance's public DNS name",
        "An arbitrary third-party domain","A private IP address"],
   "a":[0],
   "x":"Alias targets are a specific set of AWS resources — load balancers, CloudFront, S3 website endpoints, API Gateway and other Route 53 records. An EC2 instance is reached with an A record instead."},
  {"q":"What is a cost advantage of alias records?",
   "o":["Queries to an alias record are not charged","They cache for longer than CNAMEs",
        "They avoid the hosted zone monthly fee","They replace the need for health checks"],
   "a":[0],
   "x":"Route 53 does not charge for queries answered by an alias to an AWS resource, while CNAME queries are billed. Over a busy domain that is a real difference."},
  {"q":"Which record should point www.example.com at an external SaaS hostname?",
   "o":["A CNAME record","An alias record","An A record with the SaaS provider's IP",
        "An NS record"],
   "a":[0],
   "x":"Alias records only target AWS resources, so an external name needs a CNAME. Hard-coding the provider's IP in an A record breaks whenever they change it."}
 ]
},
{
 "id":"routing-policies",
 "nm":"Routing policies",
 "goal":"Match each routing policy to the sentence in a question that demands it.",
 "min":9,
 "blocks":[
  {"t":"table","head":["Policy","What it does","The wording that names it"],
   "rows":[
    ["**Simple**","One record, one or more values returned at random","No steering requirement at all"],
    ["**Weighted**","Splits traffic by percentage","\"send 10% to the new version\", canary, blue/green"],
    ["**Latency**","Sends the user to the region with the lowest latency for them","\"best performance\", \"lowest latency\" — not \"nearest\""],
    ["**Failover**","Primary while healthy, secondary when not","\"active-passive disaster recovery\""],
    ["**Geolocation**","Routes by where the user is","\"users in Germany must reach the German site\", compliance, language"],
    ["**Geoproximity**","Routes by distance, with a **bias** that can shift the boundary","\"shift more traffic towards a region\" by moving the boundary"],
    ["**IP-based**","Routes by the client's CIDR block","\"route this ISP's users to a specific endpoint\""],
    ["**Multivalue answer**","Returns up to eight healthy records at random","\"simple health-checked spreading, not a load balancer\""]]},
  {"t":"key","x":"Latency and geolocation are the pair most often confused. **Latency** optimises speed; **geolocation** enforces where a user is sent regardless of speed, which is what compliance and content licensing need."},
  {"t":"h","x":"Weighted, precisely"},
  {"t":"list","x":[
   "Weights are relative, not percentages: 10 and 90 behave the same as 1 and 9.",
   "A weight of **0** stops traffic to a record — handy for draining one endpoint.",
   "If **all** weights are 0, all records are returned as if equally weighted.",
   "Weighted plus health checks is the usual canary release mechanism."]},
  {"t":"h","x":"Multivalue is not a load balancer"},
  {"t":"p","x":"It returns several healthy addresses and leaves the client to choose. There is no health-aware distribution, no connection draining and no metrics — when a question wants real load balancing, the answer is an ELB."},
  {"t":"trap","x":"Geolocation has a **default record** for locations that match nothing. Without it, users from an unlisted country get no answer at all — a favourite detail in exam questions."}
 ],
 "checks":[
  {"q":"Ten percent of traffic should go to a new version of an application while it is evaluated. Which routing policy?",
   "o":["Weighted","Latency","Geolocation","Failover"],
   "a":[0],
   "x":"Weighted routing splits traffic by relative weight, which is exactly how a canary release is expressed in DNS. The other policies steer by location, speed or health instead."},
  {"q":"Users in Germany must be served from the German site for data residency reasons, even when another region would be faster. Which policy?",
   "o":["Geolocation","Latency","Geoproximity with a bias","Multivalue answer"],
   "a":[0],
   "x":"Geolocation routes on where the user is, which is what a residency or licensing requirement needs. Latency would happily send a user in Germany elsewhere if it were quicker."},
  {"q":"What is the purpose of the default record in a geolocation configuration?",
   "o":["To answer queries from locations that match no other record",
        "To set the TTL for all other records","To act as the health check target",
        "To define the weight distribution"],
   "a":[0],
   "x":"Without a default, a query from an unlisted country matches nothing and receives no answer. Creating one is a standard part of a geolocation setup."},
  {"q":"A requirement asks for several healthy IP addresses to be returned so clients can spread themselves, without a load balancer. Which policy?",
   "o":["Multivalue answer","Simple","Weighted","Latency"],
   "a":[0],
   "x":"Multivalue answer returns up to eight health-checked records at random. Simple routing returns values without health awareness, and the other policies steer rather than spread."}
 ]
},
{
 "id":"health-failover",
 "nm":"Health checks and failover",
 "goal":"Configure DNS failover correctly, including private resources, and know its limits.",
 "min":7,
 "blocks":[
  {"t":"p","x":"Route 53 health checkers live outside your network and probe endpoints from many locations. A record associated with a failing health check stops being returned."},
  {"t":"table","head":["Type","Watches","Notes"],
   "rows":[
    ["Endpoint","A public IP or name, over HTTP, HTTPS or TCP","Considered healthy above a threshold of checkers agreeing"],
    ["Calculated","Other health checks","Combine several with AND, OR or NOT — the parent check"],
    ["CloudWatch alarm","A metric","**The only way to health-check a private resource**"]]},
  {"t":"key","x":"Route 53 health checkers are on the public internet and cannot reach a private endpoint. The way to watch something private is a **CloudWatch alarm** and a health check tied to it."},
  {"t":"h","x":"Active-passive failover"},
  {"t":"flow","x":["Primary record with a health check","Health check fails","Route 53 returns the secondary","Traffic moves once the TTL expires"],
   "cap":"Recovery time is the health check interval plus the TTL — not instant."},
  {"t":"h","x":"Firewall rule that catches people out"},
  {"t":"p","x":"Health checkers come from published AWS address ranges. If an endpoint's security group only allows office addresses, every health check fails and the endpoint is treated as down."},
  {"t":"h","x":"Resolvers and hybrid DNS"},
  {"t":"list","x":[
   "**Route 53 Resolver inbound endpoint** — on-premises servers resolve names in your private hosted zones.",
   "**Outbound endpoint with forwarding rules** — resources in the VPC resolve names held by your on-premises DNS.",
   "Together they make a hybrid network resolve both ways."]},
  {"t":"trap","x":"DNS failover is not instant and cannot be made instant. When a question demands sub-second failover, the answer is a load balancer or Global Accelerator, not a DNS record."}
 ],
 "checks":[
  {"q":"How do you health-check an endpoint that has no public address?",
   "o":["Create a CloudWatch alarm and a health check that watches it",
        "Open the endpoint to the internet temporarily","Use a calculated health check with no children",
        "Use a TCP health check on the private IP"],
   "a":[0],
   "x":"Route 53 health checkers run on the public internet and cannot reach private resources. Routing the signal through a CloudWatch metric and alarm is the supported path."},
  {"q":"Health checks all fail even though the site works from a browser. What is the likely cause?",
   "o":["The security group does not allow the Route 53 health checker address ranges",
        "The TTL is too low","The record is an alias","The hosted zone is private"],
   "a":[0],
   "x":"Checkers probe from published AWS ranges, so a security group that only admits office addresses blocks them. The endpoint then looks unhealthy even though real users are fine."},
  {"q":"What determines how long a DNS failover takes to reach users?",
   "o":["The health check interval plus the record's TTL","The instance type of the secondary",
        "The number of records in the zone","The registrar of the domain"],
   "a":[0],
   "x":"Route 53 must first notice the failure, and resolvers must then expire their cached answer. That sum is why DNS failover is measured in seconds to minutes, not milliseconds."},
  {"q":"On-premises servers must resolve names held in a private hosted zone. What do you deploy?",
   "o":["A Route 53 Resolver inbound endpoint","A Route 53 Resolver outbound endpoint",
        "A public hosted zone with the same names","A CloudFront distribution"],
   "a":[0],
   "x":"An inbound endpoint gives on-premises resolvers an address inside your VPC to query. The outbound endpoint handles the opposite direction, where VPC resources need to resolve on-premises names."}
 ]
}
],
"recap":[
 {"t":"h","x":"Routing policy, decided by one sentence"},
 {"t":"dtree","x":[
  ["Send a percentage to a new version","Weighted"],
  ["Best performance for each user","Latency"],
  ["Users in a country must reach a specific site","Geolocation — and set a default record"],
  ["Shift the boundary between two regions","Geoproximity with bias"],
  ["Route a specific ISP's address ranges","IP-based"],
  ["Active-passive disaster recovery","Failover with health checks"],
  ["Return several healthy addresses, no load balancer","Multivalue answer"],
  ["Nothing to steer","Simple"]]},
 {"t":"h","x":"Alias against CNAME"},
 {"t":"table","head":["","Alias","CNAME"],
  "rows":[["Zone apex","Yes","No"],
          ["Target","AWS resources only","Any name"],
          ["Query cost","Free","Charged"],
          ["TTL","Set by AWS","Set by you"]]},
 {"t":"key","x":"Latency optimises speed. Geolocation enforces where. Compliance and licensing are always geolocation, however slow it might be."},
 {"t":"h","x":"Health checks"},
 {"t":"table","head":["Situation","Answer"],
  "rows":[["A public endpoint","An endpoint health check over HTTP, HTTPS or TCP"],
          ["A private resource","A CloudWatch alarm health check"],
          ["Several checks combined","A calculated health check"],
          ["Checks failing but the site works","Allow the AWS health checker address ranges"],
          ["Sub-second failover required","Not DNS — use a load balancer or Global Accelerator"]]},
 {"t":"h","x":"Hybrid resolution"},
 {"t":"split","cols":[
  {"nm":"Inbound endpoint","items":["On-premises resolvers query into your VPC","Resolves your private hosted zones"]},
  {"nm":"Outbound endpoint","items":["VPC resources query out to on-premises DNS","Driven by forwarding rules"]}]},
 {"t":"trap","x":"Recurring distractors: a CNAME at the zone apex; geolocation and latency swapped; a geolocation setup with no default record; DNS failover offered where sub-second recovery is required; and health checks aimed at private endpoints."}
],
"final":[
 {"m":"alias",
  "q":"The apex domain shop.example.com must resolve to a CloudFront distribution. Which record should be created?",
  "o":["An alias record targeting the distribution",
       "A CNAME record targeting the distribution","An A record with the distribution's IP addresses","An NS record delegating to CloudFront"],
  "a":[0],
  "w":["Correct — alias records work at the apex, target AWS resources directly, and are free to query.",
      "A CNAME cannot exist at a zone apex, because it may not coexist with the required NS and SOA records.",
      "CloudFront addresses are not fixed, so hard-coding them would break.",
      "NS records delegate a zone; they do not point a name at a distribution."],
  "x":"Apex plus AWS resource is the alias record's exact purpose. Any option that puts a CNAME at the apex is disqualified by the DNS standard, regardless of the rest of its wording."},
 {"m":"routing-policies",
  "q":"A media company must serve users in Canada from a Canadian endpoint for licensing reasons, even when a US endpoint would respond faster. Which routing policy applies?",
  "o":["Geolocation","Latency","Geoproximity without bias","Weighted"],
  "a":[0],
  "w":["Correct — geolocation routes on the user's location, which is what a licensing boundary requires.",
      "Latency would send Canadian users to a faster US endpoint, violating the requirement.",
      "Geoproximity routes by distance and can still cross the boundary the licence draws.",
      "Weighted routing splits traffic by proportion and ignores location entirely."],
  "x":"Whenever the requirement is legal or contractual rather than performance, geolocation is the answer. Remember to configure the default record for locations that match nothing."},
 {"m":"health-failover",
  "q":"An active-passive setup fails over correctly in testing, but real users take almost an hour to move after an outage. What is the most likely cause?",
  "o":["The record's TTL is long, so resolvers keep serving the cached primary",
       "The health check interval is too short","The secondary is in another region","The record is an alias"],
  "a":[0],
  "w":["Correct — nothing can shorten the time a resolver keeps a cached answer other than a lower TTL.",
      "A short interval makes detection faster, not slower.",
      "Region placement does not affect how long resolvers cache.",
      "Alias TTLs are managed by AWS and are not the cause of an hour-long delay."],
  "x":"DNS failover time is detection plus caching. The health check handles detection; the TTL governs the rest, which is why records used for failover carry short TTLs."},
 {"m":"health-failover",
  "q":"A private internal service in a VPC must be part of a Route 53 failover configuration. How is its health monitored?",
  "o":["Publish a metric to CloudWatch, create an alarm, and attach a health check to that alarm",
       "Create a TCP health check against its private IP","Open the service to the internet for health checks only","Use a calculated health check with no child checks"],
  "a":[0],
  "w":["Correct — the CloudWatch alarm health check is the supported way to monitor something the public checkers cannot reach.",
      "Route 53 health checkers are on the public internet and cannot reach private addresses.",
      "Exposing an internal service publicly to satisfy monitoring is a security regression.",
      "A calculated check aggregates other checks and needs children to evaluate."],
  "x":"The constraint is that health checkers live outside your network. Routing the health signal through CloudWatch keeps the service private while still driving DNS failover."},
 {"m":"routing-policies",
  "q":"During a release, all traffic must be drained from one of two weighted endpoints without deleting its record. How?",
  "o":["Set that record's weight to 0","Delete the health check on that record",
       "Set both weights to 0","Change the policy to simple routing"],
  "a":[0],
  "w":["Correct — a weight of zero stops traffic to that record while leaving it configured and ready to restore.",
      "Removing the health check makes the record eligible again rather than draining it.",
      "If every weight is zero, Route 53 treats them as equal and returns them all.",
      "Switching the policy discards the split entirely and changes behaviour unpredictably."],
  "x":"Weights are relative, and zero means no traffic — unless every record is zero, in which case they are all returned equally. That exception is a favourite exam detail."},
 {"m":"records-ttl",
  "q":"A team plans to repoint a production record to a new load balancer next Tuesday and needs the change to take effect quickly. What should they do this week?",
  "o":["Lower the record's TTL now, so caches expire before the change",
       "Raise the TTL now to reduce query cost","Switch the record to a CNAME","Create a second hosted zone for the new target"],
  "a":[0],
  "w":["Correct — resolvers honour the TTL they last received, so it must be reduced ahead of the change.",
      "A higher TTL makes the change propagate more slowly, which is the opposite of the goal.",
      "Record type does not control propagation speed.",
      "A second hosted zone for the same domain creates conflicting authority."],
  "x":"TTL reduction has to be published in advance because caches hold the previous value for its full lifetime. The usual pattern is lower it days ahead, make the change, then raise it again."},
 {"m":"routing-policies",
  "q":"An application is deployed in three regions and users should reach whichever responds fastest for them. Which policy fits?",
  "o":["Latency-based routing","Geolocation routing","Multivalue answer routing","Simple routing with three values"],
  "a":[0],
  "w":["Correct — latency routing uses measured latency between the user's network and each region.",
      "Geolocation enforces a mapping by location and ignores measured speed.",
      "Multivalue returns healthy records at random, with no performance awareness.",
      "Simple routing returns values without steering by anything."],
  "x":"\"Best performance\" and \"lowest latency\" are the latency policy's trigger words. Note that the nearest region is not always the fastest, which is why latency is measured rather than assumed."},
 {"m":"records-ttl",
  "q":"Internal hostnames such as db.corp.internal must resolve inside two VPCs and nowhere else. What is the correct configuration?",
  "o":["A private hosted zone associated with both VPCs",
       "A public hosted zone with private IP addresses","A CNAME chain from a public zone","A Resolver outbound endpoint alone"],
  "a":[0],
  "w":["Correct — a private hosted zone answers only for the VPCs it is associated with.",
      "Publishing private addresses in a public zone exposes internal naming to anyone who queries it.",
      "A CNAME chain does not restrict who can resolve the name.",
      "An outbound endpoint forwards queries to on-premises DNS and does not host a zone."],
  "x":"Private hosted zones are the internal DNS mechanism, and association with specific VPCs is what scopes them. Outbound and inbound resolver endpoints extend this to hybrid networks."},
 {"m":"health-failover",
  "q":"On-premises applications must resolve names held in an AWS private hosted zone. What is deployed?",
  "o":["A Route 53 Resolver inbound endpoint in the VPC",
       "A Route 53 Resolver outbound endpoint in the VPC","A public hosted zone mirroring the names","A NAT gateway for DNS traffic"],
  "a":[0],
  "w":["Correct — the inbound endpoint gives on-premises resolvers IP addresses in the VPC to forward queries to.",
      "The outbound endpoint is for the opposite direction, when VPC resources query on-premises DNS.",
      "Mirroring internal names publicly defeats the purpose of a private zone.",
      "A NAT gateway carries traffic but does not answer DNS queries for a private zone."],
  "x":"Direction decides the endpoint type: inbound means queries coming into AWS, outbound means queries leaving it. A full hybrid setup usually has both."},
 {"m":"alias",
  "q":"A record must point at a third-party monitoring service's hostname, which changes addresses periodically. Which record type is appropriate?",
  "o":["A CNAME record pointing at the provider's hostname",
       "An alias record pointing at the provider's hostname","An A record with the current address","A multivalue record listing known addresses"],
  "a":[0],
  "w":["Correct — a CNAME follows the provider's own DNS, so address changes need no action from you.",
      "Alias records can only target a defined set of AWS resources, not external names.",
      "A hard-coded address breaks the next time the provider changes it.",
      "Listing addresses manually has the same staleness problem, multiplied."],
  "x":"Alias is for AWS targets; CNAME is for everything else. Pointing at someone else's name rather than their address is what keeps the record correct as they change infrastructure."}
]
}
