# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 8,
"nm": "CloudFront and Global Accelerator",
"tag": "Edge",
"modules": [
{
 "id": "cdn-basics",
 "nm": "How a CDN changes the picture",
 "goal": "Explain what CloudFront caches, from which origins, and why it lowers latency.",
 "min": 6,
 "blocks": [
  {"t":"p","x":"**CloudFront** is a content delivery network: hundreds of edge locations that cache your content close to users. A request goes to the nearest edge, which serves the cached copy or fetches it from the origin once."},
  {"t":"flow","x":["User","Nearest edge location","Cache hit? Serve it","Cache miss? Fetch from the origin over the AWS backbone"],
   "cap":"Even a miss is faster, because the edge-to-origin hop uses AWS's own network."},
  {"t":"h","x":"Origins"},
  {"t":"table","head":["Origin","Typical use"],
   "rows":[
    ["S3 bucket","Static assets, with **Origin Access Control** so the bucket stays private"],
    ["Application Load Balancer, EC2, or any HTTP server","Dynamic content, including origins outside AWS"],
    ["API Gateway or Lambda function URL","APIs at the edge"],
    ["S3 website endpoint","When you want S3's redirect and error-document behaviour"]]},
  {"t":"key","x":"**Origin Access Control (OAC)** lets CloudFront read a private S3 bucket while everyone else is blocked. It replaces the older Origin Access Identity, and it is the correct answer for \"users must not bypass CloudFront and hit S3 directly\"."},
  {"t":"h","x":"Behaviours"},
  {"t":"p","x":"A distribution can have several **cache behaviours**, matched by path pattern. `/api/*` can go to a load balancer with caching disabled while `/static/*` goes to S3 with a long cache lifetime — one domain, two origins."},
  {"t":"h","x":"Price classes"},
  {"t":"p","x":"Restricting a distribution to fewer edge locations lowers cost at the expense of latency in the regions you drop. It is the lever when a question wants CloudFront but cheaper."},
  {"t":"trap","x":"CloudFront caches; it does not replicate storage. \"Store content permanently in every region\" is S3 cross-region replication, not a CDN."}
 ],
 "checks":[
  {"q":"Users must not be able to reach the S3 bucket directly, only through CloudFront. What do you configure?",
   "o":["Origin Access Control with a bucket policy allowing only the distribution",
        "A public bucket policy","A presigned URL for every object","Transfer Acceleration on the bucket"],
   "a":[0],
   "x":"OAC gives the distribution a signed identity that the bucket policy can allow, while Block Public Access keeps everyone else out. It is the modern replacement for Origin Access Identity."},
  {"q":"One domain must serve static files from S3 and API calls from a load balancer. What makes that possible?",
   "o":["Multiple cache behaviours matched by path pattern","Two separate distributions on the same domain",
        "A Route 53 weighted record","An S3 website redirect"],
   "a":[0],
   "x":"Cache behaviours match path patterns and each can have its own origin and caching rules, so a single distribution can front several backends."},
  {"q":"Why is a cache miss on CloudFront still often faster than going straight to the origin?",
   "o":["The edge fetches from the origin over the AWS backbone rather than the public internet",
        "The origin compresses the response automatically","The user's DNS cache is bypassed",
        "The object is stored in every region in advance"],
   "a":[0],
   "x":"The connection from the user terminates at a nearby edge, and the longer hop to the origin runs on AWS's own network, which is generally faster and more consistent than the public internet."},
  {"q":"What does choosing a smaller price class do?",
   "o":["Serves from fewer edge locations, lowering cost and raising latency in dropped regions",
        "Reduces the cache lifetime","Disables HTTPS","Limits the number of origins"],
   "a":[0],
   "x":"Price classes trade global reach for cost. Users in regions whose edges are excluded are served from further away, so it is a deliberate latency-for-money decision."}
 ]
},
{
 "id":"cache-control",
 "nm":"Controlling the cache",
 "goal":"Decide what is cached, for how long, and how to push a change out immediately.",
 "min":6,
 "blocks":[
  {"t":"h","x":"How long something is cached"},
  {"t":"list","x":[
   "The origin's `Cache-Control` or `Expires` header decides, within the minimum, default and maximum TTLs set on the behaviour.",
   "A **long TTL** gives a high hit ratio and a cheap, fast site.",
   "A **short TTL** keeps content fresh at the cost of more origin traffic."]},
  {"t":"h","x":"The cache key"},
  {"t":"p","x":"By default CloudFront keys the cache on the URL alone. A **cache policy** adds selected headers, cookies or query strings. Every value you add multiplies the number of stored copies and lowers the hit ratio, so add only what changes the response."},
  {"t":"split","cols":[
   {"nm":"Cache policy","items":["Decides what is part of the cache key","Also what is forwarded to the origin","Fewer values means a better hit ratio"]},
   {"nm":"Origin request policy","items":["Forwards headers or cookies to the origin **without** putting them in the cache key","Use it for things the origin needs to log but that do not change the response"]}]},
  {"t":"key","x":"Something that must never be cached — a personalised page, an API response — gets a behaviour with caching disabled, not a very short TTL."},
  {"t":"h","x":"Pushing a change out now"},
  {"t":"table","head":["Approach","Effect"],
   "rows":[
    ["**Invalidation**","Removes a path from every edge now. The first few thousand paths per month are free; heavy use is charged"],
    ["**Versioned file names**","`app.v7.js` is a different URL, so it is never stale — the recommended pattern"],
    ["Lowering the TTL","Works eventually, not immediately"]]},
  {"t":"trap","x":"Invalidating `/*` on every deployment is the expensive habit. Versioned object names achieve the same result with no invalidation at all."},
  {"t":"h","x":"Edge compute"},
  {"t":"table","head":["","CloudFront Functions","Lambda@Edge"],
   "rows":[
    ["Runs on","Viewer request and response only","Viewer and origin, request and response"],
    ["Language","JavaScript, sub-millisecond","Node.js or Python, up to seconds"],
    ["Good for","Header manipulation, URL rewrites, simple redirects, token checks","Anything needing a network call, a library, or the origin response body"]]}
 ],
 "checks":[
  {"q":"A deployment must be visible to all users immediately. What is the recommended approach?",
   "o":["Serve the new assets under versioned file names","Invalidate /* after every deployment",
        "Set the TTL to zero permanently","Disable the distribution and re-enable it"],
   "a":[0],
   "x":"A new file name is a new cache key, so there is nothing stale to remove and no invalidation to pay for. Invalidation works but becomes costly as a routine."},
  {"q":"An API response must never be served from cache. What is the correct configuration?",
   "o":["A cache behaviour for that path with caching disabled","A one-second TTL",
        "An origin request policy forwarding all headers","A smaller price class"],
   "a":[0],
   "x":"Disabling caching on the behaviour is explicit and reliable. A very short TTL still allows a stale response inside the window and still stores copies."},
  {"q":"What is the effect of adding many headers and cookies to the cache key?",
   "o":["More cached variants and a lower cache hit ratio","A longer TTL for every object",
        "Faster origin responses","Automatic compression"],
   "a":[0],
   "x":"Each distinct combination becomes its own cached object, so the cache fragments and more requests reach the origin. Only values that genuinely change the response belong in the key."},
  {"q":"A simple URL rewrite must run on every viewer request with the lowest possible overhead. What should be used?",
   "o":["A CloudFront Function","A Lambda@Edge function on the origin response",
        "An S3 Object Lambda access point","An origin request policy"],
   "a":[0],
   "x":"CloudFront Functions run in sub-millisecond time at the viewer request and response stages, which suits header and URL manipulation. Lambda@Edge is heavier and reaches the origin stages too."}
 ]
},
{
 "id":"cdn-security",
 "nm":"Restricting who gets the content",
 "goal":"Serve private content through a CDN and block the traffic you do not want.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Control","What it does"],
   "rows":[
    ["**Signed URLs**","Time-limited access to **one file** — a download link for a purchased item"],
    ["**Signed cookies**","Time-limited access to **many files** — a subscriber's whole video library"],
    ["**Geo restriction**","Allow or block whole countries, evaluated at the edge"],
    ["**AWS WAF**","Rules against SQL injection, bad bots, rate limits — attached to the distribution"],
    ["**Origin Access Control**","Keeps the S3 origin private"],
    ["**Field-level encryption**","Encrypts specific form fields at the edge so only the intended service can read them"]]},
  {"t":"key","x":"One file is a **signed URL**; a whole set of files is a **signed cookie**. That single distinction is the most common CloudFront security question."},
  {"t":"h","x":"CloudFront signed URLs against S3 presigned URLs"},
  {"t":"split","cols":[
   {"nm":"CloudFront signed URL","items":["Served from the edge, so it is fast worldwide","Can cover many files with cookies","Works with geo restriction and WAF"]},
   {"nm":"S3 presigned URL","items":["Goes straight to S3 in one region","One object only","Carries the signer's IAM permissions"]}]},
  {"t":"h","x":"HTTPS"},
  {"t":"list","x":[
   "A viewer protocol policy can redirect HTTP to HTTPS or refuse HTTP outright.",
   "A custom domain needs a certificate from **ACM in us-east-1** — CloudFront is a global service and only reads certificates from that region.",
   "The connection to the origin can be HTTPS independently of the viewer connection."]},
  {"t":"trap","x":"An ACM certificate for CloudFront must be in **us-east-1**, whatever region the origin is in. Certificates for a regional load balancer must be in that load balancer's region instead."}
 ],
 "checks":[
  {"q":"Subscribers must stream hundreds of video files, each protected and time limited. What fits?",
   "o":["CloudFront signed cookies","CloudFront signed URLs, one per file",
        "S3 presigned URLs, one per file","A public bucket policy with geo restriction"],
   "a":[0],
   "x":"Signed cookies grant access to a set of files with one credential, which suits a whole library. Signing every file individually is the answer for a single download, not a catalogue."},
  {"q":"In which region must an ACM certificate live to be used with CloudFront?",
   "o":["us-east-1","The region of the origin","Any region","The region closest to most users"],
   "a":[0],
   "x":"CloudFront is a global service and reads its certificates from us-east-1 only. A certificate in the origin's region works for a regional load balancer but not for the distribution."},
  {"q":"Traffic from a set of countries must be blocked before it reaches the application. What does this most cheaply?",
   "o":["CloudFront geo restriction","A security group rule per country",
        "A Route 53 geolocation record","An origin request policy"],
   "a":[0],
   "x":"Geo restriction is evaluated at the edge, so blocked requests never reach the origin. Security groups cannot express countries, and geolocation routing steers rather than blocks."},
  {"q":"How do you stop users bypassing CloudFront and fetching objects directly from the S3 origin?",
   "o":["Use Origin Access Control and a bucket policy that allows only the distribution",
        "Enable geo restriction","Use signed cookies","Shorten the TTL"],
   "a":[0],
   "x":"OAC gives CloudFront an identity the bucket policy can allow while Block Public Access keeps everyone else out, so the only path to the object is through the distribution."}
 ]
},
{
 "id":"global-accelerator",
 "nm":"Global Accelerator, and choosing between the two",
 "goal":"Say what Global Accelerator does that CloudFront does not, and pick between them.",
 "min":6,
 "blocks":[
  {"t":"p","x":"**Global Accelerator** gives you two **static anycast IP addresses**. Traffic enters the AWS network at the nearest edge and travels the backbone to your endpoint — but nothing is cached."},
  {"t":"table","head":["","CloudFront","Global Accelerator"],
   "rows":[
    ["Caches content","**Yes** — that is the point","**No**"],
    ["Protocols","HTTP and HTTPS","**Any TCP or UDP**"],
    ["Addressing","A DNS name","**Two static anycast IPs**"],
    ["Failover","Per origin","**Fast regional failover**, typically about a minute"],
    ["Use it for","Static and dynamic web content","Gaming, VoIP, IoT, non-HTTP protocols, regional failover"]]},
  {"t":"key","x":"Two phrases separate them. **\"Cache static content closer to users\"** is CloudFront. **\"Static IP addresses\"** or **\"UDP\"** or **\"fail over between regions quickly\"** is Global Accelerator."},
  {"t":"h","x":"Endpoint groups and traffic dials"},
  {"t":"list","x":[
   "An accelerator has a listener, and **endpoint groups** — one per region, each containing load balancers, EC2 instances or Elastic IPs.",
   "A **traffic dial** shifts a percentage away from a region, which is how a blue/green or gradual regional cutover is done.",
   "**Health checks** remove an unhealthy endpoint group, and traffic moves in about a minute without any DNS change."]},
  {"t":"flow","x":["User","Nearest AWS edge via anycast IP","AWS backbone","Healthy regional endpoint"],
   "cap":"No DNS change on failover, because the client keeps using the same IP address."},
  {"t":"trap","x":"Global Accelerator does not cache. Offering it to speed up repeated downloads of the same large file is wrong — that is CloudFront's job."}
 ],
 "checks":[
  {"q":"A multiplayer game uses UDP and clients must connect to fixed IP addresses. Which service?",
   "o":["AWS Global Accelerator","Amazon CloudFront","Route 53 latency routing","An Application Load Balancer"],
   "a":[0],
   "x":"Global Accelerator supports any TCP or UDP traffic and provides two static anycast IPs. CloudFront handles HTTP and HTTPS only and is addressed by DNS name."},
  {"q":"An application must fail over between two regions within about a minute without relying on DNS propagation. What provides this?",
   "o":["Global Accelerator with endpoint groups in both regions","Route 53 failover records",
        "CloudFront with two origins","An Auto Scaling group spanning both regions"],
   "a":[0],
   "x":"Because clients keep using the same anycast addresses, failover happens inside the AWS network rather than through DNS, so no resolver cache can delay it."},
  {"q":"What does a traffic dial on an endpoint group do?",
   "o":["Shifts a percentage of traffic away from that region","Changes the cache TTL",
        "Limits the number of connections per client","Selects the price class"],
   "a":[0],
   "x":"The dial reduces the share of traffic a region receives, which makes gradual regional cutovers and blue/green releases possible without touching DNS."},
  {"q":"Users repeatedly download the same large static file from around the world. Which service reduces the load on the origin?",
   "o":["CloudFront, because it caches the file at the edge","Global Accelerator, because it uses the backbone",
        "Route 53 multivalue answer routing","An Application Load Balancer with stickiness"],
   "a":[0],
   "x":"Caching is what removes repeated origin fetches, and only CloudFront caches. Global Accelerator improves the network path but forwards every request to the origin."}
 ]
}
],
"recap":[
 {"t":"h","x":"CloudFront or Global Accelerator"},
 {"t":"dtree","x":[
  ["Cache static or dynamic web content near users","CloudFront"],
  ["Static IP addresses required","Global Accelerator"],
  ["UDP or a non-HTTP protocol","Global Accelerator"],
  ["Fail over between regions in about a minute","Global Accelerator"],
  ["Block countries at the edge","CloudFront geo restriction"],
  ["Protect one file with a time-limited link","CloudFront signed URL"],
  ["Protect a whole library for a subscriber","CloudFront signed cookies"]]},
 {"t":"h","x":"Cache behaviour settings that matter"},
 {"t":"table","head":["Goal","Setting"],
  "rows":[["Higher hit ratio","Fewer values in the cache key; longer TTLs"],
          ["Never cache this path","A behaviour with caching disabled"],
          ["Origin needs a header that does not change the response","Origin request policy, not the cache key"],
          ["Push a change out now","Versioned file names, or an invalidation"],
          ["Cheap edge logic","CloudFront Functions"],
          ["Edge logic needing a network call","Lambda@Edge"]]},
 {"t":"key","x":"Keep the S3 origin private with Origin Access Control, and put the ACM certificate for a custom domain in us-east-1. Both facts are used to make otherwise plausible options wrong."},
 {"t":"h","x":"Signed URL, signed cookie, presigned URL"},
 {"t":"table","head":["","Covers","Served by"],
  "rows":[["CloudFront signed URL","One file","The edge"],
          ["CloudFront signed cookie","Many files","The edge"],
          ["S3 presigned URL","One object","S3 directly"]]},
 {"t":"h","x":"What each one is not"},
 {"t":"split","cols":[
  {"nm":"CloudFront is not","items":["A replication service","A way to get static IP addresses","A load balancer for UDP"]},
  {"nm":"Global Accelerator is not","items":["A cache","An HTTP-aware service","A replacement for a CDN on static content"]}]},
 {"t":"trap","x":"Recurring distractors: Global Accelerator offered for caching; CloudFront offered where static IPs are required; an ACM certificate in the origin's region for a distribution; and `/*` invalidation as the routine deployment step."}
],
"final":[
 {"m":"global-accelerator",
  "q":"A voice application uses UDP, and enterprise customers must allow-list fixed IP addresses in their firewalls. Which service should front it?",
  "o":["AWS Global Accelerator","Amazon CloudFront","An Application Load Balancer","Route 53 latency-based routing"],
  "a":[0],
  "w":["Correct — it supports UDP and provides two static anycast IP addresses that customers can allow-list.",
      "CloudFront handles only HTTP and HTTPS and is reached by DNS name.",
      "An ALB is HTTP-only and has no static addresses.",
      "Latency routing returns names or addresses that change and does not carry UDP."],
  "x":"Two requirements point the same way: a non-HTTP protocol and fixed addresses. Global Accelerator is the only service that satisfies both, with the added benefit of fast regional failover."},
 {"m":"cdn-security",
  "q":"A media service must let a subscriber stream any of thousands of files for the next four hours, without generating a link per file. What should it use?",
  "o":["CloudFront signed cookies","CloudFront signed URLs","S3 presigned URLs","A bucket policy restricted by IP"],
  "a":[0],
  "w":["Correct — one signed cookie grants time-limited access to a set of files matching a policy.",
      "Signed URLs are per file, which is exactly the work the requirement avoids.",
      "Presigned URLs are also per object and bypass CloudFront entirely.",
      "IP restrictions cannot express per-subscriber, time-limited entitlement."],
  "x":"The file count decides it: signed URL for one file, signed cookies for many. Cookies also keep working as the client moves between files without new signatures."},
 {"m":"cdn-basics",
  "q":"Static assets are served through CloudFront, but users can still fetch them straight from the S3 bucket URL, bypassing WAF rules. What fixes this?",
  "o":["Enable Origin Access Control and restrict the bucket policy to the distribution",
       "Enable geo restriction on the distribution","Shorten the cache TTL","Move the bucket to another region"],
  "a":[0],
  "w":["Correct — OAC plus a bucket policy naming the distribution makes CloudFront the only path to the objects.",
      "Geo restriction filters by country at the edge and does nothing about direct bucket access.",
      "TTL affects freshness, not access control.",
      "Region has no bearing on who may read the bucket."],
  "x":"Bypassing the CDN also bypasses WAF, signed URLs and geo restriction, so locking the origin is part of making those controls meaningful. OAC is the current mechanism for it."},
 {"m":"cache-control",
  "q":"Every deployment is followed by an invalidation of /*, and the invalidation charges are now significant. What is the recommended alternative?",
  "o":["Give assets versioned file names so each release has new cache keys",
       "Reduce the default TTL to sixty seconds","Disable caching on all behaviours","Use a smaller price class"],
  "a":[0],
  "w":["Correct — a new file name is a new object at the edge, so nothing stale has to be removed.",
      "A short TTL raises origin load continuously and still allows stale content briefly.",
      "Disabling caching removes the benefit of the CDN entirely.",
      "Price class affects which edges serve traffic, not cache invalidation."],
  "x":"Content-hashed or versioned file names are the standard practice with any CDN: the HTML referencing them changes, and the assets themselves can be cached effectively forever."},
 {"m":"cdn-security",
  "q":"A custom domain on a CloudFront distribution shows a certificate error, although an ACM certificate for that domain exists in eu-west-1 where the origin runs. What is wrong?",
  "o":["CloudFront requires the certificate to be in us-east-1",
       "The certificate must be imported rather than issued by ACM","Certificates cannot be used with alternate domain names","The distribution needs a dedicated IP"],
  "a":[0],
  "w":["Correct — CloudFront is global and reads certificates only from us-east-1.",
      "ACM-issued certificates work fine; the region is the problem.",
      "Alternate domain names are exactly what such certificates are for.",
      "Dedicated IP support is a legacy option unrelated to the certificate region."],
  "x":"This is a standing gotcha: regional services want the certificate in their own region, while CloudFront wants it in us-east-1 regardless of where the origin lives."},
 {"m":"cache-control",
  "q":"An origin needs the viewer's country header for logging, but the response is identical for every country. How should CloudFront be configured?",
  "o":["Forward the header with an origin request policy and leave it out of the cache key",
       "Add the header to the cache policy so it is part of the cache key","Disable caching for that behaviour","Use a Lambda@Edge function on the origin response"],
  "a":[0],
  "w":["Correct — the origin receives the header while the cache still stores a single variant.",
      "Adding it to the cache key would create a copy per country and fragment the cache for no benefit.",
      "Disabling caching discards the CDN's value entirely.",
      "An edge function is unnecessary work for something a policy handles directly."],
  "x":"The separation between cache policy and origin request policy exists for exactly this case: the origin can see values that do not influence the cached response."},
 {"m":"global-accelerator",
  "q":"During a regional migration, traffic must be shifted gradually from eu-west-1 to eu-central-1 with no DNS changes. What supports this?",
  "o":["Global Accelerator traffic dials on the endpoint groups",
       "Route 53 weighted records","CloudFront cache behaviours","An Application Load Balancer with two target groups"],
  "a":[0],
  "w":["Correct — the dial adjusts the share a region receives while clients keep using the same anycast IPs.",
      "Weighted DNS records would work but are exactly the DNS change the requirement excludes.",
      "Cache behaviours route by path, not by region.",
      "A load balancer's target groups are within a single region."],
  "x":"Because Global Accelerator holds the client connection at fixed addresses, shifting traffic is a control-plane change that takes effect immediately, with no resolver caching involved."},
 {"m":"cdn-basics",
  "q":"A single domain must serve cached images from S3 and uncached API responses from an Application Load Balancer. How is this configured?",
  "o":["One distribution with two cache behaviours, each with its own origin and caching settings",
       "Two distributions sharing the same alternate domain name","A Route 53 weighted split between the two origins","An origin group with automatic failover"],
  "a":[0],
  "w":["Correct — path patterns select the behaviour, and each behaviour has its own origin and cache policy.",
      "Two distributions cannot share the same alternate domain name.",
      "Weighted DNS splits traffic randomly rather than by path.",
      "Origin groups handle failover between origins, not routing by path."],
  "x":"Cache behaviours are the mechanism for mixed workloads behind one CDN domain, which is how a site serves static assets and APIs from one name."},
 {"m":"cache-control",
  "q":"A viewer request must be rewritten and a header added, with the lowest possible latency and cost, and no external calls. Which option fits?",
  "o":["A CloudFront Function at the viewer request stage",
       "A Lambda@Edge function at the origin request stage","An S3 Object Lambda access point","An AWS WAF rule"],
  "a":[0],
  "w":["Correct — CloudFront Functions run in sub-millisecond time and are priced for very high volume.",
      "Lambda@Edge is heavier and origin-stage execution would not run on every viewer request.",
      "Object Lambda transforms S3 retrievals and is unrelated to CloudFront request handling.",
      "WAF inspects and blocks requests; it does not rewrite them."],
  "x":"CloudFront Functions cover header manipulation, URL rewrites, redirects and simple token checks. Anything requiring a network call or a library is Lambda@Edge territory."},
 {"m":"cdn-basics",
  "q":"A team wants CloudFront's benefits but the bill for edge locations in distant regions is hard to justify, and those users are a tiny minority. What is the lever?",
  "o":["Select a smaller price class so the distribution uses fewer edge locations",
       "Reduce the default TTL","Disable IPv6 on the distribution","Move the origin closer to those users"],
  "a":[0],
  "w":["Correct — price classes limit which edge locations serve the distribution, lowering cost.",
      "TTL changes affect hit ratio and origin load, not edge pricing tiers.",
      "IPv6 has no meaningful effect on cost here.",
      "Moving the origin helps a minority at the expense of the majority."],
  "x":"Price classes are the explicit cost-versus-reach control. Users in excluded regions are still served, just from a more distant edge, which is the trade-off being accepted."}
]
}
