# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 9,
"nm": "Storage extras: Snow, FSx, Storage Gateway, DataSync",
"tag": "Storage",
"modules": [
{
 "id": "snow-family",
 "nm": "Moving data when the network cannot",
 "goal": "Decide between the network and a physical device, and pick the right Snow device.",
 "min": 6,
 "blocks": [
  {"t":"p","x":"The **Snow Family** is physical hardware AWS ships to you. You fill it, ship it back, and AWS loads the data into S3. It exists because some transfers are simply too large for the link you have."},
  {"t":"table","head":["Device","Capacity","Also does"],
   "rows":[
    ["**Snowcone**","8 TB usable","Small, rugged, battery powered; can be shipped or use DataSync over the network"],
    ["**Snowball Edge Storage Optimized**","~80 TB","Bulk transfer, plus some local compute"],
    ["**Snowball Edge Compute Optimized**","~42 TB","Local processing at the edge, with optional GPU"],
    ["**Snowmobile**","Up to 100 PB","A shipping container on a lorry, for exabyte-scale migrations"]]},
  {"t":"key","x":"The rough rule: if the transfer would take **more than about a week** over your connection, ship a device. Divide the data size by your usable bandwidth before answering."},
  {"t":"h","x":"Beyond transfer"},
  {"t":"list","x":[
   "Snowball Edge devices run EC2 instances and Lambda functions **locally**, which is how data is processed at a site with no connectivity.",
   "Data is encrypted with KMS, and the device is tamper-resistant.",
   "**OpsHub** is the graphical tool for managing devices without the command line.",
   "Once the data is in S3 you can apply a lifecycle rule straight into Glacier — devices do not import directly into Glacier."]},
  {"t":"flow","x":["Order the device","AWS ships it","Copy data on site","Ship it back","AWS imports to S3","Lifecycle to Glacier if needed"]},
  {"t":"trap","x":"A Snow device cannot import directly into Glacier. The import lands in S3, and a lifecycle rule moves it — an option claiming direct Glacier import is wrong."}
 ],
 "checks":[
  {"q":"A company must move 500 TB to AWS over a link that would take eight months. What should they use?",
   "o":["A Snowball Edge device, or several","S3 Transfer Acceleration","A VPN with compression",
        "Cross-region replication"],
   "a":[0],
   "x":"When the network transfer time is measured in months, physical shipping is faster and cheaper. Transfer Acceleration helps a slow long-distance link but cannot overcome a fundamental bandwidth shortfall."},
  {"q":"A remote site with no reliable connectivity must process data locally before it ever reaches AWS. Which device?",
   "o":["Snowball Edge Compute Optimized","Snowcone","Snowmobile","A gateway endpoint"],
   "a":[0],
   "x":"Compute Optimized devices are built to run EC2 instances and Lambda functions on site, with optional GPU. The other devices are aimed at capacity rather than processing."},
  {"q":"Where does a Snow device import land?",
   "o":["In S3, from where a lifecycle rule can move it onwards","Directly into Glacier Deep Archive",
        "On an EBS volume","In an EFS file system"],
   "a":[0],
   "x":"Imports always arrive in S3. Anything colder is reached afterwards with a lifecycle transition, which is why options promising direct Glacier import are incorrect."},
  {"q":"Which device suits an 8 TB transfer from a rugged environment with limited power?",
   "o":["Snowcone","Snowball Edge Storage Optimized","Snowmobile","Storage Gateway"],
   "a":[0],
   "x":"Snowcone is the small, portable, battery-capable device sized for terabytes rather than tens of terabytes, which fits both the capacity and the environment described."}
 ]
},
{
 "id":"fsx",
 "nm":"FSx: the file systems S3 and EFS do not cover",
 "goal":"Pick the FSx flavour that matches a protocol or a workload named in a question.",
 "min":7,
 "blocks": [
  {"t":"table","head":["FSx for…","Protocol","Choose it when"],
   "rows":[
    ["**Windows File Server**","SMB","Windows applications, **Active Directory** integration, NTFS permissions, DFS"],
    ["**Lustre**","Lustre / POSIX","High performance computing, machine learning, **hundreds of GB/s**; links to an S3 bucket"],
    ["**NetApp ONTAP**","NFS, SMB **and** iSCSI","Moving an existing ONTAP estate, or needing snapshots, cloning and deduplication"],
    ["**OpenZFS**","NFS","Moving a ZFS estate, with snapshots and low-latency NFS"]]},
  {"t":"key","x":"The protocol usually gives it away. **SMB and Active Directory** means FSx for Windows. **Lustre** or an HPC and machine-learning phrasing means FSx for Lustre. Multi-protocol including iSCSI means NetApp ONTAP."},
  {"t":"h","x":"Lustre and S3 together"},
  {"t":"p","x":"A Lustre file system can be **linked to an S3 bucket**: objects appear as files, and results written back can be exported to S3. That is the standard pattern for running an HPC job over data that lives in S3."},
  {"t":"split","cols":[
   {"nm":"Scratch file system","items":["Highest performance","**No replication** — data is lost if a file server fails","Temporary processing"]},
   {"nm":"Persistent file system","items":["Replicated within one Availability Zone","Failed servers are replaced automatically","Longer-term storage"]}]},
  {"t":"trap","x":"EFS is Linux and NFS only. Any question mentioning Windows, SMB, or Active Directory joins moves the answer to FSx for Windows File Server."}
 ],
 "checks":[
  {"q":"Windows servers need a shared file system with Active Directory integration and NTFS permissions. Which service?",
   "o":["FSx for Windows File Server","Amazon EFS","FSx for Lustre","S3 with a mounted client"],
   "a":[0],
   "x":"FSx for Windows speaks SMB and integrates with Active Directory, which is exactly what Windows file sharing expects. EFS offers NFS only and no AD integration."},
  {"q":"A machine learning training job must read a dataset that lives in S3 at very high throughput as a POSIX file system. What fits?",
   "o":["FSx for Lustre linked to the S3 bucket","EFS with provisioned throughput",
        "FSx for Windows File Server","An EBS volume restored from a snapshot"],
   "a":[0],
   "x":"Lustre is built for HPC and machine learning throughput, and its S3 linkage presents objects as files and exports results back. EFS cannot reach those throughput levels."},
  {"q":"What is the trade-off of an FSx for Lustre scratch file system?",
   "o":["Highest performance, but no replication, so a server failure loses data",
        "Lower performance, but replicated across regions","The same as persistent, but cheaper to read",
        "It supports SMB rather than POSIX"],
   "a":[0],
   "x":"Scratch is designed for temporary processing where the data can be regenerated. Persistent file systems replicate within an Availability Zone and replace failed servers automatically."},
  {"q":"A workload must expose the same data over NFS, SMB and iSCSI. Which service?",
   "o":["FSx for NetApp ONTAP","FSx for OpenZFS","Amazon EFS","Storage Gateway volume gateway"],
   "a":[0],
   "x":"ONTAP is the multi-protocol option, and it also brings snapshots, cloning and deduplication from the NetApp feature set. OpenZFS is NFS only and EFS supports NFS alone."}
 ]
},
{
 "id":"storage-gateway",
 "nm":"Storage Gateway: keeping on-premises, backed by AWS",
 "goal":"Choose the gateway type from what the on-premises application expects to see.",
 "min":7,
 "blocks":[
  {"t":"p","x":"**Storage Gateway** is a virtual appliance that runs in your data centre and presents familiar storage to local applications while keeping the bulk of the data in AWS. It is the hybrid answer, not a migration tool."},
  {"t":"table","head":["Gateway","Local systems see","Data ends up in"],
   "rows":[
    ["**S3 File Gateway**","An **NFS or SMB** file share","S3 objects, with lifecycle rules available"],
    ["**FSx File Gateway**","An SMB share with a local cache","FSx for Windows File Server"],
    ["**Volume Gateway — cached**","**iSCSI** disks, with hot data cached locally","S3, with EBS snapshots"],
    ["**Volume Gateway — stored**","iSCSI disks holding the **full dataset locally**","S3 as an asynchronous backup"],
    ["**Tape Gateway**","A **virtual tape library** over iSCSI","S3 and Glacier"]]},
  {"t":"key","x":"Read what the local application expects. A **file share** is File Gateway. A **block device** is Volume Gateway. **Backup software writing tapes** is Tape Gateway."},
  {"t":"h","x":"Cached against stored"},
  {"t":"split","cols":[
   {"nm":"Cached volumes","items":["Primary data in S3","Only the hot subset kept locally","Choose when local capacity is the constraint"]},
   {"nm":"Stored volumes","items":["Primary data on site, so local access is fast","Asynchronously backed up to S3 as snapshots","Choose when low-latency local access to everything matters"]}]},
  {"t":"trap","x":"Tape Gateway is the answer whenever a question mentions an existing backup product that writes to tape and a desire to stop buying tapes. It works because the software still thinks it sees a tape library."},
  {"t":"note","x":"All gateway types need a local cache disk and an upload buffer; sizing them is part of the deployment, and the appliance can also run on a hardware appliance AWS ships."}
 ],
 "checks":[
  {"q":"An on-premises application writes to an SMB share, and the team wants the data to end up in S3 with lifecycle rules. Which gateway?",
   "o":["S3 File Gateway","Volume Gateway in stored mode","Tape Gateway","FSx File Gateway"],
   "a":[0],
   "x":"S3 File Gateway presents NFS or SMB locally and stores each file as an S3 object, so lifecycle rules and S3 features apply directly."},
  {"q":"Existing backup software writes to a tape library and the company wants to stop buying physical tapes. What fits?",
   "o":["Tape Gateway","S3 File Gateway","FSx for Lustre","Snowball Edge"],
   "a":[0],
   "x":"Tape Gateway presents a virtual tape library over iSCSI, so the backup product needs no changes while the tapes become objects in S3 and Glacier."},
  {"q":"An application needs low-latency access to its entire dataset locally, with an off-site copy in AWS. Which volume gateway mode?",
   "o":["Stored volumes","Cached volumes","Tape Gateway","S3 File Gateway"],
   "a":[0],
   "x":"Stored volumes keep the full dataset on site and back it up asynchronously to S3 as snapshots. Cached volumes hold only the hot subset locally, with the rest in S3."},
  {"q":"What does Storage Gateway present to local systems in cached volume mode?",
   "o":["iSCSI block devices with hot data cached locally","An NFS file share",
        "A virtual tape library","An SMB share backed by FSx"],
   "a":[0],
   "x":"Volume gateways are block storage over iSCSI. In cached mode the authoritative copy lives in S3 and only frequently used blocks are held on the local cache disk."}
 ]
},
{
 "id":"datasync-transfer",
 "nm":"DataSync and Transfer Family",
 "goal":"Choose the right service for a recurring copy or an inbound file protocol.",
 "min":6,
 "blocks":[
  {"t":"h","x":"DataSync"},
  {"t":"list","x":[
   "An agent-driven service that **copies large amounts of data on a schedule**, with checksums, retries and file metadata preserved.",
   "Between on-premises storage (NFS, SMB, HDFS) and AWS, or **between AWS services** — S3, EFS, FSx.",
   "Handles permissions and timestamps, which plain scripts usually lose.",
   "Can run over Direct Connect or the internet, and over a **Snowcone** for disconnected sites."]},
  {"t":"key","x":"DataSync is for a **recurring, verified copy**. Storage Gateway is for **ongoing hybrid access**. Snow is for a **one-off bulk move**. Those three are the ones a question will try to blur."},
  {"t":"h","x":"Transfer Family"},
  {"t":"table","head":["Protocol","Why it exists"],
   "rows":[
    ["**SFTP**","Partners who already send files over SFTP"],
    ["**FTPS**","Legacy integrations requiring FTP over TLS"],
    ["**FTP**","Plain FTP, VPC-internal only"],
    ["**AS2**","Business-to-business document exchange"]]},
  {"t":"p","x":"Transfer Family puts a managed endpoint for those protocols in front of **S3 or EFS**, with identities in Directory Service, a custom identity provider, or its own store. Nothing about the partner's workflow changes."},
  {"t":"flow","x":["Partner's SFTP client","AWS Transfer Family endpoint","S3 bucket","Event notification starts processing"],
   "cap":"The file arrives as an object, so the rest of the pipeline is ordinary S3."},
  {"t":"trap","x":"Do not answer \"run an SFTP server on EC2\" when Transfer Family exists. The exam treats a managed endpoint as the lower-overhead answer unless something specific rules it out."}
 ],
 "checks":[
  {"q":"Partners already send files over SFTP and must keep doing so, but the files should land in S3. What fits?",
   "o":["AWS Transfer Family with an SFTP endpoint","An EC2 instance running an SFTP server",
        "S3 Transfer Acceleration","Storage Gateway"],
   "a":[0],
   "x":"Transfer Family provides a managed SFTP endpoint that writes straight into S3, so partners keep their workflow and you run no servers."},
  {"q":"Ten terabytes must be copied from an on-premises NFS share to EFS every night, with permissions and timestamps preserved. Which service?",
   "o":["AWS DataSync","Storage Gateway in cached mode","Snowball Edge","Transfer Family"],
   "a":[0],
   "x":"DataSync is built for scheduled, verified bulk copies and preserves file metadata. Storage Gateway provides ongoing access rather than a scheduled copy, and Snow is for one-off physical moves."},
  {"q":"Which statement distinguishes DataSync from Storage Gateway?",
   "o":["DataSync copies data on a schedule; Storage Gateway provides ongoing hybrid access",
        "DataSync runs only inside AWS","Storage Gateway is a one-off migration tool",
        "DataSync cannot preserve file permissions"],
   "a":[0],
   "x":"The two are often confused. DataSync moves data from one place to another repeatedly; Storage Gateway leaves the application on site and backs it with AWS storage continuously."},
  {"q":"A disconnected site must collect data and ship it, then have it copied into AWS with verification. Which combination fits?",
   "o":["DataSync running on a Snowcone device","Transfer Family with an FTP endpoint",
        "Tape Gateway with a virtual library","CloudFront with an S3 origin"],
   "a":[0],
   "x":"Snowcone can run DataSync, which is how data collected at a disconnected site is transferred with checksums and retries once the device is back online or shipped."}
 ]
}
],
"recap":[
 {"t":"h","x":"The four services, separated"},
 {"t":"table","head":["Service","Question it answers"],
  "rows":[["Snow Family","How do I move a lot of data when the network cannot carry it?"],
          ["FSx","How do I get a file system S3 and EFS do not provide?"],
          ["Storage Gateway","How do I keep the application on site but the data in AWS?"],
          ["DataSync","How do I copy data repeatedly, verified, and keep the metadata?"],
          ["Transfer Family","How do partners keep using SFTP, FTPS, FTP or AS2?"]]},
 {"t":"h","x":"FSx by protocol"},
 {"t":"table","head":["Clue in the question","Answer"],
  "rows":[["SMB, Active Directory, NTFS","FSx for Windows File Server"],
          ["HPC, machine learning, extreme throughput, S3 linkage","FSx for Lustre"],
          ["NFS and SMB and iSCSI together, or an existing NetApp estate","FSx for NetApp ONTAP"],
          ["An existing ZFS estate, NFS with snapshots","FSx for OpenZFS"],
          ["Linux NFS, simple and elastic","Amazon EFS, not FSx"]]},
 {"t":"key","x":"Storage Gateway is chosen by what the local application expects: a file share means File Gateway, a block device means Volume Gateway, and tapes mean Tape Gateway."},
 {"t":"h","x":"Snow sizing"},
 {"t":"dtree","x":[
  ["8 TB from a rugged or low-power site","Snowcone"],
  ["Tens of terabytes, bulk transfer","Snowball Edge Storage Optimized"],
  ["Processing must happen on site","Snowball Edge Compute Optimized"],
  ["Petabytes, an entire data centre","Snowmobile"],
  ["Transfer would finish in a day or two over the network","No device — use the network"]]},
 {"t":"h","x":"One-off, recurring, or continuous"},
 {"t":"split","cols":[
  {"nm":"One-off","items":["Snow Family for bulk physical transfer","Lands in S3, then lifecycle onwards"]},
  {"nm":"Recurring","items":["DataSync on a schedule","Checksums, retries, metadata preserved"]},
  {"nm":"Continuous","items":["Storage Gateway for hybrid access","Local cache, AWS holds the bulk"]}]},
 {"t":"trap","x":"Recurring distractors: a Snow device importing straight into Glacier; EFS offered to Windows SMB clients; an EC2-hosted SFTP server where Transfer Family fits; and DataSync and Storage Gateway used interchangeably."}
],
"final":[
 {"m":"fsx",
  "q":"A design team runs Windows applications that need a shared drive with Active Directory permissions and DFS namespaces. Which service should be used?",
  "o":["FSx for Windows File Server","Amazon EFS","FSx for Lustre","S3 File Gateway"],
  "a":[0],
  "w":["Correct — it speaks SMB, joins Active Directory, and supports NTFS permissions and DFS.",
      "EFS supports NFS and Linux clients only, with no Active Directory integration.",
      "Lustre targets HPC throughput over POSIX, not Windows file sharing.",
      "A File Gateway would present SMB on premises, but the requirement is a shared drive in AWS."],
  "x":"SMB plus Active Directory is the FSx for Windows signature. EFS is ruled out by protocol alone, whatever else the question says about scale or elasticity."},
 {"m":"snow-family",
  "q":"A broadcaster must move 900 TB of archive footage into S3. Their internet link would take over a year. What should they do?",
  "o":["Order Snowball Edge devices and ship the data physically",
       "Use S3 Transfer Acceleration over the existing link","Set up a Site-to-Site VPN and copy overnight","Use DataSync over the internet"],
  "a":[0],
  "w":["Correct — at this ratio of data to bandwidth, physical shipping is the only practical option.",
      "Transfer Acceleration improves long-distance throughput but cannot manufacture missing bandwidth.",
      "A VPN adds encryption overhead to the same insufficient link.",
      "DataSync is efficient but still bounded by the same link speed."],
  "x":"The calculation matters: divide the data by the usable bandwidth. Anything beyond roughly a week of continuous transfer is where Snow devices become the intended answer."},
 {"m":"storage-gateway",
  "q":"An enterprise backup product writes to tape and the company wants to eliminate physical tape handling without replacing the software. What fits?",
  "o":["Tape Gateway, which presents a virtual tape library over iSCSI",
       "S3 File Gateway with an SMB share","DataSync from the backup server to S3","Snowball Edge for each backup cycle"],
  "a":[0],
  "w":["Correct — the backup software continues writing tapes while the tapes become objects in S3 and Glacier.",
      "A file share would require reconfiguring the backup product to write files instead of tapes.",
      "DataSync copies files and does not present a tape interface.",
      "Shipping a device for each backup cycle is impractical and not what Snow is for."],
  "x":"Tape Gateway exists precisely so that a tape-based backup estate can move to AWS without changing the software or the operational procedures around it."},
 {"m":"datasync-transfer",
  "q":"A hospital's nightly export must copy 4 TB from an on-premises SMB share into S3, preserving file permissions and verifying integrity. Which service?",
  "o":["AWS DataSync","AWS Transfer Family","S3 File Gateway","Cross-region replication"],
  "a":[0],
  "w":["Correct — DataSync schedules verified transfers and preserves metadata such as permissions and timestamps.",
      "Transfer Family provides inbound protocol endpoints; it does not pull from a share on a schedule.",
      "A File Gateway gives continuous access rather than a scheduled, verified copy.",
      "Replication copies between S3 buckets and cannot read an on-premises share."],
  "x":"The words \"nightly\", \"preserve permissions\" and \"verify\" together describe DataSync. Storage Gateway would be the answer if the requirement were ongoing access rather than a copy."},
 {"m":"fsx",
  "q":"A genomics pipeline needs a POSIX file system delivering hundreds of gigabytes per second over data that is stored in S3. Which service?",
  "o":["FSx for Lustre with an S3 data repository association",
       "Amazon EFS in Max I/O mode","FSx for OpenZFS","An io2 EBS volume with Multi-Attach"],
  "a":[0],
  "w":["Correct — Lustre is the HPC file system, and linking it to S3 presents the objects as files.",
      "EFS scales well but does not reach Lustre's throughput for this class of workload.",
      "OpenZFS targets NFS workloads migrating from ZFS, not extreme parallel throughput.",
      "Multi-Attach is block storage confined to one Availability Zone with far lower aggregate throughput."],
  "x":"The pairing of HPC-scale throughput with data already in S3 is what makes Lustre the intended answer, since the data repository association removes any copy step."},
 {"m":"storage-gateway",
  "q":"A branch office application needs low-latency access to all of its data locally, with a copy kept in AWS for recovery. Which configuration fits?",
  "o":["Volume Gateway in stored mode","Volume Gateway in cached mode","S3 File Gateway","FSx File Gateway"],
  "a":[0],
  "w":["Correct — the entire dataset stays on site for low latency and is asynchronously snapshotted to S3.",
      "Cached mode keeps only hot data locally, so cold reads would cross the network.",
      "A file share changes the interface the application uses; the requirement describes block storage.",
      "FSx File Gateway caches an SMB share and does not keep the full dataset locally as blocks."],
  "x":"Stored versus cached is decided by where the authoritative copy lives. \"All data locally, low latency\" means stored, and S3 then holds the recovery copy."},
 {"m":"datasync-transfer",
  "q":"External suppliers must upload files using FTPS into S3, authenticating against the company's Active Directory. What should be deployed?",
  "o":["AWS Transfer Family with an FTPS endpoint and Directory Service authentication",
       "An EC2 fleet running an FTPS server behind a load balancer","S3 presigned URLs emailed to suppliers","Storage Gateway in file mode at the supplier's site"],
  "a":[0],
  "w":["Correct — Transfer Family provides a managed FTPS endpoint backed by S3 with directory-based identities.",
      "Running the servers yourself adds patching, scaling and availability work the managed service removes.",
      "Presigned URLs change the supplier's workflow, which the requirement preserves.",
      "Deploying an appliance at each supplier's site is impractical and not what Storage Gateway is for."],
  "x":"Transfer Family exists so legacy file protocols can be kept without operating servers. The exam consistently prefers the managed endpoint when the protocol is SFTP, FTPS, FTP or AS2."},
 {"m":"snow-family",
  "q":"An oil rig collects sensor data and must run analysis locally before any of it is sent to AWS, with no reliable connectivity. What fits?",
  "o":["A Snowball Edge Compute Optimized device running EC2 instances locally",
       "A Snowcone shipped weekly with no processing","Storage Gateway in cached mode","DataSync over a satellite link"],
  "a":[0],
  "w":["Correct — Compute Optimized devices run EC2 and Lambda on site, which is what local analysis requires.",
      "Snowcone is a transfer device sized for terabytes and is not the compute answer here.",
      "Storage Gateway assumes a usable network connection to AWS.",
      "DataSync needs connectivity that the scenario explicitly lacks."],
  "x":"Snowball Edge's local compute is what distinguishes it from a plain transfer device, and it is the intended answer whenever processing has to happen before the data can travel."},
 {"m":"fsx",
  "q":"An FSx for Lustre file system is used for temporary processing where results are written back to S3, and cost matters more than durability. Which deployment type fits?",
  "o":["A scratch file system","A persistent file system","FSx for OpenZFS","FSx for NetApp ONTAP"],
  "a":[0],
  "w":["Correct — scratch gives the highest performance at the lowest cost and accepts that a server failure loses data.",
      "Persistent replicates within an Availability Zone and costs more than this workload needs.",
      "OpenZFS is a different service aimed at NFS workloads.",
      "ONTAP is multi-protocol and considerably more than this requirement asks for."],
  "x":"Scratch is explicitly for regenerable, temporary data. The presence of an S3 copy and the phrase \"cost matters more than durability\" is what makes it appropriate here."},
 {"m":"storage-gateway",
  "q":"A company wants on-premises users to keep using an SMB share while the data is stored as objects in S3 with lifecycle policies applied. Which gateway?",
  "o":["S3 File Gateway","FSx File Gateway","Volume Gateway in cached mode","Tape Gateway"],
  "a":[0],
  "w":["Correct — files written to the share become S3 objects, so lifecycle rules and other S3 features apply.",
      "FSx File Gateway stores the data in FSx for Windows, not as S3 objects with lifecycle rules.",
      "Volume Gateway stores blocks and EBS snapshots, not individually addressable objects.",
      "Tape Gateway presents tapes, which is not a file share."],
  "x":"The requirement for S3 lifecycle policies is what selects S3 File Gateway specifically: only it stores each file as an object that S3 features can act on."}
]
}
