# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 10,
"nm": "Decoupling: SQS, SNS, Kinesis and MQ",
"tag": "Integration",
"modules": [
{
 "id": "sqs-queues",
 "nm": "SQS: a buffer between producer and consumer",
 "goal": "Explain what a queue protects you from, and configure visibility and retries correctly.",
 "min": 8,
 "blocks": [
  {"t":"p","x":"**SQS** is a queue. Producers write messages, consumers read and then delete them. Nothing is pushed — a consumer **polls**. The point is that producer and consumer no longer have to be available at the same moment or run at the same speed."},
  {"t":"table","head":["Property","Standard queue","FIFO queue"],
   "rows":[
    ["Ordering","Best effort","**Strictly in order**, per message group"],
    ["Delivery","**At least once** — duplicates are possible","Exactly once, with deduplication"],
    ["Throughput","Nearly unlimited","300 messages/s, or 3,000 with batching; higher with high-throughput mode"],
    ["Queue name","Anything","Must end in `.fifo`"]]},
  {"t":"key","x":"Standard queues can deliver a message **more than once**, so consumers must be idempotent. If a question says duplicates are unacceptable and order matters, the answer is FIFO."},
  {"t":"h","x":"Visibility timeout"},
  {"t":"flow","x":["Consumer receives a message","It becomes invisible to others","Consumer finishes and deletes it","If not deleted in time, it reappears"],
   "cap":"Default 30 seconds, up to 12 hours."},
  {"t":"list","x":[
   "Too **short** and a slow consumer's message is handed to a second consumer, so the work runs twice.",
   "Too **long** and a failed consumer's message is stuck waiting before anyone can retry it.",
   "A consumer that needs more time can extend it with `ChangeMessageVisibility`."]},
  {"t":"h","x":"Dead-letter queues"},
  {"t":"p","x":"After a message has been received **maxReceiveCount** times without being deleted, it is moved to a **dead-letter queue**. That stops one poison message blocking the queue forever and gives you somewhere to inspect failures."},
  {"t":"h","x":"Polling and other settings"},
  {"t":"table","head":["Setting","What it does"],
   "rows":[
    ["**Long polling**","Waits up to 20 seconds for a message instead of returning empty — fewer API calls, lower cost, less latency"],
    ["**Delay queue**","Every message is invisible for up to 15 minutes after being sent"],
    ["**Message retention**","1 minute to **14 days**, default 4 days"],
    ["**Message size**","Up to 256 KB; larger payloads go to S3 with the Extended Client Library"]]},
  {"t":"trap","x":"\"The same job is being processed twice\" on a standard queue is usually a **visibility timeout shorter than the processing time**, not a bug in the consumer."}
 ],
 "checks":[
  {"q":"Orders must be processed strictly in sequence and never duplicated. Which queue type?",
   "o":["A FIFO queue","A standard queue with long polling","A standard queue with a delay",
        "A standard queue with a dead-letter queue"],
   "a":[0],
   "x":"FIFO queues preserve order within a message group and deduplicate, which is exactly the stated requirement. Standard queues are at-least-once and only best-effort ordered."},
  {"q":"Jobs take four minutes but the visibility timeout is thirty seconds. What is the symptom?",
   "o":["The same job is picked up and processed repeatedly","Messages are deleted before processing",
        "The queue stops accepting messages","Messages go straight to the dead-letter queue"],
   "a":[0],
   "x":"The message becomes visible again long before the first consumer finishes, so another consumer starts the same work. The fix is a visibility timeout longer than the processing time."},
  {"q":"What causes a message to be moved to a dead-letter queue?",
   "o":["Being received more than maxReceiveCount times without being deleted",
        "Exceeding 256 KB in size","Being older than one hour","Being sent to a FIFO queue out of order"],
   "a":[0],
   "x":"The redrive policy counts receives. Once the count is exceeded the message is moved aside so a single failing message cannot block the queue indefinitely."},
  {"q":"Consumers make constant empty ReceiveMessage calls and the API bill is high. What should be enabled?",
   "o":["Long polling","A delay queue","A dead-letter queue","FIFO mode"],
   "a":[0],
   "x":"Long polling holds the request open for up to twenty seconds waiting for a message, which removes most empty responses and lowers both cost and latency."}
 ]
},
{
 "id":"sns-fanout",
 "nm":"SNS and the fan-out pattern",
 "goal":"Send one event to many consumers, and say when SNS alone is not enough.",
 "min":6,
 "blocks":[
  {"t":"p","x":"**SNS** is publish and subscribe. A publisher sends to a **topic** and every subscriber receives a copy. It pushes; unlike a queue, there is nothing to poll and nothing stored for later."},
  {"t":"table","head":["Subscriber","Notes"],
   "rows":[["SQS queue","The durable option — this is what fan-out means in practice"],
           ["Lambda","Invoked per message"],
           ["HTTP or HTTPS endpoint","With retry policies"],
           ["Email, SMS, mobile push","Human-facing notifications"],
           ["Kinesis Data Firehose","Straight into S3, Redshift or OpenSearch"]]},
  {"t":"key","x":"**SNS plus SQS is the fan-out pattern.** Each consumer gets its own queue, so one slow or broken consumer never affects the others, and nothing is lost while a consumer is down."},
  {"t":"flow","x":["Order placed","SNS topic","Queue per consumer: billing, shipping, analytics","Each team processes at its own pace"]},
  {"t":"h","x":"Filtering"},
  {"t":"p","x":"A **subscription filter policy** means a subscriber only receives messages matching attributes it cares about. That is cheaper and simpler than every consumer receiving everything and discarding most of it."},
  {"t":"h","x":"FIFO topics"},
  {"t":"p","x":"An SNS **FIFO topic** preserves ordering and deduplication, and may only deliver to SQS FIFO queues. Use it when the ordering guarantee has to survive the fan-out."},
  {"t":"trap","x":"SNS on its own has no storage. If a subscriber is unavailable, delivery is retried and may ultimately fail — which is why a durable consumer subscribes with an SQS queue rather than an HTTP endpoint."}
 ],
 "checks":[
  {"q":"One event must reach three teams, each processing at its own pace, with no loss if a team's service is down. What is the design?",
   "o":["An SNS topic with an SQS queue subscribed for each team",
        "Three SNS topics, one per team","One SQS queue read by all three teams",
        "An SNS topic with three HTTPS endpoints"],
   "a":[0],
   "x":"Fan-out with a queue per consumer isolates the teams and buffers messages while a consumer is unavailable. A shared queue would let one team consume another's messages."},
  {"q":"A subscriber should only receive messages about one product category. What avoids sending it everything?",
   "o":["A subscription filter policy on attributes","A dead-letter queue","A delay queue",
        "A FIFO topic"],
   "a":[0],
   "x":"Filter policies evaluate message attributes at the topic, so non-matching messages are never delivered. That reduces both cost and the work a consumer does discarding messages."},
  {"q":"What happens to an SNS message if a subscribed HTTPS endpoint is down?",
   "o":["Delivery is retried according to the policy and can ultimately fail","It is stored for fourteen days",
        "It is moved to the topic's backlog","It is delivered to the other subscribers only after the endpoint recovers"],
   "a":[0],
   "x":"SNS does not store messages for later collection. Retries follow the delivery policy and then give up, which is why durable consumers subscribe an SQS queue instead."},
  {"q":"Which subscriber type can an SNS FIFO topic deliver to?",
   "o":["An SQS FIFO queue","An SQS standard queue","An email address","A Lambda function"],
   "a":[0],
   "x":"FIFO topics exist to preserve ordering end to end, so they only deliver to SQS FIFO queues, which can maintain that guarantee."}
 ]
},
{
 "id":"kinesis",
 "nm":"Kinesis: streams instead of queues",
 "goal":"Tell a stream apart from a queue, and choose between Data Streams and Firehose.",
 "min":8,
 "blocks":[
  {"t":"p","x":"A queue gives each message to one consumer and deletes it. A **stream** keeps an ordered log that many consumers read independently, each tracking its own position, and the data stays for its retention period."},
  {"t":"split","cols":[
   {"nm":"SQS","items":["One consumer per message","Deleted once processed","No replay","Scale by adding consumers"]},
   {"nm":"Kinesis Data Streams","items":["Many independent consumers","Retained 1 to 365 days","**Replay from any point**","Ordered per shard"]}]},
  {"t":"key","x":"**\"Replay\"**, **\"multiple applications read the same data\"**, or **\"ordered by device\"** means Kinesis Data Streams. \"Work queue\" means SQS."},
  {"t":"h","x":"Shards and partition keys"},
  {"t":"list","x":[
   "A stream is made of **shards**; each gives 1 MB/s in and 2 MB/s out.",
   "The **partition key** decides the shard, and ordering is guaranteed **within a shard**. Using the device id as the key keeps each device's events in order.",
   "A hot partition key concentrates traffic on one shard and throttles it — `ProvisionedThroughputExceeded`.",
   "**On-demand mode** removes shard management and scales automatically; provisioned mode is cheaper at steady high volume."]},
  {"t":"h","x":"Data Streams against Firehose"},
  {"t":"table","head":["","Kinesis Data Streams","Data Firehose"],
   "rows":[
    ["Nature","A stream you read from","A **delivery** pipeline"],
    ["Latency","Real time, ~200 ms","**Near real time**, buffered by size or time"],
    ["Storage","Retained for replay","**Nothing is retained**"],
    ["Scaling","Shards, or on-demand","Fully automatic"],
    ["Destinations","Your consumers","S3, Redshift, OpenSearch, Splunk, HTTP endpoints"],
    ["Transformation","Your code","A Lambda function in the pipeline"]]},
  {"t":"trap","x":"**\"Real time\"** points at Data Streams; **\"near real time\"** or \"load into S3 with no code\" points at Firehose. The exam uses those exact phrases deliberately."},
  {"t":"note","x":"**Managed Service for Apache Flink** reads a stream and runs continuous SQL or Flink applications over it — the answer for windowed aggregation and anomaly detection on live data."}
 ],
 "checks":[
  {"q":"Three separate applications must each read the same event feed from the beginning of the day. What fits?",
   "o":["Kinesis Data Streams, where each consumer tracks its own position",
        "An SQS standard queue read by all three","An SQS FIFO queue","Kinesis Data Firehose"],
   "a":[0],
   "x":"A stream retains records so multiple consumers can read independently and replay. A queue deletes each message once a consumer processes it, so the three would compete."},
  {"q":"Events from each device must be processed in order. How is that arranged in Kinesis?",
   "o":["Use the device id as the partition key so its events share a shard",
        "Use a random partition key to spread load","Enable FIFO mode on the stream",
        "Reduce the retention period"],
   "a":[0],
   "x":"Ordering is guaranteed within a shard, and the partition key selects the shard. Keying on the device id keeps that device's events together and therefore ordered."},
  {"q":"Streaming data must land in S3 with no consumer code and near real-time latency is acceptable. Which service?",
   "o":["Kinesis Data Firehose","Kinesis Data Streams","An SQS queue with a Lambda consumer",
        "SNS with an S3 subscription"],
   "a":[0],
   "x":"Firehose is a managed delivery pipeline that buffers and writes to S3 without you running consumers. Data Streams would require you to build and operate the consumer."},
  {"q":"A stream reports ProvisionedThroughputExceeded on one shard while others are idle. What is the cause?",
   "o":["A hot partition key concentrating records on one shard","Too long a retention period",
        "Too many consumers","Records larger than 256 KB"],
   "a":[0],
   "x":"The partition key determines shard placement, so a key with low cardinality or a dominant value overloads one shard while the rest sit idle. A better key distributes the load."}
 ]
},
{
 "id":"choosing",
 "nm":"Choosing between them, and Amazon MQ",
 "goal":"Read a scenario and name the right integration service with confidence.",
 "min":6,
 "blocks":[
  {"t":"h","x":"Amazon MQ"},
  {"t":"p","x":"Managed **ActiveMQ** or **RabbitMQ**. It exists for one reason: an existing application already speaks **MQTT, AMQP, STOMP, OpenWire or JMS** and must not be rewritten."},
  {"t":"key","x":"Amazon MQ is the answer only when the question names an industry-standard protocol or says the application cannot be changed. For anything new, SQS and SNS are cheaper and scale further."},
  {"t":"h","x":"The comparison that gets tested"},
  {"t":"table","head":["","SQS","SNS","Kinesis Data Streams","Amazon MQ"],
   "rows":[
    ["Model","Queue, pull","Topic, push","Stream, pull","Broker, either"],
    ["Consumers","One per message","Every subscriber","Many, independent","Depends on protocol"],
    ["Retention","Up to 14 days","None","1 to 365 days","Broker managed"],
    ["Replay","No","No","**Yes**","No"],
    ["Ordering","FIFO queues only","FIFO topics only","Per shard","Protocol dependent"],
    ["Scale","Nearly unlimited","Nearly unlimited","By shard","Limited by the broker"]]},
  {"t":"h","x":"Patterns worth recognising"},
  {"t":"dtree","x":[
   ["Smooth a traffic spike so the database is not overwhelmed","SQS between the tiers"],
   ["One event, several independent consumers","SNS fan-out to a queue each"],
   ["Replay yesterday's events into a new application","Kinesis Data Streams"],
   ["Clickstream into S3 for Athena, no code","Kinesis Data Firehose"],
   ["Windowed aggregation over live data","Managed Service for Apache Flink"],
   ["Legacy application speaking JMS or AMQP","Amazon MQ"],
   ["Scale workers with the backlog","SQS queue depth driving an Auto Scaling policy"]]},
  {"t":"trap","x":"Do not pick Amazon MQ for a new system just because the word \"messaging\" appears. Without a protocol or migration constraint, SQS or SNS is the expected answer."}
 ],
 "checks":[
  {"q":"An existing application uses JMS and must move to AWS without code changes. Which service?",
   "o":["Amazon MQ","Amazon SQS","Amazon SNS","Kinesis Data Streams"],
   "a":[0],
   "x":"Amazon MQ runs managed ActiveMQ or RabbitMQ, which speak the industry-standard protocols. SQS and SNS have their own APIs and would require the application to be rewritten."},
  {"q":"A web tier writes far faster than the database tier can absorb during spikes. What smooths it?",
   "o":["An SQS queue between the two tiers","An SNS topic between the two tiers",
        "A larger database instance only","Kinesis Data Firehose into the database"],
   "a":[0],
   "x":"A queue absorbs the spike and lets consumers drain at their own rate, which is the textbook decoupling pattern. SNS pushes immediately and would not buffer anything."},
  {"q":"Which service retains records so a new application can reprocess the last seven days?",
   "o":["Kinesis Data Streams","Amazon SNS","Kinesis Data Firehose","Amazon MQ"],
   "a":[0],
   "x":"Data Streams retains records for a configurable period up to 365 days and lets each consumer choose where to start. Firehose retains nothing once it has delivered."},
  {"q":"Clickstream data must be delivered into S3 for later analysis with the least operational work. What fits?",
   "o":["Kinesis Data Firehose","Kinesis Data Streams with a custom consumer",
        "An SQS queue with an EC2 consumer fleet","Amazon MQ with a file bridge"],
   "a":[0],
   "x":"Firehose buffers and writes to S3 with no consumers to run, and can transform records with Lambda on the way. Every other option requires you to build and operate the delivery code."}
 ]
}
],
"recap":[
 {"t":"h","x":"One table for the whole subject"},
 {"t":"table","head":["","SQS","SNS","Kinesis Data Streams","Firehose","Amazon MQ"],
  "rows":[
   ["Shape","Queue","Topic","Stream","Delivery pipeline","Broker"],
   ["Consumers","One per message","All subscribers","Many, independent","None — it writes","Protocol clients"],
   ["Replay","No","No","Yes","No","No"],
   ["Retention","Up to 14 days","None","1 to 365 days","None","Broker"],
   ["Use it for","Buffering work","Fan-out and notifications","Real-time analytics","Loading into stores","Legacy protocols"]]},
 {"t":"key","x":"Queue means one consumer takes each message. Stream means everyone reads the same log at their own position. Almost every question here is testing that distinction."},
 {"t":"h","x":"SQS settings to get right"},
 {"t":"table","head":["Symptom","Setting"],
  "rows":[["Work processed twice","Visibility timeout shorter than processing time"],
          ["A poison message blocking progress","Dead-letter queue with maxReceiveCount"],
          ["High cost from empty receives","Long polling, up to 20 seconds"],
          ["Messages must wait before processing","Delay queue, up to 15 minutes"],
          ["Payload larger than 256 KB","S3 with the Extended Client Library"],
          ["Order and no duplicates required","FIFO queue"]]},
 {"t":"h","x":"Fan-out, drawn"},
 {"t":"flow","x":["Producer","SNS topic","SQS queue per consumer","Independent processing, nothing lost"]},
 {"t":"h","x":"Scaling on a backlog"},
 {"t":"split","cols":[
  {"nm":"Right","items":["Alarm on messages visible, or backlog per instance","Auto Scaling adds consumers","Queue drains"]},
  {"nm":"Wrong","items":["Scaling on CPU while workers wait on I/O","Adding consumers to a stream shard that is already at its limit"]}]},
 {"t":"trap","x":"Recurring distractors: SNS offered where messages must survive a consumer outage; SQS offered where several applications must read the same events; Firehose offered for true real-time; and Amazon MQ offered for a greenfield system."}
],
"final":[
 {"m":"sns-fanout",
  "q":"An order event must reach billing, shipping and analytics. Each must process independently, and nothing may be lost if one service is down for an hour. What is the correct design?",
  "o":["Publish to an SNS topic with a separate SQS queue subscribed for each service",
       "Publish to one SQS queue that all three services poll","Publish to an SNS topic with three HTTPS endpoint subscriptions","Write the event to Kinesis Firehose and have each service read from S3"],
  "a":[0],
  "w":["Correct — each queue buffers independently, so an outage in one service does not affect the others or lose messages.",
      "A shared queue means whichever consumer polls first takes the message, so the others never see it.",
      "HTTPS subscriptions have no storage; once retries are exhausted the message is gone.",
      "Firehose adds buffering delay and turns an event flow into a file-processing job."],
  "x":"Fan-out means topic plus a queue per consumer. The queue is what provides durability and back-pressure isolation, which is precisely what \"nothing lost if one service is down\" requires."},
 {"m":"sqs-queues",
  "q":"Workers take about five minutes per message, and messages are being processed more than once. The queue is standard with default settings. What is the fix?",
  "o":["Raise the visibility timeout above the processing time",
       "Switch to a FIFO queue","Enable long polling","Shorten the message retention period"],
  "a":[0],
  "w":["Correct — the default 30-second timeout makes the message visible again long before a five-minute job finishes.",
      "FIFO changes ordering and deduplication of sends, not the redelivery of in-flight messages.",
      "Long polling reduces empty receives and has no effect on redelivery.",
      "Retention controls how long unprocessed messages survive, not visibility."],
  "x":"Duplicate processing on a standard queue is almost always a visibility timeout problem. Either raise it above the worst-case processing time or extend it from the consumer while work is in progress."},
 {"m":"kinesis",
  "q":"A fraud system must analyse transactions within a second, and a second team needs to reprocess the same events later to train a model. Which service?",
  "o":["Kinesis Data Streams","Kinesis Data Firehose","An SQS FIFO queue","SNS with two subscriptions"],
  "a":[0],
  "w":["Correct — sub-second reads plus retention for replay is exactly what a stream provides.",
      "Firehose buffers before delivery and retains nothing, so neither requirement is met.",
      "A FIFO queue deletes messages once processed, so reprocessing later is impossible.",
      "SNS has no retention, so the second team would have nothing to reprocess."],
  "x":"Two clues combine: real-time latency and replay. Only Data Streams offers both, because it keeps an ordered log that each consumer reads at its own position."},
 {"m":"choosing",
  "q":"A monolithic application uses AMQP with RabbitMQ on premises and is being lifted into AWS on a tight schedule with no code changes. What should it use?",
  "o":["Amazon MQ","Amazon SQS","Amazon SNS","Kinesis Data Streams"],
  "a":[0],
  "w":["Correct — Amazon MQ runs managed RabbitMQ and speaks AMQP, so the application is unchanged.",
      "SQS has its own API and would require rewriting the messaging layer.",
      "SNS is a different model entirely and also requires code changes.",
      "Kinesis is a streaming service with its own API and semantics."],
  "x":"The phrase \"no code changes\" plus a named standard protocol is the Amazon MQ signal. For anything greenfield, SQS and SNS are preferred for cost and scale."},
 {"m":"kinesis",
  "q":"A Kinesis stream reports throughput exceeded errors on one shard while the others are barely used. What should be changed?",
  "o":["The partition key, so records spread evenly across shards",
       "The retention period, to reduce storage pressure","The number of consumers reading the stream","The record size limit"],
  "a":[0],
  "w":["Correct — the partition key selects the shard, and a dominant key value concentrates all traffic on one.",
      "Retention affects how long records are kept, not how they are distributed.",
      "Consumer count affects read throughput, not which shard a record lands on.",
      "Record size is not the cause of an uneven distribution across shards."],
  "x":"Hot shards come from low-cardinality partition keys. Choosing a key with even distribution — or moving to on-demand mode — is the fix, not adding shards blindly."},
 {"m":"sqs-queues",
  "q":"One malformed message keeps failing and blocks a queue's progress. What configuration handles this automatically?",
  "o":["A dead-letter queue with a redrive policy and a maxReceiveCount",
       "A delay queue of fifteen minutes","Long polling with a twenty-second wait","A FIFO queue with deduplication"],
  "a":[0],
  "w":["Correct — after the receive count is exceeded the message is moved aside for inspection and the queue continues.",
      "A delay only postpones the message; it would fail again afterwards.",
      "Long polling changes how consumers wait for messages, not how failures are handled.",
      "Deduplication prevents duplicate sends and does nothing for a message that cannot be processed."],
  "x":"The dead-letter queue is the standard poison-message pattern, and inspecting what lands there is how the underlying defect gets found."},
 {"m":"choosing",
  "q":"A checkout service writes bursts far faster than the fulfilment service can process, and during sales the fulfilment service falls over. What is the minimal architectural change?",
  "o":["Put an SQS queue between checkout and fulfilment and scale consumers on queue depth",
       "Increase the fulfilment service's instance size","Publish directly to an SNS topic that fulfilment subscribes to","Move both services into one process to avoid network overhead"],
  "a":[0],
  "w":["Correct — the queue absorbs the burst and lets fulfilment consume at a sustainable rate, with scaling driven by backlog.",
      "A bigger instance raises the ceiling but still collapses under a large enough burst.",
      "SNS pushes immediately and provides no buffering, so fulfilment is overwhelmed just the same.",
      "Coupling the services more tightly makes the failure mode worse, not better."],
  "x":"Buffering a rate mismatch is the canonical use of a queue. Pairing it with an Auto Scaling policy on queue depth turns a fragile synchronous call into an elastic pipeline."},
 {"m":"sns-fanout",
  "q":"A topic carries events for many product categories, and one subscriber only cares about one category. What avoids delivering everything to it?",
  "o":["A subscription filter policy matching the category attribute",
       "A separate topic for every category","A FIFO topic with message groups","A dead-letter queue on the subscription"],
  "a":[0],
  "w":["Correct — filter policies evaluate message attributes at the topic and deliver only matching messages.",
      "A topic per category multiplies configuration and forces publishers to know the routing.",
      "Message groups control ordering, not which subscribers receive a message.",
      "A dead-letter queue collects failures and has nothing to do with filtering."],
  "x":"Filter policies keep routing logic in one place and cut both delivery cost and consumer work, which is why they are preferred over topic proliferation."},
 {"m":"kinesis",
  "q":"Application logs must be delivered continuously into S3 and OpenSearch with transformation along the way, and the team wants to run no consumer code. Which service?",
  "o":["Kinesis Data Firehose with a Lambda transformation",
       "Kinesis Data Streams with a custom consumer","An SQS queue consumed by EC2 workers","SNS with an S3 subscription"],
  "a":[0],
  "w":["Correct — Firehose delivers to both destinations and can invoke Lambda to transform records in the pipeline.",
      "Data Streams requires you to write, deploy and scale the consumers yourself.",
      "An EC2 consumer fleet is exactly the operational work the requirement rules out.",
      "SNS cannot write to S3 as a delivery destination in this way."],
  "x":"Firehose is the managed delivery path: buffered by size or time, transformed by an optional Lambda, and written to supported destinations without any consumer to operate."},
 {"m":"sqs-queues",
  "q":"A message payload can reach 2 MB. How should it be sent through SQS?",
  "o":["Store the payload in S3 and send a reference using the Extended Client Library",
       "Split it across eight messages and reassemble them","Use a FIFO queue, which allows larger messages","Compress it below 256 KB and accept the loss"],
  "a":[0],
  "w":["Correct — the library stores the body in S3 and passes a pointer through the queue transparently.",
      "Manual splitting introduces ordering and reassembly problems the service does not solve for you.",
      "FIFO queues have the same 256 KB limit as standard queues.",
      "Lossy compression changes the data, which is not an acceptable general solution."],
  "x":"The 256 KB limit applies to every SQS queue type. The Extended Client Library is the supported pattern for large payloads and keeps the queue semantics intact."}
]
}
