# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 11,
"nm": "Containers: ECS, Fargate, ECR and EKS",
"tag": "Compute",
"modules": [
{
 "id": "ecs-basics",
 "nm": "ECS and the two launch types",
 "goal": "Name the parts of an ECS deployment and choose between EC2 and Fargate.",
 "min": 7,
 "blocks": [
  {"t":"p","x":"**ECS** is AWS's own container orchestrator. You describe a container, ECS places it somewhere and keeps the right number running."},
  {"t":"table","head":["Piece","What it is"],
   "rows":[
    ["**Task definition**","The blueprint: image, CPU and memory, ports, environment, volumes, IAM roles"],
    ["**Task**","One running instance of that blueprint"],
    ["**Service**","Keeps a desired number of tasks running, replaces failures, registers with a load balancer"],
    ["**Cluster**","The logical grouping the tasks run in"],
    ["**Capacity provider**","Where the tasks actually run — EC2 instances, or Fargate"]]},
  {"t":"split","cols":[
   {"nm":"EC2 launch type","items":["You run the instances and the ECS agent","You choose instance types and patch them","Cheaper at steady high utilisation","Use when you need GPUs, special instance types, or host-level control"]},
   {"nm":"Fargate launch type","items":["**No instances at all**","You pay per vCPU and GB per second for the task","Nothing to patch or scale underneath","The default answer when the question says least operational overhead"]}]},
  {"t":"key","x":"\"Run containers without managing servers\" is **Fargate**. If a question stresses operational overhead and does not require host access or special hardware, Fargate is the intended answer."},
  {"t":"h","x":"Deployments"},
  {"t":"list","x":[
   "**Rolling update** replaces tasks gradually, bounded by minimum healthy percent and maximum percent.",
   "**Blue/green** through CodeDeploy shifts traffic between two target groups and can roll back instantly.",
   "A **circuit breaker** can stop and roll back a deployment whose tasks keep failing to become healthy."]},
  {"t":"trap","x":"Fargate cannot use GPUs or give you host access, and it does not support every networking mode. A question that requires either of those is pointing at the EC2 launch type."}
 ],
 "checks":[
  {"q":"A team wants to run containers without provisioning or patching any servers. Which launch type?",
   "o":["Fargate","EC2 with a capacity provider","EC2 with Spot instances","EC2 with a launch template"],
   "a":[0],
   "x":"Fargate runs tasks with no instances for you to manage, which is exactly what removing provisioning and patching means. All EC2 launch type options still leave you with hosts."},
  {"q":"What does an ECS service do that a standalone task does not?",
   "o":["Keeps a desired number of tasks running and replaces failures",
        "Defines the container image and memory","Stores the container image",
        "Creates the cluster"],
   "a":[0],
   "x":"The service is the controller: it maintains desired count, replaces unhealthy tasks and registers them with a load balancer. The task definition holds the image and resources."},
  {"q":"A workload needs GPU instances for inference. Which ECS launch type supports it?",
   "o":["EC2, because Fargate does not offer GPUs","Fargate with a GPU task size",
        "Either, with the right task definition","Neither — GPUs require EKS"],
   "a":[0],
   "x":"Fargate has no GPU support, so GPU workloads run on the EC2 launch type where you choose the instance family. EKS is not required for this."},
  {"q":"Which deployment option allows an instant rollback by shifting traffic back to the previous version?",
   "o":["Blue/green deployment through CodeDeploy","A rolling update with a high maximum percent",
        "Restarting the service","Increasing the desired count"],
   "a":[0],
   "x":"Blue/green keeps both versions running behind separate target groups, so reverting is a traffic shift rather than a redeployment. Rolling updates replace tasks in place."}
 ]
},
{
 "id":"ecs-networking-iam",
 "nm":"Networking and the two IAM roles",
 "goal":"Tell the task role from the execution role, and connect tasks to a load balancer.",
 "min":7,
 "blocks":[
  {"t":"h","x":"Two roles, constantly confused"},
  {"t":"table","head":["Role","Used by","Grants"],
   "rows":[
    ["**Task execution role**","The ECS **agent**, before the container starts","Pulling the image from ECR, writing logs to CloudWatch, reading secrets for injection"],
    ["**Task role**","**Your application code** inside the container","Whatever AWS APIs the application calls: S3, DynamoDB, SQS"]]},
  {"t":"key","x":"If the task cannot **start** — image pull failure, log configuration failure — look at the **execution role**. If the application gets AccessDenied while running, look at the **task role**."},
  {"t":"h","x":"Network modes"},
  {"t":"list","x":[
   "**awsvpc** gives each task its own ENI and private IP, so it has its own security group. Required by Fargate and the recommended mode on EC2.",
   "**bridge** shares the host's network with port mapping; **dynamic port mapping** lets many copies of a container run on one instance, with the ALB tracking the ports.",
   "**host** binds directly to the instance's interface, so only one copy per host can use a port."]},
  {"t":"flow","x":["ALB target group","Task registered with its IP and port","Health check on the task","Unhealthy tasks replaced by the service"]},
  {"t":"h","x":"Configuration and secrets"},
  {"t":"p","x":"A task definition can pull values from **Secrets Manager** or **SSM Parameter Store** and inject them as environment variables. The execution role needs permission to read them — that is a classic start-up failure."},
  {"t":"trap","x":"Putting a database password directly in the task definition's environment variables exposes it to anyone who can describe the task. The expected answer is a secret reference."}
 ],
 "checks":[
  {"q":"A task fails to start with an error pulling the image from ECR. Which role should you check?",
   "o":["The task execution role","The task role","The instance profile of the cluster",
        "The service-linked role for Auto Scaling"],
   "a":[0],
   "x":"Pulling the image happens before the container runs and is done with the execution role. The task role only matters once the application code is executing."},
  {"q":"An application in a container gets AccessDenied writing to S3. Which role needs the permission?",
   "o":["The task role","The task execution role","The ECS cluster role","The load balancer's role"],
   "a":[0],
   "x":"Calls made by the application use the task role. The execution role is only used by the agent to set the task up."},
  {"q":"Each task must have its own security group and private IP. Which network mode?",
   "o":["awsvpc","bridge","host","none"],
   "a":[0],
   "x":"awsvpc attaches an ENI per task, giving it its own address and security group. It is mandatory on Fargate and recommended on EC2 for exactly this isolation."},
  {"q":"How should a database password reach a container?",
   "o":["As a secret reference to Secrets Manager or Parameter Store in the task definition",
        "As a plain environment variable in the task definition","Baked into the container image",
        "In the container's command line arguments"],
   "a":[0],
   "x":"A secret reference keeps the value out of the task definition, which anyone with describe permission can read. The execution role is then granted access to that secret."}
 ]
},
{
 "id":"ecr-eks",
 "nm":"ECR and EKS",
 "goal":"Describe where images live and when Kubernetes is the right answer.",
 "min":6,
 "blocks":[
  {"t":"h","x":"ECR"},
  {"t":"list","x":[
   "A private container registry, backed by S3, with images controlled by **IAM**.",
   "**Image scanning** finds known vulnerabilities on push or on demand.",
   "**Lifecycle policies** expire old or untagged images so the registry does not grow forever.",
   "**Cross-region and cross-account replication** puts images near the clusters that pull them.",
   "A public gallery exists as well, but the exam usually means the private registry."]},
  {"t":"h","x":"EKS"},
  {"t":"p","x":"Managed **Kubernetes**. AWS runs the control plane; you choose how the nodes are provided."},
  {"t":"table","head":["Node option","What it means"],
   "rows":[
    ["**Managed node groups**","EC2 instances AWS provisions and upgrades for you"],
    ["**Self-managed nodes**","You own the Auto Scaling group entirely"],
    ["**Fargate profile**","Pods matching a selector run with no nodes at all"]]},
  {"t":"key","x":"Choose **EKS** when the question says Kubernetes, or names Helm, kubectl, or a multi-cloud or portability requirement. Choose **ECS** when it just says containers and wants the least moving parts."},
  {"t":"h","x":"Identity for pods"},
  {"t":"p","x":"**IRSA** — IAM roles for service accounts — maps a Kubernetes service account to an IAM role, so a pod gets only the permissions it needs. **EKS Pod Identity** is the newer mechanism that does the same without a per-cluster OIDC provider."},
  {"t":"trap","x":"A **Fargate profile does not support DaemonSets**, because there are no nodes for a per-node pod to land on. A logging or monitoring agent deployed as a DaemonSet will not schedule."}
 ],
 "checks":[
  {"q":"How is access to images in a private ECR repository controlled?",
   "o":["By IAM policies and repository policies","By security groups on the repository",
        "By a key pair","By the container's network mode"],
   "a":[0],
   "x":"ECR is an AWS service, so access is IAM based, with repository policies for cross-account sharing. Network controls apply to the VPC endpoint, not to authorisation."},
  {"q":"A team already runs Kubernetes on premises with Helm charts and wants the same tooling on AWS. Which service?",
   "o":["EKS","ECS with Fargate","App Runner","Elastic Beanstalk"],
   "a":[0],
   "x":"EKS runs upstream Kubernetes, so existing manifests, Helm charts and kubectl workflows carry over. ECS has its own concepts and would require a rewrite of the deployment tooling."},
  {"q":"A monitoring agent deployed as a DaemonSet never schedules on pods running under a Fargate profile. Why?",
   "o":["Fargate has no nodes, so DaemonSets have nothing to run on","The agent image is not in ECR",
        "The Fargate profile lacks a task role","DaemonSets require awsvpc networking"],
   "a":[0],
   "x":"A DaemonSet places one pod per node, and Fargate profiles remove nodes entirely. Sidecar containers inside each pod are the usual workaround."},
  {"q":"What does IRSA provide in EKS?",
   "o":["An IAM role mapped to a Kubernetes service account so a pod gets scoped permissions",
        "Automatic node patching","Cross-region image replication","A managed load balancer controller"],
   "a":[0],
   "x":"IRSA binds a service account to an IAM role so each pod receives only the permissions it needs, instead of inheriting the node's instance profile."}
 ]
},
{
 "id":"scaling-containers",
 "nm":"Scaling containers and the simpler options",
 "goal":"Scale an ECS service correctly and recognise when a simpler service is the answer.",
 "min":6,
 "blocks":[
  {"t":"h","x":"Two levels of scaling"},
  {"t":"split","cols":[
   {"nm":"Service auto scaling","items":["Changes the number of **tasks**","Target tracking on CPU, memory, or ALB requests per target","This is the one that matters on Fargate"]},
   {"nm":"Cluster capacity","items":["Changes the number of **EC2 instances**","Driven by a capacity provider with managed scaling","Not needed at all on Fargate"]}]},
  {"t":"key","x":"On Fargate there is only one thing to scale: the task count. On the EC2 launch type you must scale tasks *and* make sure there is somewhere to put them, which is what a capacity provider does."},
  {"t":"h","x":"Cost levers"},
  {"t":"list","x":[
   "**Fargate Spot** runs interruptible tasks far cheaper — suitable for batch and stateless workers.",
   "A capacity provider strategy can mix Fargate and Fargate Spot with a base and a weight.",
   "On EC2, Spot instances in the cluster do the same for the underlying capacity.",
   "**Compute Savings Plans** cover Fargate as well as EC2 and Lambda."]},
  {"t":"h","x":"When ECS and EKS are more than you need"},
  {"t":"table","head":["Service","Fits when"],
   "rows":[
    ["**App Runner**","A container or repository should become a scalable HTTPS service with no infrastructure decisions at all"],
    ["**Elastic Beanstalk**","A whole application environment — capacity, load balancer, health — from uploaded code"],
    ["**Lambda**","Event-driven, short-lived work, including container images up to 10 GB"],
    ["**ECS Anywhere / EKS Anywhere**","The same control plane managing containers that run in your own data centre"]]},
  {"t":"trap","x":"\"Deploy a containerised web API with the least possible operational work\" often points at **App Runner** rather than ECS. Read whether the question wants control or wants nothing to configure."}
 ],
 "checks":[
  {"q":"On the Fargate launch type, what does service auto scaling adjust?",
   "o":["The number of running tasks","The number of EC2 instances in the cluster",
        "The size of the container image","The number of Availability Zones"],
   "a":[0],
   "x":"Fargate has no instances, so the only lever is how many tasks run. Target tracking on CPU, memory or requests per target drives that number."},
  {"q":"An EC2-backed cluster runs out of room to place new tasks during scale-out. What addresses this?",
   "o":["A capacity provider with managed scaling for the instances","A larger task definition",
        "More Availability Zones in the load balancer","Switching the network mode to host"],
   "a":[0],
   "x":"Scaling tasks does nothing if there is no instance capacity. A capacity provider with managed scaling grows the Auto Scaling group to make room."},
  {"q":"Batch worker containers are stateless and can be interrupted. What reduces their cost most?",
   "o":["Fargate Spot","A larger task size","Longer health check grace periods","Host network mode"],
   "a":[0],
   "x":"Fargate Spot offers a deep discount for interruptible tasks, which matches a stateless batch worker exactly. The other options do not change pricing."},
  {"q":"A single containerised web API should be deployed with almost no infrastructure configuration. Which service fits best?",
   "o":["AWS App Runner","EKS with a managed node group","ECS on EC2 with a capacity provider",
        "A self-managed Kubernetes cluster"],
   "a":[0],
   "x":"App Runner takes a container image or source repository and runs it as a scalable HTTPS service, handling load balancing, scaling and certificates. Everything else requires cluster decisions."}
 ]
}
],
"recap":[
 {"t":"h","x":"Which container service"},
 {"t":"dtree","x":[
  ["Containers, least operational overhead, no host access needed","ECS on Fargate"],
  ["Kubernetes, Helm, kubectl, portability","EKS"],
  ["GPUs or specific instance types","ECS or EKS on EC2"],
  ["One web service, no infrastructure decisions","App Runner"],
  ["Event-driven and short-lived","Lambda"],
  ["Containers in your own data centre, one control plane","ECS Anywhere or EKS Anywhere"],
  ["An application environment from uploaded code","Elastic Beanstalk"]]},
 {"t":"h","x":"The two roles"},
 {"t":"table","head":["Symptom","Role to fix"],
  "rows":[["Cannot pull the image","Task execution role"],
          ["Cannot write logs at start-up","Task execution role"],
          ["Cannot read the injected secret","Task execution role"],
          ["Application gets AccessDenied calling S3","Task role"],
          ["Pod in EKS needs scoped AWS permissions","IRSA or EKS Pod Identity"]]},
 {"t":"key","x":"Execution role is for getting the task started; task role is for what the code does once it is running. That single sentence answers a whole family of questions."},
 {"t":"h","x":"Networking modes"},
 {"t":"table","head":["Mode","Effect"],
  "rows":[["awsvpc","An ENI, IP and security group per task; required on Fargate"],
          ["bridge","Port mapping on the host; dynamic ports let many copies share an instance"],
          ["host","Binds the host interface directly; one copy per port per host"]]},
 {"t":"h","x":"Scaling, in two layers"},
 {"t":"flow","x":["Metric crosses the target","Service auto scaling changes the task count","Capacity provider adds instances if needed","Tasks are placed and registered"],
  "cap":"On Fargate the third step does not exist."},
 {"t":"trap","x":"Recurring distractors: Fargate offered where GPUs or host access are required; plaintext secrets in a task definition; the task role blamed for an image pull failure; and a DaemonSet expected to run under a Fargate profile."}
],
"final":[
 {"m":"ecs-networking-iam",
  "q":"An ECS task stops immediately after launch with an error retrieving a value from Secrets Manager. What is the most likely cause?",
  "o":["The task execution role lacks permission to read the secret",
       "The task role lacks permission to read the secret","The container image is too large","The service has no load balancer attached"],
  "a":[0],
  "w":["Correct — secret injection happens before the container starts and uses the execution role.",
      "The task role is only used by the application once it is running.",
      "Image size affects start-up time but does not cause a secrets error.",
      "A load balancer is unrelated to whether a task can start."],
  "x":"Anything that happens before your code runs — pulling the image, configuring logging, injecting secrets — is the execution role's responsibility. That split is the point of having two roles."},
 {"m":"ecs-basics",
  "q":"A company wants to run a containerised microservice with no servers to patch, no instance types to choose, and per-second billing. Which option fits?",
  "o":["ECS with the Fargate launch type","ECS with the EC2 launch type and Spot instances",
       "EKS with self-managed nodes","A container on an EC2 instance behind a load balancer"],
  "a":[0],
  "w":["Correct — Fargate removes instances entirely and charges per vCPU and GB per second.",
      "Spot lowers cost but still leaves instances to manage and patch.",
      "Self-managed nodes are the most operational work of the options listed.",
      "Running containers directly on an instance means owning the whole host lifecycle."],
  "x":"\"No servers to manage\" plus per-second billing is Fargate's exact description. The EC2 launch type only wins when you need GPUs, specific instance types, or host-level access."},
 {"m":"ecr-eks",
  "q":"An organisation standardising on Kubernetes needs each pod to receive only the AWS permissions it requires, rather than the node's. What provides this?",
  "o":["IAM roles for service accounts, or EKS Pod Identity",
       "The node group's instance profile","A task role on the pod specification","A security group per pod"],
  "a":[0],
  "w":["Correct — both mechanisms bind a Kubernetes service account to an IAM role scoped to that workload.",
      "The instance profile grants the same permissions to every pod on the node, which is what this avoids.",
      "Task roles are an ECS concept and do not exist in Kubernetes.",
      "Security groups control network reachability, not AWS API permissions."],
  "x":"Without IRSA or Pod Identity, pods inherit the node role, so every workload on a node shares permissions. Binding roles to service accounts restores least privilege."},
 {"m":"scaling-containers",
  "q":"An ECS service on the EC2 launch type scales its task count up, but new tasks stay in a pending state. What is missing?",
  "o":["Cluster capacity — a capacity provider with managed scaling to add instances",
       "A larger CPU reservation in the task definition","A second load balancer listener","A longer deregistration delay"],
  "a":[0],
  "w":["Correct — tasks cannot be placed if no instance has room, so the underlying Auto Scaling group must grow too.",
      "Raising the reservation would make placement harder, not easier.",
      "Listeners affect traffic routing, not task placement.",
      "Deregistration delay applies when targets leave the load balancer."],
  "x":"The EC2 launch type has two scaling layers. Service auto scaling sets the desired task count; the capacity provider ensures there is somewhere to run them. Fargate collapses this into one."},
 {"m":"ecs-basics",
  "q":"A deployment repeatedly launches tasks that fail their health checks, leaving the service in a broken state. Which feature stops and reverses it automatically?",
  "o":["The deployment circuit breaker with rollback enabled",
       "A higher maximum percent on the rolling update","A longer health check grace period","Increasing the desired count"],
  "a":[0],
  "w":["Correct — the circuit breaker detects repeated failures and rolls back to the last working task definition.",
      "A higher maximum percent replaces tasks faster, which makes a bad deployment worse.",
      "A longer grace period delays detection rather than handling the failure.",
      "More tasks of a broken version does not help."],
  "x":"The circuit breaker is the ECS safety net for bad deployments, and pairing it with rollback restores the previous revision without human intervention."},
 {"m":"ecr-eks",
  "q":"Container images should be scanned for known vulnerabilities as soon as they are pushed, and old untagged images removed automatically. What provides both?",
  "o":["ECR image scanning together with an ECR lifecycle policy",
       "Amazon Inspector on the running tasks","A CodeBuild step that deletes images","GuardDuty findings on the cluster"],
  "a":[0],
  "w":["Correct — scanning on push reports vulnerabilities and lifecycle policies expire images by age or count.",
      "Inspector assesses running workloads rather than pruning a registry.",
      "A custom build step duplicates a feature the registry already provides.",
      "GuardDuty detects threats and does not manage image retention."],
  "x":"These are two built-in ECR features that pair naturally: scanning on push for security, lifecycle policies for cost and clutter."},
 {"m":"ecs-networking-iam",
  "q":"Multiple copies of the same container must run on one EC2 instance behind an Application Load Balancer without port conflicts. What makes this work?",
  "o":["Dynamic port mapping in bridge mode, with the ALB tracking each task's port",
       "Host network mode with a fixed port","Assigning an Elastic IP to each task","Running one task per instance"],
  "a":[0],
  "w":["Correct — the host port is assigned automatically and registered with the target group per task.",
      "Host mode binds a fixed port, so only one copy can use it per instance.",
      "Elastic IPs are not assigned to tasks and would not resolve a port conflict.",
      "One task per instance wastes capacity and is the limitation being avoided."],
  "x":"Dynamic port mapping is the classic ECS-on-EC2 density pattern. With awsvpc mode the problem disappears differently, because each task has its own ENI and IP."},
 {"m":"scaling-containers",
  "q":"A stateless image-processing fleet runs on Fargate and the finance team wants a large cost reduction, accepting occasional task interruption. What should be used?",
  "o":["Fargate Spot, optionally mixed with on-demand through a capacity provider strategy",
       "A smaller task size with the same task count","Reserved Instances for Fargate","EKS with managed node groups"],
  "a":[0],
  "w":["Correct — Fargate Spot is priced for interruptible work and can be mixed with on-demand for a guaranteed base.",
      "Under-sizing tasks degrades throughput rather than reducing unit cost.",
      "Reserved Instances apply to EC2, not to Fargate capacity.",
      "Moving to EKS adds operational work without addressing price directly."],
  "x":"Stateless and interruptible is the Spot profile wherever it appears. A capacity provider strategy with a base of on-demand and a weight of Spot balances cost against a minimum guaranteed capacity."},
 {"m":"ecs-basics",
  "q":"Which statement correctly distinguishes a task definition from a service in ECS?",
  "o":["The task definition describes the container; the service keeps a desired number of tasks running",
       "The task definition keeps tasks running; the service stores the image","They are two names for the same object","The service defines CPU and memory; the task definition handles load balancing"],
  "a":[0],
  "w":["Correct — one is the blueprint, the other is the controller that maintains it.",
      "This reverses both roles.",
      "They are distinct objects with different responsibilities.",
      "CPU and memory belong to the task definition, and load balancer registration to the service."],
  "x":"Getting this vocabulary right makes the rest of ECS straightforward: task definition is the what, task is the running instance, and service is the thing keeping the right number alive."},
 {"m":"ecr-eks",
  "q":"A logging agent deployed as a DaemonSet does not appear for workloads running on an EKS Fargate profile. What is the correct explanation and workaround?",
  "o":["Fargate profiles have no nodes, so DaemonSets cannot schedule; use a sidecar container in each pod",
       "The DaemonSet image must be replicated to ECR in the same region","The Fargate profile is missing a node selector for the agent","DaemonSets require awsvpc networking, which Fargate disables"],
  "a":[0],
  "w":["Correct — a DaemonSet places one pod per node, and Fargate removes nodes from the model entirely.",
      "Image location affects pulling, not whether a DaemonSet can schedule.",
      "Node selectors cannot create nodes that do not exist.",
      "Fargate uses awsvpc networking; that is not the limitation."],
  "x":"This is the practical catch when moving pods to Fargate: anything assuming a node — DaemonSets, host paths, privileged containers — has to be restructured, usually as a sidecar."}
]
}
