# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 12,
"nm": "Serverless: Lambda, DynamoDB, API Gateway, Cognito",
"tag": "Serverless",
"modules": [
{
 "id": "lambda-basics",
 "nm": "Lambda: limits, triggers and what they imply",
 "goal": "Recall Lambda's hard limits and decide when a workload does not belong in it.",
 "min": 8,
 "blocks": [
  {"t":"p","x":"**Lambda** runs your function when something invokes it, and charges per millisecond of execution. There are no servers, but there are limits — and most Lambda questions are really limit questions."},
  {"t":"table","head":["Limit","Value"],
   "rows":[
    ["Maximum execution time","**15 minutes**"],
    ["Memory","128 MB to 10,240 MB — **CPU scales with memory**"],
    ["Temporary disk in `/tmp`","512 MB, configurable up to 10 GB"],
    ["Deployment package","50 MB zipped, 250 MB unzipped; **10 GB as a container image**"],
    ["Environment variables","4 KB in total"],
    ["Concurrent executions","1,000 per region by default, raisable"]]},
  {"t":"key","x":"**Fifteen minutes** is the limit that decides most questions. A job that runs longer belongs in Fargate, Batch, Step Functions, or an EC2 instance — not in a Lambda function."},
  {"t":"h","x":"Invocation models"},
  {"t":"table","head":["Model","Examples","On failure"],
   "rows":[
    ["Synchronous","API Gateway, an ALB, a direct invoke","The caller sees the error; you handle retries"],
    ["Asynchronous","S3 events, SNS, EventBridge","Lambda retries twice, then sends it to a dead-letter queue or on-failure destination"],
    ["Poll based","SQS, Kinesis, DynamoDB Streams","Lambda polls with an event source mapping; a batch can be retried"]]},
  {"t":"h","x":"Tuning"},
  {"t":"list","x":[
   "More memory means more CPU, so a **larger memory setting often makes a function cheaper** by finishing sooner.",
   "**Layers** share libraries between functions and keep packages small.",
   "A **container image** is the answer when dependencies exceed the zip limits.",
   "**Lambda SnapStart** cuts Java cold starts dramatically by restoring an initialised snapshot."]},
  {"t":"trap","x":"\"Increase the timeout\" cannot fix a job that needs an hour, because the ceiling is fifteen minutes. Any option offering a longer Lambda timeout than that is wrong on the number alone."}
 ],
 "checks":[
  {"q":"A data conversion job takes about 40 minutes. Why is Lambda unsuitable?",
   "o":["The maximum execution time is 15 minutes","The memory limit is too low",
        "It cannot read from S3","It cannot run on a schedule"],
   "a":[0],
   "x":"Fifteen minutes is a hard ceiling that cannot be raised. Work that runs longer belongs in Fargate, AWS Batch, or an orchestration that breaks it into shorter steps."},
  {"q":"A function's dependencies total 400 MB unzipped. How can it be deployed?",
   "o":["As a container image, which allows up to 10 GB","By raising the deployment package limit",
        "By storing the dependencies in environment variables","By enabling SnapStart"],
   "a":[0],
   "x":"The zip limit is 250 MB unzipped and cannot be raised, but a container image supports up to 10 GB. Layers help with sharing but do not lift the total."},
  {"q":"What happens to an asynchronous invocation that keeps failing?",
   "o":["Lambda retries twice and then sends it to a dead-letter queue or failure destination",
        "The caller receives the error immediately","It is retried indefinitely",
        "It is silently discarded on the first failure"],
   "a":[0],
   "x":"Asynchronous invocations are retried twice by Lambda itself, after which the event goes to the configured destination so it can be inspected rather than lost."},
  {"q":"Why can increasing a function's memory reduce its cost?",
   "o":["CPU scales with memory, so the function finishes in less time","Memory above 1 GB is not billed",
        "Larger functions get a discounted rate","It avoids cold starts entirely"],
   "a":[0],
   "x":"Billing is memory multiplied by duration, and more memory brings proportionally more CPU. A CPU-bound function can therefore cost less at a higher memory setting."}
 ]
},
{
 "id":"lambda-scaling",
 "nm":"Concurrency, cold starts and VPC access",
 "goal":"Control how many copies run at once and explain what a cold start is.",
 "min":7,
 "blocks":[
  {"t":"h","x":"Concurrency"},
  {"t":"split","cols":[
   {"nm":"Reserved concurrency","items":["Caps how many copies of this function may run","Guarantees that capacity for it","Setting it to 0 **disables** the function — a useful emergency stop","Protects a downstream database from being overwhelmed"]},
   {"nm":"Provisioned concurrency","items":["Keeps initialised environments warm","Removes cold starts for a predictable number of concurrent requests","Costs money whether used or not"]}]},
  {"t":"key","x":"**Reserved** concurrency limits and protects. **Provisioned** concurrency pre-warms and removes cold starts. Questions about latency spikes want provisioned; questions about overwhelming a database want reserved."},
  {"t":"h","x":"Cold starts"},
  {"t":"flow","x":["First request","Environment created","Runtime and dependencies initialised","Handler runs","Environment reused for later requests"],
   "cap":"Only the first request of a new environment pays the initialisation cost."},
  {"t":"list","x":[
   "Heavy initialisation code, large packages and some runtimes make cold starts worse.",
   "**SnapStart** addresses Java specifically by restoring a pre-initialised snapshot.",
   "Reusing connections declared outside the handler avoids repeating setup on every warm invocation."]},
  {"t":"h","x":"Lambda in a VPC"},
  {"t":"p","x":"A function placed in a VPC can reach private resources such as RDS. It then has **no internet access** unless the subnet routes through a **NAT gateway**, and reaching AWS services privately uses **VPC endpoints**."},
  {"t":"trap","x":"\"The function can reach the database but calls to a public API now time out\" is the classic VPC Lambda symptom: it needs a NAT gateway, or a VPC endpoint for the AWS service it is calling."},
  {"t":"h","x":"Connections to relational databases"},
  {"t":"p","x":"Thousands of concurrent functions each opening a database connection exhausts the database. **RDS Proxy** pools them, and it is the expected answer whenever Lambda meets RDS at scale."}
 ],
 "checks":[
  {"q":"A function is overwhelming a small database during traffic spikes. Which setting limits the damage?",
   "o":["Reserved concurrency on the function","Provisioned concurrency on the function",
        "A larger memory allocation","A longer timeout"],
   "a":[0],
   "x":"Reserved concurrency caps how many copies can run at once, which bounds the load reaching the database. Provisioned concurrency pre-warms environments and does not limit anything."},
  {"q":"An API backed by Lambda shows occasional latency spikes on the first request after a quiet period. What removes them?",
   "o":["Provisioned concurrency","Reserved concurrency","A shorter timeout","A smaller deployment package only"],
   "a":[0],
   "x":"Provisioned concurrency keeps initialised environments ready, so requests do not pay the initialisation cost. Reducing package size helps a little but does not eliminate cold starts."},
  {"q":"A Lambda function placed in a VPC can reach RDS but its calls to a public HTTPS API now time out. Why?",
   "o":["A function in a VPC has no internet access without a NAT gateway",
        "The function's timeout is too short","The security group blocks outbound HTTPS by default",
        "Public APIs cannot be called from Lambda"],
   "a":[0],
   "x":"Placing a function in private subnets removes the default internet path. A NAT gateway restores outbound access, and VPC endpoints cover AWS services without one."},
  {"q":"What does setting reserved concurrency to zero do?",
   "o":["Stops the function from being invoked at all","Removes the concurrency limit",
        "Doubles the available concurrency","Enables provisioned concurrency"],
   "a":[0],
   "x":"A reservation of zero leaves the function no capacity, which is an effective emergency stop while a problem is investigated."}
 ]
},
{
 "id":"dynamodb",
 "nm":"DynamoDB",
 "goal":"Design keys and indexes, and choose a capacity mode and consistency level.",
 "min":9,
 "blocks":[
  {"t":"p","x":"**DynamoDB** is a managed key-value and document database with single-digit millisecond latency at any scale. It is regional, replicated across Availability Zones, and has no servers to size."},
  {"t":"h","x":"Keys"},
  {"t":"table","head":["Key","Role"],
   "rows":[
    ["**Partition key**","Decides which partition the item lives on. A poor choice makes a hot partition"],
    ["**Sort key**","Orders items within a partition and enables range queries"],
    ["Together","The **primary key**, which must be unique"]]},
  {"t":"key","x":"A **query** uses the partition key and is efficient. A **scan** reads the whole table and is the thing to avoid — an answer that fixes slowness by scanning more efficiently is usually the wrong one."},
  {"t":"h","x":"Indexes"},
  {"t":"split","cols":[
   {"nm":"Local Secondary Index","items":["Same partition key, **different sort key**","Must be created **with the table**","Shares the table's capacity","Supports strongly consistent reads"]},
   {"nm":"Global Secondary Index","items":["**Any** partition and sort key","Can be added at any time","Has its **own capacity**","Eventually consistent only"]}]},
  {"t":"h","x":"Capacity"},
  {"t":"table","head":["Mode","Fits"],
   "rows":[
    ["**On-demand**","Unpredictable or spiky traffic, or a new workload — no capacity planning, higher unit price"],
    ["**Provisioned**","Steady, predictable traffic — cheaper, with auto scaling and reserved capacity available"]]},
  {"t":"h","x":"Features that answer questions"},
  {"t":"table","head":["Feature","What it does"],
   "rows":[
    ["**DAX**","An in-memory cache in front of DynamoDB, microsecond reads, **no application changes beyond the endpoint**"],
    ["**Streams**","An ordered log of item changes, consumed by Lambda — the basis of event-driven patterns"],
    ["**Global Tables**","Multi-region, **multi-active** replication"],
    ["**TTL**","Deletes expired items automatically at no cost"],
    ["**Transactions**","All-or-nothing writes across several items"],
    ["**PITR**","Point-in-time recovery over the last 35 days"]]},
  {"t":"trap","x":"For caching **DynamoDB specifically**, the answer is **DAX**, not ElastiCache — DAX is DynamoDB-aware and needs only an endpoint change."}
 ],
 "checks":[
  {"q":"A table needs a second access pattern on a completely different attribute, and the table already exists. What do you create?",
   "o":["A global secondary index","A local secondary index","A new table with a scan",
        "A DAX cluster"],
   "a":[0],
   "x":"Only a global secondary index can use a different partition key and can be added after the table is created. Local secondary indexes must be defined at table creation and keep the same partition key."},
  {"q":"Traffic is unpredictable and the team does not want to plan capacity. Which mode?",
   "o":["On-demand capacity","Provisioned capacity with auto scaling","Provisioned capacity with reserved capacity",
        "Provisioned capacity at the peak level"],
   "a":[0],
   "x":"On-demand removes capacity planning entirely and absorbs spikes, at a higher price per request. Provisioned modes are cheaper but require a reasonable estimate of the load."},
  {"q":"Reads from DynamoDB must drop to microseconds with minimal application change. What should be added?",
   "o":["A DAX cluster in front of the table","An ElastiCache for Redis cluster",
        "A global secondary index","A read replica of the table"],
   "a":[0],
   "x":"DAX is a DynamoDB-specific cache that speaks the same API, so only the endpoint changes. ElastiCache would require the application to manage cache logic itself."},
  {"q":"Every change to a table must trigger processing. What provides the events?",
   "o":["DynamoDB Streams consumed by Lambda","A scheduled scan of the table",
        "S3 event notifications","A global secondary index"],
   "a":[0],
   "x":"Streams emit an ordered record of each item change and integrate directly with Lambda, which is the standard event-driven pattern. Scanning periodically is both expensive and late."}
 ]
},
{
 "id":"apigw-cognito",
 "nm":"API Gateway and Cognito",
 "goal":"Expose an API safely and pick the right authentication for its callers.",
 "min":8,
 "blocks":[
  {"t":"h","x":"API Gateway"},
  {"t":"table","head":["Concern","Feature"],
   "rows":[
    ["Protecting the backend","**Throttling** and **usage plans** with API keys per client"],
    ["Latency and cost","**Caching** of responses per stage"],
    ["Releases","**Stages** and **canary deployments** that send a percentage to a new version"],
    ["Authentication","IAM, a **Lambda authorizer**, or a **Cognito user pool authorizer**"],
    ["Validation","Request validation against a model, before the backend is called"],
    ["Private APIs","A **private endpoint type** reachable only through an interface VPC endpoint"]]},
  {"t":"split","cols":[
   {"nm":"REST API","items":["The full feature set: API keys, usage plans, request validation, caching, WAF","Choose when a question names any of those"]},
   {"nm":"HTTP API","items":["Cheaper and faster, fewer features","JWT authorizers built in","Choose for a simple proxy to Lambda"]}]},
  {"t":"key","x":"**Throttling and usage plans** is the answer to \"protect the backend from a misbehaving client\". **Caching** is the answer to \"reduce backend calls for repeated identical requests\"."},
  {"t":"h","x":"Cognito"},
  {"t":"table","head":["","User pool","Identity pool"],
   "rows":[
    ["Purpose","**Authentication** — sign-up, sign-in, MFA, social and SAML federation","**Authorisation to AWS** — exchanges a token for temporary AWS credentials"],
    ["Produces","A JWT the application validates","Short-lived credentials from STS"],
    ["Used with","An API Gateway Cognito authorizer","Direct access to S3, DynamoDB and other services"]]},
  {"t":"flow","x":["User signs in to the user pool","Receives a JWT","API Gateway Cognito authorizer validates it","Lambda runs"],
   "cap":"If the client must call S3 directly instead, an identity pool trades the JWT for AWS credentials."},
  {"t":"trap","x":"Cognito is for the **users of your application**. Employees signing in to AWS accounts is **IAM Identity Center**. Swapping those two is one of the most common wrong answers in this area."}
 ],
 "checks":[
  {"q":"One client's script is flooding an API and starving other customers. Which feature addresses it?",
   "o":["Usage plans with per-key throttling","Response caching","A canary deployment",
        "A larger Lambda memory setting"],
   "a":[0],
   "x":"Usage plans attach rate and burst limits to API keys, so a single client can be capped without affecting others. Caching would help only if the requests were identical."},
  {"q":"Mobile users sign in and the API must verify their identity with no custom authentication code. What fits?",
   "o":["A Cognito user pool authorizer on API Gateway","A Lambda authorizer calling an external database",
        "An IAM role attached to each device","API keys distributed with the app"],
   "a":[0],
   "x":"A user pool handles sign-up and sign-in and issues a JWT that API Gateway validates natively. API keys identify a client application, not a user, and must never be treated as a secret in a mobile app."},
  {"q":"After signing in, the mobile app must upload directly to S3 with temporary AWS credentials. What provides them?",
   "o":["A Cognito identity pool","A Cognito user pool alone","An API Gateway usage plan",
        "A Lambda authorizer"],
   "a":[0],
   "x":"The identity pool exchanges the authenticated identity for short-lived AWS credentials scoped by an IAM role. The user pool authenticates but does not issue AWS credentials."},
  {"q":"Identical read requests are hitting the backend repeatedly and costing money. What reduces them?",
   "o":["API Gateway caching on the stage","A usage plan with a lower quota",
        "A canary deployment","Switching to an HTTP API"],
   "a":[0],
   "x":"Stage caching returns a stored response for repeated identical requests without invoking the backend. Usage plans limit clients rather than serving them faster."}
 ]
}
],
"recap":[
 {"t":"h","x":"Lambda limits worth memorising"},
 {"t":"table","head":["Limit","Value","What it decides"],
  "rows":[["Timeout","15 minutes","Longer work goes to Fargate, Batch or Step Functions"],
          ["Memory","128 MB to 10 GB","CPU scales with it, so more memory can be cheaper"],
          ["Package","250 MB unzipped, 10 GB as an image","Big dependencies mean a container image"],
          ["/tmp","512 MB, up to 10 GB","Large temporary files"],
          ["Concurrency","1,000 per region by default","Raise it, or reserve capacity per function"]]},
 {"t":"key","x":"Reserved concurrency protects a downstream system and can disable a function at zero. Provisioned concurrency pre-warms environments and removes cold starts. They are not interchangeable."},
 {"t":"h","x":"DynamoDB design"},
 {"t":"table","head":["Requirement","Answer"],
  "rows":[["A new query pattern on an existing table","Global secondary index"],
          ["A different sort order, planned at creation","Local secondary index"],
          ["Microsecond reads with minimal change","DAX"],
          ["React to every item change","Streams into Lambda"],
          ["Multi-region, writable everywhere","Global Tables"],
          ["Expire old items automatically","TTL"],
          ["All-or-nothing across items","Transactions"],
          ["Unpredictable traffic","On-demand capacity"]]},
 {"t":"h","x":"API Gateway, by symptom"},
 {"t":"dtree","x":[
  ["One client overwhelming the backend","Usage plan with throttling"],
  ["Repeated identical requests","Stage caching"],
  ["Gradual release of a new version","Canary deployment on the stage"],
  ["Users of your application must sign in","Cognito user pool authorizer"],
  ["Custom authorisation logic","Lambda authorizer"],
  ["Only reachable from inside the VPC","Private API with an interface endpoint"],
  ["Cheapest simple proxy to Lambda","HTTP API"]]},
 {"t":"h","x":"Cognito, in one line each"},
 {"t":"split","cols":[
  {"nm":"User pool","items":["Authenticates the users of your app","Sign-up, MFA, social and SAML federation","Issues a JWT"]},
  {"nm":"Identity pool","items":["Turns an identity into AWS credentials","Scoped by an IAM role","For direct calls to S3, DynamoDB and friends"]}]},
 {"t":"trap","x":"Recurring distractors: a Lambda timeout longer than fifteen minutes; ElastiCache offered where DAX fits; a scan proposed instead of an index; Cognito used for workforce access; and a VPC-attached Lambda expected to reach the internet without a NAT gateway."}
],
"final":[
 {"m":"lambda-basics",
  "q":"A nightly job processes a large file and takes around 45 minutes. It currently runs on an oversized EC2 instance that is idle the rest of the day. What is the most appropriate change?",
  "o":["Run it as an AWS Batch or Fargate task triggered on a schedule",
       "Move it to a Lambda function with the timeout raised to 45 minutes","Move it to a Lambda function with 10 GB of memory","Keep EC2 but enable hibernation between runs"],
  "a":[0],
  "w":["Correct — a scheduled container task has no fifteen-minute ceiling and costs nothing while idle.",
      "Lambda's fifteen-minute maximum cannot be raised, so this option is impossible.",
      "More memory speeds a function up but does not change the timeout ceiling.",
      "Hibernation reduces boot time but keeps the instance and its storage costs."],
  "x":"The fifteen-minute limit is the deciding fact. Scheduled Fargate or Batch work keeps the serverless cost profile while removing the duration constraint."},
 {"m":"dynamodb",
  "q":"An application queries a DynamoDB table by customer id, and a new report must find orders by status. The table is in production with millions of items. What should be added?",
  "o":["A global secondary index on status",
       "A local secondary index on status","A DAX cluster","A scheduled scan writing results to S3"],
  "a":[0],
  "w":["Correct — a GSI can use a different partition key and can be added to an existing table.",
      "Local secondary indexes must be created with the table and keep the original partition key.",
      "DAX caches reads; it does not create a new access pattern.",
      "Scanning millions of items repeatedly is expensive and slow, which indexes exist to avoid."],
  "x":"New access patterns on an existing table are global secondary indexes. The LSI restriction — same partition key, defined at creation — is what makes it the wrong answer here."},
 {"m":"lambda-scaling",
  "q":"A Lambda function was moved into private subnets to reach an RDS database. It now succeeds against the database but every call to an external payment API times out. What is required?",
  "o":["A NAT gateway in a public subnet with a route from the function's subnets",
       "A larger function timeout","An internet gateway attached directly to the private subnets","RDS Proxy in front of the database"],
  "a":[0],
  "w":["Correct — a VPC-attached function has no internet path until one is provided, and a NAT gateway is that path.",
      "A longer timeout waits longer for a connection that can never be established.",
      "Attaching an internet gateway to a subnet does not make it private, and private subnets route through NAT by design.",
      "RDS Proxy addresses connection pooling, not outbound internet access."],
  "x":"This is the standard trade-off of putting Lambda in a VPC: private resources become reachable and the internet does not, until a NAT gateway or VPC endpoint restores the path you need."},
 {"m":"apigw-cognito",
  "q":"A public API must let each customer make no more than 100 requests per second, with a monthly quota per customer. What provides this?",
  "o":["API Gateway usage plans with API keys, throttling and quotas",
       "AWS WAF rate-based rules on the stage","Reserved concurrency on the backing Lambda function","CloudFront caching in front of the API"],
  "a":[0],
  "w":["Correct — usage plans attach per-key rate, burst and quota limits, which is exactly per-customer metering.",
      "WAF rate rules work on IP addresses rather than identified customers.",
      "Reserved concurrency caps the whole function, not individual customers.",
      "Caching reduces backend load but enforces no per-customer limit."],
  "x":"Per-client limits and quotas are what usage plans exist for. WAF rate limiting is the answer to abusive traffic by address, which is a different question."},
 {"m":"dynamodb",
  "q":"A gaming table sees uneven performance: one partition key value receives most of the traffic. What is the correct remedy?",
  "o":["Redesign the partition key to spread requests, for example by adding a suffix",
       "Switch from on-demand to provisioned capacity","Add a local secondary index","Increase the read capacity units on the table"],
  "a":[0],
  "w":["Correct — throughput is distributed by partition key, so an even key distribution is the only real fix.",
      "Capacity mode does not change how requests map to partitions.",
      "An index adds an access pattern; it does not rebalance the base table's traffic.",
      "More capacity on a table with one hot key still throttles that key."],
  "x":"Hot partitions come from key design. Adding a computed suffix, or choosing a higher-cardinality attribute, is what spreads the load across partitions."},
 {"m":"lambda-scaling",
  "q":"An API's p99 latency spikes whenever traffic arrives after a quiet period, and the business requires consistent response times during business hours. What should be configured?",
  "o":["Provisioned concurrency, optionally scheduled for business hours",
       "Reserved concurrency set to the expected peak","A longer function timeout","A smaller memory allocation to speed initialisation"],
  "a":[0],
  "w":["Correct — provisioned concurrency keeps environments initialised so requests avoid the cold start entirely.",
      "Reserved concurrency limits how many copies may run; it does not pre-warm anything.",
      "Timeout governs how long a function may run, not how quickly it starts.",
      "Less memory means less CPU and slower initialisation, making the problem worse."],
  "x":"Cold starts are an initialisation cost paid by the first request into a new environment. Provisioned concurrency pays it in advance, and Application Auto Scaling can schedule it around known traffic."},
 {"m":"apigw-cognito",
  "q":"A mobile application authenticates users and must then upload photographs directly to S3 without routing the files through a backend. What combination is correct?",
  "o":["A Cognito user pool for sign-in and an identity pool to obtain temporary AWS credentials",
       "A Cognito user pool alone, with the app using its JWT to call S3","API Gateway with a Lambda proxy that forwards the file","An IAM user created for each mobile device"],
  "a":[0],
  "w":["Correct — the user pool authenticates and the identity pool exchanges that identity for scoped STS credentials.",
      "S3 does not accept a Cognito JWT; it requires AWS credentials.",
      "Routing large files through Lambda is exactly what the requirement avoids.",
      "Creating an IAM user per device does not scale and leaves long-lived credentials on phones."],
  "x":"The two Cognito halves do different jobs: authentication in the user pool, AWS authorisation in the identity pool. Direct-to-S3 uploads need the second one."},
 {"m":"lambda-basics",
  "q":"An S3 event triggers a Lambda function asynchronously. Some events fail every time due to malformed files, and the team needs to inspect them. What should be configured?",
  "o":["An on-failure destination or dead-letter queue for the function",
       "A longer timeout on the function","Synchronous invocation from S3","Reserved concurrency of zero"],
  "a":[0],
  "w":["Correct — after Lambda's two automatic retries, the event is delivered there for inspection instead of being lost.",
      "A longer timeout does not help an event that fails because of its content.",
      "S3 event notifications to Lambda are asynchronous; this is not configurable.",
      "Zero reserved concurrency would stop the function entirely."],
  "x":"Asynchronous invocations retry twice and then need somewhere to go. Failure destinations and dead-letter queues are how bad events are captured rather than silently discarded."},
 {"m":"dynamodb",
  "q":"A global application must accept writes in three regions with low latency in each, on a key-value data model. What fits?",
  "o":["DynamoDB Global Tables","DynamoDB with cross-region read replicas",
       "Aurora Global Database","DynamoDB Streams replicating with custom Lambda code"],
  "a":[0],
  "w":["Correct — Global Tables provide multi-region, multi-active replication built into the service.",
      "DynamoDB has no separate cross-region read replica feature of that kind.",
      "Aurora is relational and its global database has a single writable region.",
      "Hand-built replication with Streams is possible but reimplements a managed feature badly."],
  "x":"Writes accepted in several regions on a key-value model is Global Tables' exact description. Aurora Global Database is the relational analogue but with one primary region for writes."},
 {"m":"apigw-cognito",
  "q":"An internal API must be reachable only from inside the company's VPCs and never from the internet. How should it be exposed?",
  "o":["A private API Gateway endpoint accessed through an interface VPC endpoint",
       "A regional API protected by a resource policy listing office IPs","An edge-optimised API behind CloudFront with geo restriction","A public API with a usage plan and API keys"],
  "a":[0],
  "w":["Correct — a private endpoint type has no public DNS path and is reached only through PrivateLink.",
      "An IP allow-list still leaves the API exposed on the internet.",
      "Geo restriction filters by country and does not make the API private.",
      "API keys identify callers but do not restrict network reachability."],
  "x":"Private endpoint type plus an interface VPC endpoint is the supported way to keep an API entirely off the internet, which is stronger than any address-based restriction."}
]
}
