# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 13,
"nm": "Choosing a database in AWS",
"tag": "Databases",
"modules": [
{
 "id": "shapes",
 "nm": "The shape of the data decides the database",
 "goal": "Read a workload description and name the category of database it needs.",
 "min": 6,
 "blocks": [
  {"t":"p","x":"AWS offers a database per data shape rather than one database for everything. Exam questions in this area are pure pattern matching: find the sentence that names the shape."},
  {"t":"table","head":["Shape of the data","Category","Service"],
   "rows":[
    ["Rows, joins, transactions","Relational","RDS, or Aurora"],
    ["Items looked up by key","Key-value","DynamoDB"],
    ["JSON documents","Document","DocumentDB"],
    ["Wide rows with a Cassandra API","Wide column","Keyspaces"],
    ["Relationships between things","Graph","Neptune"],
    ["Measurements over time","Time series","Timestream"],
    ["Aggregations over billions of rows","Data warehouse","Redshift"],
    ["Files and objects","Object store","S3"],
    ["Anything that must be microseconds","Cache","ElastiCache, or DAX"]]},
  {"t":"key","x":"The phrases that give it away: **\"relationships\"** or \"friends of friends\" means Neptune; **\"time series\"** or \"sensor readings over time\" means Timestream; **\"complex analytical queries\"** means Redshift."},
  {"t":"h","x":"Managed or not"},
  {"t":"p","x":"Every option here is managed. Running a database on EC2 is only right when a question demands operating-system access, an engine AWS does not offer, or a specific version AWS does not support."},
  {"t":"flow","x":["What shape is the data?","Which access pattern dominates?","What are the availability and scale needs?","Pick the managed service that matches"]},
  {"t":"trap","x":"\"Relational\" does not automatically mean RDS. If the question also says serverless, unpredictable traffic, or global with fast failover, it is pointing at **Aurora** specifically."}
 ],
 "checks":[
  {"q":"An application must answer questions like \"which customers are connected to this customer through two or fewer relationships\". Which database?",
   "o":["Amazon Neptune","Amazon DynamoDB","Amazon Timestream","Amazon Redshift"],
   "a":[0],
   "x":"Traversing relationships is a graph query, which is what Neptune is built for. Expressing the same thing in a key-value or relational model requires expensive repeated joins."},
  {"q":"Millions of sensor readings arrive with a timestamp and must be queried over time windows. Which database?",
   "o":["Amazon Timestream","Amazon DocumentDB","Amazon Neptune","Amazon RDS for PostgreSQL"],
   "a":[0],
   "x":"Timestream is purpose-built for time series: it stores recent and historical data in different tiers and has time-window functions built in."},
  {"q":"When is running a database engine on EC2 the right answer?",
   "o":["When operating system access or an unsupported engine version is required",
        "Whenever high availability is needed","Whenever the data is relational",
        "Whenever cost must be minimised"],
   "a":[0],
   "x":"Managed services are preferred unless something specific rules them out, and host access or an unsupported engine is that something. Availability and cost usually argue for the managed option."},
  {"q":"A workload runs complex analytical queries aggregating billions of rows. Which service fits?",
   "o":["Amazon Redshift","Amazon DynamoDB","Amazon Keyspaces","Amazon ElastiCache"],
   "a":[0],
   "x":"Redshift is a columnar data warehouse built for large aggregations. Key-value and wide-column stores are optimised for point lookups, not for scanning and summarising whole datasets."}
 ]
},
{
 "id":"relational-vs-nosql",
 "nm":"Relational against key-value",
 "goal":"Justify choosing DynamoDB or a relational database for a stated access pattern.",
 "min":7,
 "blocks":[
  {"t":"split","cols":[
   {"nm":"Relational: RDS and Aurora","items":["Joins, complex queries, ad-hoc reporting","Transactions across many tables","A schema that is enforced","Scales up, and out for reads with replicas","Writes scale by making the instance bigger"]},
   {"nm":"Key-value: DynamoDB","items":["Known access patterns, looked up by key","Single-digit millisecond latency at any scale","**Writes scale horizontally without limit**","No joins; you design the keys around the queries","Serverless — nothing to size"]}]},
  {"t":"key","x":"The deciding question is whether the **access patterns are known in advance**. If they are, DynamoDB scales further and costs less to operate. If the application needs ad-hoc queries and joins, use a relational database."},
  {"t":"h","x":"Where each one hurts"},
  {"t":"table","head":["Problem","Relational","DynamoDB"],
   "rows":[
    ["A new query pattern appears","Easy — write new SQL","Needs a new index, or a redesign"],
    ["Write volume grows tenfold","Bigger instance, eventually sharding","Handled automatically"],
    ["A report across everything","Natural","Awkward — export to S3 and use Athena"],
    ["Strict schema","Enforced","Only what your code enforces"]]},
  {"t":"h","x":"Aurora, when relational is right"},
  {"t":"list","x":[
   "**Aurora Serverless v2** for intermittent or unpredictable load.",
   "**Aurora Global Database** for cross-region recovery in about a minute.",
   "**Reader endpoint** for spreading read traffic across up to fifteen replicas.",
   "Standard **RDS** when the engine is Oracle or SQL Server, or when Aurora's compatibility is not needed."]},
  {"t":"trap","x":"\"Migrate a relational application to DynamoDB to make it scale\" is usually wrong unless the question says the access patterns are simple and known. A join-heavy application rewritten onto a key-value store is a rewrite, not a migration."}
 ],
 "checks":[
  {"q":"A shopping cart is always read and written by cart id, and write volume grows unpredictably. Which database fits best?",
   "o":["DynamoDB","RDS for MySQL","Redshift","Neptune"],
   "a":[0],
   "x":"A single known access pattern by key with unbounded write growth is exactly DynamoDB's profile, and it scales writes horizontally with no capacity planning."},
  {"q":"An analytics team needs to run ad-hoc joins across ten tables that change weekly. Which database?",
   "o":["A relational database such as Aurora","DynamoDB with global secondary indexes",
        "Amazon Keyspaces","ElastiCache for Redis"],
   "a":[0],
   "x":"Ad-hoc joins across changing tables are what SQL and a relational engine are for. In a key-value store each new pattern needs a new index or a redesign."},
  {"q":"Which statement about scaling writes is correct?",
   "o":["DynamoDB scales writes horizontally; a relational database usually scales writes by growing the instance",
        "Both scale writes horizontally by default","Read replicas scale relational writes",
        "DynamoDB scales writes only with provisioned capacity"],
   "a":[0],
   "x":"Relational read replicas take read load but all writes still go to one primary. DynamoDB distributes writes across partitions, which is why it is chosen for very high write volume."},
  {"q":"A workload is relational but idle for most of the day with unpredictable bursts. Which option fits?",
   "o":["Aurora Serverless v2","A provisioned RDS instance sized for the peak",
        "DynamoDB on-demand","Redshift with concurrency scaling"],
   "a":[0],
   "x":"Serverless v2 scales capacity with demand, so idle periods are cheap and bursts are absorbed without a redesign. Keeping a peak-sized instance running pays for capacity that is mostly unused."}
 ]
},
{
 "id":"specialised",
 "nm":"The specialised engines",
 "goal":"Recognise the one-line description of DocumentDB, Keyspaces, Neptune and Timestream.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Service","Compatible with","Reach for it when"],
   "rows":[
    ["**DocumentDB**","MongoDB","An existing MongoDB application should keep its drivers and queries"],
    ["**Keyspaces**","Apache Cassandra (CQL)","An existing Cassandra workload, or a wide-column model, without running the cluster"],
    ["**Neptune**","Gremlin, openCypher, SPARQL","Relationships are the query: social graphs, fraud rings, recommendations, knowledge graphs"],
    ["**Timestream**","Its own SQL-like language","Measurements arriving with timestamps, queried over windows"],
    ["**Redshift**","PostgreSQL-like SQL","Analytical queries over very large datasets"]]},
  {"t":"key","x":"Compatibility is the signal. MongoDB means DocumentDB; Cassandra means Keyspaces. Neither is a general-purpose answer — they exist so an existing application does not have to be rewritten."},
  {"t":"h","x":"Timestream's shape"},
  {"t":"p","x":"Timestream keeps recent data in a **memory store** for fast queries and moves older data to a cheaper **magnetic store** on a schedule you set, which is why it is far cheaper than a relational database for the same data."},
  {"t":"h","x":"Redshift, briefly"},
  {"t":"list","x":[
   "Columnar storage with massively parallel processing across nodes.",
   "**Concurrency scaling** adds capacity for bursts of queries.",
   "**Redshift Spectrum** queries data that is still in S3, without loading it.",
   "It is a warehouse, not a transactional database — it is the wrong answer for high-volume single-row writes."]},
  {"t":"trap","x":"Redshift is for analytics, not for an application's live transactions. An option that puts an online transaction workload on Redshift is wrong however well the scale seems to match."}
 ],
 "checks":[
  {"q":"An existing MongoDB application must move to a managed service with minimal code change. Which service?",
   "o":["Amazon DocumentDB","Amazon DynamoDB","Amazon Keyspaces","Amazon Neptune"],
   "a":[0],
   "x":"DocumentDB is MongoDB compatible, so drivers and queries carry over. DynamoDB has a different API entirely and would require the data access layer to be rewritten."},
  {"q":"A team runs Apache Cassandra on EC2 and wants the same CQL interface without managing nodes. Which service?",
   "o":["Amazon Keyspaces","Amazon DocumentDB","Amazon Timestream","Amazon Aurora"],
   "a":[0],
   "x":"Keyspaces is Cassandra compatible and serverless, so existing CQL applications connect with little change and there is no cluster to operate."},
  {"q":"How does Timestream keep costs low for long retention?",
   "o":["Recent data sits in a memory store and older data moves to a cheaper magnetic store",
        "It compresses everything into a single file","It deletes data older than 30 days",
        "It stores only aggregates, not raw readings"],
   "a":[0],
   "x":"The tiered storage model means fast queries over recent data and cheap storage for history, with the transition governed by a retention policy you configure."},
  {"q":"Why is Redshift the wrong choice for an application's live transactional writes?",
   "o":["It is a columnar analytical warehouse, not a transactional database",
        "It cannot store more than a terabyte","It has no SQL interface",
        "It cannot be accessed from a VPC"],
   "a":[0],
   "x":"Columnar storage and parallel scans make aggregation fast but single-row inserts and updates slow. Transactional workloads belong in RDS, Aurora or DynamoDB."}
 ]
},
{
 "id":"decisions",
 "nm":"Putting it together",
 "goal":"Work through a mixed scenario and justify each database choice.",
 "min":6,
 "blocks":[
  {"t":"p","x":"Real questions rarely name a database. They describe a workload, and the right answer falls out of two or three phrases."},
  {"t":"dtree","x":[
   ["\"Joins\", \"transactions\", \"reporting\"","Relational: RDS or Aurora"],
   ["\"Key-value\", \"any scale\", \"single-digit millisecond\"","DynamoDB"],
   ["\"MongoDB\"","DocumentDB"],
   ["\"Cassandra\"","Keyspaces"],
   ["\"Relationships\", \"graph\", \"recommendation\"","Neptune"],
   ["\"Time series\", \"IoT readings\"","Timestream"],
   ["\"Data warehouse\", \"business intelligence\"","Redshift"],
   ["\"Microsecond\", \"cache\"","ElastiCache, or DAX for DynamoDB"],
   ["\"Query files in place\"","Athena over S3"]]},
  {"t":"key","x":"When two answers both fit the data shape, the tiebreaker is usually **operational overhead** or **scale**. The exam consistently rewards the more managed option unless something explicit rules it out."},
  {"t":"h","x":"Combinations that appear together"},
  {"t":"table","head":["Pattern","Why"],
   "rows":[
    ["DynamoDB plus DAX","Key-value at scale, with microsecond reads for hot items"],
    ["Aurora plus ElastiCache","Relational source of truth with a cache in front for read-heavy pages"],
    ["DynamoDB plus Streams plus Lambda","React to changes without polling"],
    ["RDS plus RDS Proxy plus Lambda","Serverless front end without exhausting connections"],
    ["S3 plus Athena","Cheap analytics without loading data anywhere"],
    ["Redshift plus Spectrum","Warehouse queries that reach into S3 for cold data"]]},
  {"t":"trap","x":"A cache is never the answer when the question forbids application changes, and a warehouse is never the answer for live transactions. Those two constraints eliminate options quickly."}
 ],
 "checks":[
  {"q":"A read-heavy product page hits a relational database hard, and the team may change the application. What is the usual addition?",
   "o":["ElastiCache in front of the database","A second relational database",
        "Redshift alongside the database","Neptune for the product relationships"],
   "a":[0],
   "x":"Caching frequently read data removes most of the repeated queries. It requires application changes, which the question explicitly permits."},
  {"q":"Which pairing gives microsecond reads on a key-value workload with almost no code change?",
   "o":["DynamoDB with DAX","DynamoDB with ElastiCache","Aurora with a reader endpoint",
        "Keyspaces with a global secondary index"],
   "a":[0],
   "x":"DAX speaks the DynamoDB API, so only the endpoint changes. ElastiCache would require the application to implement its own cache logic."},
  {"q":"Data already sits in S3 and analysts want SQL over it without loading it anywhere. What fits?",
   "o":["Amazon Athena","Amazon Redshift with a full load","Amazon DocumentDB","Amazon Timestream"],
   "a":[0],
   "x":"Athena queries data in place in S3 and charges per data scanned, which avoids any loading step or cluster to run."},
  {"q":"Two options both match the data shape. What usually decides between them on this exam?",
   "o":["Which one has lower operational overhead or scales further",
        "Which one was released more recently","Which one has a shorter name",
        "Which one supports the most regions"],
   "a":[0],
   "x":"The exam consistently favours the more managed option and the one that scales to the stated requirement, unless a constraint in the question rules it out."}
 ]
}
],
"recap":[
 {"t":"h","x":"The whole subject in one table"},
 {"t":"table","head":["The question says","Service"],
  "rows":[["Joins, transactions, reporting","RDS, or Aurora"],
          ["Unpredictable relational load, or global failover in a minute","Aurora Serverless v2, or Aurora Global Database"],
          ["Key-value at any scale","DynamoDB"],
          ["Microsecond reads on DynamoDB","DAX"],
          ["MongoDB compatible","DocumentDB"],
          ["Cassandra compatible","Keyspaces"],
          ["Relationships and traversals","Neptune"],
          ["Time-stamped measurements","Timestream"],
          ["Analytical aggregation at scale","Redshift"],
          ["SQL over files already in S3","Athena"],
          ["Sub-millisecond cache","ElastiCache"]]},
 {"t":"key","x":"Known access patterns favour DynamoDB; unknown or ad-hoc queries favour a relational engine. That single question separates the two most common answers in this subject."},
 {"t":"h","x":"What each one is bad at"},
 {"t":"table","head":["Service","Do not use it for"],
  "rows":[["DynamoDB","Ad-hoc joins and reporting"],
          ["Redshift","Live transactional writes"],
          ["ElastiCache","Anything where the application cannot be changed"],
          ["Neptune","Plain key lookups at scale"],
          ["Timestream","Relational business data"],
          ["RDS","Workloads needing host access — use EC2 or RDS Custom"]]},
 {"t":"h","x":"Pairings that keep appearing"},
 {"t":"split","cols":[
  {"nm":"For speed","items":["DynamoDB with DAX","Aurora with ElastiCache","Redshift with concurrency scaling"]},
  {"nm":"For reach","items":["DynamoDB Global Tables","Aurora Global Database","Redshift Spectrum over S3"]},
  {"nm":"For events","items":["DynamoDB Streams into Lambda","RDS event notifications","S3 events into Lambda"]}]},
 {"t":"trap","x":"Recurring distractors: DynamoDB proposed for a join-heavy application; Redshift proposed for transactions; a cache proposed when the application cannot change; and EC2-hosted databases proposed where a managed service would do."}
],
"final":[
 {"m":"shapes",
  "q":"A fraud team needs to find accounts connected to a suspicious account through shared devices, addresses and payment methods, within two or three hops. Which database fits?",
  "o":["Amazon Neptune","Amazon DynamoDB","Amazon Redshift","Amazon Timestream"],
  "a":[0],
  "w":["Correct — multi-hop traversal across relationships is precisely what a graph database is optimised for.",
      "Expressing traversals in a key-value store requires many round trips and careful key design.",
      "A warehouse can express this as repeated joins but performs poorly and is aimed at aggregation.",
      "Time series storage has no notion of relationships between entities."],
  "x":"\"Connected through\" and a hop count are the graph signals. Neptune supports Gremlin, openCypher and SPARQL, so the query language follows the team's existing skills."},
 {"m":"relational-vs-nosql",
  "q":"A session store is read and written by session id millions of times per minute, with no reporting requirement. Which service is the best fit?",
  "o":["DynamoDB, optionally with TTL to expire sessions",
       "RDS for PostgreSQL with read replicas","Redshift with concurrency scaling","Neptune with a session vertex per user"],
  "a":[0],
  "w":["Correct — a single key-based access pattern at very high volume is DynamoDB's core case, and TTL removes expired sessions for free.",
      "Replicas take read load but every write still goes to one primary, which becomes the bottleneck.",
      "A warehouse is designed for analytical scans, not millions of point writes per minute.",
      "A graph database adds relationship machinery this workload never uses."],
  "x":"Known access pattern, extreme volume, no joins. DynamoDB's TTL also handles expiry without a cleanup job, which is why session stores are a textbook use of it."},
 {"m":"specialised",
  "q":"A company runs a self-managed MongoDB cluster and wants to stop operating it while keeping its application code. Which service should it move to?",
  "o":["Amazon DocumentDB","Amazon DynamoDB","Amazon Keyspaces","Amazon Aurora PostgreSQL"],
  "a":[0],
  "w":["Correct — DocumentDB is MongoDB compatible, so existing drivers and queries continue to work.",
      "DynamoDB has a different API and data model, making this a rewrite rather than a migration.",
      "Keyspaces is Cassandra compatible, which is a different wire protocol entirely.",
      "Moving to a relational engine would mean redesigning the document model."],
  "x":"Compatibility is the whole reason DocumentDB and Keyspaces exist. When a question names an open-source engine and says code should not change, the compatible managed service is the answer."},
 {"m":"decisions",
  "q":"Analysts want SQL over ten terabytes of JSON logs already in S3, queried a few times a week. What is the most cost-effective option?",
  "o":["Amazon Athena querying the data in place",
       "Loading the data into Redshift","Loading the data into RDS","Importing the data into DynamoDB"],
  "a":[0],
  "w":["Correct — Athena charges per data scanned and needs no cluster, which suits infrequent queries.",
      "A Redshift cluster is worth it for constant analytical load, not for a few queries a week.",
      "A relational instance would struggle with this volume and require a lengthy load.",
      "A key-value store cannot answer ad-hoc analytical SQL."],
  "x":"Query frequency is the deciding factor. Infrequent queries over data in S3 favour Athena; sustained heavy analytics justify a warehouse, and Redshift Spectrum bridges the two."},
 {"m":"shapes",
  "q":"An industrial platform ingests millions of sensor readings per hour and reports averages per minute, hour and day. Which database is purpose-built for this?",
  "o":["Amazon Timestream","Amazon DocumentDB","Amazon Neptune","Amazon RDS for MySQL"],
  "a":[0],
  "w":["Correct — Timestream stores time-stamped measurements with tiered storage and time-window query functions.",
      "A document store has no time-series optimisations or built-in windowing.",
      "A graph database models relationships, not measurement series.",
      "A relational engine can store this but becomes expensive and slow at this volume."],
  "x":"The pairing of timestamped readings with window aggregations is the Timestream signature, and its memory-then-magnetic tiering is what makes long retention affordable."},
 {"m":"relational-vs-nosql",
  "q":"A relational application must survive a regional outage with a recovery time of about one minute and minimal data loss. Which option meets it?",
  "o":["Aurora Global Database with a secondary region",
       "RDS Multi-AZ in one region","A nightly snapshot copied to another region","DynamoDB Global Tables"],
  "a":[0],
  "w":["Correct — replication is typically under a second and a secondary region can be promoted in about a minute.",
      "Multi-AZ protects against zone failure, not the loss of an entire region.",
      "Nightly snapshots mean up to a day of data loss and a long restore.",
      "Global Tables are a key-value solution and would require abandoning the relational model."],
  "x":"The recovery time objective in minutes, on a relational workload, is Aurora Global Database's defining case. Multi-AZ and snapshots sit at very different points on that scale."},
 {"m":"specialised",
  "q":"Which statement correctly characterises Amazon Redshift?",
  "o":["A columnar data warehouse for analytical queries, unsuited to high-volume single-row transactions",
       "A key-value store with single-digit millisecond latency","A managed MongoDB-compatible document database","An in-memory cache for microsecond reads"],
  "a":[0],
  "w":["Correct — columnar storage and parallel processing favour large aggregations over point writes.",
      "That describes DynamoDB.",
      "That describes DocumentDB.",
      "That describes ElastiCache or DAX."],
  "x":"Knowing what each service is *not* for eliminates options quickly. Redshift's columnar design is exactly why it excels at aggregation and struggles with transactional write patterns."},
 {"m":"decisions",
  "q":"A DynamoDB-backed API is fast overall, but a handful of extremely popular items are read constantly and the team wants microsecond latency with minimal code change. What should be added?",
  "o":["A DAX cluster in front of the table",
       "An ElastiCache for Redis cluster","A global secondary index on the popular items","Aurora as a read cache"],
  "a":[0],
  "w":["Correct — DAX is DynamoDB-aware, so adopting it is largely an endpoint change.",
      "Redis would work but requires the application to implement cache population and invalidation.",
      "An index creates a new access pattern; it does not cache anything.",
      "Introducing a relational database as a cache is neither simple nor appropriate."],
  "x":"DAX exists for exactly this: hot-item read caching for DynamoDB with API compatibility, which is what makes it the low-change answer compared with a general-purpose cache."},
 {"m":"shapes",
  "q":"A team must run a database engine version that AWS does not offer as a managed service, and needs operating system access for a vendor agent. What should they do?",
  "o":["Run the engine on EC2 and manage it themselves",
       "Use RDS with a custom parameter group","Use Aurora with a compatible engine","Use DynamoDB and adapt the schema"],
  "a":[0],
  "w":["Correct — an unsupported version plus host access rules out every managed relational option.",
      "Parameter groups tune settings; they cannot provide an unsupported version or host access.",
      "Aurora offers even less host access than RDS.",
      "Changing data model to avoid an operational constraint is a rewrite, not a solution."],
  "x":"Managed services are the default answer, but two constraints override that: an engine or version AWS does not support, and a requirement for operating system access. RDS Custom covers some of this for Oracle and SQL Server."},
 {"m":"relational-vs-nosql",
  "q":"An existing order system uses complex SQL joins across a dozen tables and must handle three times its current traffic. What is the most appropriate change?",
  "o":["Move to Aurora and scale reads with the reader endpoint",
       "Rewrite the data layer onto DynamoDB","Move the tables into Redshift","Replace the database with ElastiCache"],
  "a":[0],
  "w":["Correct — Aurora keeps the relational model while offering up to fifteen replicas and higher throughput.",
      "A join-heavy application on a key-value store is a full redesign, not a scaling step.",
      "Redshift is analytical and unsuited to transactional order processing.",
      "A cache cannot replace the system of record."],
  "x":"Scaling a join-heavy relational workload is usually answered within the relational family: Aurora for throughput and replicas, plus a cache if reads dominate. Moving to DynamoDB is only right when the access patterns are simple and known."}
]
}
