# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 14,
"nm": "Data and Analytics",
"tag": "Analytics",
"modules": [
{
 "id": "query-in-place",
 "nm": "Querying data where it already lives",
 "goal": "Choose between Athena, Redshift and a lake formation approach for a query workload.",
 "min": 7,
 "blocks": [
  {"t":"p","x":"The cheapest analytics is the kind that does not move data. S3 is the data lake, and several services read from it directly."},
  {"t":"table","head":["Service","What it is","Fits when"],
   "rows":[
    ["**Athena**","Serverless SQL over S3, charged per **data scanned**","Ad-hoc or occasional queries, no cluster to run"],
    ["**Redshift**","A provisioned columnar warehouse","Sustained, heavy analytical workloads with many concurrent users"],
    ["**Redshift Spectrum**","Redshift querying S3 directly","Joining warehouse tables with cold data still in S3"],
    ["**Glue**","Serverless ETL and the **Data Catalog**","Discovering schemas and transforming data between stores"],
    ["**Lake Formation**","Permissions and governance over the lake","Column and row level access control across many teams"]]},
  {"t":"key","x":"Athena charges for the **bytes scanned**, so converting data to a **columnar format such as Parquet**, compressing it, and **partitioning** by date cuts both cost and time dramatically. That is the standard answer to \"Athena queries are expensive\"."},
  {"t":"h","x":"The Glue Data Catalog"},
  {"t":"p","x":"A **crawler** inspects data in S3, infers the schema, and registers a table in the catalog. Athena, Redshift Spectrum and EMR all read that same catalog, so the schema is defined once."},
  {"t":"flow","x":["Raw files land in S3","Glue crawler infers the schema","Table appears in the Data Catalog","Athena queries it with SQL"]},
  {"t":"h","x":"Lake Formation"},
  {"t":"p","x":"Sits on top and grants access at **database, table, column and row** level, rather than through bucket policies. It is the answer when different teams must see different columns of the same dataset."},
  {"t":"trap","x":"Athena is not a database. It cannot serve an application's transactional reads, and it has no indexes — its performance comes entirely from how the data is laid out in S3."}
 ],
 "checks":[
  {"q":"Athena queries scan terabytes and cost more than expected. What reduces both cost and runtime most?",
   "o":["Convert the data to Parquet, compress it, and partition by date",
        "Increase the Athena query timeout","Move the data to a larger S3 storage class",
        "Add a global secondary index"],
   "a":[0],
   "x":"Athena bills per byte scanned, so a columnar format lets it read only the needed columns and partitioning lets it skip whole prefixes. Storage class and timeouts do not affect what is scanned."},
  {"q":"What does a Glue crawler produce?",
   "o":["A table definition in the Data Catalog, inferred from the data",
        "A compressed copy of the data","A Redshift cluster","An Athena workgroup"],
   "a":[0],
   "x":"The crawler infers schema and partitions and registers a table that Athena, Redshift Spectrum and EMR can all read, so the schema is defined once and shared."},
  {"q":"Different teams must see different columns of the same dataset in the lake. What provides that control?",
   "o":["AWS Lake Formation permissions","A bucket policy per team","Separate S3 buckets per team",
        "Athena workgroups"],
   "a":[0],
   "x":"Lake Formation grants access down to column and row level across catalog tables. Bucket policies only work at the object or prefix level and cannot express a column restriction."},
  {"q":"When is Redshift a better choice than Athena?",
   "o":["For sustained, heavy analytical workloads with many concurrent users",
        "For a handful of ad-hoc queries per week","When no cluster may be provisioned",
        "When the data must stay in S3 untouched"],
   "a":[0],
   "x":"A provisioned warehouse pays off when queries are constant and concurrency is high. Occasional queries are cheaper on Athena because there is nothing running between them."}
 ]
},
{
 "id":"pipelines",
 "nm":"Getting data in and moving it around",
 "goal":"Assemble an ingestion pipeline from Kinesis, Glue, EMR and MSK.",
 "min":7,
 "blocks":[
  {"t":"table","head":["Service","Role in a pipeline"],
   "rows":[
    ["**Kinesis Data Streams**","Real-time ingestion with replay, read by several consumers"],
    ["**Data Firehose**","Buffered delivery into S3, Redshift, OpenSearch or Splunk, with optional Lambda transformation"],
    ["**Managed Service for Apache Flink**","Continuous SQL or Flink applications over a stream: windows, aggregations, anomaly detection"],
    ["**MSK**","Managed Apache Kafka, for teams already on Kafka or needing its ecosystem"],
    ["**Glue**","Serverless Spark ETL jobs, plus the catalog"],
    ["**EMR**","Managed Hadoop, Spark, Hive and Presto clusters when you need control over the framework"]]},
  {"t":"key","x":"**Glue** is serverless ETL with nothing to size. **EMR** is a cluster you configure — the answer when a question names Hadoop, HBase, or a specific Spark configuration, or when Spot instances must back the compute."},
  {"t":"h","x":"A typical ingestion pipeline"},
  {"t":"flow","x":["Producers","Kinesis Data Streams","Firehose or Flink","S3 data lake","Glue catalog","Athena or Redshift","QuickSight"]},
  {"t":"h","x":"MSK against Kinesis"},
  {"t":"split","cols":[
   {"nm":"Kinesis Data Streams","items":["AWS native, shards or on-demand","Retention 1 to 365 days","Tight integration with Lambda and Firehose","Less to operate"]},
   {"nm":"Amazon MSK","items":["Real Apache Kafka, so existing producers and consumers work","Unlimited retention with tiered storage","Kafka ecosystem: Connect, Streams","More configuration, more control"]}]},
  {"t":"trap","x":"A question naming **Kafka** explicitly, or saying existing Kafka applications must keep working, is pointing at **MSK**, not Kinesis — the same logic as DocumentDB and MongoDB."}
 ],
 "checks":[
  {"q":"A team already runs Apache Kafka producers and consumers and wants a managed equivalent on AWS. Which service?",
   "o":["Amazon MSK","Kinesis Data Streams","Kinesis Data Firehose","Amazon SQS"],
   "a":[0],
   "x":"MSK runs actual Apache Kafka, so existing clients connect unchanged. Kinesis has its own API and would require rewriting producers and consumers."},
  {"q":"An ETL job must run without provisioning or tuning a cluster. Which service?",
   "o":["AWS Glue","Amazon EMR","Amazon Redshift","Amazon MSK"],
   "a":[0],
   "x":"Glue runs serverless Spark jobs and manages the capacity itself. EMR gives you a cluster to configure, which is the right answer only when that control is needed."},
  {"q":"Anomalies must be detected on a live stream using time windows. Which service fits?",
   "o":["Managed Service for Apache Flink","Kinesis Data Firehose","AWS Glue crawlers",
        "Amazon Athena"],
   "a":[0],
   "x":"Flink applications perform continuous windowed computation over a stream, which is what anomaly detection on live data requires. Firehose only delivers, and Athena queries data at rest."},
  {"q":"When is EMR preferred over Glue?",
   "o":["When you need control over the framework, such as Hadoop or a specific Spark configuration",
        "When no cluster may be provisioned","When the job must be serverless",
        "When only SQL is required"],
   "a":[0],
   "x":"EMR exposes the cluster and its configuration, and can run on Spot instances. Glue is the answer whenever the requirement is to avoid managing that cluster at all."}
 ]
},
{
 "id":"search-and-bi",
 "nm":"Search, dashboards and the rest",
 "goal":"Name the service for log search, dashboards and managed data movement.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Service","What it does"],
   "rows":[
    ["**OpenSearch Service**","Full-text search and log analytics, with dashboards — the answer for searching logs by content"],
    ["**QuickSight**","Business intelligence dashboards, with **SPICE** for fast in-memory analysis"],
    ["**Data Pipeline**","Older scheduled data movement; Glue and Step Functions are now usually preferred"],
    ["**AppFlow**","Managed transfers between SaaS applications and AWS, such as Salesforce to S3"]]},
  {"t":"key","x":"**CloudWatch Logs Insights** searches log groups inside CloudWatch. **OpenSearch** is the answer when logs must be searched at scale with rich full-text queries and dashboards, often fed by Firehose."},
  {"t":"h","x":"QuickSight details that get tested"},
  {"t":"list","x":[
   "**SPICE** is an in-memory engine that caches a dataset so dashboards respond quickly without hitting the source.",
   "**Row-level security** restricts which rows each user sees within a dashboard.",
   "It connects to Athena, Redshift, RDS, S3 and many external sources.",
   "Sessions can be embedded in your own application."]},
  {"t":"flow","x":["Logs","Firehose","OpenSearch Service","Dashboards and alerting"]},
  {"t":"trap","x":"OpenSearch is not a database of record and not a data warehouse. It is for search and observability; large analytical aggregation belongs in Redshift or Athena."}
 ],
 "checks":[
  {"q":"Operations must search application logs by free text and visualise them on dashboards at scale. Which service?",
   "o":["Amazon OpenSearch Service","Amazon Redshift","Amazon QuickSight","AWS Glue"],
   "a":[0],
   "x":"OpenSearch is built for full-text search and log analytics and ships with dashboards. Redshift is for aggregation and QuickSight visualises data rather than indexing it."},
  {"q":"What is SPICE in QuickSight?",
   "o":["An in-memory engine that caches a dataset for fast dashboards",
        "A row-level security feature","A connector to Salesforce","A columnar storage format in S3"],
   "a":[0],
   "x":"SPICE holds a copy of the dataset in memory so dashboards respond without querying the source every time, which both speeds them up and reduces load on the source."},
  {"q":"Data must be transferred regularly from a SaaS application such as Salesforce into S3 with no custom code. Which service?",
   "o":["Amazon AppFlow","AWS DataSync","AWS Glue crawlers","Kinesis Data Firehose"],
   "a":[0],
   "x":"AppFlow provides managed connectors to SaaS applications and can run on a schedule or on events. DataSync moves data between file and object storage, not SaaS APIs."},
  {"q":"Which feature restricts the rows a particular user sees in a QuickSight dashboard?",
   "o":["Row-level security","SPICE","A Glue crawler","An Athena workgroup"],
   "a":[0],
   "x":"Row-level security filters the dataset per user or group, so one dashboard can serve many audiences without duplicating it."}
 ]
},
{
 "id":"analytics-decisions",
 "nm":"Reading an analytics question",
 "goal":"Assemble the right services for an end-to-end scenario without over-building.",
 "min":6,
 "blocks":[
  {"t":"dtree","x":[
   ["Ad-hoc SQL over files in S3","Athena, with Glue catalog"],
   ["Constant heavy analytics, many users","Redshift"],
   ["Warehouse query needing cold data in S3","Redshift Spectrum"],
   ["Serverless ETL","Glue"],
   ["Hadoop, HBase, or a tuned Spark cluster","EMR"],
   ["Real-time ingestion with replay","Kinesis Data Streams"],
   ["Deliver a stream into S3 with no code","Firehose"],
   ["Windowed aggregation on a live stream","Managed Service for Apache Flink"],
   ["Existing Kafka applications","MSK"],
   ["Full-text log search and dashboards","OpenSearch Service"],
   ["Business dashboards for non-engineers","QuickSight"],
   ["Column-level access across teams","Lake Formation"]]},
  {"t":"key","x":"Most analytics answers are a **chain**: ingest, store in S3, catalog, query, visualise. When an option skips the lake and loads everything into a warehouse immediately, check whether the question actually justifies the cost."},
  {"t":"h","x":"Cost levers worth naming"},
  {"t":"table","head":["Lever","Effect"],
   "rows":[
    ["Parquet or ORC instead of JSON or CSV","Athena and Spectrum scan far fewer bytes"],
    ["Partitioning by date or tenant","Whole prefixes are skipped"],
    ["Compression","Less scanned and less stored"],
    ["Lifecycle rules on raw data","Cold raw files move to Glacier tiers"],
    ["EMR on Spot instances","Large discount on interruptible processing"],
    ["Redshift concurrency scaling","Pay only for the burst capacity used"]]},
  {"t":"trap","x":"Do not answer EMR when the question stresses \"no clusters to manage\", and do not answer Redshift when it stresses \"only a few queries a week\". The operational wording is doing the work."}
 ],
 "checks":[
  {"q":"Clickstream data must land in S3 continuously with no consumer code, then be queried ad hoc with SQL. What is the chain?",
   "o":["Firehose into S3, a Glue crawler, then Athena","Kinesis Data Streams into EMR, then Redshift",
        "SQS into Lambda, then DynamoDB","AppFlow into QuickSight"],
   "a":[0],
   "x":"Firehose delivers without consumers to run, the crawler registers the schema, and Athena queries it in place. The other chains add clusters or change the data model unnecessarily."},
  {"q":"Which change most reduces the cost of repeated Athena queries?",
   "o":["Storing the data as partitioned, compressed Parquet","Running the queries at night",
        "Moving the bucket to another region","Using a larger Athena workgroup"],
   "a":[0],
   "x":"Cost is a function of bytes scanned, so columnar storage plus partitioning and compression attacks it directly. Scheduling and region have no effect on the amount scanned."},
  {"q":"A requirement says no clusters may be managed. Which option does that rule out?",
   "o":["Amazon EMR","AWS Glue","Amazon Athena","Kinesis Data Firehose"],
   "a":[0],
   "x":"EMR is explicitly a cluster you size and configure. Glue, Athena and Firehose are all serverless from the user's point of view."},
  {"q":"Redshift queries slow down sharply during a daily reporting burst. Which feature handles the burst without permanently resizing?",
   "o":["Concurrency scaling","Redshift Spectrum","A Glue crawler","SPICE in QuickSight"],
   "a":[0],
   "x":"Concurrency scaling adds temporary capacity for queued queries and is charged only while it is used, which fits a predictable burst better than permanently larger nodes."}
 ]
}
],
"recap":[
 {"t":"h","x":"The pipeline, drawn once"},
 {"t":"flow","x":["Producers","Kinesis or MSK","Firehose or Flink","S3 lake","Glue catalog","Athena or Redshift","QuickSight"]},
 {"t":"h","x":"Service by sentence"},
 {"t":"table","head":["The question says","Service"],
  "rows":[["Ad-hoc SQL over S3","Athena"],
          ["Heavy sustained analytics","Redshift"],
          ["Join warehouse data with S3","Redshift Spectrum"],
          ["Serverless ETL and schema discovery","Glue"],
          ["Hadoop, HBase, tuned Spark, Spot","EMR"],
          ["Real time with replay","Kinesis Data Streams"],
          ["Near real time into S3, no code","Firehose"],
          ["Windowed stream analytics","Managed Service for Apache Flink"],
          ["Existing Kafka clients","MSK"],
          ["Full-text log search","OpenSearch Service"],
          ["Dashboards for the business","QuickSight"],
          ["Column and row level lake permissions","Lake Formation"],
          ["SaaS to AWS transfers","AppFlow"]]},
 {"t":"key","x":"Athena is priced by bytes scanned. Parquet, compression and partitioning are therefore the answer to almost every Athena cost or performance question."},
 {"t":"h","x":"Managed or configured"},
 {"t":"split","cols":[
  {"nm":"Nothing to manage","items":["Athena","Glue","Firehose","QuickSight","Lake Formation"]},
  {"nm":"A cluster to size","items":["EMR","Redshift, though it also has serverless","MSK","OpenSearch Service"]}]},
 {"t":"h","x":"Cost levers, collected"},
 {"t":"table","head":["Lever","Where it applies"],
  "rows":[["Parquet or ORC instead of JSON","Athena, Redshift Spectrum, EMR"],
          ["Partition by date or tenant","Athena and Spectrum skip whole prefixes"],
          ["Compression","Everything that scans S3"],
          ["Spot instances","EMR task nodes"],
          ["Concurrency scaling","Redshift bursts"],
          ["SPICE","QuickSight dashboards, and less load on the source"]]},
 {"t":"trap","x":"Recurring distractors: EMR where the question forbids clusters; Redshift for a handful of weekly queries; Kinesis where existing Kafka clients must keep working; and OpenSearch proposed as a data warehouse."}
],
"final":[
 {"m":"query-in-place",
  "q":"A team queries 40 TB of JSON logs in S3 with Athena a few times a day, and the cost has become the largest line on the analytics bill. What change helps most?",
  "o":["Convert the logs to partitioned, compressed Parquet",
       "Move the bucket to a cheaper region","Increase the Athena query concurrency limit","Load everything into Redshift"],
  "a":[0],
  "w":["Correct — Athena bills per byte scanned, and a columnar partitioned format cuts that by an order of magnitude.",
      "Region affects storage and transfer pricing, not the volume Athena scans.",
      "Concurrency changes how many queries run at once, not what each one costs.",
      "Provisioning a warehouse for a few queries a day adds fixed cost for no benefit."],
  "x":"Athena's pricing model makes data layout the main lever. Parquet lets it read only the needed columns, partitioning lets it skip irrelevant prefixes, and compression shrinks what remains."},
 {"m":"pipelines",
  "q":"A company runs Kafka producers and consumers on premises and wants a managed broker on AWS with no client changes. Which service?",
  "o":["Amazon MSK","Kinesis Data Streams","Kinesis Data Firehose","Amazon SQS"],
  "a":[0],
  "w":["Correct — MSK runs Apache Kafka, so existing clients connect with only a broker endpoint change.",
      "Kinesis uses a different API and would require rewriting every producer and consumer.",
      "Firehose is a delivery pipeline with no Kafka protocol support.",
      "SQS is a queue with entirely different semantics."],
  "x":"Protocol compatibility is the deciding factor, exactly as with DocumentDB for MongoDB. MSK also supports the wider Kafka ecosystem such as Connect and Streams."},
 {"m":"search-and-bi",
  "q":"Support engineers need to search millions of application log lines by free text and build dashboards on error trends. Which service is intended?",
  "o":["Amazon OpenSearch Service","Amazon Redshift","Amazon Athena","Amazon QuickSight"],
  "a":[0],
  "w":["Correct — full-text indexing with dashboards is what OpenSearch is designed for.",
      "A warehouse handles aggregation well but is not a search engine.",
      "Athena runs SQL over files and has no full-text index.",
      "QuickSight visualises data but does not index or search raw logs."],
  "x":"Free-text search over logs at scale is the OpenSearch signal, usually fed by Firehose. Aggregation-heavy analytics without search belongs in Redshift or Athena."},
 {"m":"analytics-decisions",
  "q":"Clickstream events must be delivered into a data lake in near real time with no consumer code, then made queryable by analysts. Which combination is correct?",
  "o":["Kinesis Data Firehose into S3, a Glue crawler to catalog it, and Athena for queries",
       "Kinesis Data Streams with an EC2 consumer fleet writing to S3","An SQS queue consumed by Lambda writing to DynamoDB","AppFlow into Redshift with a nightly load"],
  "a":[0],
  "w":["Correct — Firehose needs no consumers, the crawler registers the schema, and Athena queries the data in place.",
      "Running a consumer fleet is exactly the operational work the requirement excludes.",
      "A key-value store does not give analysts ad-hoc SQL over the events.",
      "AppFlow moves SaaS data and is not a clickstream ingestion path."],
  "x":"This chain — Firehose, S3, Glue catalog, Athena — is the default serverless analytics pipeline and appears repeatedly in exam scenarios."},
 {"m":"query-in-place",
  "q":"Several teams share one dataset, but each may only see certain columns. Bucket policies cannot express the requirement. What provides it?",
  "o":["AWS Lake Formation permissions on catalog tables",
       "One S3 bucket per team with copies of the data","Athena workgroups per team","IAM policies with object-level conditions"],
  "a":[0],
  "w":["Correct — Lake Formation grants access at database, table, column and row level.",
      "Copying data per team creates drift and multiplies storage cost.",
      "Workgroups separate query cost and settings, not data visibility.",
      "IAM conditions act on objects and prefixes, not on columns inside a file."],
  "x":"Column and row level control over a shared lake is Lake Formation's core purpose, and it applies consistently to Athena, Redshift Spectrum and EMR through the catalog."},
 {"m":"pipelines",
  "q":"A fraud pipeline must compute five-minute rolling averages over a live event stream and raise alerts on anomalies. Which service performs the computation?",
  "o":["Amazon Managed Service for Apache Flink","Kinesis Data Firehose",
       "AWS Glue crawlers","Amazon QuickSight"],
  "a":[0],
  "w":["Correct — Flink applications perform continuous windowed aggregation and anomaly detection over streams.",
      "Firehose buffers and delivers records but performs no windowed computation.",
      "Crawlers infer schemas and have nothing to do with stream processing.",
      "QuickSight visualises results rather than computing them on a stream."],
  "x":"Windows, rolling aggregates and anomaly detection on live data are the Flink signals. Firehose plus Lambda can transform individual records, but not compute across a time window."},
 {"m":"analytics-decisions",
  "q":"A Redshift cluster performs well except during a two-hour reporting window each morning, when queries queue. The team does not want to pay for larger nodes all day. What fits?",
  "o":["Enable concurrency scaling so extra capacity is added only during the burst",
       "Resize the cluster to the peak requirement","Move all reporting to Athena","Add a Glue job to precompute every report"],
  "a":[0],
  "w":["Correct — concurrency scaling adds transient capacity for queued queries and is billed only while used.",
      "Permanent resizing pays for peak capacity for twenty-four hours a day.",
      "Moving everything to Athena discards the warehouse's advantages for sustained workloads.",
      "Precomputing every report is a large project and does not address ad-hoc queries."],
  "x":"Concurrency scaling exists for exactly this shape of load: a predictable burst on top of a steady baseline, paid for by the burst rather than by the peak."},
 {"m":"search-and-bi",
  "q":"A dashboard must show each regional manager only their own region's rows, from one shared dataset. What provides this in QuickSight?",
  "o":["Row-level security on the dataset","A separate dashboard per region",
       "SPICE refresh schedules","A Lake Formation column permission"],
  "a":[0],
  "w":["Correct — row-level security filters the dataset per user or group within a single dashboard.",
      "Duplicating dashboards multiplies maintenance and drifts over time.",
      "Refresh schedules control freshness, not visibility.",
      "Lake Formation governs lake access; the requirement is inside QuickSight."],
  "x":"Row-level security keeps one dashboard serving many audiences, which is why it is the expected answer rather than duplicating assets per region."},
 {"m":"pipelines",
  "q":"A batch job needs a tuned Spark configuration and should run on Spot instances to cut cost. Which service fits?",
  "o":["Amazon EMR","AWS Glue","Amazon Athena","Kinesis Data Firehose"],
  "a":[0],
  "w":["Correct — EMR exposes cluster and framework configuration and supports Spot instances for task nodes.",
      "Glue abstracts the cluster away, which is the opposite of what tuning requires.",
      "Athena runs SQL and does not execute arbitrary Spark jobs.",
      "Firehose is a delivery service, not a processing framework."],
  "x":"The combination of framework tuning and Spot pricing is what distinguishes EMR from Glue. When a question instead stresses \"no cluster to manage\", Glue is the answer."},
 {"m":"query-in-place",
  "q":"Analysts must join tables in a Redshift warehouse with three years of colder history that remains in S3, without loading it. What enables this?",
  "o":["Redshift Spectrum","A Glue crawler alone","Athena federated to Redshift","QuickSight with SPICE"],
  "a":[0],
  "w":["Correct — Spectrum lets Redshift query external tables in S3 and join them with local tables.",
      "A crawler registers schemas but performs no querying.",
      "Federation runs the query from Athena rather than joining inside the warehouse.",
      "SPICE caches datasets for dashboards and does not perform the join."],
  "x":"Spectrum is the bridge between the warehouse and the lake: hot data stays in Redshift, cold history stays in S3, and a single query spans both."}
]
}
