# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 15,
"nm": "Machine learning services",
"tag": "AI",
"modules": [
{
 "id": "vision-speech",
 "nm": "Images, documents, speech",
 "goal": "Name the right service for a picture, a scanned document, or audio.",
 "min": 6,
 "blocks": [
  {"t":"p","x":"These services are pre-trained. You call an API and get a result — no model to train, no data science. For the exam, each one has a single sentence that identifies it."},
  {"t":"table","head":["Service","One sentence"],
   "rows":[
    ["**Rekognition**","Finds objects, faces, text and unsafe content in **images and video**"],
    ["**Textract**","Extracts text, **forms and tables** from scanned documents and PDFs"],
    ["**Transcribe**","Speech **to** text, with speaker identification and automatic redaction of personal data"],
    ["**Polly**","Text **to** speech, in lifelike voices"],
    ["**Translate**","Translates text between languages"]]},
  {"t":"key","x":"Rekognition reads **pictures**; Textract reads **documents**. If the question mentions a form, an invoice, a receipt or a table of values on a page, it is Textract."},
  {"t":"h","x":"Details that appear in questions"},
  {"t":"list","x":[
   "Rekognition does **content moderation**, flagging inappropriate images and video — the usual answer for a user-upload platform.",
   "Rekognition also does **face comparison** and celebrity recognition.",
   "Transcribe can **redact personally identifiable information** automatically, which suits call recordings.",
   "Polly supports **lexicons** for custom pronunciation and **SSML** for emphasis and pauses."]},
  {"t":"flow","x":["User uploads an image to S3","S3 event triggers Lambda","Rekognition moderates it","Rejected images quarantined"]},
  {"t":"trap","x":"Do not answer SageMaker for a task a pre-trained service already covers. \"Detect inappropriate images\" is Rekognition; training a custom model would be more work for a worse result."}
 ],
 "checks":[
  {"q":"Scanned invoices must have their line items and totals extracted, preserving the table structure. Which service?",
   "o":["Amazon Textract","Amazon Rekognition","Amazon Transcribe","Amazon Comprehend"],
   "a":[0],
   "x":"Textract is built for documents and understands forms and tables, not just characters. Rekognition can detect text in an image but does not reconstruct a table's structure."},
  {"q":"A platform must automatically flag inappropriate user-uploaded images. Which service?",
   "o":["Amazon Rekognition content moderation","Amazon Textract","Amazon Polly","Amazon Translate"],
   "a":[0],
   "x":"Rekognition includes content moderation for images and video, which is exactly this use case and needs no training data of your own."},
  {"q":"Recorded support calls must be converted to text with personal data removed. Which service?",
   "o":["Amazon Transcribe with redaction","Amazon Polly","Amazon Comprehend Medical","Amazon Kendra"],
   "a":[0],
   "x":"Transcribe converts speech to text and can redact personally identifiable information automatically, which is why it fits call recordings specifically."},
  {"q":"An application must read notifications aloud in a natural voice. Which service?",
   "o":["Amazon Polly","Amazon Transcribe","Amazon Translate","Amazon Rekognition"],
   "a":[0],
   "x":"Polly is text to speech. Transcribe goes the other way, and the remaining services deal with language translation and images."}
 ]
},
{
 "id":"language-search",
 "nm":"Language, conversation and search",
 "goal":"Distinguish Comprehend, Lex, Kendra and Personalize by what each produces.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Service","What it produces"],
   "rows":[
    ["**Comprehend**","Sentiment, entities, key phrases, language and topics from text"],
    ["**Comprehend Medical**","Medical entities such as conditions, medications and dosages from clinical text"],
    ["**Lex**","A **conversational interface** — the engine behind chatbots, with intents and slots"],
    ["**Connect**","A cloud **contact centre**, which pairs with Lex for self-service"],
    ["**Kendra**","**Intelligent search** across enterprise documents, answering natural-language questions"],
    ["**Personalize**","Real-time **recommendations**, the same technology Amazon uses for products"]]},
  {"t":"key","x":"Kendra **searches documents and answers questions**. Comprehend **analyses text** and returns sentiment or entities. A question about \"employees can ask where the expense policy is\" is Kendra."},
  {"t":"h","x":"Lex and Connect together"},
  {"t":"flow","x":["Caller dials in","Amazon Connect answers","Lex understands the intent","Lambda fulfils it","Escalate to an agent if needed"]},
  {"t":"h","x":"Personalize in practice"},
  {"t":"list","x":[
   "You supply interaction history — views, purchases, ratings — plus item and user metadata.",
   "It returns recommendations through an API in real time, with no model built by hand.",
   "It is the answer whenever a question describes product or content recommendations."]},
  {"t":"trap","x":"Comprehend tells you **how a review feels**. Kendra tells you **where the answer is**. Swapping those two is the most common mistake in this group."}
 ],
 "checks":[
  {"q":"Employees must ask natural-language questions and get answers from thousands of internal documents. Which service?",
   "o":["Amazon Kendra","Amazon Comprehend","Amazon Lex","Amazon Personalize"],
   "a":[0],
   "x":"Kendra is an intelligent enterprise search service that returns answers rather than a list of keyword matches. Comprehend analyses text but does not search a corpus."},
  {"q":"Product reviews must be classified as positive or negative and have brand names extracted. Which service?",
   "o":["Amazon Comprehend","Amazon Kendra","Amazon Textract","Amazon Polly"],
   "a":[0],
   "x":"Sentiment analysis and entity extraction are Comprehend's core functions. Textract reads documents and Kendra searches them, neither of which produces sentiment."},
  {"q":"A chatbot must understand customer intent and collect the details needed to act. Which service provides the conversational engine?",
   "o":["Amazon Lex","Amazon Connect","Amazon Comprehend","Amazon Personalize"],
   "a":[0],
   "x":"Lex models intents and slots and handles the dialogue. Connect is the contact centre that a Lex bot can sit inside, and the other services do not manage conversation."},
  {"q":"A streaming site wants to suggest titles based on each viewer's history. Which service?",
   "o":["Amazon Personalize","Amazon Comprehend","Amazon Kendra","Amazon Rekognition"],
   "a":[0],
   "x":"Personalize turns interaction history into real-time recommendations through an API, which is exactly a recommendation use case with no custom model to build."}
 ]
},
{
 "id":"sagemaker",
 "nm":"SageMaker, and when to build your own",
 "goal":"Decide between a pre-trained service and a custom model, and name SageMaker's parts.",
 "min":6,
 "blocks":[
  {"t":"p","x":"**SageMaker AI** is the platform for building, training and hosting your own models. On this exam it appears mainly as the answer when no pre-trained service fits."},
  {"t":"table","head":["Stage","What SageMaker provides"],
   "rows":[
    ["Prepare","Notebooks, Data Wrangler, feature storage"],
    ["Train","Managed training jobs, including on Spot instances, with automatic tuning"],
    ["Deploy","Real-time endpoints, **serverless inference**, and batch transform for offline scoring"],
    ["Operate","Model Monitor for drift, and a registry for versions"]]},
  {"t":"key","x":"Choose SageMaker when the task is **specific to your data** — predicting churn for your customers, forecasting your demand. Choose a pre-trained service when the task is general — reading text, detecting objects, translating."},
  {"t":"h","x":"Inference options"},
  {"t":"split","cols":[
   {"nm":"Real-time endpoint","items":["Always on, low latency","Pay while it runs","For interactive predictions"]},
   {"nm":"Serverless inference","items":["Scales to zero","Cold starts possible","For intermittent traffic"]},
   {"nm":"Batch transform","items":["Scores a whole dataset at once","No endpoint to keep running","For offline scoring jobs"]}]},
  {"t":"h","x":"Cost"},
  {"t":"p","x":"Training on **Spot instances** — managed spot training — cuts cost substantially, with checkpointing so an interruption resumes rather than restarts."},
  {"t":"trap","x":"A question that mentions labelled historical data and a prediction specific to the business is pointing at SageMaker. A question that describes a generic perception task is pointing at a pre-trained service."}
 ],
 "checks":[
  {"q":"A company has five years of its own sales data and wants to predict which customers will churn. Which approach fits?",
   "o":["Train a model in SageMaker on the historical data","Use Amazon Comprehend on the customer records",
        "Use Amazon Personalize to recommend products","Use Amazon Kendra to search the records"],
   "a":[0],
   "x":"Churn prediction depends on patterns specific to this business, so no pre-trained service covers it. SageMaker is the platform for training and hosting such a model."},
  {"q":"Predictions are needed only a few times an hour and an always-on endpoint is wasteful. Which inference option fits?",
   "o":["Serverless inference","A real-time endpoint on a large instance","Batch transform on a schedule",
        "Managed spot training"],
   "a":[0],
   "x":"Serverless inference scales to zero between requests, so intermittent traffic costs nothing while idle. Batch transform suits scoring a whole dataset rather than answering individual requests."},
  {"q":"A model must score ten million records overnight with no endpoint kept running. What fits?",
   "o":["Batch transform","A real-time endpoint","Serverless inference","Model Monitor"],
   "a":[0],
   "x":"Batch transform runs a job over a whole dataset and shuts down afterwards, which is the right shape for offline scoring."},
  {"q":"How does managed spot training reduce cost safely?",
   "o":["It uses Spot instances with checkpointing, so an interruption resumes rather than restarts",
        "It trains on a smaller sample of the data","It caches results between runs",
        "It runs only during off-peak hours"],
   "a":[0],
   "x":"Checkpoints are written during training, so when capacity is reclaimed the job continues from the last checkpoint. That is what makes Spot acceptable for long training runs."}
 ]
}
],
"recap":[
 {"t":"h","x":"One sentence each"},
 {"t":"table","head":["Service","Identify it by"],
  "rows":[["Rekognition","Images and video: objects, faces, text, moderation"],
          ["Textract","Documents: forms and tables"],
          ["Transcribe","Speech to text, with redaction"],
          ["Polly","Text to speech"],
          ["Translate","Between languages"],
          ["Comprehend","Sentiment, entities, key phrases"],
          ["Comprehend Medical","Clinical entities and dosages"],
          ["Lex","Chatbot intents and slots"],
          ["Connect","Cloud contact centre"],
          ["Kendra","Enterprise search that answers questions"],
          ["Personalize","Recommendations"],
          ["SageMaker AI","Build, train and host your own model"]]},
 {"t":"key","x":"Pre-trained service for a general perception task; SageMaker for a prediction specific to your own data. That one rule answers most questions in this subject."},
 {"t":"h","x":"The pairs that get confused"},
 {"t":"table","head":["Pair","How to tell them apart"],
  "rows":[["Rekognition and Textract","Picture versus document with forms and tables"],
          ["Transcribe and Polly","Speech to text versus text to speech"],
          ["Comprehend and Kendra","How the text feels versus where the answer is"],
          ["Lex and Connect","The conversation engine versus the contact centre it runs in"],
          ["Personalize and SageMaker","Recommendations out of the box versus any custom prediction"]]},
 {"t":"h","x":"SageMaker inference"},
 {"t":"split","cols":[
  {"nm":"Real-time endpoint","items":["Always on","Interactive predictions","Paid while running"]},
  {"nm":"Serverless inference","items":["Scales to zero","Intermittent traffic","Cold starts possible"]},
  {"nm":"Batch transform","items":["Whole dataset at once","No endpoint","Offline scoring"]}]},
 {"t":"flow","x":["Is the task generic?","Yes: a pre-trained service","No: is it recommendations?","Yes: Personalize","Otherwise: SageMaker"]},
 {"t":"trap","x":"Recurring distractors: SageMaker offered for a task a pre-trained service already solves; Rekognition offered for a scanned form; Comprehend offered where the requirement is search; and a real-time endpoint kept running for a nightly batch job."}
],
"final":[
 {"m":"vision-speech",
  "q":"An insurer receives scanned claim forms as PDFs and must pull out named fields and a table of itemised costs. Which service fits?",
  "o":["Amazon Textract","Amazon Rekognition","Amazon Comprehend","Amazon Transcribe"],
  "a":[0],
  "w":["Correct — Textract extracts text along with form fields and table structure from documents.",
      "Rekognition can detect text in an image but does not reconstruct forms or tables.",
      "Comprehend analyses text that has already been extracted; it cannot read a PDF layout.",
      "Transcribe works on audio, not documents."],
  "x":"The words \"form\" and \"table\" are the Textract signals. Rekognition is for pictures of the world, Textract is for pages of information."},
 {"m":"language-search",
  "q":"Staff must ask questions such as \"how many days of parental leave do I get?\" and receive an answer drawn from internal policy documents. Which service?",
  "o":["Amazon Kendra","Amazon Comprehend","Amazon Lex","Amazon Textract"],
  "a":[0],
  "w":["Correct — Kendra performs natural-language search over a document corpus and returns answers.",
      "Comprehend extracts sentiment and entities; it does not search a corpus.",
      "Lex manages conversation flow but has no index of the documents.",
      "Textract extracts content from documents rather than answering questions about them."],
  "x":"Kendra is the enterprise search answer. A full solution might put Lex in front for conversation, but the component that finds the answer is Kendra."},
 {"m":"sagemaker",
  "q":"A logistics company has years of its own delivery data and wants to predict late shipments. No AWS service offers this prediction off the shelf. What should they use?",
  "o":["Amazon SageMaker AI to train and host a custom model",
       "Amazon Personalize with the shipment history","Amazon Comprehend on the delivery notes","Amazon Forecast is unavailable, so use Amazon Kendra"],
  "a":[0],
  "w":["Correct — a prediction specific to this business's data requires a model trained on that data.",
      "Personalize produces recommendations for users and items, not operational predictions.",
      "Comprehend analyses text and cannot predict delivery outcomes.",
      "Kendra searches documents and has no predictive capability."],
  "x":"The dividing line is whether the task is generic or specific to your data. Late-shipment prediction depends on this company's routes and history, which is SageMaker territory."},
 {"m":"vision-speech",
  "q":"A social platform must block sexually explicit and violent images at upload time, with no training data of its own. What is the least-effort solution?",
  "o":["Call Amazon Rekognition content moderation from a Lambda triggered by the S3 upload",
       "Train an image classifier in SageMaker on public datasets","Use Amazon Textract to read the images","Use Amazon Comprehend on the file names"],
  "a":[0],
  "w":["Correct — moderation is a pre-trained Rekognition capability invoked with a single API call.",
      "Training a classifier duplicates a solved problem and needs data the company does not have.",
      "Textract reads documents and has no notion of unsafe content.",
      "File names say nothing reliable about image content."],
  "x":"Content moderation is one of Rekognition's built-in capabilities, and the S3-event-to-Lambda pattern is the standard way to apply it as uploads arrive."},
 {"m":"language-search",
  "q":"A contact centre wants callers to resolve simple requests by voice before reaching an agent. Which pairing provides this?",
  "o":["Amazon Connect for the contact centre with Amazon Lex for the conversation",
       "Amazon Polly with Amazon Comprehend","Amazon Kendra with Amazon Personalize","Amazon Transcribe with Amazon Translate"],
  "a":[0],
  "w":["Correct — Connect handles the telephony and Lex understands intent and collects the required details.",
      "Polly speaks and Comprehend analyses sentiment; neither manages a dialogue.",
      "Kendra searches and Personalize recommends; neither answers a phone call.",
      "Transcription and translation do not implement self-service flows."],
  "x":"Connect plus Lex is the standard self-service contact centre pattern, with Lambda called to fulfil an intent against backend systems."},
 {"m":"sagemaker",
  "q":"A trained model must score a nightly file of twenty million records, and no endpoint should run during the day. Which deployment option fits?",
  "o":["SageMaker batch transform","A real-time SageMaker endpoint","SageMaker serverless inference","SageMaker Model Monitor"],
  "a":[0],
  "w":["Correct — batch transform processes a whole dataset as a job and then shuts down.",
      "An always-on endpoint is exactly the cost the requirement avoids.",
      "Serverless inference suits sporadic individual requests, not one large bulk job.",
      "Model Monitor detects drift and does not perform scoring."],
  "x":"Batch versus real-time is decided by whether predictions are requested interactively or produced in bulk. Twenty million records overnight is the batch case."},
 {"m":"language-search",
  "q":"A retailer wants to show each shopper items they are likely to buy, based on browsing and purchase history, without building a model. Which service?",
  "o":["Amazon Personalize","Amazon SageMaker AI","Amazon Comprehend","Amazon Kendra"],
  "a":[0],
  "w":["Correct — Personalize takes interaction history and returns recommendations through an API.",
      "SageMaker would work but requires building and operating a model, which the question excludes.",
      "Comprehend analyses text and produces no recommendations.",
      "Kendra searches documents rather than suggesting products."],
  "x":"Recommendations are one of the few business-specific predictions that has a ready-made service. When the question says no model building, Personalize beats SageMaker."},
 {"m":"vision-speech",
  "q":"Recorded customer calls must be searchable as text, with credit card numbers removed automatically. Which service handles this?",
  "o":["Amazon Transcribe with personally identifiable information redaction",
       "Amazon Polly with SSML","Amazon Comprehend Medical","Amazon Rekognition video analysis"],
  "a":[0],
  "w":["Correct — Transcribe converts the audio and can redact sensitive values as part of the transcription.",
      "Polly generates speech rather than transcribing it.",
      "Comprehend Medical extracts clinical entities and is not a transcription service.",
      "Rekognition analyses video frames, not call audio."],
  "x":"Transcribe's built-in redaction is what makes it the specific answer for call recordings, where transcripts routinely contain payment and identity data."},
 {"m":"sagemaker",
  "q":"A long training job costs too much on on-demand instances, and occasional interruption is acceptable. What reduces the cost with least risk?",
  "o":["Managed spot training with checkpointing enabled",
       "Training on a smaller random sample","A serverless inference endpoint","Model Monitor with automatic retraining"],
  "a":[0],
  "w":["Correct — Spot capacity cuts cost sharply, and checkpoints let an interrupted job resume rather than restart.",
      "Sampling changes the model rather than the cost of training it properly.",
      "Inference options do not affect training cost.",
      "Monitoring detects drift and does not reduce training cost."],
  "x":"Managed spot training is the SageMaker equivalent of the general Spot pattern: cheap interruptible capacity made safe by checkpointing progress."},
 {"m":"language-search",
  "q":"A team must analyse thousands of free-text survey responses to find the main topics and overall sentiment. Which service?",
  "o":["Amazon Comprehend","Amazon Kendra","Amazon Lex","Amazon Textract"],
  "a":[0],
  "w":["Correct — Comprehend performs sentiment analysis, entity extraction and topic modelling over text.",
      "Kendra searches a corpus for answers rather than summarising sentiment across it.",
      "Lex handles conversational flow, not bulk text analysis.",
      "Textract extracts text from documents; the responses are already text."],
  "x":"Comprehend is the text analytics service: sentiment, entities, key phrases and topics. Kendra is the search service — the distinction is what the output looks like."}
]
}
