# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 16,
"nm": "Monitoring and audit",
"tag": "Operations",
"modules": [
{
 "id": "cloudwatch-metrics",
 "nm": "CloudWatch metrics and alarms",
 "goal": "Know which metrics exist by default, publish the ones that do not, and alarm correctly.",
 "min": 7,
 "blocks": [
  {"t":"p","x":"**CloudWatch metrics** are time-ordered numbers about a resource. Most AWS services publish them automatically, but only what the hypervisor or the service itself can see."},
  {"t":"key","x":"**Memory usage and disk space on EC2 are not default metrics.** They are inside the guest operating system, so the **CloudWatch agent** must be installed to publish them as custom metrics. This is one of the most frequently tested facts in the subject."},
  {"t":"table","head":["Concept","Detail"],
   "rows":[
    ["Default resolution","5 minutes; **detailed monitoring** gives 1 minute for EC2"],
    ["High resolution","Custom metrics can be published at 1 second"],
    ["Namespace","Groups metrics, such as `AWS/EC2` or your own"],
    ["Dimensions","Name-value pairs that identify which resource a datapoint belongs to"],
    ["Retention","Kept for 15 months, aggregated as they age"]]},
  {"t":"h","x":"Alarms"},
  {"t":"list","x":[
   "An alarm watches one metric, or a **metric math** expression, against a threshold for a number of periods.",
   "States are **OK**, **ALARM** and **INSUFFICIENT_DATA**.",
   "Actions: notify through SNS, trigger Auto Scaling, or **recover or stop an EC2 instance**.",
   "A **composite alarm** combines several alarms so one underlying fault raises one notification instead of twenty."]},
  {"t":"flow","x":["Metric crosses the threshold","Alarm enters ALARM after the evaluation periods","SNS notifies, or a scaling policy runs"]},
  {"t":"trap","x":"An alarm sitting in INSUFFICIENT_DATA usually means the metric is not being published at all — often because the agent was never installed, or the resource is idle and emits nothing."}
 ],
 "checks":[
  {"q":"An alarm is needed on EC2 memory usage. What must be done first?",
   "o":["Install the CloudWatch agent to publish memory as a custom metric",
        "Enable detailed monitoring","Create a composite alarm","Turn on EC2 instance recovery"],
   "a":[0],
   "x":"Memory is visible only inside the guest operating system, so it is not a default metric. The agent publishes it as a custom metric, after which an alarm can watch it."},
  {"q":"What does enabling detailed monitoring on EC2 change?",
   "o":["Metrics arrive every minute instead of every five",
        "Memory and disk metrics become available","Logs are sent to CloudWatch",
        "Alarms evaluate twice as fast for free"],
   "a":[0],
   "x":"Detailed monitoring increases the publishing frequency to one minute. It does not add guest-level metrics, which still require the agent."},
  {"q":"An alarm is stuck in INSUFFICIENT_DATA. What is the most likely cause?",
   "o":["No datapoints are being published for that metric","The threshold is set too high",
        "The alarm has too many evaluation periods","The SNS topic has no subscribers"],
   "a":[0],
   "x":"That state means CloudWatch has nothing to evaluate. Either the metric is not being published, or the resource is idle and emitting nothing in that period."},
  {"q":"Twenty alarms all fire from one underlying failure, flooding the on-call channel. What reduces the noise?",
   "o":["A composite alarm combining them","Raising every threshold",
        "Deleting the SNS topic","Switching to high-resolution metrics"],
   "a":[0],
   "x":"A composite alarm expresses a rule over several alarms so one notification is produced for one root cause, rather than one per symptom."}
 ]
},
{
 "id":"logs",
 "nm":"CloudWatch Logs",
 "goal":"Get logs into CloudWatch, search them, and turn a log pattern into a metric.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Concept","Meaning"],
   "rows":[
    ["**Log group**","One application or resource; retention is set here, from 1 day to forever"],
    ["**Log stream**","One source inside a group, typically one instance or one container"],
    ["**Metric filter**","Turns a pattern in the logs into a **metric** you can alarm on"],
    ["**Subscription filter**","Streams matching log events to Lambda, Firehose or OpenSearch in real time"],
    ["**Logs Insights**","A query language for searching and aggregating log data"],
    ["**Live Tail**","Watches log events as they arrive"]]},
  {"t":"key","x":"To alarm on something that appears in a log — a specific error message, a failed login — create a **metric filter** and then alarm on the metric it produces. There is no way to alarm on raw text directly."},
  {"t":"h","x":"Getting logs in"},
  {"t":"list","x":[
   "EC2 and on-premises servers need the **CloudWatch agent**; nothing is collected from inside the OS by default.",
   "Lambda writes to CloudWatch Logs automatically, provided its execution role allows it.",
   "ECS and EKS use the `awslogs` or FireLens log drivers.",
   "VPC Flow Logs, Route 53 query logs and many other services can deliver logs here or to S3."]},
  {"t":"h","x":"Getting logs out"},
  {"t":"flow","x":["Log group","Subscription filter","Firehose","S3 or OpenSearch"],
   "cap":"The usual route for long-term retention and full-text search."},
  {"t":"trap","x":"Retention defaults to **never expire** on a new log group, which is a quiet and steadily growing cost. Setting retention is a standard cost-optimisation answer."}
 ],
 "checks":[
  {"q":"An alarm must fire when a specific error string appears in an application log. What is required?",
   "o":["A metric filter on the log group, then an alarm on the resulting metric",
        "An alarm directly on the log group","A subscription filter to SNS",
        "Logs Insights running on a schedule"],
   "a":[0],
   "x":"Alarms watch metrics, not text. A metric filter counts occurrences of the pattern and publishes a metric that an alarm can then evaluate."},
  {"q":"Logs must be streamed to OpenSearch as they arrive. What provides that?",
   "o":["A subscription filter on the log group","A metric filter","A longer retention period",
        "Live Tail"],
   "a":[0],
   "x":"Subscription filters deliver matching log events in near real time to Lambda, Firehose or OpenSearch, which is the standard path for search and dashboards."},
  {"q":"Why do EC2 instances send no application logs to CloudWatch by default?",
   "o":["The CloudWatch agent must be installed and configured","Log groups must be created manually first",
        "Detailed monitoring is disabled","The instance needs a public IP"],
   "a":[0],
   "x":"Nothing inside the guest operating system is visible to AWS, so an agent is required to read log files and ship them, with an instance role granting permission."},
  {"q":"A log group has been growing for two years and storage costs are rising. What is the usual fix?",
   "o":["Set a retention period on the log group","Delete the log streams manually each month",
        "Switch to high-resolution metrics","Enable Live Tail"],
   "a":[0],
   "x":"New log groups never expire by default. Setting a retention period, and exporting anything that must be kept to S3, is the standard remedy."}
 ]
},
{
 "id":"trail-config",
 "nm":"CloudTrail and AWS Config",
 "goal":"Say precisely which service answers who did what, and which answers what changed.",
 "min":7,
 "blocks":[
  {"t":"split","cols":[
   {"nm":"CloudTrail","items":["**Who called which API, when, from where**","Management events on by default, 90 days of history in the console","**Data events** — S3 object level, Lambda invocations — are off by default and charged","A trail delivers to S3 for long retention"]},
   {"nm":"AWS Config","items":["**What is the configuration, and how did it change**","Records resource state over time","**Rules** evaluate compliance, with optional auto-remediation","Answers \"was this bucket ever public?\""]}]},
  {"t":"key","x":"**CloudTrail is the who. Config is the what.** \"Who deleted the bucket?\" is CloudTrail. \"Which buckets are public, and were they always?\" is Config."},
  {"t":"h","x":"CloudTrail details that get tested"},
  {"t":"list","x":[
   "An **organization trail** captures every account in the organisation into one bucket.",
   "**Log file validation** proves the logs have not been tampered with.",
   "Logs can also go to **CloudWatch Logs**, so a metric filter can alarm on a specific API call.",
   "**CloudTrail Lake** stores and queries events without building a pipeline."]},
  {"t":"h","x":"Config details that get tested"},
  {"t":"list","x":[
   "**Managed rules** cover common checks; **custom rules** run a Lambda function.",
   "**Conformance packs** group rules into a standard that can be deployed across accounts.",
   "**Remediation actions** can fix a non-compliant resource automatically through Systems Manager.",
   "Config is **regional**, so it must be enabled per region you care about."]},
  {"t":"flow","x":["An API call happens","CloudTrail records who made it","Config records the resulting configuration","A Config rule evaluates compliance","EventBridge reacts"]},
  {"t":"trap","x":"S3 **data events are not recorded by default**. A question asking who read or deleted a specific object needs data events enabled on the trail, which is a separate and charged setting."}
 ],
 "checks":[
  {"q":"An investigation must determine which identity deleted a security group, when, and from which source address. Which service?",
   "o":["CloudTrail","AWS Config","CloudWatch Logs Insights","Amazon Inspector"],
   "a":[0],
   "x":"CloudTrail records each API call with the identity that made it, the time and the source address. Config would show that the resource configuration changed but not who called the API."},
  {"q":"A compliance team must show that no S3 bucket has been publicly readable at any point in the past six months. Which service?",
   "o":["AWS Config with a managed rule and its configuration history",
        "CloudTrail management events","CloudWatch alarms","AWS Trusted Advisor"],
   "a":[0],
   "x":"Config records configuration state over time and evaluates rules against it, which is what produces a compliance history. CloudTrail shows the calls, not the resulting state at every moment."},
  {"q":"Why does a trail show no record of who downloaded a particular S3 object?",
   "o":["S3 data events are not logged by default and must be enabled",
        "CloudTrail does not support S3","The object was encrypted",
        "The bucket had no lifecycle policy"],
   "a":[0],
   "x":"Management events are captured by default but object-level data events are opt-in and charged separately, precisely because their volume can be enormous."},
  {"q":"A non-compliant resource should be corrected automatically as soon as Config detects it. What provides that?",
   "o":["A Config remediation action through Systems Manager","A CloudWatch composite alarm",
        "A CloudTrail organization trail","A metric filter"],
   "a":[0],
   "x":"Config rules can attach remediation actions that run an SSM Automation document, which is how drift is corrected without human intervention."}
 ]
},
{
 "id":"eventbridge",
 "nm":"EventBridge and putting it together",
 "goal":"React to an event, run something on a schedule, and pick the right observability tool.",
 "min":6,
 "blocks":[
  {"t":"p","x":"**EventBridge** is the event bus. AWS services publish events to it, your applications can publish their own, and rules match events and send them to targets."},
  {"t":"table","head":["Capability","Use"],
   "rows":[
    ["**Rules on a pattern**","React to an EC2 state change, a Config finding, a GuardDuty finding, an S3 event"],
    ["**Scheduled rules**","Cron-style scheduling, which replaces a server whose only job was running cron"],
    ["**Custom buses**","Separate application events from AWS ones"],
    ["**Schema registry**","Discovers and documents event structures"],
    ["**Archive and replay**","Store events and replay them later — useful after fixing a consumer"],
    ["**Partner event sources**","Events from SaaS providers"]]},
  {"t":"key","x":"\"Run something every night\" or \"react automatically when X happens\" is **EventBridge**. Its scheduled rules are the standard answer for replacing a cron server."},
  {"t":"h","x":"The other observability services"},
  {"t":"table","head":["Service","Answers"],
   "rows":[
    ["**X-Ray**","Where is the latency in this distributed request? It traces a call across services"],
    ["**CloudWatch Synthetics**","Is the site working from outside, right now? Canaries run scripted checks"],
    ["**CloudWatch RUM**","What are real users experiencing in their browsers?"],
    ["**Container Insights** and **Lambda Insights**","Curated metrics for containers and functions"],
    ["**Trusted Advisor**","Checks on cost, security, limits and fault tolerance across the account"]]},
  {"t":"trap","x":"A slow request across microservices is an **X-Ray** question. CloudWatch tells you a service is slow; X-Ray tells you which hop in the chain is responsible."}
 ],
 "checks":[
  {"q":"A job must run at 02:00 every day with no server dedicated to scheduling it. What fits?",
   "o":["An EventBridge scheduled rule invoking Lambda","A CloudWatch alarm on a timer metric",
        "A Config rule with remediation","An X-Ray sampling rule"],
   "a":[0],
   "x":"EventBridge scheduled rules provide cron-style scheduling and can invoke Lambda, Step Functions or other targets directly, which removes the need for a cron server."},
  {"q":"A request passing through five microservices is intermittently slow. Which service identifies the slow hop?",
   "o":["AWS X-Ray","CloudWatch alarms","AWS Config","Amazon Inspector"],
   "a":[0],
   "x":"X-Ray traces a single request across services and shows the time spent in each segment, which is what locates the bottleneck in a distributed call."},
  {"q":"A team must be alerted when a checkout flow breaks from an end user's perspective, even with no traffic. What provides this?",
   "o":["A CloudWatch Synthetics canary running the flow on a schedule",
        "A metric filter on the application logs","A Config conformance pack","An EventBridge archive"],
   "a":[0],
   "x":"Canaries execute a scripted user journey from outside on a schedule, so a broken flow is detected even when no real users are on the site."},
  {"q":"An automated response must run whenever GuardDuty reports a finding. What connects them?",
   "o":["An EventBridge rule matching the finding and invoking a target",
        "A CloudWatch metric filter","A CloudTrail data event","An S3 lifecycle rule"],
   "a":[0],
   "x":"GuardDuty publishes findings as events, and an EventBridge rule can match them and invoke Lambda, Step Functions or SNS — the standard automated-response pattern."}
 ]
}
],
"recap":[
 {"t":"h","x":"The three that get confused"},
 {"t":"table","head":["Question","Service"],
  "rows":[["Who made this API call?","CloudTrail"],
          ["What does this resource look like, and did it change?","AWS Config"],
          ["How is this resource performing right now?","CloudWatch"],
          ["Where is the time going in this request?","X-Ray"],
          ["Does the site work from outside?","CloudWatch Synthetics"]]},
 {"t":"key","x":"Memory and disk on EC2 need the CloudWatch agent. S3 object-level access needs CloudTrail data events. Both are off by default, and both are used repeatedly to make an option wrong."},
 {"t":"h","x":"From a log line to an alarm"},
 {"t":"flow","x":["Agent ships the log","Log group","Metric filter counts the pattern","Metric","Alarm","SNS"]},
 {"t":"h","x":"Defaults worth remembering"},
 {"t":"table","head":["Setting","Default"],
  "rows":[["EC2 metric resolution","5 minutes, or 1 minute with detailed monitoring"],
          ["Metric retention","15 months, aggregated as it ages"],
          ["Log group retention","Never expires — set it"],
          ["CloudTrail management events","On, 90 days visible in the console"],
          ["CloudTrail data events","Off, and charged when enabled"],
          ["AWS Config","Off, and enabled per region"]]},
 {"t":"h","x":"EventBridge, the connective tissue"},
 {"t":"split","cols":[
  {"nm":"React","items":["Match a pattern from any AWS service","Invoke Lambda, Step Functions, SNS or SQS","Archive and replay events"]},
  {"nm":"Schedule","items":["Cron-style rules","Replaces a server whose only job was cron","Targets the same set of services"]}]},
 {"t":"trap","x":"Recurring distractors: an alarm on memory without the agent; CloudTrail expected to show object reads without data events; Config and CloudTrail used interchangeably; and CloudWatch offered where the question needs a distributed trace."}
],
"final":[
 {"m":"cloudwatch-metrics",
  "q":"An operations team wants an alarm when an EC2 instance's free disk space falls below 10%. What must be in place first?",
  "o":["The CloudWatch agent, publishing disk metrics as custom metrics",
       "Detailed monitoring enabled on the instance","A composite alarm across the fleet","An EventBridge scheduled rule"],
  "a":[0],
  "w":["Correct — disk and memory are inside the guest operating system, so only an agent can publish them.",
      "Detailed monitoring increases the frequency of existing metrics; it adds no new ones.",
      "A composite alarm combines alarms that already exist.",
      "Scheduling does not create the missing metric."],
  "x":"The hypervisor cannot see inside the instance, so memory and disk are never default metrics. Installing the agent, with an instance role permitting PutMetricData, is the prerequisite."},
 {"m":"trail-config",
  "q":"An auditor asks which IAM user terminated a production instance and from which IP address. Where is that recorded?",
  "o":["CloudTrail event history and the trail in S3",
       "AWS Config configuration history","CloudWatch Logs Insights","VPC Flow Logs"],
  "a":[0],
  "w":["Correct — CloudTrail records the identity, the API call, the time and the source IP.",
      "Config shows that the instance disappeared but not who made the call.",
      "Logs Insights searches application logs, which do not contain AWS API calls.",
      "Flow Logs record network traffic, not API activity."],
  "x":"CloudTrail is the audit trail of API activity. Config is the record of resource state — the two answer different halves of an investigation and are frequently confused."},
 {"m":"logs",
  "q":"Security wants an alert whenever the string \"AuthenticationFailure\" appears more than ten times in five minutes in an application log. What should be configured?",
  "o":["A metric filter on the log group and a CloudWatch alarm on its metric",
       "A subscription filter delivering to SNS","A Config rule matching the string","An X-Ray sampling rule"],
  "a":[0],
  "w":["Correct — the filter turns matching log lines into a metric, and the alarm applies the threshold and period.",
      "Subscription filters stream events but do not evaluate thresholds.",
      "Config evaluates resource configuration, not log content.",
      "X-Ray traces requests and does not inspect log text."],
  "x":"Alarms only ever evaluate metrics, so anything in a log must first become a metric. Metric filters are the bridge, and they support counting occurrences of a pattern."},
 {"m":"eventbridge",
  "q":"A nightly cleanup script runs on a small EC2 instance whose only purpose is cron. How should this be replaced?",
  "o":["An EventBridge scheduled rule invoking a Lambda function",
       "A CloudWatch alarm scheduled for 02:00","An Auto Scaling scheduled action","An AWS Config rule with remediation"],
  "a":[0],
  "w":["Correct — scheduled rules provide cron semantics and invoke Lambda directly, removing the instance.",
      "Alarms respond to metrics; they have no schedule of their own.",
      "Scheduled scaling changes capacity rather than running a task.",
      "Config rules evaluate compliance and are not a general scheduler."],
  "x":"Replacing a cron server with an EventBridge schedule and Lambda is one of the standard serverless simplifications, provided the task fits within Lambda's limits."},
 {"m":"trail-config",
  "q":"A team must prove that every EBS volume in the account has been encrypted continuously for the last year, and be alerted if one is not. What provides this?",
  "o":["AWS Config with a managed rule and its configuration history",
       "CloudTrail with log file validation","CloudWatch metric filters on the EC2 log group","Trusted Advisor checks"],
  "a":[0],
  "w":["Correct — Config records configuration over time and continuously evaluates rules against it.",
      "CloudTrail records the API calls but does not evaluate ongoing compliance state.",
      "Metric filters read log text and know nothing about volume configuration.",
      "Trusted Advisor gives point-in-time checks without a full configuration history."],
  "x":"Continuous compliance with a historical record is Config's defining capability, and remediation actions can additionally fix violations automatically."},
 {"m":"eventbridge",
  "q":"A customer-facing API intermittently takes several seconds, and the team cannot tell which downstream service is responsible. What should be added?",
  "o":["AWS X-Ray tracing across the services",
       "A CloudWatch dashboard of each service's CPU","A Config conformance pack","CloudWatch Synthetics canaries"],
  "a":[0],
  "w":["Correct — X-Ray traces a single request end to end and shows the latency of each segment.",
      "Per-service metrics show symptoms without attributing a slow request to a hop.",
      "Conformance packs assess compliance, not latency.",
      "Canaries detect outside failures but do not break a request into segments."],
  "x":"Distributed tracing is the tool for \"which hop is slow\". Metrics tell you that something is slow; traces tell you where the time went within one request."},
 {"m":"cloudwatch-metrics",
  "q":"During an incident, twenty alarms fire simultaneously from a single database failure and the on-call channel becomes unusable. What is the appropriate change?",
  "o":["Create a composite alarm so one notification represents the underlying fault",
       "Raise every alarm threshold to reduce sensitivity","Move the alarms to a different SNS topic","Switch the metrics to high resolution"],
  "a":[0],
  "w":["Correct — composite alarms express a rule over other alarms and notify once for a root cause.",
      "Raising thresholds hides real problems rather than organising the signal.",
      "Changing topics moves the noise without reducing it.",
      "Higher resolution produces more datapoints and, if anything, more alarms."],
  "x":"Composite alarms exist for exactly this: suppressing symptom alarms while still surfacing the failure, so that alerting stays actionable during an incident."},
 {"m":"logs",
  "q":"A team discovers that log storage costs have grown steadily since the account was created three years ago. What is the most likely cause and fix?",
  "o":["Log groups default to never expiring; set retention periods and export what must be kept to S3",
       "Detailed monitoring was left enabled; disable it","Metric filters are duplicating the logs; remove them","Live Tail sessions are being billed; close them"],
  "a":[0],
  "w":["Correct — new log groups retain data indefinitely unless a retention period is configured.",
      "Detailed monitoring affects metric frequency and is not the source of log storage cost.",
      "Metric filters read logs; they do not store additional copies.",
      "Live Tail is a live view and does not accumulate storage."],
  "x":"Unbounded log retention is a quiet, compounding cost. Setting per-group retention, with an export to S3 and lifecycle rules for anything that must be kept, is the standard remedy."},
 {"m":"trail-config",
  "q":"An organisation with forty accounts must collect API activity from all of them into one place, with proof the records have not been altered. What should be configured?",
  "o":["An organization trail in CloudTrail with log file validation enabled, delivering to a central S3 bucket",
       "AWS Config aggregators in each account","A CloudWatch cross-account dashboard","GuardDuty in the management account"],
  "a":[0],
  "w":["Correct — an organization trail captures every member account, and log file validation proves integrity.",
      "Config aggregates configuration state, not API activity.",
      "Dashboards visualise metrics and do not collect audit records.",
      "GuardDuty detects threats but is not an audit log."],
  "x":"Organization trails plus log file validation is the standard multi-account audit design, usually paired with a locked-down central logging account."},
 {"m":"eventbridge",
  "q":"A business requires notification within minutes if the public checkout page stops working, including overnight when there is little traffic. What detects this?",
  "o":["A CloudWatch Synthetics canary running the checkout journey on a schedule",
       "A CloudWatch alarm on ALB request count","A metric filter on the web server logs","An EventBridge rule on EC2 state changes"],
  "a":[0],
  "w":["Correct — a canary exercises the journey from outside on a fixed schedule regardless of real traffic.",
      "Request count alarms cannot distinguish a quiet night from an outage.",
      "Log-based detection requires traffic to generate the logs.",
      "Instance state changes say nothing about whether the checkout flow works."],
  "x":"Synthetic monitoring is the answer whenever detection must not depend on real user traffic, which is exactly the overnight low-traffic case."}
]
}
