# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 17,
"nm": "IAM advanced: Organizations, Identity Center, STS",
"tag": "Identity",
"modules": [
{
 "id": "organizations",
 "nm": "Organizations and service control policies",
 "goal": "Structure many accounts and apply a permission ceiling that cannot be escaped.",
 "min": 7,
 "blocks": [
  {"t":"p","x":"**AWS Organizations** groups accounts under one management account, with **organizational units** (OUs) for structure. It gives consolidated billing, shared discounts, and the ability to apply policies across accounts."},
  {"t":"table","head":["Feature","What it does"],
   "rows":[
    ["Consolidated billing","One bill; Reserved Instances and Savings Plans are shared across accounts"],
    ["Organizational units","A tree of accounts, so policies apply to a group"],
    ["**Service control policies**","A **maximum permission** boundary for member accounts"],
    ["Tag policies","Enforce consistent tag keys and values"],
    ["Backup policies","Apply AWS Backup plans organisation-wide"],
    ["Account creation API","New accounts created programmatically, already in the right OU"]]},
  {"t":"key","x":"An **SCP never grants anything**. It only sets a ceiling on what identities in member accounts may be allowed. A user still needs an IAM policy granting the action, and the SCP must not deny it."},
  {"t":"h","x":"How an SCP is evaluated"},
  {"t":"flow","x":["SCP allows the action?","IAM policy allows it?","No explicit Deny anywhere?","Allowed"],
   "cap":"All three must hold. Fail any one and the call is denied."},
  {"t":"list","x":[
   "SCPs **do not apply to the management account** — a reason to keep it empty of workloads.",
   "They do not apply to service-linked roles.",
   "A common pattern is an allow-list SCP on a sandbox OU restricting which regions and services may be used."]},
  {"t":"h","x":"Control Tower"},
  {"t":"p","x":"**Control Tower** builds a multi-account landing zone for you: an organisation, a log archive account, an audit account, and **guardrails** that are SCPs and Config rules under the covers."},
  {"t":"trap","x":"\"Prevent anyone, including administrators, from using a region\" is an SCP. A permissions boundary constrains one identity; an SCP constrains a whole account or OU."}
 ],
 "checks":[
  {"q":"What does a service control policy do?",
   "o":["Sets the maximum permissions available in member accounts, granting nothing itself",
        "Grants permissions to users in member accounts","Replaces IAM policies entirely",
        "Applies only to the management account"],
   "a":[0],
   "x":"An SCP is a ceiling. Identities still need IAM policies granting the actions, and anything the SCP does not allow cannot be used no matter what those policies say."},
  {"q":"An organisation must prevent all member accounts from creating resources outside two regions. What enforces this?",
   "o":["A service control policy on the root or the relevant OUs","An IAM policy on each user",
        "A permissions boundary on each role","A Config rule with remediation"],
   "a":[0],
   "x":"SCPs apply to whole accounts, so no identity within them can exceed the ceiling. Per-user policies and boundaries would have to be applied and maintained everywhere and could be changed locally."},
  {"q":"Which account is not affected by service control policies?",
   "o":["The management account","The log archive account","Any account in a nested OU",
        "The audit account"],
   "a":[0],
   "x":"SCPs never restrict the management account, which is why workloads should not run there and its use should be tightly controlled."},
  {"q":"What does AWS Control Tower provide?",
   "o":["A landing zone with an organisation, logging and audit accounts, and guardrails",
        "A replacement for IAM roles","A single-account security scanner",
        "A billing dashboard only"],
   "a":[0],
   "x":"Control Tower sets up a multi-account baseline and applies guardrails implemented as SCPs and Config rules, which is the fast path to a governed landing zone."}
 ]
},
{
 "id":"identity-center",
 "nm":"Identity Center, federation and Directory Service",
 "goal":"Give workforce users access across accounts without creating users in each one.",
 "min":7,
 "blocks":[
  {"t":"p","x":"**IAM Identity Center** is the front door for people. Users come from its own directory, from Active Directory, or from an external identity provider, and are assigned **permission sets** in accounts."},
  {"t":"flow","x":["User signs in once","Identity Center portal","Assigned permission set","A role is assumed in the target account"],
   "cap":"No IAM user is created in any account."},
  {"t":"key","x":"**Employees across many accounts → Identity Center. Customers of your application → Cognito.** That distinction is worth more marks than any other fact in this subject."},
  {"t":"h","x":"Federation without Identity Center"},
  {"t":"table","head":["Mechanism","Use"],
   "rows":[
    ["**SAML 2.0 federation**","An enterprise identity provider assumes IAM roles directly"],
    ["**OIDC federation**","A CI system or a Kubernetes cluster assumes a role with **no stored keys**"],
    ["**Cross-account roles**","One account's principals assume a role in another"]]},
  {"t":"h","x":"Directory Service"},
  {"t":"table","head":["Option","Fits"],
   "rows":[
    ["**AWS Managed Microsoft AD**","A real managed Active Directory in AWS, with a trust to on-premises if needed"],
    ["**AD Connector**","A proxy — authentication still happens on premises, nothing is stored in AWS"],
    ["**Simple AD**","A small, low-cost directory for basic needs, not a full Active Directory"]]},
  {"t":"trap","x":"**AD Connector stores no users in AWS** — it forwards authentication on premises. If a question requires directory objects to remain on premises, that is the answer, not Managed Microsoft AD."}
 ],
 "checks":[
  {"q":"Two hundred employees need access to twenty AWS accounts with centrally managed permissions. What fits?",
   "o":["IAM Identity Center with permission sets assigned to groups",
        "An IAM user per employee per account","A shared role with a shared password",
        "Cognito user pools federated into each account"],
   "a":[0],
   "x":"Identity Center assigns permission sets centrally and users assume roles per account, so there are no per-account users to create or offboard. Cognito is for application end users."},
  {"q":"A CI pipeline outside AWS must obtain credentials without any stored access keys. What mechanism?",
   "o":["OIDC federation assuming an IAM role","An IAM user with rotated keys",
        "A shared access key in the pipeline's secret store","The root account's keys"],
   "a":[0],
   "x":"OIDC federation lets the pipeline present a signed token and assume a role, so no long-lived credential exists to leak or rotate."},
  {"q":"A company must keep all directory objects on premises while allowing AWS applications to authenticate against it. Which option?",
   "o":["AD Connector","AWS Managed Microsoft AD","Simple AD","An IAM user per employee"],
   "a":[0],
   "x":"AD Connector proxies authentication requests to the on-premises directory and stores nothing in AWS, which is exactly the stated constraint."},
  {"q":"What does a permission set define in Identity Center?",
   "o":["The permissions a user receives when they access a particular account",
        "The user's password policy","Which region the user may sign in from",
        "The billing allocation for a team"],
   "a":[0],
   "x":"A permission set becomes an IAM role in each assigned account, so one definition can be applied consistently across the organisation."}
 ]
},
{
 "id":"policy-evaluation",
 "nm":"Advanced policies and evaluation",
 "goal":"Work out the effective permissions when several policy types apply at once.",
 "min":8,
 "blocks":[
  {"t":"table","head":["Policy type","Grants?","Applies to"],
   "rows":[
    ["Identity-based","Yes","A user, group or role"],
    ["Resource-based","Yes","A bucket, queue, key, topic — and can name external principals"],
    ["**Permissions boundary**","**No — a ceiling**","One user or role"],
    ["**Service control policy**","**No — a ceiling**","An account or OU"],
    ["Session policy","No — a ceiling","One assumed-role session"]]},
  {"t":"key","x":"Effective permission is the **intersection** of every ceiling with the union of every grant, and an explicit Deny anywhere wins outright. Two of the five types can only take away."},
  {"t":"h","x":"The order to reason in"},
  {"t":"steps","x":[
   "Is there an explicit **Deny** anywhere? If so, denied — stop.",
   "Does an **SCP** allow the action for this account? If not, denied.",
   "Does a **permissions boundary** allow it for this identity? If not, denied.",
   "Does an **identity or resource policy** allow it? If not, denied.",
   "Otherwise, allowed."]},
  {"t":"h","x":"A worked example"},
  {"t":"table","head":["Policy in play","What it says"],
   "rows":[
    ["Identity policy on the role","Allow every S3 and DynamoDB action"],
    ["Permissions boundary on the role","Allow DynamoDB only"],
    ["SCP on the account","Deny DynamoDB writes in this region"],
    ["**Effective permission**","**DynamoDB reads only** — S3 falls outside the boundary, and writes are denied outright"]]},
  {"t":"h","x":"Conditions worth knowing"},
  {"t":"table","head":["Condition key","Use"],
   "rows":[
    ["`aws:MultiFactorAuthPresent`","Require MFA for sensitive actions"],
    ["`aws:SourceIp`","Restrict to an address range — careful, it breaks for calls through AWS services"],
    ["`aws:SourceVpce` / `aws:SourceVpc`","Restrict access to a specific VPC endpoint or VPC"],
    ["`aws:PrincipalOrgID`","Allow only principals from your organisation"],
    ["`aws:RequestedRegion`","Restrict which regions may be used"],
    ["`aws:ResourceTag` / `aws:PrincipalTag`","Attribute-based access control"]]},
  {"t":"h","x":"Attribute-based access control"},
  {"t":"p","x":"**ABAC** grants access by comparing tags rather than listing resources: a policy saying \"allow if the resource's `Project` tag equals the principal's `Project` tag\" scales to any number of projects without new policies."},
  {"t":"trap","x":"A permissions boundary and an SCP both look like restrictions and are often swapped. The boundary applies to **one identity**; the SCP applies to **a whole account or OU** and cannot be removed from inside it."}
 ],
 "checks":[
  {"q":"A role's identity policy allows every S3 action, but its permissions boundary allows only DynamoDB. What can the role do in S3?",
   "o":["Nothing — effective permissions are the intersection","Everything, since the identity policy is more specific",
        "Read but not write","Everything, but only from the console"],
   "a":[0],
   "x":"A boundary is a ceiling, so effective permission is the overlap between it and the identity policy. With no overlap in S3 there is no access at all."},
  {"q":"Which difference separates a permissions boundary from a service control policy?",
   "o":["A boundary applies to one identity; an SCP applies to a whole account or OU",
        "A boundary grants permissions; an SCP does not","An SCP applies to one identity; a boundary applies to an account",
        "They are two names for the same mechanism"],
   "a":[0],
   "x":"Both are ceilings that grant nothing, but they operate at different scopes. Only the SCP constrains every identity in an account, including administrators."},
  {"q":"Access should be granted where a resource's Project tag matches the principal's Project tag. What is this approach called?",
   "o":["Attribute-based access control","A service control policy","A permissions boundary",
        "A resource-based policy"],
   "a":[0],
   "x":"ABAC compares tags in a policy condition, which means one policy serves any number of projects without being rewritten as resources are added."},
  {"q":"Which condition key restricts access to principals belonging to your own organisation?",
   "o":["aws:PrincipalOrgID","aws:SourceIp","aws:RequestedRegion","aws:MultiFactorAuthPresent"],
   "a":[0],
   "x":"PrincipalOrgID matches the organisation the calling principal belongs to, which is the cleanest way to share a resource internally without listing account numbers."}
 ]
},
{
 "id":"sts-patterns",
 "nm":"STS in practice",
 "goal":"Use temporary credentials correctly, including external access and revocation.",
 "min":6,
 "blocks":[
  {"t":"table","head":["STS operation","Use"],
   "rows":[
    ["`AssumeRole`","Cross-account access, or elevating within an account"],
    ["`AssumeRoleWithSAML`","A user authenticated by an enterprise identity provider"],
    ["`AssumeRoleWithWebIdentity`","A user or workload authenticated by an OIDC provider"],
    ["`GetSessionToken`","MFA-backed temporary credentials for an IAM user"],
    ["`GetFederationToken`","Credentials for a federated user from a long-term identity"]]},
  {"t":"h","x":"The external ID"},
  {"t":"p","x":"When a **third party** assumes a role in your account, the trust policy should require an **external ID** they alone know. It prevents the *confused deputy* problem, where another of that vendor's customers tricks them into acting on your account."},
  {"t":"key","x":"Third-party vendor access → a cross-account role **with an external ID** in the trust policy. It is the specific control the exam expects here."},
  {"t":"h","x":"Revoking a session"},
  {"t":"list","x":[
   "Temporary credentials cannot be deleted, so you cannot recall them directly.",
   "Add a policy statement denying all actions when `aws:TokenIssueTime` is **before now** — this invalidates every existing session immediately.",
   "Future assumptions get fresh credentials and are unaffected."]},
  {"t":"flow","x":["Credentials leaked","Add a deny on TokenIssueTime before now","All existing sessions stop working","New sessions continue normally"]},
  {"t":"trap","x":"Deleting the role or detaching its policies to stop a leaked session also breaks everything legitimate that uses it. The token-issue-time deny is the surgical option."}
 ],
 "checks":[
  {"q":"A third-party monitoring vendor will assume a role in your account. What should the trust policy require?",
   "o":["An external ID that only that vendor knows","The vendor's public IP address",
        "MFA from the vendor's employees","A shared access key"],
   "a":[0],
   "x":"The external ID defeats the confused deputy problem, where another customer of the same vendor could otherwise cause them to act against your account."},
  {"q":"Temporary credentials for a role have leaked. How do you invalidate existing sessions without breaking the role?",
   "o":["Attach a policy denying all actions when the token was issued before now",
        "Delete the role","Rotate the account's root access keys",
        "Change the role's name"],
   "a":[0],
   "x":"A condition on aws:TokenIssueTime cuts off every session issued before the cut-off while leaving new assumptions working, which is why it is the surgical remedy."},
  {"q":"Which STS operation is used by a workload authenticated through an OIDC provider?",
   "o":["AssumeRoleWithWebIdentity","AssumeRoleWithSAML","GetSessionToken","GetFederationToken"],
   "a":[0],
   "x":"Web identity federation covers OIDC providers, which is how CI systems and Kubernetes workloads obtain role credentials without stored keys."},
  {"q":"Which operation gives an IAM user MFA-backed temporary credentials?",
   "o":["GetSessionToken","AssumeRoleWithSAML","AssumeRoleWithWebIdentity","GetFederationToken"],
   "a":[0],
   "x":"GetSessionToken issues temporary credentials that carry the MFA flag, which is what makes a policy condition requiring MFA satisfiable from the CLI."}
 ]
}
],
"recap":[
 {"t":"h","x":"Ceilings and grants"},
 {"t":"table","head":["Policy","Grants","Scope"],
  "rows":[["Identity-based","Yes","One user, group or role"],
          ["Resource-based","Yes","One resource, can name external principals"],
          ["Permissions boundary","No","One identity"],
          ["Service control policy","No","An account or OU, and not the management account"],
          ["Session policy","No","One assumed-role session"]]},
 {"t":"key","x":"Explicit Deny beats everything. After that, a call must pass every ceiling and find at least one grant. Two of the five policy types can only take permissions away."},
 {"t":"h","x":"Who signs in, and how"},
 {"t":"dtree","x":[
  ["Employees across many AWS accounts","IAM Identity Center with permission sets"],
  ["Customers of your application","Cognito"],
  ["An enterprise identity provider assuming roles directly","SAML federation"],
  ["A CI system with no stored keys","OIDC federation"],
  ["A third-party vendor's account","Cross-account role with an external ID"],
  ["Directory objects must stay on premises","AD Connector"],
  ["A managed Active Directory in AWS","AWS Managed Microsoft AD"]]},
 {"t":"h","x":"Conditions that answer questions"},
 {"t":"table","head":["Requirement","Condition key"],
  "rows":[["Require MFA","aws:MultiFactorAuthPresent"],
          ["Only from our organisation","aws:PrincipalOrgID"],
          ["Only through our VPC endpoint","aws:SourceVpce"],
          ["Only in approved regions","aws:RequestedRegion"],
          ["Tag-matching access","aws:ResourceTag and aws:PrincipalTag"],
          ["Invalidate leaked sessions","aws:TokenIssueTime before now"]]},
 {"t":"h","x":"Organizations in one picture"},
 {"t":"flow","x":["Management account","Organizational units","Service control policies as a ceiling","Member accounts","Identity Center assigns access into them"]},
 {"t":"trap","x":"Recurring distractors: an SCP described as granting permissions; a permissions boundary offered where a whole account must be restricted; Cognito used for employees; and deleting a role to stop a leaked session."}
],
"final":[
 {"m":"organizations",
  "q":"A company must ensure that no account in its development organizational unit can create resources outside eu-west-1, even by an account administrator. What enforces this?",
  "o":["A service control policy on that organizational unit restricting the region",
       "An IAM policy attached to every developer","A permissions boundary on each role in those accounts","An AWS Config rule that deletes non-compliant resources"],
  "a":[0],
  "w":["Correct — an SCP caps what any identity in those accounts can do, including administrators.",
      "Per-user policies can be changed by an account administrator, so they are not a real ceiling.",
      "Boundaries constrain single identities and would have to be applied and maintained on every role.",
      "Config detects and can remediate after the fact, but does not prevent creation."],
  "x":"The words \"even by an administrator\" are the SCP signal. Only an organisation-level control applies above the account's own administrators, and only prevention satisfies \"cannot create\"."},
 {"m":"identity-center",
  "q":"An enterprise with an existing corporate identity provider wants staff to sign in once and reach thirty AWS accounts with role-based access. What should be implemented?",
  "o":["IAM Identity Center connected to the identity provider, with permission sets assigned to groups",
       "An IAM user per staff member in a central account, with cross-account roles","Cognito user pools federated into each account","AD Connector in each of the thirty accounts"],
  "a":[0],
  "w":["Correct — Identity Center federates to the provider and assigns permission sets across accounts centrally.",
      "Central IAM users plus manual role assumption reintroduces user lifecycle management.",
      "Cognito is for the end users of an application, not for workforce access.",
      "AD Connector proxies authentication but does not assign access across accounts."],
  "x":"Workforce identity across many accounts is Identity Center's defining case: one assignment, roles assumed per account, and offboarding handled in the identity provider."},
 {"m":"policy-evaluation",
  "q":"A developer's role has an identity policy allowing s3:* and ec2:*. A permissions boundary on the role allows only s3:GetObject. An SCP on the account denies all EC2 actions. What can the role actually do?",
  "o":["Only s3:GetObject","All S3 and EC2 actions","All S3 actions but no EC2","Nothing at all"],
  "a":[0],
  "w":["Correct — the boundary caps the role to GetObject, and the SCP separately denies EC2 regardless.",
      "Both ceilings would have to permit these, and neither does.",
      "The boundary limits S3 to GetObject, so the broader S3 access is not available.",
      "GetObject passes the boundary, the SCP and the identity policy, so it is allowed."],
  "x":"Work through the ceilings in order: SCP, then boundary, then the grants. Effective permission is the intersection, and any explicit Deny removes an action outright."},
 {"m":"sts-patterns",
  "q":"A SaaS vendor requires access to your account to collect metrics. What is the correct and safest configuration?",
  "o":["A cross-account role whose trust policy names the vendor's account and requires an external ID",
       "An IAM user created for the vendor with access keys sent securely","A role with a trust policy allowing any AWS account","Adding the vendor's principal to the account's root policy"],
  "a":[0],
  "w":["Correct — the external ID prevents the confused deputy problem where another of the vendor's customers triggers access to your account.",
      "Long-lived keys given to a third party cannot be rotated reliably and outlive the relationship.",
      "Trusting every account is an open door to anyone who learns the role ARN.",
      "There is no such thing as adding a principal to a root policy."],
  "x":"Third-party access is the specific scenario the external ID exists for, and it is what distinguishes a correct cross-account answer from a merely plausible one."},
 {"m":"policy-evaluation",
  "q":"A bucket must be reachable only through a specific VPC endpoint, and never from the internet, even by principals with valid credentials. What implements this?",
  "o":["A bucket policy with a condition on aws:SourceVpce",
       "A security group on the bucket","An SCP denying S3 in all regions","A permissions boundary on every role"],
  "a":[0],
  "w":["Correct — the condition ties access to requests arriving through the named endpoint.",
      "Buckets do not have security groups; that is an EC2 concept.",
      "Denying S3 everywhere would block the legitimate access too.",
      "Boundaries limit identities but cannot express the network path of a request."],
  "x":"Network-path conditions such as aws:SourceVpce and aws:SourceVpc are how S3 access is restricted to private paths, which pairs naturally with a gateway endpoint."},
 {"m":"sts-patterns",
  "q":"Credentials for a widely used role have leaked, and the role must keep working for legitimate users. What should be done first?",
  "o":["Attach an inline policy denying all actions when aws:TokenIssueTime is earlier than now",
       "Delete the role and recreate it","Detach all policies from the role temporarily","Rotate the account's root access keys"],
  "a":[0],
  "w":["Correct — this invalidates every session issued before the cut-off while new assumptions continue to work.",
      "Deleting the role breaks every legitimate integration that references its ARN.",
      "Detaching policies stops legitimate users too, and for as long as it stays detached.",
      "Root keys are unrelated, and a well-run account has none."],
  "x":"Temporary credentials cannot be revoked directly, so the standard technique is a deny conditioned on when the token was issued — surgical, immediate and reversible."},
 {"m":"organizations",
  "q":"A new company needs a governed multi-account setup quickly, with centralised logging, an audit account, and preventive guardrails. What should they use?",
  "o":["AWS Control Tower to build a landing zone",
       "A single account with strict IAM policies","AWS Config deployed manually in each account","IAM Identity Center alone"],
  "a":[0],
  "w":["Correct — Control Tower provisions the organisation, log archive and audit accounts, and applies guardrails.",
      "One account cannot provide the isolation a multi-account structure exists to give.",
      "Config alone detects drift but does not create the account structure or preventive controls.",
      "Identity Center handles access, not account structure or guardrails."],
  "x":"Control Tower is the packaged landing zone: Organizations, SCP-based preventive guardrails, Config-based detective guardrails, and a standard account factory."},
 {"m":"identity-center",
  "q":"A regulated business must keep all user accounts and passwords in its on-premises Active Directory, with nothing replicated to AWS, while Windows workloads in AWS authenticate against it. Which option fits?",
  "o":["AD Connector","AWS Managed Microsoft AD with a one-way trust","Simple AD","IAM users synchronised nightly"],
  "a":[0],
  "w":["Correct — AD Connector proxies authentication to the on-premises directory and stores no directory objects in AWS.",
      "Managed Microsoft AD holds a directory in AWS, which the requirement forbids even with a trust.",
      "Simple AD is a standalone directory in AWS and would hold the objects locally.",
      "Synchronising to IAM users copies identities into AWS, which is what must be avoided."],
  "x":"The distinguishing requirement is that no directory data may live in AWS. AD Connector is the only option that satisfies it, at the cost of depending on connectivity to the data centre."},
 {"m":"policy-evaluation",
  "q":"A platform team wants engineers to manage only the resources tagged with their own team name, without writing a policy per team. What approach fits?",
  "o":["Attribute-based access control comparing aws:PrincipalTag with aws:ResourceTag",
       "A separate IAM role and policy per team","An SCP per organizational unit","A permissions boundary listing every resource ARN"],
  "a":[0],
  "w":["Correct — one policy comparing tags scales to any number of teams without modification.",
      "A policy per team is exactly the maintenance burden the question rules out.",
      "SCPs are account-level ceilings and cannot express per-team resource ownership within an account.",
      "Listing ARNs does not scale and would need updating for every new resource."],
  "x":"ABAC is the standard answer whenever access should follow tags rather than an enumerated list, because the policy stays constant as resources and teams are added."},
 {"m":"organizations",
  "q":"Finance wants Reserved Instance and Savings Plan discounts to apply across all accounts in the company. What provides this?",
  "o":["Consolidated billing through AWS Organizations",
       "A service control policy on the billing OU","One shared account for all workloads","Cost Explorer with grouped tags"],
  "a":[0],
  "w":["Correct — consolidated billing pools usage so commitments are shared across member accounts.",
      "SCPs are permission ceilings and have no effect on billing discounts.",
      "Collapsing into one account discards the isolation multi-account structures exist to provide.",
      "Cost Explorer reports on spend but does not change how discounts apply."],
  "x":"Discount sharing is one of the concrete benefits of Organizations, alongside volume pricing tiers, and it is why commitments are usually purchased in the management account."}
]
}
