# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 18,
"nm": "Security and encryption",
"tag": "Security",
"modules": [
{
 "id": "kms",
 "nm": "KMS and key management",
 "goal": "Choose a key type, control who may use it, and handle cross-region keys.",
 "min": 8,
 "blocks": [
  {"t":"p","x":"**KMS** holds encryption keys and performs cryptographic operations. A **KMS key** never leaves the service; data is encrypted with a **data key** that KMS generates and wraps — this is **envelope encryption**."},
  {"t":"flow","x":["Ask KMS for a data key","Get it in plaintext and encrypted form","Encrypt the data locally","Store the encrypted data key beside the data","Discard the plaintext key"],
   "cap":"Only KMS can unwrap the data key again, so control of the key policy is control of the data."},
  {"t":"table","head":["Key type","Who controls it","Notes"],
   "rows":[
    ["**AWS owned**","AWS entirely","Invisible to you, free"],
    ["**AWS managed**","AWS, per service","Named like `aws/s3`; rotated yearly; **cannot be shared across accounts**"],
    ["**Customer managed**","You","Own key policy, rotation, and the only option for cross-account sharing"],
    ["**Imported key material**","You supply the material","For bring-your-own-key requirements; you own availability of the material"],
    ["**CloudHSM**","You, in a dedicated hardware module","**FIPS 140-2 Level 3**, single-tenant, for the strictest requirements"]]},
  {"t":"key","x":"Access to a KMS key needs **both** the key policy and, for a different account, an IAM policy. The key policy is authoritative — an IAM policy alone cannot grant use of a key whose policy does not allow it."},
  {"t":"h","x":"Rotation and multi-region"},
  {"t":"list","x":[
   "**Automatic rotation** creates new key material yearly; old material is retained so old ciphertext still decrypts.",
   "**Multi-region keys** are related keys in several regions sharing key material, so data encrypted in one region can be decrypted in another. Ordinary KMS keys are regional and cannot do this.",
   "Deleting a key has a **waiting period of 7 to 30 days**, because deletion is irreversible and makes the data unreadable.",
   "**Grants** give a service temporary, narrowly scoped use of a key without editing the key policy."]},
  {"t":"trap","x":"Copying an encrypted snapshot to another region **re-encrypts it with a key in the destination region** unless a multi-region key is used. A question about cross-region disaster recovery with encryption is usually testing this."}
 ],
 "checks":[
  {"q":"What does envelope encryption mean in KMS?",
   "o":["Data is encrypted with a data key, which is itself encrypted by the KMS key",
        "Data is sent to KMS to be encrypted","Each object gets its own KMS key",
        "Data is encrypted twice with the same key"],
   "a":[0],
   "x":"KMS generates a data key, returns it in plaintext and encrypted form, and you encrypt locally. Only the encrypted data key is stored, and only KMS can unwrap it."},
  {"q":"An encrypted resource must be shared with another AWS account. Which key type is required?",
   "o":["A customer managed key","An AWS managed key","An AWS owned key","Any key, with an IAM policy"],
   "a":[0],
   "x":"AWS managed keys have no shareable key policy, so only a customer managed key can grant another account permission to use it."},
  {"q":"Why is a waiting period enforced when deleting a KMS key?",
   "o":["Deletion is irreversible and makes everything encrypted with it unreadable",
        "To allow automatic rotation to finish","To replicate the key to other regions",
        "To generate a final audit report"],
   "a":[0],
   "x":"Once a key is gone, ciphertext under it can never be decrypted. The 7 to 30 day window gives time to notice and cancel a mistake."},
  {"q":"Data encrypted in one region must be decrypted in another without re-encrypting. What supports this?",
   "o":["A multi-region KMS key","Automatic key rotation","A KMS grant","An imported key"],
   "a":[0],
   "x":"Multi-region keys share key material across regions, so ciphertext moves without a decrypt-and-re-encrypt step. Ordinary keys are regional."}
 ]
},
{
 "id":"secrets",
 "nm":"Secrets, parameters and certificates",
 "goal":"Store credentials and certificates in the right service and rotate them.",
 "min":6,
 "blocks":[
  {"t":"split","cols":[
   {"nm":"Secrets Manager","items":["**Automatic rotation**, with built-in support for RDS, Redshift and DocumentDB","Cross-region replication of secrets","Charged per secret and per API call","The answer whenever rotation is mentioned"]},
   {"nm":"SSM Parameter Store","items":["Configuration and secrets, **standard tier is free**","SecureString values encrypted with KMS","Hierarchical paths and version history","No built-in rotation"]}]},
  {"t":"key","x":"**Rotation** is the word that decides between them. Secrets Manager rotates automatically; Parameter Store does not. If the question only needs somewhere cheap to keep configuration, Parameter Store is the better answer."},
  {"t":"h","x":"ACM"},
  {"t":"list","x":[
   "**Public certificates are free** and renew automatically when used with integrated services.",
   "Integrated with load balancers, CloudFront and API Gateway. Certificates for CloudFront must live in **us-east-1**.",
   "ACM cannot install a certificate on an EC2 instance — that needs a manual process or Nitro Enclaves.",
   "**ACM Private CA** issues internal certificates for private domains."]},
  {"t":"flow","x":["Application starts","Reads the secret reference","Secrets Manager returns the current value","Rotation replaces it on schedule without redeployment"]},
  {"t":"trap","x":"ACM certificates **cannot be exported** for use on EC2 or on-premises servers. A question about putting a certificate on an instance is not answered by ACM public certificates."}
 ],
 "checks":[
  {"q":"A database password must be rotated automatically every thirty days. Which service?",
   "o":["AWS Secrets Manager","SSM Parameter Store standard tier","AWS KMS","AWS Certificate Manager"],
   "a":[0],
   "x":"Secrets Manager provides scheduled rotation with built-in integrations for RDS and similar databases. Parameter Store can store the value but has no rotation mechanism."},
  {"q":"Application configuration values must be stored cheaply with version history and no rotation requirement. Which service?",
   "o":["SSM Parameter Store","AWS Secrets Manager","AWS KMS","Amazon S3 with encryption"],
   "a":[0],
   "x":"Parameter Store's standard tier is free, supports hierarchical paths and keeps versions, which suits configuration that does not need rotating."},
  {"q":"Where must an ACM certificate be requested for use with CloudFront?",
   "o":["us-east-1","The region of the origin","Any region","The region with the most viewers"],
   "a":[0],
   "x":"CloudFront is a global service and only reads certificates from us-east-1. Regional services such as load balancers need the certificate in their own region."},
  {"q":"Why can an ACM public certificate not be installed directly on an EC2 web server?",
   "o":["ACM public certificates cannot be exported","EC2 does not support TLS",
        "The certificate would expire immediately","ACM only issues private certificates"],
   "a":[0],
   "x":"The private key stays inside ACM for integrated services, so there is nothing to copy onto an instance. ACM Private CA or a manual certificate is used instead."}
 ]
},
{
 "id":"perimeter",
 "nm":"WAF, Shield and Firewall Manager",
 "goal":"Place the right protection at the right layer for an attack described in a question.",
 "min":7,
 "blocks":[
  {"t":"table","head":["Service","Layer","Protects against"],
   "rows":[
    ["**AWS WAF**","7 — HTTP","SQL injection, cross-site scripting, bad bots, **rate-based** flooding from an address"],
    ["**Shield Standard**","3 and 4","Common network and transport floods, **free and automatic**"],
    ["**Shield Advanced**","3, 4 and 7","Larger attacks, 24/7 response team, **cost protection** against scaling charges"],
    ["**Firewall Manager**","Across accounts","Applies WAF, Shield and security group rules organisation-wide"],
    ["**Network Firewall**","VPC","Stateful traffic inspection at the VPC boundary, including domain filtering"]]},
  {"t":"key","x":"WAF attaches to a **CloudFront distribution, an Application Load Balancer, API Gateway, AppSync or Cognito** — never directly to an EC2 instance or a Network Load Balancer."},
  {"t":"h","x":"Layer by layer"},
  {"t":"flow","x":["Route 53 and CloudFront absorb and spread","Shield handles volumetric floods","WAF filters malicious requests","Auto Scaling absorbs what is left"],
   "cap":"The standard DDoS answer is this whole chain, not any single service."},
  {"t":"h","x":"Detection services"},
  {"t":"table","head":["Service","Finds"],
   "rows":[
    ["**GuardDuty**","Threats from logs and telemetry: crypto mining, compromised credentials, communication with known bad hosts"],
    ["**Inspector**","Vulnerabilities and unintended network exposure in EC2, containers and Lambda"],
    ["**Macie**","**Sensitive data in S3** — personal data, credentials — by classifying objects"],
    ["**Security Hub**","Aggregates findings from all of the above against standards"],
    ["**Detective**","Investigates a finding by linking the events behind it"]]},
  {"t":"trap","x":"**Macie is the only one that looks inside S3 objects for sensitive data.** GuardDuty detects threat behaviour and Inspector finds vulnerabilities — neither classifies content."}
 ],
 "checks":[
  {"q":"An application is being attacked with SQL injection attempts through its HTTP API. Which service blocks them?",
   "o":["AWS WAF","Shield Standard","GuardDuty","Macie"],
   "a":[0],
   "x":"WAF inspects HTTP requests and can block injection patterns with managed rule groups. Shield addresses network-layer floods and the other two are detection services."},
  {"q":"Which service finds personal data stored in S3 buckets?",
   "o":["Amazon Macie","Amazon GuardDuty","Amazon Inspector","AWS Security Hub"],
   "a":[0],
   "x":"Macie classifies S3 objects and reports sensitive data such as personal information and credentials. The others look at behaviour, vulnerabilities and aggregated findings."},
  {"q":"Where can a WAF web ACL be attached?",
   "o":["A CloudFront distribution, an Application Load Balancer, or API Gateway",
        "An EC2 instance directly","A Network Load Balancer","An EBS volume"],
   "a":[0],
   "x":"WAF operates on HTTP, so it attaches to services that terminate HTTP. A Network Load Balancer works at layer 4 and cannot inspect requests."},
  {"q":"What does Shield Advanced add beyond the free tier?",
   "o":["Cost protection against scaling charges during an attack, and a response team",
        "Encryption of data at rest","Vulnerability scanning of EC2","Classification of S3 objects"],
   "a":[0],
   "x":"Shield Standard already covers common network floods for free. Advanced adds larger-scale protection, a 24/7 response team, and reimbursement of scaling costs caused by an attack."}
 ]
},
{
 "id":"data-protection",
 "nm":"Protecting data across services",
 "goal":"Apply encryption consistently and recognise the compliance answers.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Where","At rest","In transit"],
   "rows":[
    ["S3","SSE-S3, SSE-KMS, DSSE-KMS, SSE-C, client-side","HTTPS, enforceable with a bucket policy condition"],
    ["EBS","KMS, set at creation","Encrypted between instance and volume automatically"],
    ["RDS and Aurora","KMS, set at creation","TLS to the endpoint"],
    ["DynamoDB","Encrypted by default","HTTPS"],
    ["EFS","KMS","TLS mount option"],
    ["Kinesis, SQS, SNS","KMS server-side encryption","HTTPS"]]},
  {"t":"key","x":"Encryption at rest is almost always **set when the resource is created**. Adding it afterwards means a snapshot or copy — for EBS, RDS and Aurora alike."},
  {"t":"h","x":"Enforcing rather than enabling"},
  {"t":"list","x":[
   "A **bucket policy** denying `s3:PutObject` without the encryption header rejects unencrypted uploads.",
   "A bucket policy denying requests where `aws:SecureTransport` is false refuses plain HTTP.",
   "**Config rules** detect unencrypted resources across the account, with remediation.",
   "An **SCP** can deny creating an unencrypted volume in the first place."]},
  {"t":"h","x":"Compliance answers"},
  {"t":"table","head":["Requirement","Answer"],
   "rows":[
    ["Dedicated single-tenant hardware for keys, FIPS 140-2 Level 3","CloudHSM"],
    ["Bring your own key material","KMS with imported key material"],
    ["Records must be immutable for years","S3 Object Lock in compliance mode"],
    ["Audit every key use","KMS with CloudTrail"],
    ["Find sensitive data already stored","Macie"],
    ["Hardware isolation for compute","Dedicated Hosts"]]},
  {"t":"trap","x":"**Detecting** and **preventing** are different answers. Config finds an unencrypted volume after the fact; an SCP or a deny policy stops it being created. Read which the question asks for."}
 ],
 "checks":[
  {"q":"Uploads to a bucket must be rejected unless they are encrypted. What enforces this?",
   "o":["A bucket policy denying PutObject without the encryption header",
        "Enabling default encryption on the bucket","A Config rule with remediation",
        "Turning on versioning"],
   "a":[0],
   "x":"Default encryption silently encrypts whatever arrives, which is not rejection. A deny policy conditioned on the header is what actually refuses the request."},
  {"q":"A regulation requires dedicated single-tenant hardware validated to FIPS 140-2 Level 3 for key storage. Which service?",
   "o":["AWS CloudHSM","AWS KMS with a customer managed key","AWS Secrets Manager","ACM Private CA"],
   "a":[0],
   "x":"CloudHSM provides a dedicated hardware security module you control. KMS is multi-tenant and validated to a different level, which is why the requirement names CloudHSM."},
  {"q":"Which difference matters when a question says resources must never be created unencrypted?",
   "o":["Prevention through an SCP or deny policy, rather than detection through Config",
        "Rotation frequency of the KMS key","Whether the key is multi-region",
        "Whether encryption uses envelope encryption"],
   "a":[0],
   "x":"Config reports non-compliance after creation. Only a preventive control — a service control policy or a deny in a policy — stops the resource existing in the first place."},
  {"q":"How is plain HTTP access to an S3 bucket refused?",
   "o":["A bucket policy denying requests where aws:SecureTransport is false",
        "Enabling SSE-KMS on the bucket","A CloudFront distribution in front",
        "Turning on Block Public Access"],
   "a":[0],
   "x":"The condition key distinguishes TLS from plain HTTP, so a deny on insecure transport refuses unencrypted connections regardless of who is calling."}
 ]
}
],
"recap":[
 {"t":"h","x":"Key management"},
 {"t":"table","head":["Requirement","Answer"],
  "rows":[["Just encrypt it","An AWS managed key"],
          ["Control the key policy, share across accounts","A customer managed key"],
          ["Audit every use of the key","KMS with CloudTrail"],
          ["Decrypt in another region without re-encrypting","A multi-region key"],
          ["Bring your own key material","Imported key material"],
          ["Dedicated hardware, FIPS 140-2 Level 3","CloudHSM"],
          ["Temporary scoped access for a service","A grant"]]},
 {"t":"key","x":"Encryption at rest is set at creation. Adding it later always means snapshot, copy with encryption, restore — for EBS, RDS and Aurora alike."},
 {"t":"h","x":"Secrets and certificates"},
 {"t":"split","cols":[
  {"nm":"Secrets Manager","items":["Automatic rotation","Cross-region replication","Charged per secret"]},
  {"nm":"Parameter Store","items":["Free standard tier","Hierarchies and versions","No rotation"]},
  {"nm":"ACM","items":["Free public certificates that renew","us-east-1 for CloudFront","Cannot be exported to EC2"]}]},
 {"t":"h","x":"Perimeter and detection"},
 {"t":"table","head":["Problem","Service"],
  "rows":[["SQL injection or bad bots","WAF"],
          ["Volumetric flood","Shield, with CloudFront and Route 53 absorbing"],
          ["Attack-driven scaling costs","Shield Advanced cost protection"],
          ["Rules across many accounts","Firewall Manager"],
          ["Stateful inspection at the VPC edge","Network Firewall"],
          ["Compromised credentials or crypto mining","GuardDuty"],
          ["Unpatched software or exposed ports","Inspector"],
          ["Personal data sitting in S3","Macie"],
          ["All findings in one place","Security Hub"]]},
 {"t":"h","x":"Prevent or detect"},
 {"t":"flow","x":["SCP or deny policy prevents","Config detects and remediates","GuardDuty and Inspector find","Security Hub aggregates"]},
 {"t":"trap","x":"Recurring distractors: an AWS managed key offered for cross-account sharing; WAF attached to a Network Load Balancer; GuardDuty offered to find sensitive data in S3; ACM certificates exported to EC2; and detection offered where the requirement is prevention."}
],
"final":[
 {"m":"kms",
  "q":"An encrypted EBS snapshot must be shared with a partner account so they can restore it. The snapshot uses the default EBS key. What is required?",
  "o":["Copy the snapshot, re-encrypting it with a customer managed key whose policy grants the partner account",
       "Share the snapshot directly and grant the partner IAM access to the default key","Make the snapshot public","Disable encryption on the snapshot before sharing"],
  "a":[0],
  "w":["Correct — AWS managed keys have no shareable policy, so a customer managed key is the only route.",
      "The default EBS key cannot be shared with another account under any IAM policy.",
      "Encrypted snapshots cannot be made public, and it would be a serious exposure.",
      "Removing encryption to enable sharing abandons the control it provides."],
  "x":"The blocker is the key, not the snapshot. Cross-account sharing of encrypted resources always requires a customer managed key whose key policy grants the other account."},
 {"m":"perimeter",
  "q":"A public web application is being flooded with requests from a small number of IP addresses, and legitimate users are timing out. What blocks the traffic closest to the edge?",
  "o":["A WAF rate-based rule on the CloudFront distribution",
       "A security group rule on the EC2 instances","A Network ACL denying those addresses on the subnet","Shield Standard, which will block them automatically"],
  "a":[0],
  "w":["Correct — rate-based rules count requests per address at the edge and block offenders before they reach the origin.",
      "Security groups act at the instance, after the traffic has already crossed the network.",
      "Network ACLs are subnet-level and must be maintained by hand as addresses change.",
      "Shield Standard covers network-layer floods, not application-layer request rates."],
  "x":"Application-layer flooding is WAF's territory, and a rate-based rule handles it without listing addresses manually. Attaching WAF to CloudFront stops the traffic furthest from the origin."},
 {"m":"secrets",
  "q":"A database credential must be rotated every 30 days, with applications picking up the new value without redeployment. What should be used?",
  "o":["AWS Secrets Manager with automatic rotation",
       "SSM Parameter Store with a SecureString","A KMS encrypted file in S3","Environment variables updated by a deployment pipeline"],
  "a":[0],
  "w":["Correct — Secrets Manager rotates on a schedule and applications retrieve the current value at run time.",
      "Parameter Store stores the value securely but has no rotation mechanism.",
      "A file in S3 requires you to build rotation and distribution yourself.",
      "Redeploying to change a credential is exactly what the requirement excludes."],
  "x":"Rotation is the word that separates Secrets Manager from Parameter Store. Applications read the secret at run time, so a rotated value is picked up without any deployment."},
 {"m":"data-protection",
  "q":"A compliance team must guarantee that no unencrypted EBS volume can be created anywhere in the organisation. What implements this?",
  "o":["A service control policy denying volume creation without encryption",
       "An AWS Config rule that flags unencrypted volumes","Enabling EBS encryption by default in each region","Amazon Inspector scanning for unencrypted volumes"],
  "a":[0],
  "w":["Correct — an SCP is preventive and applies to every identity in every member account.",
      "Config detects violations after the volume already exists.",
      "Encryption by default helps but can be turned off, and it is per region per account.",
      "Inspector finds software vulnerabilities, not encryption settings."],
  "x":"\"Guarantee that it cannot be created\" is a prevention requirement, which rules out every detective control. Encryption by default is a good complement but is not a guarantee."},
 {"m":"perimeter",
  "q":"A security team needs to know whether any S3 bucket contains customer identity documents or credentials. Which service answers this?",
  "o":["Amazon Macie","Amazon GuardDuty","Amazon Inspector","AWS Config"],
  "a":[0],
  "w":["Correct — Macie classifies objects and reports the sensitive data types found.",
      "GuardDuty analyses behaviour and logs for threats, not object contents.",
      "Inspector assesses software vulnerabilities and network exposure.",
      "Config records configuration state and does not read object contents."],
  "x":"Macie is the only service that inspects the contents of S3 objects. Whenever a question asks what data is stored rather than how the resource is configured, Macie is the answer."},
 {"m":"kms",
  "q":"A disaster recovery plan replicates encrypted data to a second region, and the team wants to avoid a decrypt-and-re-encrypt step on failover. What should be used?",
  "o":["A multi-region KMS key","Automatic key rotation on the existing key",
       "An AWS managed key in each region","A KMS grant for the destination region"],
  "a":[0],
  "w":["Correct — multi-region keys share key material, so ciphertext from one region decrypts in the other.",
      "Rotation changes key material over time and does nothing for cross-region use.",
      "Separate AWS managed keys are unrelated and cannot decrypt each other's ciphertext.",
      "Grants scope access to a key; they do not span regions."],
  "x":"KMS keys are regional by default, which is why cross-region copies normally re-encrypt. Multi-region keys exist specifically to remove that step in disaster recovery designs."},
 {"m":"secrets",
  "q":"A custom domain served by an Application Load Balancer needs a TLS certificate that renews automatically at no cost. What should be used, and where?",
  "o":["An ACM public certificate in the same region as the load balancer",
       "An ACM public certificate in us-east-1","A certificate from ACM Private CA","A self-signed certificate installed on the instances"],
  "a":[0],
  "w":["Correct — public ACM certificates are free, renew automatically, and must be in the load balancer's region.",
      "us-east-1 is required for CloudFront, not for a regional load balancer.",
      "Private CA issues internal certificates that public browsers will not trust.",
      "Self-signed certificates produce browser warnings and must be renewed by hand."],
  "x":"Region placement is the detail being tested: regional services want the certificate in their own region, and CloudFront wants it in us-east-1."},
 {"m":"data-protection",
  "q":"An existing production RDS instance is unencrypted and must become encrypted with the least disruption. What is the correct procedure?",
  "o":["Take a snapshot, copy it with encryption enabled, restore a new instance, then repoint the application",
       "Enable encryption on the running instance from the console","Enable Multi-AZ, which encrypts the standby","Attach a KMS key to the instance's security group"],
  "a":[0],
  "w":["Correct — encryption is fixed at creation, so an encrypted copy has to be produced through a snapshot.",
      "There is no in-place toggle for encryption on an existing RDS instance.",
      "Multi-AZ creates a standby with the same encryption state as the primary.",
      "Security groups control network access and have nothing to do with KMS."],
  "x":"This mirrors the EBS procedure exactly, and the practical consequence is a new endpoint that the application must be repointed to, usually during a planned cutover."},
 {"m":"perimeter",
  "q":"During a large distributed denial of service attack, Auto Scaling grew the fleet and the bill rose sharply. Which service would have reimbursed those charges?",
  "o":["AWS Shield Advanced, which includes cost protection",
       "AWS Shield Standard","AWS WAF with managed rules","AWS Firewall Manager"],
  "a":[0],
  "w":["Correct — Shield Advanced includes cost protection for scaling charges caused by a covered attack.",
      "Shield Standard is free and protects against common floods but offers no cost protection.",
      "WAF filters requests but does not reimburse infrastructure charges.",
      "Firewall Manager applies rules across accounts and has no billing component."],
  "x":"Cost protection and the 24/7 response team are the two features that most often justify Shield Advanced, alongside its broader attack coverage."},
 {"m":"kms",
  "q":"An auditor must confirm exactly which principals decrypted a particular dataset and when. What combination provides this?",
  "o":["Encrypt with a customer managed KMS key and review CloudTrail events for that key",
       "Encrypt with an AWS owned key and review S3 access logs","Use SSE-C and review the application logs","Use CloudHSM without CloudTrail"],
  "a":[0],
  "w":["Correct — every KMS operation is recorded in CloudTrail, including which principal requested a decrypt.",
      "AWS owned keys are invisible to you and produce no key-usage trail.",
      "With SSE-C the key never reaches KMS, so there is no managed audit record of its use.",
      "Without CloudTrail there is no audit trail to review at all."],
  "x":"The pairing of a customer managed key with CloudTrail is the standard answer for auditable key use, which is precisely why SSE-KMS beats SSE-S3 in compliance scenarios."}
]
}
