# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 19,
"nm": "Networking: VPC",
"tag": "Networking",
"modules": [
{
 "id": "vpc-subnets",
 "nm": "CIDR, subnets and what makes one public",
 "goal": "Lay out a VPC correctly and explain exactly what makes a subnet public.",
 "min": 8,
 "blocks": [
  {"t":"p","x":"A **VPC** is a private network in one region, defined by a CIDR block. It is divided into **subnets**, each living in exactly one Availability Zone."},
  {"t":"table","head":["Rule","Detail"],
   "rows":[
    ["VPC CIDR size","Between /16 and /28"],
    ["Subnet scope","One Availability Zone, always"],
    ["Reserved addresses","**Five per subnet**: network, VPC router, DNS, future use, broadcast"],
    ["Private ranges","10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"],
    ["Overlap","CIDRs must not overlap if the networks will ever be peered or connected"]]},
  {"t":"key","x":"A subnet is **public only because its route table has a route to an internet gateway**. Nothing else makes it public — not its name, not its address range, not having public IPs assigned."},
  {"t":"h","x":"The pieces that carry traffic"},
  {"t":"table","head":["Component","Direction"],
   "rows":[
    ["**Internet gateway**","Both ways, for resources with public addresses"],
    ["**NAT gateway**","**Outbound only**, for private subnets; managed, scalable, per-AZ"],
    ["NAT instance","The legacy self-managed version"],
    ["**Egress-only internet gateway**","Outbound only, for **IPv6**"],
    ["Route table","Decides where a subnet's traffic goes"]]},
  {"t":"flow","x":["Private subnet instance","Route table sends 0.0.0.0/0 to the NAT gateway","NAT gateway in a public subnet","Internet gateway","Internet"],
   "cap":"Return traffic comes back the same way; nothing can start a connection inwards."},
  {"t":"h","x":"NAT gateway details that get tested"},
  {"t":"list","x":[
   "It lives **in a public subnet** and needs an Elastic IP.",
   "It is bound to **one Availability Zone**. For resilience, deploy one per zone and route each zone's subnets to its own.",
   "It is charged hourly **and per gigabyte processed** — the reason VPC endpoints save money.",
   "It cannot be used by IPv6 traffic; that is the egress-only internet gateway."]},
  {"t":"trap","x":"A NAT gateway in a **private** subnet does not work: it needs a route to an internet gateway itself. That mistake appears in exam options regularly."}
 ],
 "checks":[
  {"q":"What makes a subnet public?",
   "o":["Its route table has a route to an internet gateway","Its instances have public IP addresses",
        "It has a CIDR outside the private ranges","It is named public in the console"],
   "a":[0],
   "x":"Routing is what defines it. Public addresses are useless without a route to an internet gateway, and names and address ranges have no effect on reachability."},
  {"q":"How many IP addresses are reserved by AWS in each subnet?",
   "o":["Five","Two","Three","Ten"],
   "a":[0],
   "x":"AWS reserves the network address, the VPC router, the DNS address, one for future use, and the broadcast address, so a /28 offers eleven usable addresses rather than sixteen."},
  {"q":"Where must a NAT gateway be placed?",
   "o":["In a public subnet, with an Elastic IP","In a private subnet, with an Elastic IP",
        "In any subnet, with no address","Outside the VPC entirely"],
   "a":[0],
   "x":"The NAT gateway itself needs to reach the internet, so it must sit in a subnet routed to an internet gateway. A NAT gateway in a private subnet cannot function."},
  {"q":"A single NAT gateway serves subnets in three Availability Zones. What is the weakness?",
   "o":["If that Availability Zone fails, the other zones lose outbound access",
        "It cannot process more than one gigabyte per hour","It requires IPv6",
        "It blocks return traffic from the internet"],
   "a":[0],
   "x":"A NAT gateway is zonal. Sharing one across zones creates a single point of failure and adds cross-zone data charges, which is why one per zone is the resilient pattern."}
 ]
},
{
 "id":"security-controls",
 "nm":"Security groups and network ACLs",
 "goal":"Diagnose a blocked connection by working out which control is responsible.",
 "min":7,
 "blocks":[
  {"t":"split","cols":[
   {"nm":"Security group","items":["Attached to an **instance** or interface","**Allow rules only**","**Stateful** — replies are automatic","Source can be another security group","Evaluated as a whole: any rule that allows is enough"]},
   {"nm":"Network ACL","items":["Attached to a **subnet**","**Allow and deny rules**","**Stateless** — return traffic needs its own rule","Source is a CIDR only","**Rules evaluated in number order**, first match wins"]}]},
  {"t":"key","x":"Because NACLs are stateless, outbound replies use **ephemeral ports** — typically 1024 to 65535. A NACL that allows inbound 443 but no outbound ephemeral range silently breaks every response."},
  {"t":"h","x":"Working out which one blocked you"},
  {"t":"dtree","x":[
   ["Traffic works one way but replies never arrive","A NACL missing the ephemeral port range"],
   ["A specific address must be blocked","A NACL — security groups cannot deny"],
   ["Tier-to-tier access without listing addresses","A security group as the source"],
   ["Everything in a subnet must be blocked at once","A NACL on the subnet"],
   ["A connection times out from outside","Security group, NACL, route table, or no public address"]]},
  {"t":"h","x":"The default network ACL"},
  {"t":"p","x":"The default NACL allows all traffic in and out. A **custom** NACL denies everything until you add rules — a common cause of a mysterious outage after someone creates one."},
  {"t":"trap","x":"A security group cannot block a specific attacking address, because it has no deny rules. Blocking one address is a **NACL** job, or better, WAF at the application layer."}
 ],
 "checks":[
  {"q":"A single malicious IP address must be blocked at the subnet level. Which control?",
   "o":["A network ACL deny rule","A security group deny rule","A route table entry",
        "An internet gateway rule"],
   "a":[0],
   "x":"Security groups only allow, so blocking one address requires a NACL, which supports deny rules evaluated in number order."},
  {"q":"A NACL allows inbound HTTPS but responses never reach clients. What is missing?",
   "o":["An outbound rule allowing the ephemeral port range","An inbound rule for port 80",
        "A second internet gateway","A security group on the subnet"],
   "a":[0],
   "x":"NACLs are stateless, so the reply is evaluated separately and leaves from a high-numbered ephemeral port. Without an outbound rule covering that range the response is dropped."},
  {"q":"What happens by default with a newly created custom network ACL?",
   "o":["It denies all traffic until rules are added","It allows all traffic like the default NACL",
        "It inherits the security group rules","It applies only to IPv6"],
   "a":[0],
   "x":"The default NACL is permissive, but a custom one starts denying everything. Associating it with a subnet before adding rules takes that subnet offline."},
  {"q":"Which statement about security groups is correct?",
   "o":["They are stateful, so a reply to an allowed request is automatically permitted",
        "They are stateless and need outbound rules for replies","They are attached to subnets",
        "They evaluate rules in number order and stop at the first match"],
   "a":[0],
   "x":"Statefulness is the defining difference from NACLs. Security groups attach to interfaces, contain only allow rules, and evaluate all rules together rather than in order."}
 ]
},
{
 "id":"private-connectivity",
 "nm":"Endpoints, peering and PrivateLink",
 "goal":"Connect networks and reach AWS services without crossing the internet.",
 "min":8,
 "blocks":[
  {"t":"table","head":["Mechanism","Connects","Notes"],
   "rows":[
    ["**Gateway endpoint**","A VPC to **S3 or DynamoDB**","A route table entry. **Free**. These two services only"],
    ["**Interface endpoint** (PrivateLink)","A VPC to most other AWS services, or to a partner service","An ENI with a private IP, **charged hourly and per GB**"],
    ["**VPC peering**","Two VPCs, one to one","**Not transitive**, CIDRs must not overlap"],
    ["**Transit Gateway**","Many VPCs and on-premises networks","A hub; replaces a mesh of peerings"],
    ["**Site-to-Site VPN**","On-premises to AWS over the internet","Encrypted, quick to set up, variable performance"],
    ["**Direct Connect**","On-premises to AWS over a private line","Consistent performance, **takes weeks to provision**"]]},
  {"t":"key","x":"S3 and DynamoDB get **free gateway endpoints**. Everything else uses an **interface endpoint**, which costs money but reaches far more services — and is also how a third party exposes a service privately."},
  {"t":"h","x":"Peering is not transitive"},
  {"t":"flow","x":["VPC A peered to VPC B","VPC B peered to VPC C","A still cannot reach C","Peer them directly, or use a Transit Gateway"]},
  {"t":"h","x":"Hybrid connectivity"},
  {"t":"list","x":[
   "**VPN over Direct Connect** is the answer when a private line must also be encrypted.",
   "A **VPN as backup** to Direct Connect is the standard resilience pattern.",
   "**Direct Connect Gateway** connects one Direct Connect to VPCs in several regions.",
   "Provisioning a Direct Connect takes **weeks**, so a VPN is the interim answer when a question says the migration starts now."]},
  {"t":"trap","x":"\"Traffic must not traverse the public internet\" is an endpoint, PrivateLink, or Direct Connect. A **NAT gateway does not satisfy it** — traffic still goes out over the internet path."}
 ],
 "checks":[
  {"q":"Instances in private subnets must reach S3 without any internet path, at no extra cost. What do you create?",
   "o":["A gateway endpoint for S3","An interface endpoint for S3","A NAT gateway","A VPC peering connection"],
   "a":[0],
   "x":"Gateway endpoints exist for S3 and DynamoDB, work by adding a route, and are free. A NAT gateway would route the traffic over the internet and charge per gigabyte."},
  {"q":"VPC A is peered with B, and B is peered with C. Can A reach C?",
   "o":["No — peering is not transitive","Yes, through B automatically",
        "Yes, if B allows routing","Only for IPv6 traffic"],
   "a":[0],
   "x":"Each peering connection joins exactly two VPCs. Reaching C from A needs a direct peering or a Transit Gateway acting as a hub."},
  {"q":"Thirty VPCs and two on-premises sites must all reach each other. What avoids a mesh of connections?",
   "o":["A Transit Gateway","VPC peering between every pair","An internet gateway in each VPC",
        "A gateway endpoint in each VPC"],
   "a":[0],
   "x":"A Transit Gateway is a hub that each VPC and VPN attaches to once, replacing hundreds of peering connections and their route table entries."},
  {"q":"A migration must begin immediately, but the company also wants consistent dedicated bandwidth long term. What is the sensible sequence?",
   "o":["Start with a Site-to-Site VPN and move to Direct Connect when it is provisioned",
        "Wait for Direct Connect before starting","Use a NAT gateway for the migration",
        "Use VPC peering to the data centre"],
   "a":[0],
   "x":"Direct Connect takes weeks to provision, so a VPN provides encrypted connectivity now. The VPN then usually stays as a backup path once the private line is live."}
 ]
},
{
 "id":"visibility-cost",
 "nm":"Flow logs, DNS and what networking costs",
 "goal":"Troubleshoot with flow logs and reduce data transfer charges.",
 "min":7,
 "blocks":[
  {"t":"h","x":"VPC Flow Logs"},
  {"t":"list","x":[
   "Capture metadata about traffic — source, destination, ports, bytes, and **ACCEPT or REJECT** — at VPC, subnet or interface level.",
   "They do **not capture packet contents**; for that you need **Traffic Mirroring**.",
   "Delivered to CloudWatch Logs, S3, or Firehose; **Athena** is the usual way to query them at volume.",
   "A stream of REJECT entries is how you confirm a security group or NACL is the thing blocking a connection."]},
  {"t":"key","x":"Flow logs answer **whether** traffic was allowed. Traffic Mirroring answers **what was in the packets**. A question about inspecting payloads is mirroring, not flow logs."},
  {"t":"h","x":"DNS inside a VPC"},
  {"t":"table","head":["Setting","Effect"],
   "rows":[
    ["`enableDnsSupport`","The VPC's DNS resolver answers queries at the base address plus two"],
    ["`enableDnsHostnames`","Instances receive public DNS hostnames"],
    ["Private hosted zone","Internal names resolvable only from associated VPCs"],
    ["Resolver endpoints","Inbound for on-premises queries into AWS, outbound for the reverse"]]},
  {"t":"h","x":"Where networking costs come from"},
  {"t":"table","head":["Path","Cost"],
   "rows":[
    ["Within one Availability Zone, private addresses","**Free**"],
    ["Between Availability Zones","Charged in both directions"],
    ["Between regions","Charged"],
    ["Out to the internet","Charged, and the largest component for most workloads"],
    ["Through a NAT gateway","Hourly **plus** per gigabyte processed"],
    ["Through a gateway endpoint","Free"]]},
  {"t":"trap","x":"Keeping chatty traffic **within one Availability Zone** and replacing NAT traffic to S3 with a **gateway endpoint** are the two networking cost answers that come up most often."}
 ],
 "checks":[
  {"q":"You need to know whether traffic to an instance was allowed or rejected, without seeing the payload. What provides this?",
   "o":["VPC Flow Logs","Traffic Mirroring","CloudTrail","Route 53 query logs"],
   "a":[0],
   "x":"Flow logs record connection metadata including an ACCEPT or REJECT action, which is exactly what confirms whether a security group or NACL blocked the traffic."},
  {"q":"A security team must inspect the actual contents of packets flowing to an instance. What provides that?",
   "o":["VPC Traffic Mirroring","VPC Flow Logs","CloudWatch metrics","A NAT gateway log"],
   "a":[0],
   "x":"Traffic Mirroring copies packets to an appliance for deep inspection. Flow logs only capture metadata and never the payload."},
  {"q":"Data transfer charges are high because private instances download large objects from S3 through a NAT gateway. What removes the charge?",
   "o":["A gateway endpoint for S3","A second NAT gateway","An interface endpoint for EC2",
        "Moving the bucket to another region"],
   "a":[0],
   "x":"A gateway endpoint routes S3 traffic privately at no cost, removing both the NAT processing charge and the internet path."},
  {"q":"Which traffic within a VPC is free?",
   "o":["Traffic between instances in the same Availability Zone using private addresses",
        "Traffic between Availability Zones","Traffic to the internet",
        "Traffic through a NAT gateway"],
   "a":[0],
   "x":"Same-zone private traffic is not charged. Crossing an Availability Zone or leaving for the internet is, which is why placement and endpoints matter to the bill."}
 ]
}
],
"recap":[
 {"t":"h","x":"The shape of a standard VPC"},
 {"t":"flow","x":["Internet gateway","Public subnets: load balancer and NAT gateway","Private subnets: application","Isolated subnets: database"],
  "cap":"Three tiers, spread across at least two Availability Zones."},
 {"t":"h","x":"Security group against network ACL"},
 {"t":"table","head":["","Security group","Network ACL"],
  "rows":[["Attaches to","An instance or interface","A subnet"],
          ["Rules","Allow only","Allow and deny"],
          ["State","Stateful","Stateless — ephemeral ports needed"],
          ["Evaluation","All rules together","In number order, first match wins"],
          ["Source","CIDR or another security group","CIDR only"]]},
 {"t":"key","x":"A subnet is public only because of a route to an internet gateway. A NAT gateway must sit in a public subnet, is zonal, and is charged per gigabyte."},
 {"t":"h","x":"Connecting things"},
 {"t":"table","head":["Requirement","Answer"],
  "rows":[["Reach S3 or DynamoDB privately, free","Gateway endpoint"],
          ["Reach another AWS service privately","Interface endpoint"],
          ["Two VPCs, one to one","VPC peering, not transitive"],
          ["Many VPCs and sites","Transit Gateway"],
          ["Encrypted link over the internet, today","Site-to-Site VPN"],
          ["Consistent private bandwidth","Direct Connect, provisioned in weeks"],
          ["Private line that must also be encrypted","VPN over Direct Connect"],
          ["IPv6 outbound only","Egress-only internet gateway"]]},
 {"t":"h","x":"Cost and visibility"},
 {"t":"split","cols":[
  {"nm":"Cheaper","items":["Keep chatty traffic in one Availability Zone","Gateway endpoints instead of NAT for S3","Fewer cross-region hops"]},
  {"nm":"Visible","items":["Flow logs for accept and reject","Traffic Mirroring for packet contents","Athena over flow logs in S3"]}]},
 {"t":"trap","x":"Recurring distractors: a NAT gateway offered where traffic must not traverse the internet; peering assumed to be transitive; a NACL used where a security group reference is cleaner; a custom NACL left with no rules; and one NAT gateway serving every Availability Zone."}
],
"final":[
 {"m":"private-connectivity",
  "q":"Instances in private subnets read large volumes from S3 through a NAT gateway, and data processing charges dominate the bill. Traffic must also stay off the public internet. What should be done?",
  "o":["Create a gateway endpoint for S3 and route S3 traffic to it",
       "Add a second NAT gateway to spread the load","Give the instances public IP addresses","Create an interface endpoint for S3 in every subnet"],
  "a":[0],
  "w":["Correct — gateway endpoints are free, keep traffic on the AWS network, and remove the NAT processing charge entirely.",
      "More NAT gateways multiply the hourly charge without reducing per-gigabyte processing.",
      "Public addressing exposes the instances and still routes over the internet.",
      "Interface endpoints for S3 exist but are charged; the gateway endpoint is the free answer for S3."],
  "x":"Gateway endpoints serve S3 and DynamoDB only, cost nothing, and satisfy both the cost and the no-internet requirement at once."},
 {"m":"security-controls",
  "q":"After a custom network ACL is applied to a subnet, inbound HTTPS works but no responses reach clients. What is the cause?",
  "o":["No outbound rule permits the ephemeral port range, and NACLs are stateless",
       "The security group is missing an outbound rule","The route table has no internet gateway","The instances lost their public IP addresses"],
  "a":[0],
  "w":["Correct — the reply leaves from a high-numbered ephemeral port and must be allowed explicitly.",
      "Security groups are stateful, so replies to allowed requests need no outbound rule.",
      "A missing route would have broken the inbound request too.",
      "Losing public addresses would prevent the inbound connection entirely."],
  "x":"Statelessness is the defining NACL property. Every NACL that allows inbound traffic also needs an outbound rule for the ephemeral range, typically 1024 to 65535."},
 {"m":"vpc-subnets",
  "q":"An architecture has one NAT gateway in us-east-1a serving private subnets in three Availability Zones. What are the two consequences?",
  "o":["A failure of that zone removes outbound access for all three, and cross-zone data charges apply (choose two answers)",
       "Outbound traffic is encrypted automatically","Inbound connections from the internet become possible","IPv6 traffic is routed through it"],
  "a":[0],
  "w":["Correct — a NAT gateway is zonal, so it is both a single point of failure and a source of cross-zone transfer charges.",
      "NAT performs address translation and does not encrypt anything.",
      "NAT gateways never allow inbound connection initiation.",
      "IPv6 egress uses an egress-only internet gateway instead."],
  "x":"The resilient pattern is one NAT gateway per Availability Zone, with each zone's private subnets routing to their own — which removes both the failure mode and the cross-zone charge."},
 {"m":"private-connectivity",
  "q":"A company has twenty VPCs across two regions plus two data centres, and the routing between them has become unmanageable. What should replace it?",
  "o":["AWS Transit Gateway as a hub, with peering between the regional gateways",
       "Full-mesh VPC peering between every pair","An internet gateway in each VPC with public routing","A separate Direct Connect for each VPC"],
  "a":[0],
  "w":["Correct — each VPC and VPN attaches once to the hub, and inter-region traffic flows over gateway peering.",
      "A full mesh of twenty VPCs requires 190 peerings and an unmanageable number of route entries.",
      "Routing internal traffic over the internet is neither private nor practical.",
      "One Direct Connect per VPC is enormously expensive and unnecessary."],
  "x":"Transit Gateway exists to replace peering meshes. Combined with a Direct Connect Gateway it also centralises hybrid connectivity across regions."},
 {"m":"security-controls",
  "q":"A specific external IP address is repeatedly probing an application and must be blocked at the network layer for an entire subnet. What is used?",
  "o":["A network ACL deny rule with a low rule number",
       "A security group deny rule","A route table blackhole entry for that address","A change to the subnet CIDR"],
  "a":[0],
  "w":["Correct — NACLs support deny rules, apply to the whole subnet, and are evaluated in number order.",
      "Security groups contain allow rules only and cannot express a deny.",
      "Route tables direct traffic by destination and cannot filter by source.",
      "Changing the CIDR would disrupt everything in the subnet and block nothing specific."],
  "x":"Blocking a source address is one of the few things only a NACL can do inside a VPC. At the application layer, WAF is usually the better place for it."},
 {"m":"visibility-cost",
  "q":"An engineer must determine whether traffic to a database instance is being rejected before it reaches the database, without capturing any payload. What should be enabled?",
  "o":["VPC Flow Logs on the interface, queried for REJECT entries",
       "VPC Traffic Mirroring to an inspection appliance","CloudTrail data events for RDS","Route 53 Resolver query logging"],
  "a":[0],
  "w":["Correct — flow logs record the accept or reject decision along with source, destination and ports.",
      "Mirroring captures full packets, which the question explicitly does not want.",
      "CloudTrail records API calls, not network traffic.",
      "Resolver logs record DNS queries, not connection outcomes."],
  "x":"Flow logs are the standard first step for connectivity troubleshooting: a REJECT entry confirms a security group or NACL is responsible, and the ports narrow it down."},
 {"m":"vpc-subnets",
  "q":"A subnet's instances have public IP addresses but cannot be reached from the internet. What is the most likely cause?",
  "o":["The subnet's route table has no route to an internet gateway",
       "The instances need Elastic IPs instead","The VPC CIDR is too small","DNS hostnames are disabled on the VPC"],
  "a":[0],
  "w":["Correct — a public address is only usable when the subnet routes to an internet gateway.",
      "An Elastic IP behaves the same way and would not help without the route.",
      "CIDR size affects how many addresses exist, not reachability.",
      "DNS hostnames affect name resolution, not routing."],
  "x":"This is the definition being tested: public addressing plus a route to an internet gateway. Either half missing means no inbound reachability."},
 {"m":"private-connectivity",
  "q":"A partner must consume an internal service hosted in your VPC without any VPC peering and without exposing it to the internet. What provides this?",
  "o":["An endpoint service behind a Network Load Balancer, consumed through PrivateLink",
       "A VPC peering connection restricted by route tables","A gateway endpoint in the partner's VPC","A Site-to-Site VPN between the two VPCs"],
  "a":[0],
  "w":["Correct — PrivateLink exposes a single service through an interface endpoint without joining the networks.",
      "Peering is explicitly excluded, and it also joins the whole address space.",
      "Gateway endpoints only serve S3 and DynamoDB.",
      "A VPN between VPCs is unnecessary and again connects entire networks."],
  "x":"PrivateLink's advantage over peering is scope: it publishes one service rather than routing between two networks, and overlapping CIDRs are not a problem."},
 {"m":"visibility-cost",
  "q":"Two chatty microservices exchange large volumes of data and the inter-Availability Zone transfer charges are significant, though the architecture must stay highly available. What is a reasonable change?",
  "o":["Keep the chatty pair's instances within the same Availability Zone while retaining capacity in others",
       "Route the traffic through a NAT gateway","Move both services to public subnets","Send the traffic through a Transit Gateway"],
  "a":[0],
  "w":["Correct — same-zone private traffic is free, and availability is preserved by keeping capacity in other zones.",
      "NAT adds a per-gigabyte charge and is for outbound internet traffic.",
      "Public subnets do not reduce cross-zone charges and increase exposure.",
      "A Transit Gateway adds attachment and processing charges for traffic inside one VPC."],
  "x":"Cross-zone charges apply in both directions, so zone-aware placement is a genuine lever. The trade-off against resilience is what makes it an architectural decision rather than an obvious win."},
 {"m":"vpc-subnets",
  "q":"An IPv6-only workload in a private subnet must make outbound calls to the internet but never receive inbound connections. What should be used?",
  "o":["An egress-only internet gateway","A NAT gateway","An internet gateway with a restrictive NACL","A NAT instance with IPv6 forwarding"],
  "a":[0],
  "w":["Correct — the egress-only internet gateway is the IPv6 equivalent of NAT for outbound-only traffic.",
      "NAT gateways handle IPv4 only.",
      "A plain internet gateway allows inbound connections, which the requirement forbids.",
      "NAT instances are legacy and do not provide IPv6 egress-only semantics."],
  "x":"IPv6 addresses on AWS are all publicly routable, so outbound-only behaviour needs a dedicated component — the egress-only internet gateway."}
]
}
