# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 20,
"nm": "Disaster recovery and migration",
"tag": "Resilience",
"modules": [
{
 "id": "rto-rpo",
 "nm": "RTO, RPO and the four strategies",
 "goal": "Convert a recovery objective into the cheapest strategy that meets it.",
 "min": 8,
 "blocks": [
  {"t":"split","cols":[
   {"nm":"RTO — Recovery Time Objective","items":["How long you may be **down**","Measured forward from the failure","Driven by how ready the standby is"]},
   {"nm":"RPO — Recovery Point Objective","items":["How much **data** you may lose","Measured backward from the failure","Driven by how often you replicate"]}]},
  {"t":"table","head":["Strategy","RTO","RPO","What is running"],
   "rows":[
    ["**Backup and restore**","Hours","Hours","Nothing — restore from backups when needed. Cheapest"],
    ["**Pilot light**","Tens of minutes","Minutes","Only the core, usually a replicated database. Everything else is off"],
    ["**Warm standby**","Minutes","Seconds","A **scaled-down but working** copy, ready to scale up"],
    ["**Multi-site active-active**","Near zero","Near zero","Full capacity in both regions, both serving. Most expensive"]]},
  {"t":"key","x":"Match the strategy to the objective and stop. If hours of downtime are acceptable, backup and restore is the correct answer — proposing active-active is wrong because it costs far more than the requirement justifies."},
  {"t":"flow","x":["What is the RTO?","What is the RPO?","Cheapest strategy that meets both","Test it"]},
  {"t":"h","x":"Recognising them in a question"},
  {"t":"dtree","x":[
   ["\"We can be down for a few hours\"","Backup and restore"],
   ["\"Back within about half an hour\"","Pilot light"],
   ["\"Only a few minutes of downtime\"","Warm standby"],
   ["\"No downtime, both regions serve traffic\"","Multi-site active-active"],
   ["\"A day of data loss is acceptable\"","Daily snapshots copied cross-region"],
   ["\"We cannot lose more than a few seconds\"","Continuous replication"]]},
  {"t":"trap","x":"A **pilot light** has the database replicating but the application servers switched off. A **warm standby** has everything running small. Mixing those two up is the most common error in this subject."}
 ],
 "checks":[
  {"q":"A business accepts up to four hours of downtime and four hours of data loss. Which strategy is appropriate?",
   "o":["Backup and restore","Pilot light","Warm standby","Multi-site active-active"],
   "a":[0],
   "x":"Objectives measured in hours are met by restoring from backups, which is by far the cheapest option. Anything warmer spends money to beat a target that does not require it."},
  {"q":"What distinguishes a pilot light from a warm standby?",
   "o":["A pilot light keeps only the core running, such as a replicated database; a warm standby runs a scaled-down full copy",
        "A pilot light runs at full capacity","A warm standby keeps nothing running",
        "They are the same strategy under two names"],
   "a":[0],
   "x":"The difference is what is switched on. A pilot light must launch and configure the application tier at failover; a warm standby only has to scale it up."},
  {"q":"Which objective describes how much data may be lost?",
   "o":["RPO","RTO","MTTR","SLA"],
   "a":[0],
   "x":"The Recovery Point Objective is measured backwards from the failure to the last usable copy of the data. RTO measures how long recovery may take."},
  {"q":"A requirement states near-zero downtime with both regions serving users. Which strategy?",
   "o":["Multi-site active-active","Warm standby","Pilot light","Backup and restore"],
   "a":[0],
   "x":"Only an active-active deployment has both regions serving live traffic, which is what removes the failover delay entirely — at the highest cost."}
 ]
},
{
 "id":"building-dr",
 "nm":"Building the recovery path",
 "goal":"Name the replication and failover mechanism for each part of a stack.",
 "min":7,
 "blocks":[
  {"t":"table","head":["Layer","Mechanism"],
   "rows":[
    ["S3 data","**Cross-region replication**, or Batch Replication for existing objects"],
    ["EBS volumes","Snapshots copied to the second region, scheduled with Data Lifecycle Manager or AWS Backup"],
    ["RDS","Cross-region read replica, or copied automated snapshots"],
    ["Aurora","**Global Database** — sub-second lag, promotion in about a minute"],
    ["DynamoDB","**Global Tables** — multi-region, multi-active"],
    ["AMIs and images","Copy the AMI to the second region in advance"],
    ["Infrastructure","**CloudFormation** so the standby can be rebuilt identically"],
    ["Traffic","Route 53 failover records, or Global Accelerator for faster switching"]]},
  {"t":"key","x":"**AWS Backup** centralises backup plans and retention across services and accounts, with **Backup Vault Lock** making backups immutable. It is the answer for an organisation-wide backup requirement."},
  {"t":"h","x":"Failing traffic over"},
  {"t":"split","cols":[
   {"nm":"Route 53 failover","items":["Health-checked primary and secondary","Recovery limited by TTL and check interval","Works with any endpoint"]},
   {"nm":"Global Accelerator","items":["Static anycast IPs, no DNS change","Failover in about a minute","Traffic dials for gradual shifts"]}]},
  {"t":"h","x":"Things people forget"},
  {"t":"list","x":[
   "Service quotas in the standby region must be raised **in advance**, or the failover cannot scale.",
   "Certificates, secrets and KMS keys must exist in the second region too.",
   "A recovery plan that has never been tested is an assumption, not a plan.",
   "**Elastic Disaster Recovery (DRS)** continuously replicates whole servers, on-premises or in AWS, for a low RPO without rearchitecting."]},
  {"t":"trap","x":"S3 replication copies only objects written **after** it is enabled. A disaster recovery design that assumes the existing objects replicated automatically is wrong until Batch Replication is run."}
 ],
 "checks":[
  {"q":"A relational workload must fail over to another region in about a minute with minimal data loss. What fits?",
   "o":["Aurora Global Database","Daily RDS snapshot copies","A same-region read replica",
        "S3 cross-region replication"],
   "a":[0],
   "x":"Global Database replicates in under a second and a secondary region can be promoted in roughly a minute, which is the tightest cross-region option for relational data."},
  {"q":"Backups across many accounts and services must follow one policy with immutable retention. What provides this?",
   "o":["AWS Backup with Backup Vault Lock","EBS snapshots taken by a cron job",
        "S3 versioning in each account","Manual RDS snapshots"],
   "a":[0],
   "x":"AWS Backup applies plans centrally across services and accounts, and Vault Lock prevents backups being deleted before their retention expires, even by an administrator."},
  {"q":"Which detail is commonly forgotten when preparing a standby region?",
   "o":["Service quotas must be raised there in advance","The region must be in the same continent",
        "Backups must be unencrypted to restore","Route 53 must be disabled during failover"],
   "a":[0],
   "x":"Default quotas in an unused region are low, so a failover that needs to launch hundreds of instances fails. Raising quotas ahead of time is part of preparing the plan."},
  {"q":"Whole servers must be replicated continuously from on premises with a low recovery point, without rearchitecting the application. Which service?",
   "o":["AWS Elastic Disaster Recovery","AWS Backup","S3 cross-region replication",
        "Aurora Global Database"],
   "a":[0],
   "x":"DRS performs continuous block-level replication of servers into AWS and launches them on demand, which suits lift-and-shift recovery without changing the application."}
 ]
},
{
 "id":"migration-tools",
 "nm":"Migration tools",
 "goal":"Pick the service that moves servers, databases or files into AWS.",
 "min":7,
 "blocks":[
  {"t":"table","head":["Service","Moves"],
   "rows":[
    ["**Application Migration Service (MGN)**","Whole servers, by continuous block replication — the standard **lift and shift**"],
    ["**Database Migration Service (DMS)**","Databases, with the source staying online during the migration"],
    ["**Schema Conversion Tool (SCT)**","The schema and code, when the engine changes — Oracle to PostgreSQL, for example"],
    ["**DataSync**","Files and objects, on a schedule, with verification"],
    ["**Snow Family**","Bulk data physically, when the network cannot carry it"],
    ["**Transfer Family**","Ongoing inbound SFTP, FTPS, FTP or AS2"]]},
  {"t":"key","x":"**Same engine → DMS alone. Different engine → SCT to convert, then DMS to move the data.** That pairing is asked about repeatedly."},
  {"t":"h","x":"DMS in practice"},
  {"t":"list","x":[
   "A replication instance runs the task between a source and a target endpoint.",
   "**Full load plus change data capture** keeps the target current while the source stays live, so the cutover is short.",
   "Sources and targets can be on premises, on EC2, or managed services — and the two need not match.",
   "Continuous replication can also feed a data lake or a stream."]},
  {"t":"flow","x":["Assess","Mobilise","Migrate with MGN or DMS","Validate","Cut over","Optimise"]},
  {"t":"h","x":"The seven strategies"},
  {"t":"table","head":["Strategy","Meaning"],
   "rows":[
    ["Rehost","Lift and shift, unchanged — MGN"],
    ["Replatform","Small optimisations, such as moving to RDS"],
    ["Refactor","Rearchitect, typically to serverless or containers"],
    ["Repurchase","Move to a SaaS product instead"],
    ["Retire","Switch it off"],
    ["Retain","Leave it where it is for now"],
    ["Relocate","Move VMware workloads without conversion"]]},
  {"t":"trap","x":"**\"No code changes\" or \"as quickly as possible\" means rehost with MGN.** Refactoring to serverless is the wrong answer when the question stresses speed or an unchanged application."}
 ],
 "checks":[
  {"q":"An Oracle database must move to Aurora PostgreSQL. Which combination is correct?",
   "o":["Schema Conversion Tool to convert, then DMS to move the data",
        "DMS alone","MGN alone","DataSync followed by a restore"],
   "a":[0],
   "x":"A change of engine means the schema and stored code must be converted first, which is SCT's job. DMS then moves and continuously replicates the data."},
  {"q":"Two hundred virtual machines must move to EC2 with no application changes and minimal downtime. Which service?",
   "o":["AWS Application Migration Service","AWS Database Migration Service",
        "AWS DataSync","AWS Transfer Family"],
   "a":[0],
   "x":"MGN replicates whole servers continuously and cuts over with minimal downtime, which is the definition of a rehost. The others move databases or files, not servers."},
  {"q":"What does change data capture add to a DMS migration?",
   "o":["The target stays current with the live source, so the cutover window is short",
        "It converts the schema automatically","It compresses the data in transit",
        "It encrypts the target database"],
   "a":[0],
   "x":"After the full load, CDC continuously applies changes from the source, so the application can keep running until a brief cutover."},
  {"q":"Which migration strategy is named rehost?",
   "o":["Lift and shift with no application changes","Rearchitecting to serverless",
        "Replacing the application with a SaaS product","Switching the application off"],
   "a":[0],
   "x":"Rehost moves the workload as it is. Refactor rearchitects it, repurchase replaces it with SaaS, and retire decommissions it."}
 ]
},
{
 "id":"hybrid-ops",
 "nm":"Running across both worlds",
 "goal":"Keep on-premises and AWS working together during and after a migration.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Need","Service"],
   "rows":[
    ["Network path during migration","Site-to-Site VPN now, Direct Connect when provisioned"],
    ["Name resolution both ways","Route 53 Resolver inbound and outbound endpoints"],
    ["Keep on-premises applications, store in AWS","Storage Gateway"],
    ["Managed AWS infrastructure in your data centre","AWS Outposts"],
    ["Containers on premises, one control plane","ECS Anywhere or EKS Anywhere"],
    ["Patch and manage servers in both places","Systems Manager with the hybrid activation"],
    ["VMware workloads moved without conversion","VMware Cloud on AWS"]]},
  {"t":"key","x":"**Outposts** is the answer when a workload must stay physically on site — for latency to local equipment or for data residency — while still using AWS APIs."},
  {"t":"h","x":"Testing the plan"},
  {"t":"list","x":[
   "Run a **game day**: fail over deliberately and measure the actual RTO and RPO.",
   "Rebuild the standby from **CloudFormation** to prove the template is complete.",
   "Check that alarms, runbooks and on-call routing work in the standby region too.",
   "Confirm quotas, certificates, secrets and KMS keys exist before you need them."]},
  {"t":"flow","x":["Document RTO and RPO","Build the recovery path","Test by failing over","Fix what the test revealed","Repeat"]},
  {"t":"trap","x":"Latency to local machinery is not solved by a nearby region. Sub-millisecond requirements on a factory floor point at **Outposts** or a **Local Zone**, not at a closer AWS region."}
 ],
 "checks":[
  {"q":"A factory needs AWS services running physically on site because of sub-millisecond latency to local equipment. What fits?",
   "o":["AWS Outposts","A Direct Connect to the nearest region","A Site-to-Site VPN",
        "A CloudFront edge location"],
   "a":[0],
   "x":"Outposts places AWS-managed infrastructure in your own data centre with the same APIs. No network link to a region can meet a sub-millisecond requirement to local equipment."},
  {"q":"On-premises servers must be patched and inventoried alongside EC2 instances from one place. What provides this?",
   "o":["Systems Manager with hybrid activations","AWS Config aggregators",
        "CloudWatch dashboards","AWS Backup"],
   "a":[0],
   "x":"A hybrid activation registers on-premises servers as managed nodes, so Patch Manager, Inventory and Run Command work across both environments."},
  {"q":"What is the point of a disaster recovery game day?",
   "o":["To measure the real RTO and RPO by failing over deliberately",
        "To reduce the cost of the standby region","To replace the need for backups",
        "To satisfy a billing requirement"],
   "a":[0],
   "x":"An untested plan is an assumption. Deliberate failover reveals missing quotas, stale templates and broken runbooks while there is still time to fix them."},
  {"q":"During a migration, VPC resources must resolve names held by the on-premises DNS. What is deployed?",
   "o":["A Route 53 Resolver outbound endpoint with forwarding rules","An inbound endpoint",
        "A private hosted zone only","A NAT gateway for DNS"],
   "a":[0],
   "x":"The outbound endpoint forwards queries from the VPC to on-premises resolvers. The inbound endpoint handles the opposite direction."}
 ]
}
],
"recap":[
 {"t":"h","x":"Strategy by objective"},
 {"t":"table","head":["RTO and RPO","Strategy","Cost"],
  "rows":[["Hours","Backup and restore","Lowest"],
          ["Tens of minutes","Pilot light","Low"],
          ["Minutes","Warm standby","Medium"],
          ["Near zero","Multi-site active-active","Highest"]]},
 {"t":"key","x":"Pick the cheapest strategy that meets the stated objectives. Over-engineering is marked wrong just as firmly as under-engineering."},
 {"t":"h","x":"Replication by layer"},
 {"t":"table","head":["Layer","Mechanism"],
  "rows":[["S3","Cross-region replication, plus Batch Replication for existing objects"],
          ["EBS","Snapshots copied cross-region on a schedule"],
          ["RDS","Cross-region read replica or copied snapshots"],
          ["Aurora","Global Database"],
          ["DynamoDB","Global Tables"],
          ["Whole servers","Elastic Disaster Recovery"],
          ["Infrastructure","CloudFormation templates"],
          ["Traffic","Route 53 failover, or Global Accelerator"]]},
 {"t":"h","x":"Migration tools"},
 {"t":"dtree","x":[
  ["Whole servers, no code changes","Application Migration Service"],
  ["Database, same engine","DMS"],
  ["Database, different engine","SCT then DMS"],
  ["Files on a schedule","DataSync"],
  ["Too much data for the network","Snow Family"],
  ["Ongoing partner file uploads","Transfer Family"],
  ["VMware without conversion","VMware Cloud on AWS"]]},
 {"t":"h","x":"Hybrid"},
 {"t":"split","cols":[
  {"nm":"Network and names","items":["VPN now, Direct Connect later","Resolver inbound and outbound endpoints"]},
  {"nm":"Compute and data on site","items":["Outposts for AWS infrastructure locally","Storage Gateway for hybrid storage","ECS or EKS Anywhere for containers"]},
  {"nm":"Operations","items":["Systems Manager hybrid activations","AWS Backup across accounts","Game days to test the plan"]}]},
 {"t":"trap","x":"Recurring distractors: active-active proposed for an objective measured in hours; pilot light and warm standby swapped; DMS alone across different engines; refactoring proposed where the question says no code changes; and S3 replication assumed to copy existing objects."}
],
"final":[
 {"m":"rto-rpo",
  "q":"A back-office system may be unavailable for up to six hours and may lose up to six hours of data. Which recovery strategy should be chosen?",
  "o":["Backup and restore with regular cross-region snapshot copies",
       "Warm standby in a second region","Multi-site active-active","Pilot light with a replicated database"],
  "a":[0],
  "w":["Correct — objectives measured in hours are met by restoring from backups at a fraction of the cost.",
      "A warm standby runs continuously and spends money to beat a target nobody asked for.",
      "Active-active is the most expensive option and far exceeds the requirement.",
      "A pilot light also runs continuous replication that these objectives do not need."],
  "x":"Cost is part of correctness here. The exam expects the cheapest strategy that satisfies the stated RTO and RPO, and over-engineering is marked wrong."},
 {"m":"building-dr",
  "q":"A payments platform must survive the loss of a region with under a minute of downtime and no more than a second of data loss, on a PostgreSQL-compatible database. What should be used?",
  "o":["Aurora Global Database with a secondary region",
       "RDS Multi-AZ in the primary region","Cross-region snapshot copies every hour","A read replica in the same region"],
  "a":[0],
  "w":["Correct — replication lag is typically under a second and promotion takes about a minute.",
      "Multi-AZ survives a zone failure, not a regional one.",
      "Hourly snapshots mean up to an hour of data loss and a long restore.",
      "A same-region replica disappears with the region."],
  "x":"Cross-region relational recovery in about a minute is Aurora Global Database's defining case. Everything else on the list operates at a much looser objective."},
 {"m":"migration-tools",
  "q":"A company is migrating an Oracle database to Amazon Aurora PostgreSQL with minimal downtime. What is the correct approach?",
  "o":["Convert the schema with SCT, then run DMS with full load and change data capture",
       "Run DMS alone with change data capture","Use Application Migration Service to move the database server","Export to S3 with DataSync and import into Aurora"],
  "a":[0],
  "w":["Correct — the engine change requires schema conversion first, then DMS moves and keeps the data current.",
      "DMS moves data but does not convert schema objects and stored code between engines.",
      "MGN rehosts servers, which would leave Oracle running on EC2 rather than migrating to Aurora.",
      "File transfer does not convert or continuously replicate a live database."],
  "x":"Same engine means DMS alone; different engine means SCT then DMS. Change data capture is what keeps the cutover window short in both cases."},
 {"m":"rto-rpo",
  "q":"A design keeps a replicated database running in a second region while all application servers there remain switched off, to be launched on failover. What is this called?",
  "o":["Pilot light","Warm standby","Multi-site active-active","Backup and restore"],
  "a":[0],
  "w":["Correct — only the core is alight; the rest is started when needed.",
      "A warm standby runs a scaled-down but working copy of the whole stack.",
      "Active-active serves live traffic from both regions.",
      "Backup and restore keeps nothing running at all."],
  "x":"The distinction between pilot light and warm standby is precisely what is running. Pilot light must launch and configure the application tier at failover; warm standby only scales it."},
 {"m":"building-dr",
  "q":"After enabling S3 cross-region replication as part of a recovery plan, an audit finds that objects older than the configuration date are missing from the destination. What is needed?",
  "o":["Run S3 Batch Replication for the existing objects",
       "Enable versioning on the destination bucket","Recreate the replication rule with a prefix filter","Switch the destination to the same region"],
  "a":[0],
  "w":["Correct — replication applies only to objects written after it is enabled, and Batch Replication copies the rest.",
      "Versioning is already required for replication to have been configured at all.",
      "A prefix filter narrows scope rather than reaching backwards in time.",
      "Region choice does not change the forward-only behaviour."],
  "x":"This catches recovery plans silently: the configuration looks correct and the destination is simply incomplete until Batch Replication has run."},
 {"m":"migration-tools",
  "q":"Three hundred virtual machines must move to AWS quickly with no changes to the applications, and the business wants the shortest possible cutover. Which approach fits?",
  "o":["Rehost with AWS Application Migration Service, cutting over after continuous replication",
       "Refactor the applications to containers as they move","Replatform every database to RDS first","Export each machine to an AMI manually"],
  "a":[0],
  "w":["Correct — MGN replicates servers continuously and cuts over in minutes, which is what a rehost requires.",
      "Refactoring is the slowest path and contradicts the no-changes requirement.",
      "Replatforming databases first adds work and risk to a migration that must be fast.",
      "Manual image export at this scale is slow and error prone."],
  "x":"\"No application changes\" and \"quickly\" together define rehosting. Optimisation happens after the migration, which is the standard order in AWS migration guidance."},
 {"m":"hybrid-ops",
  "q":"A hospital must keep patient data physically within its own building for regulatory reasons, while using AWS services and APIs to process it. What fits?",
  "o":["AWS Outposts installed in the hospital's data centre",
       "A Direct Connect to the nearest AWS region","A Local Zone in the nearest city","Storage Gateway with a local cache"],
  "a":[0],
  "w":["Correct — Outposts places AWS-managed infrastructure on site so the data never leaves the building.",
      "A private link still moves the data into a region, which the regulation forbids.",
      "A Local Zone is closer but still outside the hospital's premises.",
      "A gateway caches locally but stores the authoritative copy in AWS."],
  "x":"Data residency down to the building, combined with a requirement for AWS APIs, is what Outposts exists for. Latency to local equipment is the other common driver."},
 {"m":"building-dr",
  "q":"An organisation with forty accounts must apply one backup policy across EC2, RDS and DynamoDB, with retention that nobody can shorten. What should be used?",
  "o":["AWS Backup with backup policies in Organizations and Backup Vault Lock",
       "Per-service scheduled snapshots in each account","S3 versioning with MFA Delete","AWS Config rules that create snapshots"],
  "a":[0],
  "w":["Correct — Backup applies plans across services and accounts, and Vault Lock makes retention immutable.",
      "Per-service scripts in forty accounts drift and are hard to prove compliant.",
      "Versioning protects S3 objects only and is not a backup policy.",
      "Config detects and remediates configuration; it is not a backup engine."],
  "x":"AWS Backup plus organisation-level backup policies is the centralised answer, and Vault Lock is what satisfies \"nobody can shorten it\"."},
 {"m":"hybrid-ops",
  "q":"A recovery plan has existed for two years and has never been exercised. What is the most important next step?",
  "o":["Run a game day, failing over deliberately and measuring the real RTO and RPO",
       "Increase the backup retention period","Add a third region to the plan","Move the standby to a cheaper instance family"],
  "a":[0],
  "w":["Correct — testing is what turns an assumption into a plan, and it usually reveals missing quotas and stale templates.",
      "Longer retention does not confirm the plan works.",
      "Adding regions multiplies untested complexity.",
      "Cost tuning an untested standby optimises something that may not function."],
  "x":"The most common real-world failure is a plan that has never been run. A game day measures actual objectives rather than intended ones, and surfaces the gaps while it is safe."},
 {"m":"migration-tools",
  "q":"During a migration, a live production database must keep serving traffic while its data is copied to AWS, with only a short cutover at the end. Which DMS capability provides this?",
  "o":["Full load followed by ongoing change data capture",
       "Schema conversion with SCT","A one-time export and import","Snowball shipment of the database files"],
  "a":[0],
  "w":["Correct — CDC applies changes continuously after the initial load, so the target stays current until cutover.",
      "SCT converts schemas between engines and does not keep data in sync.",
      "A one-time export means the target is stale from the moment it completes.",
      "Physical shipment adds days of staleness and is for bulk transfer, not live databases."],
  "x":"Full load plus CDC is what makes a near-zero-downtime database migration possible, and it works whether the engines match or SCT has converted the schema first."}
]
}
