# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 21,
"nm": "Other services worth knowing",
"tag": "Operations",
"modules": [
{
 "id": "cloudformation",
 "nm": "CloudFormation and infrastructure as code",
 "goal": "Describe what a template gives you and how stacks are organised at scale.",
 "min": 7,
 "blocks": [
  {"t":"p","x":"**CloudFormation** creates resources from a template. The template is the source of truth: the same file produces the same environment in any account or region."},
  {"t":"table","head":["Concept","Meaning"],
   "rows":[
    ["Template","JSON or YAML describing resources, parameters and outputs"],
    ["Stack","One deployment of a template; deleting it removes the resources it created"],
    ["**Change set**","A preview of what an update would do **before** it does it"],
    ["**Drift detection**","Finds resources changed outside CloudFormation"],
    ["**StackSets**","Deploys one template across many accounts and regions"],
    ["Nested stacks","A stack that creates other stacks, for reuse"]]},
  {"t":"key","x":"**StackSets** is the answer for deploying the same baseline into many accounts and regions at once. **Change sets** are the answer for previewing a risky update."},
  {"t":"h","x":"Behaviour worth knowing"},
  {"t":"list","x":[
   "A failed create **rolls back** by default, removing what it made.",
   "A **deletion policy** of `Retain` keeps a resource — usually a database or bucket — when the stack is deleted.",
   "**Stack policies** protect specific resources from being updated accidentally.",
   "A **service role** lets CloudFormation act with permissions the deploying user does not have."]},
  {"t":"flow","x":["Template in version control","Change set previews the update","Stack applies it","Drift detection confirms nothing diverged"]},
  {"t":"h","x":"The related services"},
  {"t":"table","head":["Service","Role"],
   "rows":[
    ["**CDK**","Write infrastructure in a programming language; it produces CloudFormation"],
    ["**SAM**","A shorthand template for serverless applications"],
    ["**Service Catalog**","Approved products that users may launch without needing the underlying permissions"],
    ["**Elastic Beanstalk**","An application platform that builds and manages the environment for you"]]},
  {"t":"trap","x":"Deleting a stack deletes its resources. When a question worries about losing a production database on stack deletion, the answer is a **deletion policy of Retain**, not a backup after the fact."}
 ],
 "checks":[
  {"q":"The same security baseline must be deployed into eighty accounts across three regions. What fits?",
   "o":["CloudFormation StackSets","One stack per account, created by hand","Nested stacks in a single account",
        "A change set applied to the organisation"],
   "a":[0],
   "x":"StackSets deploy and maintain one template across many accounts and regions from a single operation, which is exactly an organisation-wide baseline."},
  {"q":"An update to a production stack must be reviewed before anything changes. What provides that?",
   "o":["A change set","Drift detection","A stack policy","A deletion policy"],
   "a":[0],
   "x":"A change set lists exactly which resources would be added, modified or replaced, so a risky replacement can be spotted before execution."},
  {"q":"A database created by a stack must survive if the stack is deleted. What achieves this?",
   "o":["A deletion policy of Retain on that resource","A stack policy denying updates",
        "Drift detection","Nested stacks"],
   "a":[0],
   "x":"The deletion policy tells CloudFormation to leave the resource in place when the stack goes away, which is standard practice for databases and buckets."},
  {"q":"What does drift detection report?",
   "o":["Resources that were changed outside CloudFormation","Which stacks cost the most",
        "Which templates are out of date","Whether a change set has been applied"],
   "a":[0],
   "x":"Drift compares the live configuration with the template's expectation, which is how manual console changes are discovered."}
 ]
},
{
 "id":"systems-manager",
 "nm":"Systems Manager",
 "goal":"Operate a fleet without SSH, and store configuration safely.",
 "min":7,
 "blocks":[
  {"t":"table","head":["Capability","What it does"],
   "rows":[
    ["**Session Manager**","A shell with **no open ports, no bastion, no keys**, fully audited"],
    ["**Run Command**","Runs a command across many instances at once"],
    ["**Patch Manager**","Scans and patches on a schedule, with baselines and maintenance windows"],
    ["**Parameter Store**","Configuration and secrets, with SecureString values encrypted by KMS"],
    ["**Automation**","Runbooks that perform multi-step operational tasks, including Config remediation"],
    ["**Inventory** and **State Manager**","What is installed, and keeping instances in a defined state"],
    ["**Fleet Manager**","A console view of instances, including file systems and logs"]]},
  {"t":"key","x":"**Session Manager** is the answer to \"administrators need shell access with no inbound ports and no bastion host\". It works because the SSM agent connects outwards."},
  {"t":"h","x":"What an instance needs"},
  {"t":"list","x":[
   "The **SSM agent** — preinstalled on current Amazon Linux and Windows images.",
   "An **instance profile** granting the managed policy for Systems Manager.",
   "A network path to the Systems Manager endpoints: an internet route, or **interface VPC endpoints** for a fully private subnet.",
   "On-premises servers join through a **hybrid activation**."]},
  {"t":"flow","x":["Agent connects outward to Systems Manager","Administrator starts a session","Commands are relayed","Every session logged to CloudTrail, S3 or CloudWatch Logs"]},
  {"t":"trap","x":"An instance that does not appear as a managed node is almost always missing the **instance profile** or the **network path to the endpoints** — not the agent, which is usually preinstalled."}
 ],
 "checks":[
  {"q":"Administrators need shell access to instances with no inbound ports open and no bastion host. What provides it?",
   "o":["Systems Manager Session Manager","SSH through an internet gateway",
        "EC2 Instance Connect","A VPN to each instance"],
   "a":[0],
   "x":"The SSM agent makes an outbound connection and the session is brokered by AWS, so nothing needs to listen on the instance. Every session is also logged for audit."},
  {"q":"An instance does not appear as a managed node in Systems Manager. What should you check first?",
   "o":["Its instance profile and its network path to the Systems Manager endpoints",
        "Its key pair","Its placement group","Its Elastic IP"],
   "a":[0],
   "x":"The agent is usually preinstalled, so the common causes are a missing instance profile or no route to the endpoints — which private subnets solve with interface VPC endpoints."},
  {"q":"Hundreds of instances must be patched on a schedule with defined maintenance windows. Which capability?",
   "o":["Patch Manager","Run Command","Session Manager","Fleet Manager"],
   "a":[0],
   "x":"Patch Manager applies baselines on a schedule within maintenance windows and reports compliance. Run Command executes ad-hoc commands rather than managing patch state."},
  {"q":"Where should a non-secret configuration value with version history be stored?",
   "o":["SSM Parameter Store","An environment variable baked into the AMI",
        "A file on each instance","A CloudFormation output only"],
   "a":[0],
   "x":"Parameter Store keeps hierarchical parameters with version history and is free in the standard tier, so configuration can change without rebuilding images."}
 ]
},
{
 "id":"cost-services",
 "nm":"Seeing and controlling spend",
 "goal":"Name the tool that answers a cost question and the one that prevents a surprise.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Tool","Answers"],
   "rows":[
    ["**Cost Explorer**","Where did the money go, and what will it be next month?"],
    ["**AWS Budgets**","Alert me before spend or usage passes a threshold — and optionally take an action"],
    ["**Cost Anomaly Detection**","Tell me when spend changes in a way it usually does not"],
    ["**Cost and Usage Report**","The full detail, in S3, for analysis with Athena or QuickSight"],
    ["**Compute Optimizer**","Which resources are the wrong size?"],
    ["**Trusted Advisor**","Checks across cost, security, fault tolerance, performance and quotas"]]},
  {"t":"key","x":"**Budgets prevents surprises; Cost Explorer explains them.** A question about being alerted in advance is Budgets, and one about analysing what already happened is Cost Explorer."},
  {"t":"h","x":"Tagging"},
  {"t":"list","x":[
   "**Cost allocation tags** must be activated in the billing console before they appear in reports.",
   "**Tag policies** in Organizations enforce consistent tag keys and values.",
   "Untagged resources are the usual reason a cost breakdown does not add up."]},
  {"t":"h","x":"Structural savings"},
  {"t":"table","head":["Lever","Where"],
   "rows":[
    ["Savings Plans and Reserved Instances","Steady compute and database usage"],
    ["Spot","Interruptible compute"],
    ["S3 lifecycle rules and Intelligent-Tiering","Storage that cools over time"],
    ["Right-sizing from Compute Optimizer","Over-provisioned instances"],
    ["Gateway endpoints instead of NAT","Networking"],
    ["Log retention periods","CloudWatch Logs"]]},
  {"t":"trap","x":"A Budget **alert** only notifies. To actually stop spend, a budget **action** must be attached — for example applying a restrictive policy or stopping instances."}
 ],
 "checks":[
  {"q":"A team must be alerted before monthly spend exceeds a threshold. Which tool?",
   "o":["AWS Budgets","Cost Explorer","Cost and Usage Report","Compute Optimizer"],
   "a":[0],
   "x":"Budgets sets thresholds on cost or usage and notifies before they are crossed, including forecasted spend. Cost Explorer analyses what has already happened."},
  {"q":"Which service recommends smaller instance types for over-provisioned workloads?",
   "o":["AWS Compute Optimizer","AWS Budgets","AWS Trusted Advisor quotas checks",
        "Cost Anomaly Detection"],
   "a":[0],
   "x":"Compute Optimizer analyses utilisation metrics and recommends right-sized configurations for EC2, EBS, Lambda and Auto Scaling groups."},
  {"q":"Why might a cost breakdown by team be incomplete?",
   "o":["Cost allocation tags were never activated, or resources are untagged",
        "Cost Explorer only reports on EC2","Budgets overwrite tag data",
        "Trusted Advisor hides tagged resources"],
   "a":[0],
   "x":"Tags only appear in cost reports once activated as cost allocation tags in the billing console, and untagged resources land in an unallocated bucket."},
  {"q":"What must be configured for a budget to stop spend rather than just warn about it?",
   "o":["A budget action, such as applying a restrictive policy","A lower threshold",
        "A second notification address","A cost anomaly monitor"],
   "a":[0],
   "x":"Alerts are informational. Budget actions apply a policy, stop instances, or otherwise intervene when the threshold is crossed."}
 ]
},
{
 "id":"misc-services",
 "nm":"The rest of the catalogue",
 "goal":"Recognise the one-line purpose of the services that appear once in an exam.",
 "min":6,
 "blocks":[
  {"t":"table","head":["Service","One sentence"],
   "rows":[
    ["**Step Functions**","Orchestrates a workflow across services with retries, branching and waits — the answer when a long process has steps"],
    ["**AWS Batch**","Runs batch jobs on managed compute, including Spot, with a queue"],
    ["**Amazon SES**","Sends transactional and bulk email"],
    ["**Amazon Pinpoint**","Customer engagement campaigns across email, SMS and push"],
    ["**AWS Amplify**","Hosting and backend for web and mobile front ends"],
    ["**AWS Glue DataBrew**","Visual data preparation without writing code"],
    ["**Amazon WorkSpaces**","Managed virtual desktops"],
    ["**AWS Fault Injection Service**","Deliberate failure experiments — chaos engineering"]]},
  {"t":"key","x":"**Step Functions** is the answer whenever a process has several steps, needs retries, or must wait — especially when the alternative is a Lambda function that would exceed fifteen minutes."},
  {"t":"h","x":"Step Functions, a little deeper"},
  {"t":"split","cols":[
   {"nm":"Standard workflows","items":["Up to a year","Exactly-once execution","Full execution history","For long business processes"]},
   {"nm":"Express workflows","items":["Up to five minutes","At-least-once","High volume, low cost","For event processing"]}]},
  {"t":"h","x":"Batch against Lambda"},
  {"t":"table","head":["","AWS Batch","Lambda"],
   "rows":[["Duration","No limit","15 minutes"],
           ["Packaging","A container image","Zip or container"],
           ["Compute","EC2 or Fargate, including Spot","Managed, per invocation"],
           ["Fits","Long-running jobs with a queue","Short event-driven work"]]},
  {"t":"trap","x":"A workflow coordinated by one Lambda function calling others, with its own retry logic, is the wrong answer when **Step Functions** would express it declaratively with built-in retries and error handling."}
 ],
 "checks":[
  {"q":"A process has eight steps with retries, branching and a wait for human approval. What coordinates it?",
   "o":["AWS Step Functions","A single Lambda function calling the others",
        "An SQS queue per step","EventBridge scheduled rules"],
   "a":[0],
   "x":"Step Functions expresses steps, retries, branching and waits declaratively, and keeps an execution history. Building the same logic inside a function makes it fragile and hard to observe."},
  {"q":"Long-running containerised jobs must be queued and run on Spot capacity. Which service?",
   "o":["AWS Batch","AWS Lambda","Amazon SES","AWS Amplify"],
   "a":[0],
   "x":"Batch manages a job queue and provisions compute, including Spot, with no fifteen-minute limit. Lambda cannot run jobs of unbounded duration."},
  {"q":"Which Step Functions workflow type suits very high volume event processing lasting seconds?",
   "o":["Express workflows","Standard workflows","Either, with the same pricing",
        "Neither — use EventBridge"],
   "a":[0],
   "x":"Express workflows run up to five minutes with at-least-once semantics at much lower cost per execution, which suits high-volume short-lived processing."},
  {"q":"A team wants to test how their system behaves when an Availability Zone becomes unavailable. Which service?",
   "o":["AWS Fault Injection Service","AWS Batch","Amazon Pinpoint","AWS Amplify"],
   "a":[0],
   "x":"Fault Injection Service runs controlled experiments that inject real failures, which is how resilience assumptions get tested rather than assumed."}
 ]
}
],
"recap":[
 {"t":"h","x":"Infrastructure as code"},
 {"t":"table","head":["Need","Answer"],
  "rows":[["Same template across many accounts and regions","StackSets"],
          ["Preview an update","Change set"],
          ["Find manual changes","Drift detection"],
          ["Keep a database when the stack is deleted","Deletion policy Retain"],
          ["Write infrastructure in code","CDK, which produces CloudFormation"],
          ["Approved self-service products","Service Catalog"],
          ["Application environment from uploaded code","Elastic Beanstalk"]]},
 {"t":"key","x":"Session Manager for shells without ports. Parameter Store for configuration. Patch Manager for patching on a schedule. Those three cover most Systems Manager questions."},
 {"t":"h","x":"Cost tools"},
 {"t":"table","head":["Question","Tool"],
  "rows":[["Where did the money go?","Cost Explorer"],
          ["Warn me before it happens","Budgets"],
          ["Stop it happening","A budget action"],
          ["This month looks unusual","Cost Anomaly Detection"],
          ["Full line-item detail","Cost and Usage Report"],
          ["Are these resources the right size?","Compute Optimizer"],
          ["General account checks","Trusted Advisor"]]},
 {"t":"h","x":"Orchestration and batch"},
 {"t":"split","cols":[
  {"nm":"Step Functions","items":["Steps, retries, branching, waits","Standard up to a year, Express up to five minutes","Full execution history"]},
  {"nm":"AWS Batch","items":["Queued container jobs","No duration limit","EC2 or Fargate, including Spot"]}]},
 {"t":"flow","x":["Template in git","Change set","Stack or StackSet","Drift detection","Systems Manager operates the result"]},
 {"t":"trap","x":"Recurring distractors: a stack deletion taking a production database with it; Run Command offered where Patch Manager fits; a budget alert described as stopping spend; and hand-built orchestration inside a Lambda where Step Functions belongs."}
],
"final":[
 {"m":"systems-manager",
  "q":"A security policy removes all bastion hosts and forbids inbound ports on production instances, but engineers still need an audited shell. What should be used?",
  "o":["Systems Manager Session Manager with an instance profile and VPC endpoints",
       "EC2 Instance Connect restricted to the office address range","SSH through a NAT gateway","A site-to-site VPN terminating on each instance"],
  "a":[0],
  "w":["Correct — the agent connects outward, so no inbound port is needed, and sessions are logged centrally.",
      "Instance Connect still requires port 22 to be reachable.",
      "NAT gateways carry outbound traffic only and cannot accept an inbound session.",
      "Terminating a VPN on every instance is impractical and still exposes a listener."],
  "x":"Session Manager reverses the connection direction, which is what satisfies \"no inbound ports, no bastion\" while keeping IAM control and a full audit trail."},
 {"m":"cloudformation",
  "q":"A governance team must deploy an identical logging and guardrail stack to every account in the organisation, including accounts created later. What should be used?",
  "o":["CloudFormation StackSets with automatic deployment to the organisation",
       "A nested stack in the management account","A change set applied per account","Service Catalog products launched manually"],
  "a":[0],
  "w":["Correct — StackSets deploy across accounts and regions and can enrol new accounts automatically.",
      "Nested stacks organise templates within one stack, not across accounts.",
      "Change sets preview updates to a single stack.",
      "Manual launches do not guarantee coverage of accounts created later."],
  "x":"Organisation-wide deployment with automatic enrolment of new accounts is what distinguishes StackSets from any per-account approach."},
 {"m":"cost-services",
  "q":"A finance team wants engineering notified at 80% of the monthly budget and wants non-production instances stopped at 100%. What configuration achieves both?",
  "o":["An AWS Budget with a notification at 80% and a budget action at 100%",
       "Cost Explorer reports emailed weekly","Cost Anomaly Detection with a monitor","A Trusted Advisor cost check"],
  "a":[0],
  "w":["Correct — budgets support both notifications and actions that intervene when a threshold is crossed.",
      "Reports explain past spend and cannot act on a threshold.",
      "Anomaly detection finds unusual patterns rather than enforcing a budget.",
      "Trusted Advisor gives recommendations, not automated enforcement."],
  "x":"The distinction between an alert and an action is the point: notifications inform, budget actions apply a policy or stop resources."},
 {"m":"misc-services",
  "q":"An order fulfilment process involves six services, needs retries with backoff, a branch for refunds, and a wait for a manual approval that may take days. What should coordinate it?",
  "o":["AWS Step Functions standard workflow",
       "A Lambda function invoking the others in sequence","An SQS FIFO queue with a consumer per step","EventBridge rules chained together"],
  "a":[0],
  "w":["Correct — standard workflows run for up to a year, support waits and human approval, and handle retries declaratively.",
      "A single function cannot wait for days and would exceed the fifteen-minute limit.",
      "Queues move messages but express no branching or approval logic.",
      "Chained rules give no execution history or coordinated error handling."],
  "x":"Long duration, branching and human approval together make this a textbook Step Functions standard workflow, with the execution history providing observability for free."},
 {"m":"cloudformation",
  "q":"A stack is being deleted after a project ends, but its RDS database must remain for archival reasons. What should have been configured?",
  "o":["A DeletionPolicy of Retain on the database resource",
       "A stack policy denying updates to the database","Drift detection on the stack","A nested stack for the database"],
  "a":[0],
  "w":["Correct — the deletion policy tells CloudFormation to leave the resource in place when the stack is removed.",
      "Stack policies protect against updates, not against deletion of the whole stack.",
      "Drift detection reports differences and prevents nothing.",
      "Nesting changes structure but the child stack would still be deleted."],
  "x":"Deletion policies are the standard protection for stateful resources in a stack, and Snapshot is the other common value for databases."},
 {"m":"systems-manager",
  "q":"Instances in a fully private subnet do not appear in Systems Manager despite having the agent and a correct instance profile. What is missing?",
  "o":["Interface VPC endpoints for the Systems Manager service endpoints",
       "A public IP address on each instance","A key pair associated with the instances","A NAT instance in the same subnet"],
  "a":[0],
  "w":["Correct — the agent must reach the Systems Manager endpoints, and endpoints provide that path privately.",
      "Public addressing contradicts the private subnet design and is unnecessary.",
      "Key pairs are for SSH and unrelated to agent registration.",
      "A NAT instance would work but is the legacy, self-managed option and still routes over the internet."],
  "x":"Agent plus instance profile plus a network path are the three requirements. In a private subnet the path is normally interface endpoints for ssm, ssmmessages and ec2messages."},
 {"m":"cost-services",
  "q":"A monthly cost report cannot attribute 30% of spend to any team, even though tagging standards exist. What is the most likely cause?",
  "o":["Cost allocation tags were never activated in the billing console, or resources are untagged",
       "Cost Explorer only supports five tags","The accounts are in different regions","Budgets are overwriting the tag data"],
  "a":[0],
  "w":["Correct — tags appear in cost reports only after activation, and untagged resources fall into an unallocated bucket.",
      "There is no such five-tag restriction on cost allocation.",
      "Region does not prevent tag-based attribution.",
      "Budgets read cost data and do not alter tags."],
  "x":"Activation is the step teams forget: tagging resources is necessary but not sufficient until the tag key is activated for cost allocation, and tag policies then keep usage consistent."},
 {"m":"misc-services",
  "q":"A nightly genomics job runs for three hours in a container and should use Spot capacity with a job queue. Which service fits?",
  "o":["AWS Batch","AWS Lambda","AWS Step Functions Express workflows","Amazon Pinpoint"],
  "a":[0],
  "w":["Correct — Batch queues jobs and provisions EC2 or Fargate capacity, including Spot, with no duration limit.",
      "Lambda is capped at fifteen minutes and cannot run a three-hour job.",
      "Express workflows are limited to five minutes and orchestrate rather than compute.",
      "Pinpoint is a customer engagement service and unrelated."],
  "x":"Duration plus a queue plus Spot is the Batch profile. Step Functions may still orchestrate around it, but the compute itself belongs in Batch."},
 {"m":"cloudformation",
  "q":"Developers must be able to launch approved, pre-configured environments without holding the IAM permissions those environments require. What provides this?",
  "o":["AWS Service Catalog with a launch role",
       "A shared administrator role","CloudFormation templates in a shared S3 bucket","A permissions boundary on each developer"],
  "a":[0],
  "w":["Correct — Service Catalog launches the product using a launch role, so users need no underlying permissions.",
      "Sharing an administrator role grants far more than the task requires.",
      "A template in a bucket still requires the launching user to hold the permissions.",
      "A boundary limits permissions rather than delegating a safe launch."],
  "x":"Service Catalog's launch role is what separates \"may launch this approved product\" from \"may create these resources directly\", which is the governance point."},
 {"m":"systems-manager",
  "q":"A compliance requirement demands that all instances are patched monthly within a defined window, with a report of which ones are compliant. What should be configured?",
  "o":["Patch Manager with a patch baseline and a maintenance window",
       "Run Command executing a patch script ad hoc","State Manager associations for package installation","Fleet Manager console sessions"],
  "a":[0],
  "w":["Correct — Patch Manager applies baselines on a schedule inside maintenance windows and reports compliance.",
      "Ad-hoc commands provide no schedule, no baseline and no compliance reporting.",
      "State Manager keeps configuration in a desired state but is not the patching workflow.",
      "Fleet Manager is a console view, not an automation mechanism."],
  "x":"The combination of a schedule, a window and compliance reporting is exactly what distinguishes Patch Manager from simply running a command across the fleet."}
]
}
