# -*- coding: utf-8 -*-
SUBJECT = {
"sec": 22,
"nm": "Well-Architected Framework and cost",
"tag": "Architecture",
"modules": [
{
 "id": "pillars",
 "nm": "The six pillars",
 "goal": "Name each pillar and the kind of answer it pushes you towards.",
 "min": 7,
 "blocks": [
  {"t":"p","x":"The **Well-Architected Framework** is six lenses on the same design. The exam uses its vocabulary constantly: the phrase a question emphasises tells you which pillar it is testing, and therefore which answer it wants."},
  {"t":"table","head":["Pillar","The question it asks","Wording that signals it"],
   "rows":[
    ["**Operational excellence**","Can we run and improve this?","\"least operational overhead\", \"managed service\", \"automate\""],
    ["**Security**","Is it protected at every layer?","\"least privilege\", \"encrypted\", \"audit\""],
    ["**Reliability**","Does it survive failure?","\"highly available\", \"fault tolerant\", \"survives an Availability Zone failure\""],
    ["**Performance efficiency**","Are we using the right resources?","\"latency\", \"throughput\", \"right-size\""],
    ["**Cost optimization**","Are we paying only for value?","\"most cost-effective\", \"reduce spend\""],
    ["**Sustainability**","Are we minimising impact?","\"minimise environmental impact\", \"maximise utilisation\""]]},
  {"t":"key","x":"**\"Least operational overhead\" means pick the managed service, even when a hand-built option is cheaper.** \"Most cost-effective\" means the opposite trade may be acceptable. Read which phrase the question used."},
  {"t":"h","x":"Design principles worth recognising"},
  {"t":"list","x":[
   "**Stop guessing capacity** — scale with demand instead of provisioning for a peak.",
   "**Test at production scale**, because environments that differ hide failures.",
   "**Automate to make architectural experimentation easier.**",
   "**Allow for evolutionary architectures** rather than one big design up front.",
   "**Drive architectures using data.**",
   "**Improve through game days** — rehearse failure deliberately."]},
  {"t":"flow","x":["Review against the pillars","Find high-risk items","Fix the highest risk first","Review again"]},
  {"t":"trap","x":"When two options both work, the pillar named in the question decides. A cheaper but more operationally involved answer loses to a managed one when the question says operational overhead — and wins when it says cost."}
 ],
 "checks":[
  {"q":"A question emphasises \"the least operational overhead\". Which kind of answer does it want?",
   "o":["The managed service, even if a self-managed option costs less",
        "The cheapest option regardless of effort","The fastest option regardless of cost",
        "The option with the most configuration control"],
   "a":[0],
   "x":"That phrase belongs to the operational excellence pillar, which values not running things yourself. Cost becomes the deciding factor only when the question says so."},
  {"q":"Which pillar does \"the system must keep working when an Availability Zone fails\" belong to?",
   "o":["Reliability","Performance efficiency","Cost optimization","Sustainability"],
   "a":[0],
   "x":"Surviving failure is the reliability pillar, which pushes towards multi-AZ deployment, health checks and automatic recovery."},
  {"q":"Which design principle argues against provisioning for a forecast peak?",
   "o":["Stop guessing capacity","Test at production scale","Drive architectures using data",
        "Allow for evolutionary architectures"],
   "a":[0],
   "x":"The principle says to scale with actual demand rather than buying for an estimate, which is what elasticity and auto scaling exist to provide."},
  {"q":"Which pillar is concerned with maximising utilisation to reduce environmental impact?",
   "o":["Sustainability","Cost optimization","Operational excellence","Security"],
   "a":[0],
   "x":"Sustainability is the sixth pillar, and its guidance overlaps with cost: fewer idle resources and better utilisation serve both."}
 ]
},
{
 "id":"reliability-patterns",
 "nm":"Reliability and performance in practice",
 "goal":"Turn a reliability or performance requirement into a concrete architecture.",
 "min":7,
 "blocks":[
  {"t":"table","head":["Requirement","Standard answer"],
   "rows":[
    ["Survive a zone failure","Multi-AZ Auto Scaling behind a load balancer"],
    ["Survive a region failure","A second region, with a strategy matched to the RTO and RPO"],
    ["Absorb a traffic spike","A queue between the tiers, and scaling on backlog"],
    ["Survive a dependency being slow","Timeouts, retries with **exponential backoff and jitter**, and a circuit breaker"],
    ["Avoid one bad client harming others","Throttling, usage plans, rate-based rules"],
    ["Lower latency for distant users","CloudFront, or Global Accelerator for non-HTTP"],
    ["Lower latency for repeated reads","A cache: ElastiCache, DAX or CloudFront"]]},
  {"t":"key","x":"**Retries need exponential backoff and jitter.** Naive immediate retries turn a brief problem into a self-inflicted flood, and the exam expects you to know the mitigation by name."},
  {"t":"h","x":"Loose coupling"},
  {"t":"flow","x":["Tight coupling: a caller waits and fails with its dependency","Add a queue","Producer and consumer scale and fail independently"]},
  {"t":"h","x":"Performance levers by resource"},
  {"t":"table","head":["Bottleneck","Lever"],
   "rows":[
    ["CPU","A compute optimised family, or more instances"],
    ["Memory","A memory optimised family, or a cache in front"],
    ["Disk IOPS","gp3 with provisioned IOPS, or io2"],
    ["Network","A larger instance, placement groups, or a CDN"],
    ["Database reads","Read replicas, a reader endpoint, or a cache"],
    ["Database writes","Sharding, or a key-value store that scales writes"]]},
  {"t":"trap","x":"Scaling up is not the same as scaling out. A question that forbids downtime rules out resizing an instance, because that requires a stop and start — the answer is more instances behind a load balancer."}
 ],
 "checks":[
  {"q":"What must retries include to avoid making an outage worse?",
   "o":["Exponential backoff with jitter","A fixed one-second interval",
        "An unlimited retry count","Retrying only on the same connection"],
   "a":[0],
   "x":"Backoff spaces retries out and jitter prevents every client retrying in lockstep, which is what turns a brief failure into a synchronised flood."},
  {"q":"A web tier overwhelms a downstream service during spikes. What is the standard architectural fix?",
   "o":["Put a queue between them and scale consumers on the backlog",
        "Increase the downstream instance size","Add sticky sessions",
        "Shorten the load balancer's idle timeout"],
   "a":[0],
   "x":"A queue absorbs the spike and decouples the rate of production from the rate of consumption, which is the core decoupling pattern."},
  {"q":"A requirement forbids any downtime while adding capacity. What does that rule out?",
   "o":["Resizing an instance, which requires a stop and start",
        "Adding instances behind a load balancer","Adding a read replica",
        "Enabling a cache"],
   "a":[0],
   "x":"Changing an instance type requires the instance to be stopped. Scaling out adds capacity without interrupting what is already serving."},
  {"q":"Which lever addresses a database bottleneck on reads?",
   "o":["Read replicas or a cache in front","Sharding the write path",
        "A larger EBS volume for logs","A placement group"],
   "a":[0],
   "x":"Reads scale horizontally with replicas or are eliminated by a cache. Sharding addresses write throughput, which is a different bottleneck."}
 ]
},
{
 "id":"cost-optimisation",
 "nm":"Cost optimisation in architecture",
 "goal":"Reduce spend by changing the architecture, not only the purchase option.",
 "min":7,
 "blocks":[
  {"t":"h","x":"The four questions to ask"},
  {"t":"steps","x":[
   "Is anything running that nobody uses? Idle instances, unattached volumes, idle Elastic IPs, old snapshots.",
   "Is anything larger than it needs to be? Compute Optimizer answers this.",
   "Is anything paying on-demand prices for predictable or interruptible work? Savings Plans and Spot.",
   "Is the **architecture** itself expensive? NAT charges, cross-zone traffic, storage in the wrong class."]},
  {"t":"table","head":["Symptom","Architectural fix"],
   "rows":[
    ["Large NAT gateway charges","Gateway endpoints for S3 and DynamoDB"],
    ["Large cross-zone transfer","Keep chatty components in one zone where resilience allows"],
    ["Storage cost growing","Lifecycle rules, Intelligent-Tiering, shorter log retention"],
    ["Idle capacity overnight","Scheduled scaling, or serverless"],
    ["Expensive database reads","A cache, so the database is not the scaling unit"],
    ["Big data transfer to users","CloudFront, which is cheaper per GB than origin egress"],
    ["Athena scanning everything","Parquet, compression, partitioning"]]},
  {"t":"key","x":"**Serverless changes the cost shape.** A workload that is idle most of the time is usually cheaper on Lambda, Fargate or Aurora Serverless than on instances sized for a peak."},
  {"t":"h","x":"Buying levers, in order of commitment"},
  {"t":"table","head":["Lever","Commitment","Saving"],
   "rows":[["On-demand","None","—"],
           ["Spot","None, but interruptible","Largest"],
           ["Savings Plans","1 or 3 years of spend","Large, and flexible across families"],
           ["Reserved Instances","1 or 3 years of a family","Large, less flexible"],
           ["Capacity Reservations","None; pay whether used or not","No discount, guaranteed capacity"]]},
  {"t":"trap","x":"Buying a three-year commitment for a workload that is about to be rearchitected is a classic wrong answer. Match the length of the commitment to the confidence in the workload."}
 ],
 "checks":[
  {"q":"An application is idle outside business hours and runs on instances sized for its peak. What changes the cost shape most?",
   "o":["Move to serverless or scheduled scaling so idle time costs nothing",
        "Buy three-year Reserved Instances for the current size",
        "Move the instances to another region","Increase the instance size to finish work faster"],
   "a":[0],
   "x":"Paying for idle capacity is the root problem, and serverless or scheduled scaling removes it. A long commitment locks in the waste instead."},
  {"q":"Private instances download heavily from S3 through a NAT gateway. What removes the largest charge?",
   "o":["A gateway endpoint for S3","A second NAT gateway","A larger instance type",
        "Transfer Acceleration on the bucket"],
   "a":[0],
   "x":"Gateway endpoints are free and remove both the NAT processing charge and the internet path for S3 traffic."},
  {"q":"When is a three-year commitment the wrong choice?",
   "o":["When the workload is about to be rearchitected","When usage is steady and predictable",
        "When the instance family will not change","When the discount is large"],
   "a":[0],
   "x":"Commitments only pay off if the usage they cover persists. Matching the term to confidence in the workload is the principle being tested."},
  {"q":"Which change reduces the cost of serving large downloads to users worldwide?",
   "o":["Put CloudFront in front of the origin","Move the origin to a larger instance",
        "Enable versioning on the bucket","Increase the NAT gateway size"],
   "a":[0],
   "x":"CloudFront serves repeated requests from cache at a lower per-gigabyte price than origin egress, so both the origin load and the transfer bill fall."}
 ]
},
{
 "id":"reviewing",
 "nm":"Reviewing an architecture",
 "goal":"Apply the framework to critique a design and choose between competing answers.",
 "min":6,
 "blocks":[
  {"t":"h","x":"The tools"},
  {"t":"table","head":["Tool","Use"],
   "rows":[
    ["**Well-Architected Tool**","A structured review producing a list of risks"],
    ["**Trusted Advisor**","Automated checks across cost, security, fault tolerance, performance and quotas"],
    ["**Compute Optimizer**","Right-sizing recommendations from real utilisation"],
    ["**Config conformance packs**","Continuous compliance against a standard"],
    ["**Security Hub**","Aggregated security findings against standards"],
    ["**Fault Injection Service**","Tests whether the reliability claims are true"]]},
  {"t":"key","x":"A review produces **risks ranked by severity**. Fixing the highest risk first is the expected answer, not fixing whatever is easiest."},
  {"t":"h","x":"Choosing between two workable answers"},
  {"t":"dtree","x":[
   ["The question says least operational overhead","The more managed option"],
   ["The question says most cost-effective","The cheaper option, if it meets the stated requirements"],
   ["The question says highly available","The one that survives losing a zone"],
   ["The question says fault tolerant","The one that also loses no data"],
   ["The question says no application changes","The one that needs no code rewrite"],
   ["The question says as quickly as possible","Rehost, not refactor"],
   ["The question says must not traverse the internet","Endpoints, PrivateLink or Direct Connect"]]},
  {"t":"h","x":"Absolute words"},
  {"t":"p","x":"Options containing **always**, **never**, **all** or **only** are usually wrong, because AWS services almost always have an exception. Read the stated constraint again before trusting one."},
  {"t":"trap","x":"Two options can both be technically correct. The one that matches the **emphasised requirement** wins — which is why reading the last sentence of a question carefully is worth more than knowing an extra service."}
 ],
 "checks":[
  {"q":"A Well-Architected review produces a list of risks. What is the expected next step?",
   "o":["Address the highest-severity risks first","Address whichever is quickest to fix",
        "Re-run the review immediately","Escalate every risk to the business"],
   "a":[0],
   "x":"The review exists to rank risk so effort goes where it matters. Prioritising by severity rather than convenience is the point of producing the list."},
  {"q":"Two options both meet the technical requirement. How do you choose?",
   "o":["By the requirement the question emphasises, such as overhead or cost",
        "By which service was released more recently","By which uses fewer services",
        "By which is listed first"],
   "a":[0],
   "x":"Exam questions are written so that an emphasised phrase decides between workable options. That phrase maps to a pillar, and the pillar selects the answer."},
  {"q":"Why are options containing words like always or never usually wrong?",
   "o":["AWS services almost always have exceptions to absolute claims",
        "They are longer than other options","They are never grammatically correct",
        "They describe deprecated services"],
   "a":[0],
   "x":"Absolute statements rarely hold across a service's features and limits, so they are a common way of constructing a plausible but incorrect option."},
  {"q":"Which service tests whether a reliability claim actually holds?",
   "o":["AWS Fault Injection Service","AWS Trusted Advisor","AWS Compute Optimizer",
        "The Well-Architected Tool"],
   "a":[0],
   "x":"Fault Injection Service runs controlled experiments that inject real failures, which verifies resilience rather than assessing it on paper."}
 ]
}
],
"recap":[
 {"t":"h","x":"The pillars and their trigger phrases"},
 {"t":"table","head":["Pillar","Phrase in the question"],
  "rows":[["Operational excellence","least operational overhead, managed, automate"],
          ["Security","least privilege, encrypted, audit"],
          ["Reliability","highly available, fault tolerant, recover automatically"],
          ["Performance efficiency","latency, throughput, right-size"],
          ["Cost optimization","most cost-effective, reduce spend"],
          ["Sustainability","minimise environmental impact, maximise utilisation"]]},
 {"t":"key","x":"When two answers both work, the emphasised phrase decides. That is the single most useful exam technique in this subject."},
 {"t":"h","x":"Patterns that answer reliability questions"},
 {"t":"table","head":["Requirement","Architecture"],
  "rows":[["Survive a zone failure","Multi-AZ Auto Scaling behind a load balancer"],
          ["Survive a region failure","A second region sized to the RTO and RPO"],
          ["Absorb spikes","A queue plus scaling on backlog"],
          ["Tolerate a slow dependency","Timeouts, backoff with jitter, circuit breaker"],
          ["Protect from one noisy client","Throttling and usage plans"],
          ["Cut latency worldwide","CloudFront, or Global Accelerator for non-HTTP"]]},
 {"t":"h","x":"Cost, structurally"},
 {"t":"split","cols":[
  {"nm":"Remove waste","items":["Idle instances and unattached volumes","Old snapshots and unused Elastic IPs","Unbounded log retention"]},
  {"nm":"Change the shape","items":["Serverless for idle-heavy workloads","Gateway endpoints instead of NAT","Lifecycle rules and Intelligent-Tiering","CloudFront instead of origin egress"]},
  {"nm":"Buy better","items":["Spot for interruptible work","Savings Plans for steady spend","Terms matched to confidence"]}]},
 {"t":"flow","x":["Review against the pillars","Rank the risks","Fix the highest first","Test with fault injection","Review again"]},
 {"t":"trap","x":"Recurring distractors: absolute words in an option; a self-managed answer where overhead is the stated concern; a three-year commitment on a workload about to change; and scaling up where the question forbids downtime."}
],
"final":[
 {"m":"pillars",
  "q":"A question describes two valid designs and stresses that the team is small and wants the least operational overhead. Which design should be chosen?",
  "o":["The one built from managed services, even if its running cost is slightly higher",
       "The one with the lowest monthly cost regardless of maintenance","The one with the most configuration options","The one using the newest services"],
  "a":[0],
  "w":["Correct — that phrase belongs to the operational excellence pillar, which values not operating infrastructure yourself.",
      "Cost becomes decisive only when the question emphasises cost.",
      "Configurability usually increases the operational burden.",
      "Novelty is never a selection criterion."],
  "x":"The emphasised phrase maps to a pillar, and the pillar selects the answer. \"Least operational overhead\" is the strongest signal towards managed and serverless options."},
 {"m":"reliability-patterns",
  "q":"A service calls a downstream API that occasionally becomes slow. During incidents, the callers retry immediately and the downstream never recovers. What should be implemented?",
  "o":["Retries with exponential backoff and jitter, plus a circuit breaker",
       "A shorter connection timeout only","More instances of the caller","Sticky sessions at the load balancer"],
  "a":[0],
  "w":["Correct — backoff spaces attempts out, jitter desynchronises clients, and the breaker stops hammering a failing dependency.",
      "A shorter timeout frees the caller but does nothing about the retry flood.",
      "More callers means more retries and a larger flood.",
      "Stickiness affects routing and has no bearing on retry behaviour."],
  "x":"Synchronised immediate retries are a self-inflicted denial of service. Backoff, jitter and circuit breaking are the named mitigations the exam expects."},
 {"m":"cost-optimisation",
  "q":"An internal reporting system runs on eight instances sized for a peak that occurs for two hours each weekday. Cost must fall without losing capacity at peak. What is the best change?",
  "o":["Scale the fleet on a schedule so capacity matches the peak window only",
       "Buy three-year Reserved Instances for all eight","Move all eight to Spot instances","Consolidate everything onto one very large instance"],
  "a":[0],
  "w":["Correct — scheduled scaling pays for capacity only when it is needed and keeps full capacity at peak.",
      "A three-year commitment locks in the idle capacity rather than removing it.",
      "Spot suits interruptible work; a reporting system needed at a fixed time is a poor fit.",
      "One large instance is a single point of failure and still runs all day."],
  "x":"The waste is idle time, not unit price, so the fix is to stop paying for it. Commitments only help once the baseline itself is right-sized."},
 {"m":"reviewing",
  "q":"Two candidate answers both provide high availability, but one keeps a warm second region and the other uses a single region across three Availability Zones. The question stresses cost-effectiveness and says a zone failure is the concern. Which is correct?",
  "o":["The single-region, three-Availability-Zone design",
       "The warm second region, because it is more resilient","Either, since both are highly available","Neither, a fourth zone is required"],
  "a":[0],
  "w":["Correct — it meets the stated failure scenario at a much lower cost than a second region.",
      "A second region exceeds the requirement and costs substantially more.",
      "Cost is the tiebreaker the question explicitly supplies.",
      "Three Availability Zones is a standard and sufficient spread."],
  "x":"Over-engineering is marked wrong. When the failure scenario named is a zone failure, multi-AZ is the proportionate answer and a second region is the expensive distractor."},
 {"m":"cost-optimisation",
  "q":"A monthly bill shows large charges for NAT gateway data processing, driven by instances reading from S3 and DynamoDB. What is the correct architectural fix?",
  "o":["Add gateway endpoints for S3 and DynamoDB and route that traffic to them",
       "Add more NAT gateways to spread the load","Move the instances to public subnets","Buy a Savings Plan to cover the charges"],
  "a":[0],
  "w":["Correct — gateway endpoints are free and remove the NAT processing charge for those two services entirely.",
      "More gateways add hourly charges without reducing per-gigabyte processing.",
      "Public subnets remove the NAT but expose the instances directly.",
      "Savings Plans cover compute, not data processing charges."],
  "x":"This is a structural cost fix rather than a purchasing one, which is the distinction the cost pillar draws: change the architecture before changing the contract."},
 {"m":"pillars",
  "q":"Which pillar most directly motivates consolidating workloads onto fewer, better-utilised instances and choosing efficient regions and instance types?",
  "o":["Sustainability","Security","Reliability","Operational excellence"],
  "a":[0],
  "w":["Correct — the sustainability pillar targets minimising environmental impact, largely through utilisation.",
      "Security concerns protection of data and systems.",
      "Reliability concerns surviving failure, which consolidation can work against.",
      "Operational excellence concerns how effectively you run and improve workloads."],
  "x":"Sustainability is the sixth pillar and overlaps heavily with cost optimisation: fewer idle resources and higher utilisation improve both at once."},
 {"m":"reliability-patterns",
  "q":"An application must add capacity during a sale without any interruption to users currently being served. What does this rule out?",
  "o":["Changing the instance type, which requires stopping the instances",
       "Adding instances to the Auto Scaling group","Adding a read replica to the database","Adding a caching layer"],
  "a":[0],
  "w":["Correct — resizing requires a stop and start, which interrupts service on those instances.",
      "Scaling out adds capacity without touching what is already running.",
      "A replica can be added while the primary keeps serving.",
      "A cache can be introduced without stopping the application tier."],
  "x":"Scaling up versus scaling out is a recurring distinction. Any requirement forbidding downtime points to horizontal scaling behind a load balancer."},
 {"m":"reviewing",
  "q":"An answer option states that a service \"always encrypts all data in every case with no configuration\". What should this signal?",
  "o":["Treat it with suspicion — absolute claims are usually incorrect",
       "Select it, since strong encryption is always preferred","Ignore the wording and judge only the service named","Select it only if the question mentions compliance"],
  "a":[0],
  "w":["Correct — AWS services almost always have exceptions, so absolutes are a common way to build a wrong option.",
      "The strength of a claim is not evidence of its accuracy.",
      "The wording is exactly what distinguishes a correct option from a plausible one.",
      "Compliance wording does not make an inaccurate claim true."],
  "x":"Absolute words such as always, never, all and only are a reliable warning sign, though not a guarantee — check the claim against the stated constraint before discarding it."},
 {"m":"cost-optimisation",
  "q":"A workload is stable today but the team plans to rearchitect it onto containers within six months. Finance wants a discount now. What is the most appropriate purchase?",
  "o":["A one-year Compute Savings Plan, which also covers Fargate",
       "A three-year Standard Reserved Instance for the current family","No commitment at all","Capacity Reservations in the current Availability Zone"],
  "a":[0],
  "w":["Correct — a shorter term matches the uncertainty, and a Compute Savings Plan follows the workload onto Fargate.",
      "A three-year commitment to a specific family would be stranded by the planned migration.",
      "Refusing any commitment forgoes a real saving on six months of steady usage.",
      "Capacity Reservations guarantee capacity but provide no discount."],
  "x":"Term length should match confidence, and Compute Savings Plans cover EC2, Fargate and Lambda, which is precisely what makes them survive a planned move to containers."},
 {"m":"reliability-patterns",
  "q":"A batch of user requests overwhelms a downstream service every time a marketing email is sent. What is the architectural remedy?",
  "o":["Place a queue between the front end and the downstream service and scale consumers on the backlog",
       "Increase the downstream instance size permanently","Add a retry loop with a fixed interval in the front end","Enable sticky sessions on the load balancer"],
  "a":[0],
  "w":["Correct — the queue absorbs the burst and lets the downstream consume at a sustainable rate.",
      "A bigger instance raises the ceiling but still breaks under a large enough burst.",
      "Fixed-interval retries worsen the flood rather than relieving it.",
      "Stickiness affects routing and does nothing about total load."],
  "x":"Decoupling a rate mismatch with a queue, then scaling consumers on queue depth, is the canonical reliability answer to predictable bursts."}
]
}
